### ISSUE TITLE
BTS and old apperture sphere button unreliable

### ISSUE THREAD

**Issue by LogicDeLuxe** [TeamSpen210/BEE2-items#1003]
The sphere button in BTS, 50's, 60's and 70's does not trigger reliable. It is reproducible almost every time when just placing a ball on top of it with the dropper disabled, so it drops on the button as soon as the map is loaded.
It also happens frequently when you drop the ball manually close to the center of the button, so it doesn't roll on it.

**Comment by LautaroL20** [comment]
I know that my english may not be perfect, and never will, but this post seems to be made with Google Translator, and therefore it's unclear. Maybe provide some screenshots?

**Comment by LogicDeLuxe** [comment]
This is the most reliable way to trigger the bug in the editor:
![spherebuttonbugeditor](https://cloud.githubusercontent.com/assets/6632046/20248153/c0cadfd4-a9dd-11e6-96c4-e24669a7a34b.jpg)
In about 9 out of 10 tries, the button will not get triggered.
As you can see in this in-game screenshot:
![spherebuttonbugingame](https://cloud.githubusercontent.com/assets/6632046/20248156/db564064-a9dd-11e6-98a9-d709ba92a3cc.jpg)

Touching the ball will trigger the button. You don't even have to pick it up for that.

**Comment by LautaroL20** [comment]
Does this occurs in other styles aswell?

**Comment by ZombiePwner1** [comment]
Why don't u test other styles @LautaroL20

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I was talking to LogiDeLuxe not you seems you must've thought I was talking to you.

**Comment by ZombiePwner1** [comment]
lol @LautaroL20 i said that since u can try other styles. Also come online
