### ISSUE TITLE
BTS Exit Door´s connections are "Out of control"

### ISSUE THREAD

**Issue by LogicDeLuxe** [TeamSpen210/BEE2-items#1004]
Each time when activated or deactivated, it closes and immediately opens again.
When "Start open" is unchecked, it starts closed es expected. But when activated for the first time, it opens quickly and closes again immediately. When deactivated again, it starts acting the same erratic behavior as before.

**Comment by LautaroL20** [comment]
Yep. The exit door´s connections are literally out of control.

**Comment by cartman1337** [comment]
I addressed this in issue #820. The exit is only out of control with exit corridors 3 or 4 selected. Exit corridors 1 and 2 work perfectly well (except exit corridor 2 has a separate issue, but the locks work well).

**Comment by ZombiePwner1** [comment]
Issue closed then if this is already addressed
