### ISSUE TITLE
[PRL23] Preview music button is not anymore and "Robo Room 7" have unordered position

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1005]
![dev](https://cloud.githubusercontent.com/assets/12244376/20258207/4c740c5a-aa2d-11e6-80f5-bc113927239b.png)

**Comment by ZombiePwner1** [comment]
That was like that in PRL 22

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Well, as for the Peview music button, the prl22 had it...

**Comment by TeamSpen210** [comment]
The preview music button is because you're running from source, a certain file is missing.

**Comment by LautaroL20** [comment]
Ive tried downloading "AVbin 10 for Windows: 64-bit",, but it didnt work, the preview button still not being displayed....

**Comment by ZombiePwner1** [comment]
It's obviously not the right file.
