### ISSUE TITLE
Overgrown Square Lights using the exactly same Light Colour

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1006]
![20161114073213_1](https://cloud.githubusercontent.com/assets/12244376/20261569/1be9fad0-aa3d-11e6-9689-1a66323347dc.jpg)

**Comment by LautaroL20** [comment]
Item description says they are brighten than light strips, in overgrown style, the HRD scale ammount is very dimly.

**Comment by TheDarkBomber** [comment]
I don't think the HRD matters.

**Comment by TeamSpen210** [comment]
It's HDR, actually (High Dynamic Range), an effect to display very bright lights by simulating how your eye adjusts to light levels.
