### ISSUE TITLE
Overgrown 4x4 Catwalk Union is missing its "Rusted visuals"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1009]
![20161116234714_1](https://cloud.githubusercontent.com/assets/12244376/20374707/1ec4f5b6-ac59-11e6-9e6a-150809588aa9.jpg)

**Comment by ZombiePwner1** [comment]
U srsly love these rusted catwalks.

**Comment by Luke18033** [comment]
@TeamSpen210 must have forgotten the model.

**Comment by Luke18033** [comment]
Wait, why does there need to be a custom model? Why can't it just use the Old Aperture model?

**Comment by ZombiePwner1** [comment]
@Luke18033 Good question.

**Comment by TeamSpen210** [comment]
Underground catwalks look different - they're more square and rectangular.

**Comment by ZombiePwner1** [comment]
What's wrong about that?

**Comment by LautaroL20** [comment]
It looks like that FrozenDragon and Luke haven´t a good taste :P, the Overgrown Catwalk Model looks pretty good. Personally i wouldn´t want to mixing up different styling Items like an Underground Catwalk, that breaks the "Overgrown Atmosphere".

**Comment by ZombiePwner1** [comment]
I like that overgrown catwalk but i'm using underground walkways until prl 23 is out. Also come online.
