### ISSUE TITLE
[PRL23 CRASH] Beemod crash when trying to launching it "Extra text in line 62!"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1011]
![crash](https://cloud.githubusercontent.com/assets/12244376/20391516/7cd3fd1a-acb2-11e6-8664-c397da5ee824.png)

**Comment by LautaroL20** [comment]
"Error occured on line 62, with file "BEE2_CATWALK:item/over/vbsp_config.cfg".

![crash](https://cloud.githubusercontent.com/assets/12244376/20391516/7cd3fd1a-acb2-11e6-8664-c397da5ee824.png)

**Comment by LautaroL20** [comment]
Ive tried to solve it myself but i don´t see anything wrong on that line. Ill have to wait until you get back on steam.

**Comment by LautaroL20** [comment]
Well, what i done was deleting the over catwalk references from "info.txt", so i can temporally use beemod while i wait for the fix.

**Comment by TeamSpen210** [comment]
It's the two quotes at the start instead of one.

**Comment by Luke18033** [comment]
This is fixed now.
