### ISSUE TITLE
Overgrown Track Platform has become into a "Blue Error"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1012]
It's now oscillating as a "Mysterious Blue Error".

_______________________________________________________________________________________

GIF:

![mysterious blue error](https://cloud.githubusercontent.com/assets/12244376/20401030/f2817312-acd5-11e6-9fbd-0177955ccd9d.gif)

**Comment by Luke18033** [comment]
Lol

**Comment by ZombiePwner1** [comment]
The brand new track platform.

**Comment by Luke18033** [comment]
[New Item] Oscillating Error

**Comment by Luke18033** [comment]
Seriously this is a bug

**Comment by LautaroL20** [comment]
You don´t say...

**Comment by Luke18033** [comment]
It's not mysterious, it's just a missing model
