### ISSUE TITLE
Overgrown Piston Platform is missing its "Grating" on its hole

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1013]
![20161117141005_1](https://cloud.githubusercontent.com/assets/12244376/20401354/41e68c70-acd7-11e6-8271-4a74487f70bb.jpg)

**Comment by ZombiePwner1** [comment]
This is the same as my static piston platform issue.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Your other report was about a STATIC piston platform, this one is a about a conective version. It may had grating on the prl22, but on the dev version it does not.

**Comment by Luke18033** [comment]
By the way, how do you get the dev version to work? There's no executable.

**Comment by TeamSpen210** [comment]
You can clone the repro, and then build the executable.

**Comment by Luke18033** [comment]
I don't understand what I'm supposed to be doing. Use the private chat, to not spam here.
