### ISSUE TITLE
wrong type of gels dropping in BTS

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#102]
i tried to put in cleansing gel and i got this...

![preview0163](https://cloud.githubusercontent.com/assets/11165643/9158344/19fcbb34-3ee3-11e5-835d-47afbf720740.jpg)

**Comment by TeamSpen210** [comment]
This should now be fixed.

**Comment by TheReviewers** [comment]
@ellingtonvengaboysmuseum Does It Work Same Is The Cleansing?
