### ISSUE TITLE
Light Strips does not intersect with the Autoportals Item, it can cause several physics errors

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#1020]
Placing two lightstrips on either side of an autoportal creates physics errors

https://youtu.be/v-2AEBOaqc4

**Comment by LautaroL20** [comment]
I think that the Light Strips should intersect with the autoportals item in order to prevent that.

**Comment by Konclan** [comment]
Well I mean its still a bug but no need to change the title :/

**Comment by LautaroL20** [comment]
I just changed the title to the actual solution for this. I highly doubt that another posible fix for this is doable, unless you get access to the Source engine code.

**Comment by Luke18033** [comment]
@TeamSpen210 could make a custom light strip model which was slightly thinner, and use that when next to autoportals.

**Comment by LautaroL20** [comment]
Or just place a light strip on the floor closely to the item, so you can highlight it. No need to overlap lights on autoportals.

**Comment by TeamSpen210** [comment]
I'll probably just switch back to occupying the whole face collision-wise (but not for antlines).
