### ISSUE TITLE
Overgrown Corridor´s Catwalks are being packed as a "Mysterious White Texture" for people who do not have Bee2.4 Installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1022]
Both the Entry and Exit corridor catwalks are being packed as a "Mysterious White Texture" for people who do not have bee2.4 installed.

_____________________________________________________________________________________________________

![20161121144343_1](https://cloud.githubusercontent.com/assets/12244376/20496226/0ce87f40-b003-11e6-9a2a-6aea3ed253e0.jpg)

**Comment by ZombiePwner1** [comment]
Hahahah missing texture this is funny.

**Comment by LautaroL20** [comment]
Its funny because it looks correct only if you have beemod installed.

**Comment by ZombiePwner1** [comment]
Brand new catwalks white edition.
