### ISSUE TITLE
Overgrown Catwalk Item is being packed as a "Mysterious White Texture" for people who do not have bee2.4 installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1026]
![20161121170446_1](https://cloud.githubusercontent.com/assets/12244376/20498847/7f88be0c-b00d-11e6-9bc1-848ad3e3885a.jpg)

**Comment by ZombiePwner1** [comment]
This is abit of a duplicate if https://github.com/TeamSpen210/BEE2-items/issues/1022 as the catwalks are the same as the item.

**Comment by LautaroL20** [comment]
Well, i would not be so sure, one is a default catwalk thats in a corridor, the other one is a custom item with its own standalone configuration maded by TeamSpen.

**Comment by Luke18033** [comment]
No, this is a duplicate. It's the same model.
