### ISSUE TITLE
Portal 1 Weighted and Sphere Button are being packed as a "Mysterious Purple Texture" for people who do not have bee2.4 installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1028]
![20161121174552_1](https://cloud.githubusercontent.com/assets/12244376/20500011/9485b198-b012-11e6-9bf8-7642dfedd91c.jpg)

**Comment by LautaroL20** [comment]
This only happens with the Shpere and Wheighted ones.

![20161121174552_1](https://cloud.githubusercontent.com/assets/12244376/20500011/9485b198-b012-11e6-9bf8-7642dfedd91c.jpg)

**Comment by ZombiePwner1** [comment]
Seems prl 23 has completely broken published maps.

**Comment by ZombiePwner1** [comment]
What about cube buttons? Are those fine?

**Comment by LautaroL20** [comment]
Well, looks like you did not play atention to what i wrote in my comment: "This only happens with the Sphere and Weighted ones."

**Comment by ZombiePwner1** [comment]
:/

**Comment by TeamSpen210** [comment]
The cube button is actually entrirely stock (excluding the sounds).
