### ISSUE TITLE
80´s Old Aperture Piston Platform is having a "Mysterious Epileptic Attack" when it starts to descend

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1031]
It is having a "Mysterious Epileptic Attack" when it starts to descend....

_________________________________________________________________________________________________

GIF:

![gif](https://cloud.githubusercontent.com/assets/12244376/20548675/35dc65e0-b104-11e6-87bc-f128164efc6d.gif)

**Comment by TeamSpen210** [comment]
That's intentional (kinda). You're at the top of the player detection range, so it swaps between detecting the player and lowering or not detecting the player and raising.
