### ISSUE TITLE
Remove EmbeddedVoxels from Camera item

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1041]
The camera doesn't take space behind the wall, this shouldn't be here.

**Comment by LautaroL20** [comment]
Lol, a camera taking space behind the wall? Thats really funny, ill gonna fix it in some minutes.

**Comment by TeamSpen210** [comment]
Actually not an issue, @Luke18033 mixed up cameras and laser catchers.
