### ISSUE TITLE
Overgrown Ditch is unstyled

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1049]
![20161123205401_1](https://cloud.githubusercontent.com/assets/19228201/20587085/16358170-b1bf-11e6-8061-727b3644aba0.jpg)

**Comment by ZombiePwner1** [comment]
This is a duplicate of another issue with the same thing.

**Comment by Luke18033** [comment]
@ZombiePwner1 What issue?
