### ISSUE TITLE
Cutout tiles are completely broken.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#1050]
![20161124153031_1](https://cloud.githubusercontent.com/assets/18079316/20589984/1096651c-b25b-11e6-8b59-104fac97026e.jpg)

The frames are still generating but there are no holes.

**Comment by LautaroL20** [comment]
Well, this is not a bug, they worked like that since the item was implelent if im not wrong. Here is a suggestion for the improvement of this item though: https://github.com/TeamSpen210/BEE2-items/issues/939

**Comment by ZombiePwner1** [comment]
there is mean't to be holes aswell.

**Comment by TeamSpen210** [comment]
I did change how they work, which makes areas close to the border less likely to have holes. Try making a bigger cutout tile area.

**Comment by ZombiePwner1** [comment]
oh alright well could you fix the frames near the border since they look out of place.
