### ISSUE TITLE
Add timer property to Cameras and Monitors

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1054]
Add a timer property to Cameras and Monitors, to allow for multiple sets of cameras. This would be useful for my map I am working on, where I currently have to use complex puzzle logic to disable one camera and enable another when you are in a certain area. Adding a timer property would simplify this a ton.

**Comment by TeamSpen210** [comment]
It's a game engine restriction, only one camera can be active at once.

**Comment by Luke18033** [comment]
Oh, that's why it switches between them. I was able to find a simpler way to do the puzzle logic, so it will work fine.
