### ISSUE TITLE
Can't compile my chamber

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1055]
I am currently working on an overgrown chamber. Every compile so far has been successful. However, the latest compile has gotten stuck at the end of "Calculating Lighting". It has been stuck like this for at least 30 minutes. The only thing I have added since the last compile is some triggers, which don't affect lighting right?

UPDATE: It finally compiled, but I can't wait this long every time.

**Comment by LautaroL20** [comment]
Thats pretty weird.... Unless you are trying to run the game into a Potato PC, it shouldn´t take that time.

**Comment by Luke18033** [comment]
I think I figured out the proplem. I had some triggers which were partially outside of the map, so it was leaked. I'm fixing the triggers and will try to re-compile.

**Comment by Luke18033** [comment]
Yes, the leak was the problem. I rearranged the triggers and now it's fine. Issue closed.
