### ISSUE TITLE
new item: rising goo pit

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#106]
similar to how you did the catwalk make a rising or draining goo pit that uses connections like the catwalk to control what level the goo will rise to or drain to.

**Comment by TeamSpen210** [comment]
This doesn't work too well in Portal. Regular goo cannot move (to allow it to do the fancy reflections), so a moving goo pit would need to use a different texture which wouldn't work as well.

**Comment by Slartibarty** [comment]
If it's anything like the Half-Life 2 'cheap' water texture it shouldn't be much of an issue.
