### ISSUE TITLE
Some Portal 3 News

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1067]
Here is some portal 3 News i heard recently from a friend who works at valve

- The Game will be about time travel and have many alternate endings which will be brought about by what choices you make
- the game will use real A.I to procedurally generate test chambers
- There will be a far more advanced version of PETI that will Rival what you have planned for Bee2 in the future
- one of the 400+ endings will be chell meeting the characters from half life
- one of the timelines you will experience Caroline become glados and the flooding of the enrichment center with Neurotoxin.
- Cave Johnson will replace glados as the central A.I like main antagonist in one of the alternate realities created by time travel and will still be voiced by J.K Simmons, friend said Cave johnson pursued the dark side of science for money in one of the games alternate realities and becomes a lot more sinister of a A.I than glados could ever be.
- Steven Merchant returns to voice wheatley.
- Kim Sasabone (of Vengaboys) and Bill Murray are signed on to voice 2 new undisclosed characters.

**Comment by LautaroL20** [comment]
Oh, no god, please no........ There we go again with fakes sources :/

**Comment by LautaroL20** [comment]
Btw, this does not have anything to do with beemod. Case closed.

**Comment by Luke18033** [comment]
Well, since @TheDarkBomber will probably be asking about this in the future, I've copied the post text to a file on my computer.

**Comment by Luke18033** [comment]
Now that GitHub has an actual delete issue option for admins, maybe we should get rid of this and #491? They were originally the fake "Portal 3 leaks", though the actual posts were erased years ago, so I don't see any reason to keep them around.
