### ISSUE TITLE
Generate nodraw on the outside of a map to make a map compile quicker

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#1071]
Make it so nodraw generates on the outside of the blocks from the map. This could optimize a lot the Grapichs process.

**Comment by Luke18033** [comment]
I don't think this would speed anything up, the compiler turns the brush faces outside the map into nodraw automatically. But then, I'm not very experienced with Source Engine compilers, so maybe I'm wrong.

**Comment by TeamSpen210** [comment]
Indeed, it doesn't speed up anything substantial.

**Comment by ZombiePwner1** [comment]
This was @LautaroL20's idea.
