### ISSUE TITLE
Overgrown and P1 Square Lights placed on Floor / Wall are "Not lighting" its placed surfaces

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1079]
![20161127211945_1](https://cloud.githubusercontent.com/assets/12244376/20655801/db4dd3ca-b504-11e6-9289-27bcc0334864.jpg)

**Comment by ZombiePwner1** [comment]
It is colouring it's surfaces beneath.

**Comment by LautaroL20** [comment]
Well, the purpose of this issue that they aren´t lighting the floor surface when its placed on.

**Comment by TeamSpen210** [comment]
That would be intentional. Lights can't light the surface they're recessed in, there isn't a path. The normal light strips should do the same actually.
