### ISSUE TITLE
Prerelease 23 is not working D:

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#1090]
[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): Line "You Make Up Your Own Rules" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "Glorious Contribution to Science" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "This Next Test Might Involve Time Travel" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "EXIT": 2/7 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Great Job, Astronaut!"
 | 	"Bullseye" "@cave_exit_lift"
 | 	"Choreo" "npc/cavejohnson/seventies_test_a_complete06.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/2 quotes..
[INFO] voiceLine.add_voice(): Using microphones...
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual', 'turret', 'observationgrate', 'deadly', 'obsworldportal']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2801, misses=286, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'retro_voice_pre_line': False, 'allowgoomist': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'rexcubepelletfizzle': False, 'bee_show_trigger': False, 'unlockdefault': False, 'restartonexit': False, 'multiversecave': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/50s/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.clump_walls(): Clumping: 160 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/underground_woodwall003c.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by TheReviewers** [comment]
@TeamSpen210

**Comment by LautaroL20** [comment]
That bug log doesn´t say anything substantial. While you are in the editor, open up the developer console, and turn on `developer 2`. then copy paste the log again, here.

**Comment by TheReviewers** [comment]
@LautaroL20  VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_ANIMAL_KING"
 | 	"Choreo" "npc/announcer/prehub46.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_RESTART"
 | 	"Choreo" "npc/announcer/mp_hub_return06.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/4 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3040, misses=305, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'fixfizzlerbump': False, 'rexcubepelletfizzle': False, 'unlockdefault': False, 'bee_show_trigger': False, 'multiversecave': True, 'nomidvoices': False, 'allowgoomist': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by TeamSpen210** [comment]
Change to use the 3ʳᵈ Overgrown corridor, I broke the others.

**Comment by LautaroL20** [comment]
Ah, i fixed this bug already. This should´t happens in next release.
