### ISSUE TITLE
I'm Stupid - How to use Catwalks?

### ISSUE THREAD

**Issue by FantomekYT** [TeamSpen210/BEE2-items#1092]
Title says it all

**Comment by Konclan** [comment]
Hey stupid, nice to meet you, just hook one catwalk to another with an antline connection. You can get more information on items if you rightclick them in the beemod program. make sure catwalks you connect are parallel to eachother, they don't have to be on the same elevation (they try their best to create stairs to eachother)

**Comment by LautaroL20** [comment]
Nah, don´t feel stupid just because you don´t know how to use an item. Feel free to ask anytime.

**Comment by Konclan** [comment]
Btw I hope you don't think I was calling you stupid, I was just making a joke (a bad one)

**Comment by FantomekYT** [comment]
Ok thanks.
