### ISSUE TITLE
Question : What is the difference between Mechanical Faith Plates And Regular Faith Plates?

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1094]
Basically what the title says.

**Comment by ZombiePwner1** [comment]
The only difference is that the large one is mean't to be used to launch things straight up but aside from that i don't see a difference.

**Comment by Konclan** [comment]
No, He's talking about the faithplate options in beemod, if you rightclick the faithplate you can change it from "Regular" to "Mechanical Faithplate"

**Comment by ZombiePwner1** [comment]
O; Haven't seen that. :/

**Comment by TeamSpen210** [comment]
That only affects Old Aperture Style. It makes the faith plates a mechanical version, instead of the gel plates.

**Comment by Konclan** [comment]
Have you ever thought of adding different versions of faithplates for all styles?
