### ISSUE TITLE
Add option to remove the covers from conveyor belts

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1097]
Add something like a stylevar or alternate version which removes the covers on the ends of Conveyor Belts.

**Comment by TeamSpen210** [comment]
There simply isn't room for this. The conveyor is split into 1-block sections, which move to the end of the track and then teleport to the start (while being cleaned of gel). If you didn't have the covers, this would be visible. Ideally you want more than one block even, to disguise it more.

**Comment by Luke18033** [comment]
Couldn't it loop around the bottom?

**Comment by TeamSpen210** [comment]
The problem is that the belts are 1-block sections, they can't bend or deform to go around. I could make them smaller parts (which would work), but then each track segment would be 8 entitities instead of 2 minimum.
