### ISSUE TITLE
Ask Josepezdj to implement Overgrown Indicator Lights for "Enabled" and "Disabled"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1108]
These are the only indicators left to styling.

______________________________________________________________________________________

![20161201223835_1](https://cloud.githubusercontent.com/assets/12244376/20820053/25f0adb6-b817-11e6-9694-5a7b0e494b7b.jpg)

**Comment by TeamSpen210** [comment]
Which ones are these?

**Comment by LautaroL20** [comment]
This:

![20161201223835_1](https://cloud.githubusercontent.com/assets/12244376/20820053/25f0adb6-b817-11e6-9694-5a7b0e494b7b.jpg)

**Comment by TeamSpen210** [comment]
I don't believe he has any for those, other than custom ones with his logo design.

**Comment by LautaroL20** [comment]
Wops, looks like the title was not acurate, maybe ask him to create these?

**Comment by LautaroL20** [comment]
Did you ever ask Josepezdj about this?
