### ISSUE TITLE
New Item : I dought this can happen but maybe Adhesion Gel

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1115]
You could get the help of one of the few people who recreated Adhesion Gel. Such As : Daniel Stelzer https://www.youtube.com/watch?v=7P0TPGGc7KI

**Comment by Byzarru** [comment]
I thought the reason Adhesion Gel wouldn't be in BEE was because the Art Therapy update replaced it with Reflection Gel. The video is three years old, so I doubt he is still working on that. With that in mind, I have two questions:
1. Why can't Adhesion Gel be pulled from an old version of Portal 2? 
2. If there is a Portal 2 update that replaces or removes Reflection Gel, will it be removed from BEE as well?

**Comment by Jadeygaming** [comment]
1)I actually don't know. 
2)I don't know

**Comment by Byzarru** [comment]
Those are questions I had for @TeamSpen210, actually.
This might be a good thing to bring back into discussion, #424 and #426 are all about this.

**Comment by TeamSpen210** [comment]
Gel is coded directly into the game, which we can't modify. If Valve was to update the game and remove it, it'd probably just crash the game or switch to that version. Adhesion Gel was never in the game, we still have the implemented portions in Reflection Gel. (It's able to counteract the slipperyness of Propulsion Gel painted cubes.) I know Felix Griffin and how he did that. That method can't work in the PeTI. It actually uses Reflection gel there too.

**Comment by Byzarru** [comment]
> If Valve was to update the game and remove it, it'd probably just crash the game or switch to that version.

I'm assuming that would be for new maps; will BEE-made maps using Reflection Gel still work after (hopefully not) it is removed/replaced? 

> I know Felix Griffin and how he did that. That method can't work in the PeTI.

Did he implement Adhesion Gel or Reflection Gel? Did he just make a new item out of the Gel, not tied to the rest or is it a hacked standard gel?

**Comment by TeamSpen210** [comment]
It's a hacked standard gel, specifically reflection gel. He basically added triggers to every single panel surface, which detects and remembers when gel touches them. Then when you touch them, he literally teleports the entire map to the new rotation, making sure to also move things like cubes or whatnot. 

If the game was updated, it would indeed crash or do whatever, unless Valve took care to keep the original functionality or something. It'd be easier to use a new gel index, so it doesn't affect anything.

**Comment by Byzarru** [comment]
Last question, then. Would it be possible to clone the original gels and turn  one of them into Reflection Gel (and make the other four into dummies)?

**Comment by TeamSpen210** [comment]
No.

**Comment by Byzarru** [comment]
Thank you.

**Comment by ZombiePwner1** [comment]
Felix's adhesion gel can only be made in hammer.
