### ISSUE TITLE
Breakable Glass causes "Failure to compile"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1116]
VBSP failed.

[INFO] vbsp.main(): BEEpy compile_vbsp_vrad.py build VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 6
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 2
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (30 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[ERROR] cond.core.check_all(): Error in <BEE2_GLASS_CUST>/items/break_gls_clean:
Traceback (most recent call last):
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 463, in check_all
    condition.test(inst)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 353, in test
    should_del = self.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 340, in test_result
    )) from None
ValueError: "BreakableGlass" is not a valid condition result!

**Comment by LautaroL20** [comment]
Alright, if you are online tomorrow, we will recompile my dev version, hope it isn´t much complicated tough.

**Comment by ZombiePwner1** [comment]
Where did you get breakable glass from?

**Comment by LautaroL20** [comment]
Im using the dev version wich is synced to the github cloud, so i get instantly any fixes or addon that isn´t public released.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber Stop removing my compile Error label I made that for a reason.

**Comment by Luke18033** [comment]
@TheDarkBomber Crash is for if the game literally crashes, it's different then a build error.
