### ISSUE TITLE
bug: partial blocks invisible in game

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#112]
there should be a bunch of partial blocks here since i placed them in PTI, none are showing up!

![preview0297](https://cloud.githubusercontent.com/assets/11165643/9562795/c6148616-4e44-11e5-8d1f-1e129f8e588c.jpg)

**Comment by TeamSpen210** [comment]
Redownload the pr9, I accidentally included the wrong version of the compiler.(It didn't actually recognize the command to create blocks).
