### ISSUE TITLE
New Item: Zero Gravity Excursion Funnel

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1121]
New Item: Zero Gravity Excursion Funnel

a variant of the excursion funnel that only pushes or pulls objects through it when triggered by a input a / b trigger. when powered doesn't push or pull any objects or player.

Could be used to create some unique puzzles where it would be used to hold a laser redirection cube in the air as it fires a laser into a laser receiver. when movement is activated on it, it pushes objects slower than the usual funnel.

**Comment by Luke18033** [comment]
I don't know if this would be possible to implement.

**Comment by Konclan** [comment]
It is, You just set a funnel speed to 0, lots of hammer maps have it.

**Comment by TeamSpen210** [comment]
A speed of zero actually turns off the funnel. A speed of `0.0001` works though.

**Comment by TeamSpen210** [comment]
See #1120 for why this can't be implemented.
