### ISSUE TITLE
New Item Variant :  Preset Monitors 

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1131]
Preset Monitors are Monitor Screens that are already out of the wall instead of coming out of the wall.

**Comment by TeamSpen210** [comment]
Why would this be useful?

**Comment by Jadeygaming** [comment]
Maybe You Want To Say Something Like, This Test chamber has already been done IDK.

**Comment by Luke18033** [comment]
Just add Start Enabled.

**Comment by TeamSpen210** [comment]
It's intentional that the monitors pop out of the wall when starting a chamber, and only do that in Clean-like maps anyway.
