### ISSUE TITLE
(DEV Version) The beemod "Style Selector Window" and  "Music Chooser Window" wouldn´t change the Style / Music when clicking on the icon if the resolution of the window is small

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1132]
Take a look at this GIF and play atention how the "Original Clean" icon is being clicked all the time without any effect, under the export options window:

![GIF](https://cloud.githubusercontent.com/assets/12244376/20858139/9570cb0c-b91c-11e6-9221-56a171d16302.gif)

**Comment by Byzarru** [comment]
It shouldn't change until you press "OK" or "Apply" (whatever the button says) anyways.

**Comment by TeamSpen210** [comment]
It doesn't actually apply until you press OK, and the window closes.

**Comment by LautaroL20** [comment]
It would be fast if you actually could use just double click. Ill gonna check if this is also in other pre-releases.

**Comment by TeamSpen210** [comment]
Yes, double-clicking should select it though.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BenVlodgi/BEE2.4/issues/437
