### ISSUE TITLE
"Scientists in Observation Rooms" stylevar

### ISSUE THREAD

**Issue by Byzarru** [TeamSpen210/BEE2-items#1135]
I'd like to suggest a stylevar to add scientist observers to observation rooms in several styles. This would be purely aesthetic: this could be part of a story when scientists still oversaw test completion or make regular chambers a bit less lonely (the PTI story itself takes place in Apertures where Cave Johnson still runs everything and GLaDOS was never invented). This stylevar would appear in the Clean, P1, BTS, P1 BTS, and Prime 50s styles.

### Clean and P1 ###
Observation rooms (both large and small) feature one or two scientists working at their desks, taking notes about the player's progress and typing on their computers. Scientists would not appear in the Sentient Cloud or CaveDOS universes. If the player model is Bendy, Bendys would populate the observation rooms.

### BTS and P1 BTS ###
Observation rooms feature technicians. They may be taking notes and measurements or building new test elements. Scientists would not appear in the CaveDOS universe. If the player model is Bendy, Bendys would populate the observation rooms.

### Prime 1950s ###
As observation rooms do not exist, this stylevar would apply to entrances and exits that resemble waiting areas. Astronauts, war heroes, olympians, and technicians would sit in chairs, reading magazines or idling and occasionally look at the player. If the player model is Bendy, Bendys would sit in chairs instead.

This is inspired by Portal Stories: Mel, which featured scientists and technicians in the first act, and the Batcature Laboratories maps by Batcat, in which Bendys are NPCs who manage the airships and oversee testing.

**Comment by Jadeygaming** [comment]
Might Not Be Able To Be Implemented..

**Comment by ellingtonvengaboysmuseum** [comment]
this will be HARD

**Comment by LautaroL20** [comment]
I don´t think this is doable unless we got an Animator modeller...

**Comment by ZombiePwner1** [comment]
If you play portal prelude there is actual scientists in that mod.

**Comment by TeamSpen210** [comment]
In Portal 2, Valve removed most of the NPC code, since it doesn't feature any humans. That means you can't place characters that work in the same way as in other source games, you can only simulate it with animated models.

**Comment by ZombiePwner1** [comment]
Damn.

**Comment by Byzarru** [comment]
Wouldn't you just need animated models, then? These aren't objects you would interact with; they are there simply to look like someone is manning the controls.

**Comment by Luke18033** [comment]
Animated models would probably work.

**Comment by LautaroL20** [comment]
If anyone would care just to read a few comments up, youll understand.

**Comment by Byzarru** [comment]
So instead of leaving open in case there is an animator willing to take this on, or a developer who wants to make a comment, this is closed to keep people from talking about it.

**Comment by LautaroL20** [comment]
The comments section isn´t looked at all, you can keep comenting if you want. I do not discredit any ideas, but be it a doable one. We do not have any animators, so people can keep posting suggestions every day, but if the idea involves another area, it would be useless.

**Comment by Luke18033** [comment]
@TeamSpen210 If Valve removed the NPC code, then how do turrets (**npc**_portal_floor_turret) and cameras (**npc**_security_camera) still work?

**Comment by TeamSpen210** [comment]
Most, not all of it - just left what's needed for those entities.

**Comment by Byzarru** [comment]
Could these be static models to see if this idea works in the first place or until an animator comes forward?
