### ISSUE TITLE
new item: gel flow switch

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1143]
add the gel flow switch seen in many underground tests such as the one where you activate the two gel flow switches to get to the vault door.

**Comment by Jadeygaming** [comment]
?What?

**Comment by Jadeygaming** [comment]
Oh I Know What You Mean. But Why?

**Comment by Luke18033** [comment]
This would probably just be the Old Aperture BTS variant of Pedestal Buttons.

**Comment by TeamSpen210** [comment]
Indeed, it would be a style variant.
