### ISSUE TITLE
Angled panels with different deactivated angles

### ISSUE THREAD

**Issue by Flametusk** [TeamSpen210/BEE2-items#1144]
They could use the standard/cube/sphere option, as the 90° one could just be a start enabled option. This would be so that you could have panels that switch between 60-90 degrees, or 45-30, or 30-60, etc.

**Comment by TheDarkBomber** [comment]
The angled panels are already basically the same. If you want to use them this way then just make sure it is start enabled when you create a connection to it.

**Comment by Flametusk** [comment]
No, because with start enabled, it just goes down to part of the surface. These wouldn't do that.

**Comment by TheDarkBomber** [comment]
Part of the surface?

**Comment by TeamSpen210** [comment]
The panel model doesn't have animations to allow this, only 0 up to an angle.

**Comment by Flametusk** [comment]
Oh. Well then. Make new animations? I don't know. Have the animations stop a certain way between the base and 0?
