### ISSUE TITLE
Cube Droppers in Existing Maps Cause Compile Failure

### ISSUE THREAD

**Issue by libbybapa** [TeamSpen210/BEE2-items#1145]
Today I installed PR23 and was very excited to try it out.  I found that existing maps would not compile... or not all existing maps, but most.  It took me a while to figure out what the issue was.  Any existing cube droppers and cubes must be deleted and replaced in order for an existing map to compile.  Just saying...

**Comment by libbybapa** [comment]
It all works fine after replacing the cubes and droppers, but tracking down what object(s) was(were) causing the issue took a considerable amount of time to track down.

**Comment by TeamSpen210** [comment]
That shouldn't happen. What timer values are they showing, and what is the error?

**Comment by libbybapa** [comment]
I only checked one map, but the timer on all existing cubes and droppers seems to be set to 3.

> 
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'bottomless_pit': '0', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (1075 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.connections.res_add_output(): Conn: ('activate', 'item_button_floor', '@voice_ball_button_pressed', 'FireUser1', '', '0.0', -1, '', '')
[INFO] cond.connections.res_add_output(): Conn: ('activate', 'item_button_floor', '@voice_ball_button_pressed', 'FireUser1', '', '0.0', -1, '', '')
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\connections.py", line 235, in res_linked_cube_dropper
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 342, in test_result
  File "F:\Git\BEE2.4\src\conditions\connections.py", line 238, in res_linked_cube_dropper
Exception: Unknown cube "linkage" value (3) in dropper!

>

**Comment by TeamSpen210** [comment]
That's the issue - set it to 'infinite', it must be messing up the default value on existing items. This allows you to link together a dropper and cube, but with them all 3 it thinks you're linking all of them in the map.

**Comment by libbybapa** [comment]
Yup, I just checked and if you switch all the existing droppers/cubes to infinite, it compiles fine.  Thanks for the work you do.

**Comment by TeamSpen210** [comment]
No problem.

**Comment by Byzarru** [comment]
I had a similar problem before, but restarting my computer after installing PR23 worked wonders.

**Comment by libbybapa** [comment]
I did a restart and verified the game cache, tried reinstalling BEE, etc...  None of it fixed the issue.  It will still give the compile error with any existing map that has more than one dropper until the timer of dropper and cube are set to infinite.  Easy to fix, but confusing until you know what the issue is.

**Comment by ZombiePwner1** [comment]
@TheDarkBomber Why did you delete my compile Error label? I made that label for a reason.
