### ISSUE TITLE
New Style: BTS + Underground Style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1152]
A new Style inspired by the BTS + Underground Combination seen in some custom maps like these photo's

the current bts style could be used as a template to design this with some changes to the vbsp

![683881532_preview_20160513225011_1](https://cloud.githubusercontent.com/assets/11165643/20943450/751f793a-bbcd-11e6-9db6-7a2806f3269e.jpg)

![683881532_preview_20160513225054_1](https://cloud.githubusercontent.com/assets/11165643/20943453/76d83726-bbcd-11e6-83cc-86b88a1cd842.jpg)

**Comment by Luke18033** [comment]
This is already going to be implemented.
