### ISSUE TITLE
New Item : Box Catcher

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1155]
Basically an upside down box dropper that you put cube in and then it projects a signal.

**Comment by Luke18033** [comment]
This was in a mod, but what mod was it?

**Comment by Luke18033** [comment]
Blue Portals maybe?

**Comment by ZombiePwner1** [comment]
Yes this was from blue portals.

**Comment by TeamSpen210** [comment]
I'd suggest just using a button with glass around it. I might want to add a button with larger trigger range for this, but that's seperate.

**Comment by Konclan** [comment]
A button is good and all but you can catch a cube on a wall or ceiling..

**Comment by Jadeygaming** [comment]
@TeamSpen210 Whatever.

**Comment by Luke18033** [comment]
Will be implemented via TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#12.
