### ISSUE TITLE
p1 entry door out of alignment

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#116]
portal 1 entry corridor 1 door is off center alignment

![preview0303](https://cloud.githubusercontent.com/assets/11165643/9565292/9050ae7e-4e94-11e5-8d96-d8e370f77a55.jpg)

**Comment by TeamSpen210** [comment]
This isn't really a bug. I might move the right-hand wall over a bit, to center it though.
