### ISSUE TITLE
New Stylevar: Entry / Exit Corridor removal override

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#1160]
we need this one 

New Style-var: Entry / Exit Corridor removal override

it removes the entry and exit corridors so the elevators take you right into and out of the test chamber.

we would also need the following to accompany it

- [ ] Placable Test Chamber Signage Item
- [ ] Custom Underground Entry and Exit Area to replace ones with entry and exit corridor built into dome

**Comment by Byzarru** [comment]
There's already a suggestion for test chamber signs (#605) and BTS/Underground style terminals (#607, #989).
