### ISSUE TITLE
Add start reversed to observation rooms to make glass breakable

### ISSUE THREAD

**Issue by Flametusk** [TeamSpen210/BEE2-items#1161]
It would be for both small and large ones, but they would take up more entities, due to the lack of nodraw and adding collisions to the props inside.

**Comment by LautaroL20** [comment]
The only sense for this would be if the player is missing a cube and the only way to get it would be breaking the observation´s glass.

**Comment by Flametusk** [comment]
Or, it could also add portal surfaces, without the extra entities from making a flip panel.

**Comment by TeamSpen210** [comment]
This wouldn't work in many styles - Old Aperture uses grating for example, and the large observation room just leads into the sphere. It'd be better to just use breakable glass, and make a recessed section.

**Comment by Byzarru** [comment]
How about recessed observation rooms (and possibly BTS corridors and chamberlocks) as a new item?
