### ISSUE TITLE
Missing item variant : Portal 1 Faith Plates UnStyled  

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#1164]
![20161208103412_1](https://cloud.githubusercontent.com/assets/22718537/21022601/185b231e-bd32-11e6-88c3-f2e22286924f.jpg)

**Comment by Jadeygaming** [comment]
@TheDarkBomber Your Quick

**Comment by Luke18033** [comment]
What would they be styled as? Faith plates weren't in Portal 1.

**Comment by Byzarru** [comment]
Faith plates weren't in Old Aperture. Neither were any of the Rexaura items, futbols, lasers, etc.

**Comment by Jadeygaming** [comment]
Yeah The One That Are Just the Panels.

**Comment by Jadeygaming** [comment]
Oh! You Can Make Them Panel With Springs That Shoot Up/Left/Right When Stepped on!

**Comment by TeamSpen210** [comment]
Nope, they're styled (note the frames around the signage). Portal 1 Style just uses the regular Portal 2 versions of things for new stuff. The only change I might perhaps do is remove the case for the panel, so you can see the orange glow below perhaps.

**Comment by Jadeygaming** [comment]
Uh... Why Would It Be Unstyled (Other Then The Frames) In Portal 1 Style?

**Comment by TeamSpen210** [comment]
It's like that for the same reason funnels look the same. They're both new inventions, which GLaDOS would have had to add to the chamber later or something. Portal 1 style is close enough to Clean style that they fit in fine.
