### ISSUE TITLE
Overgrown Style not working?

### ISSUE THREAD

**Issue by FantomekYT** [TeamSpen210/BEE2-items#1168]
It doesn't matter what i will use for my map (I even used the original peti pallete with nothing placed in the map) it always says "There was a problem when building your chamber." Also if that's just something wrong with this release will it be fixed in the next release?

**Comment by LautaroL20** [comment]
This is fixed for next release, however if you use the SP Exit corridor N°3, it should compile well. 

Duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/1040

**Comment by FantomekYT** [comment]
Oh. Okay thanks
