### ISSUE TITLE
50's catwalk near exit out of alignment

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#117]
very hard to see, near portal fire target cursor. i ran into it by accident, out of alignment by 1 tiny block. in exit corridor 1 in 50's style

![preview0302](https://cloud.githubusercontent.com/assets/11165643/9565295/ca382da6-4e94-11e5-97b2-0728c72e0984.jpg)

**Comment by BenVlodgi** [comment]
That's not even a whole unit lol.
Could be a mathmatical error, like a floating point problem.
