### ISSUE TITLE
New item: Rexaura Radiated Flux Fields.

### ISSUE THREAD

**Issue by Flametusk** [TeamSpen210/BEE2-items#1172]
They would act similar to how the work in the game.

**Comment by Byzarru** [comment]
Are these the switch on/off fields? These are already going to be implemented. (#490)

**Comment by Flametusk** [comment]
Yes it is, so you can close this problem.

**Comment by ZombiePwner1** [comment]
Conversation locked :)

**Comment by Luke18033** [comment]
@ZombiePwner1 You don't need to lock duplicates either. Just close them.
