### ISSUE TITLE
tiles which can suck in the Pneumatic Diversity Vent

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [TeamSpen210/BEE2-items#1176]
![image_27910](https://cloud.githubusercontent.com/assets/24510029/21083356/c04b318e-bfff-11e6-8ed2-adb5e893d0f9.jpg)

**Comment by Luke18033** [comment]
I think this has already been requested before, let me check...

**Comment by TeamSpen210** [comment]
Why would this be useful?

**Comment by Jadeygaming** [comment]
To Look Cool?

**Comment by Jadeygaming** [comment]
I Don't Know. :/

**Comment by ZombiePwner1** [comment]
This has no use whatsoever

**Comment by Luke18033** [comment]
You could use it to create hidden areas, although hidden areas aren't really useful without a texture override to make ratman dens or BTS areas.

**Comment by ZombiePwner1** [comment]
Issue locked till further notice.

**Comment by Luke18033** [comment]
@ZombiePwner1 Only issues which are spam need to be locked. If it's just something which is unneeded, it doesn't need to be locked, just closed.
