### ISSUE TITLE
why did you twerpy my ideas

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [TeamSpen210/BEE2-items#1178]
![image_27910](https://cloud.githubusercontent.com/assets/24510029/21088107/3f029548-c03d-11e6-9c73-5f2be484bf32.jpg)
![default](https://cloud.githubusercontent.com/assets/24510029/21088108/3f1c9a10-c03d-11e6-973a-0d47d02bd36b.PNG)

**Comment by Luke18033** [comment]
Seriously?

**Comment by LautaroL20** [comment]
@ILIA-NENASHEV - I'd suggest to write some lines on the description for next time, so you can provide as much info as possible on your suggestions.

**Comment by TheDarkBomber** [comment]
????

**Comment by TheDarkBomber** [comment]
This issue makes no sense, and will be locked until further notice.
