### ISSUE TITLE
Cant Use Over Grown Sytle Please Help!!!!

### ISSUE THREAD

**Issue by ajrocks33** [TeamSpen210/BEE2-items#1179]
every time i use it then i build my level/map it says theres a error when it finishes the first bar plese help

**Comment by ZombiePwner1** [comment]
You have to use overgrown exit 3 since the other exits cause compile errors due to a missing instance.

**Comment by LautaroL20** [comment]
No, the instance always was there. The problem is that it had a spelling error on it, and therefore the compiler weren't able to find it.......

**Comment by Luke18033** [comment]
`exit_stair.vmf` when it should have been `exit_stairs.vmf`.

**Comment by ajrocks33** [comment]
exit 3?

**Comment by LautaroL20** [comment]
@ajrocks33 - Launch Beemod, then open up the Compile Option´s window:

![Beemod](https://cloud.githubusercontent.com/assets/12244376/21119265/9cd94e06-c0a0-11e6-9ad2-0367034c1bd8.png)

**Comment by ajrocks33** [comment]
i just Accidentally found that out a couple of minutes ago
