### ISSUE TITLE
When will the Wheatley style be released?

### ISSUE THREAD

**Issue by I-love-bee-2** [TeamSpen210/BEE2-items#1187]

**Comment by TheDarkBomber** [comment]
Soon.

**Comment by I-love-bee-2** [comment]
@TheDarkBomber using some of these elements of the program?

**Comment by I-love-bee-2** [comment]
what program do you do these items for bee 2? @TheDarkBomber

**Comment by Luke18033** [comment]
Art Therapy and Refurbished are the only styles in development.

**Comment by LautaroL20** [comment]
First off, some actual styles must be finished like the BTS which is pretty much broken right now. Art Therapy is in the works too. After that we may think on next Styles.
