### ISSUE TITLE
Clean/Overgrown Fizzlers missing EmbeddedVoxels

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1190]
![20161212173504_1](https://cloud.githubusercontent.com/assets/19228201/21124110/b9e7c5b8-c091-11e6-9d61-9334e2012f74.jpg)
 Clean fizzlers take space inside the wall, but don't have `EmbeddedVoxels`.

**Comment by TeamSpen210** [comment]
Valve decided that, it's kinda an advantage... I'll actually want to make that happen for some other items (like lasers, 50s buttons) so you can place them near each other.

**Comment by Luke18033** [comment]
@TeamSpen210 That works fine. Who would put items like this anyway? I did it *specifically* to see if the model would clip through. The only question I have is: isn't `EmbeddedVoxels` needed to properly cut a hole in the wall for items to go in?

**Comment by TeamSpen210** [comment]
It is, fizzlers don't cut holes. You can see in PeTI maps the wall goes through the model. I improved that by adding a pure-black texture in the space, so it's not as noticable but I'll need to do some complex things to allow the compiler to properly generate holes for them.
