### ISSUE TITLE
How Do I add A Model

### ISSUE THREAD

**Issue by ajrocks33** [TeamSpen210/BEE2-items#1191]
How do i add a model or thing to the pallet maker thing is there a tutorial?

**Comment by LautaroL20** [comment]
Unfortunately, there isn´t any tutorial for this or a Wiki page, but i have maded my own custom tutorial for this. It is in Spanish though:

![bee2 4 package tutorial - models and pallete icons](https://cloud.githubusercontent.com/assets/12244376/21144460/7e978884-c129-11e6-9f22-5f0dba3f05be.png)

**Comment by ajrocks33** [comment]
almost done translateing 
![7e978884-c129-11e6-9f22-5f0dba3f05be](https://cloud.githubusercontent.com/assets/12651151/21163611/00696c8c-c149-11e6-897d-9ab5f64bb6a8.png)

**Comment by LautaroL20** [comment]
Nice! Im glad that Google Translator handled it, its not a perfect translation but youll gonna have an idea of how it works at least.

**Comment by ajrocks33** [comment]
i am done translateing
![7e978884-c129-11e6-9f22-5f0dba3f05be](https://cloud.githubusercontent.com/assets/12651151/21164300/f7acd288-c14c-11e6-81b7-a81bf7cf65bd.png)

**Comment by ajrocks33** [comment]
only if there was video

**Comment by ajrocks33** [comment]
still dosent make sence

**Comment by LautaroL20** [comment]
:(

**Comment by ajrocks33** [comment]
the reason i wanted to add a model to the bee mod thing is so then i dont have to make the rest of the map in editor because i cant export hammer maps to the gamer editor can i?

**Comment by ajrocks33** [comment]
any other tutorials you know that might help?

**Comment by ZombiePwner1** [comment]
@ajrocks33 U can't export hammer maps to the game editor and this is due to reasons. You can only export the game edit map to hammer.

**Comment by TheDarkBomber** [comment]
Well, if you need to **create** a model, you can Hex Edit an existing model.

**Comment by ajrocks33** [comment]
packages? Wasp things have happend when i was gone
