### ISSUE TITLE
What innovations and elements will be updated?

### ISSUE THREAD

**Issue by I-love-bee-2** [TeamSpen210/BEE2-items#1203]

**Comment by LautaroL20** [comment]
- Breakable Glass.
- Half Plate.
- Cube Coloriser.
- Cube Cleaner.
- Protruding Pedestal Buttons. (In case we firuge out a fix to prevent a bug when its set to infinite).
- Many bugfixes.

**Comment by TheDarkBomber** [comment]
And **much** more.

**Comment by TheDarkBomber** [comment]
@TeamSpen210 said that my items will be added to BEE2.4 for PR24 as well. ([see here](https://gitter.im/TheDarkBomber/BEE2-items-TheDarkBomber-Contributions))

**Comment by I-love-bee-2** [comment]
and will be a new style or a skybox?

**Comment by TheDarkBomber** [comment]
Probably not.

**Comment by Luke18033** [comment]
@LautaroL20 What are Half Plate and Protruding Pedestal Button?

**Comment by I-love-bee-2** [comment]
elements are crumbling? tile or concrete and so dalie

**Comment by TheDarkBomber** [comment]
No, packages don't crumble into a million pieces into the Recycle Bin.
