### ISSUE TITLE
It will be translated into other languages for bees 2?

### ISSUE THREAD

**Issue by I-love-bee-2** [TeamSpen210/BEE2-items#1204]

**Comment by TheDarkBomber** [comment]
Maybe.

**Comment by Luke18033** [comment]
If I'm correct, Pr23 supports languages other than English. It's based on what language is set on the computer.

**Comment by I-love-bee-2** [comment]
@Luke18033 you made a mistake, he can not be translated

**Comment by TheDarkBomber** [comment]
@I-love-bee-2 Who can't be translated? @Luke18033?

**Comment by LautaroL20** [comment]
Well, respect to this i can oficially confirm that beemod will include a Spanish translation ive maded with Poeditor. For more info, see here: https://github.com/BenVlodgi/BEE2.4/issues/416

**Comment by Luke18033** [comment]
Oh, I get it. Pr23 only added the translation support, the actual translations haven't been added yet.
