### ISSUE TITLE
Cube Cleaner causes "Failure to compile" in Overgrown Style

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1208]
| Could not open instance file instances/BEE2/over/items/tspen/cleaner.vmf

**Comment by LautaroL20** [comment]
The instance is inside the package, but for some reason beemod isn´t sending it to the P2 Sdk_content folder, so ill gonna check the items folder.

**Comment by Luke18033** [comment]
Stop changing it back to "dev". "Development Version" makes more sense, you need to at least make it "dev version".

**Comment by LautaroL20** [comment]
I'm sorry to dissapoint you i didn´t change any levels, it must be someone else.....
Like i said before, there must be a guy here that loves playing with all the lavels.

**Comment by Luke18033** [comment]
@LautaroL20 Maybe @TheDarkBomber?

**Comment by LautaroL20** [comment]
Maybe, who knows...

**Comment by ZombiePwner1** [comment]
Most likely @TheDarkBomber

**Comment by TheDarkBomber** [comment]
It is @TheDarkBomber

**Comment by ZombiePwner1** [comment]
@LautaroL20 I was able to compile the cube cleaner in overgrown just fine.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Thats because i already have fixed the bug u wheely. It looks like you didn´t play atention at what labels this issue has...

**Comment by Luke18033** [comment]
Even if it's not a bug now, it still was a bug.
