### ISSUE TITLE
overgrown and clean entry corridor single panel issue

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#121]
this single panel has a bug in overgrown and clean

![preview0310](https://cloud.githubusercontent.com/assets/11165643/9565355/0bf56fe4-4e98-11e5-913c-99f0f75df7f9.jpg)

when the panel is retracted, the clip for it is still active

![preview0313](https://cloud.githubusercontent.com/assets/11165643/9565354/f67097e8-4e97-11e5-88c0-d4885ac65fb2.jpg)

bendy standing off floor where retracted panel is if you can see it

![preview0314](https://cloud.githubusercontent.com/assets/11165643/9565357/196dbb04-4e98-11e5-9b87-2190d18077c5.jpg)

same thing happens in clean style with this panel.

**Comment by TeamSpen210** [comment]
What do you mean by the clean style panel? These are overgrown-specific instances.

**Comment by ellingtonisland** [comment]
there is a single clean panel in entry corridor 1 in the clean style that sometimes hangs out of the wall, it does the same thing and is solid where it should not be when it is retracted.

**Comment by SpyyZ158** [comment]
@ZombiePwner1 Stop closing everything if it's not done by far yet.
