### ISSUE TITLE
Beemod is compiling the overgrown style with "Leaks" into some corridors, for people who do not have beemod installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1211]
This is how looks the SP Entry Corridor N°6 (Only for people who do not have BEEMOD Installed)

![20161217012536_1](https://cloud.githubusercontent.com/assets/12244376/21284539/df31f82a-c3fc-11e6-9f07-995762657dc9.jpg)

**Comment by LautaroL20** [comment]
I can confirm that these bugs also happens with the public PRL23 too.

**Comment by Luke18033** [comment]
Why is this invalid?

**Comment by TheDarkBomber** [comment]
It's not.

**Comment by LautaroL20** [comment]
I have verify game cache files and now it works fine. Probably a mixed up files were causing this weirdness. If anyone wants to compile a map using this corridor then play the map with a 100% Clean Install, go ahead.

**Comment by TheDarkBomber** [comment]
@LautaroL20 Please check your [Gitter](https://gitter.im/TheDarkBomber) (This comment will be deleted)
