### ISSUE TITLE
Beemod is compiling the overgrown style using a "Different Skybox" and without visuals effects like "drip_stream_01" for people who do not have beemod installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#1212]
Beemod is compiling the overgrown style with a "Different Skybox" from the selected, and also not showing some visuals like the "drip_stream_01" (Only for people that do not have beemod installed):

![20161217012542_1](https://cloud.githubusercontent.com/assets/12244376/21284564/de0876bc-c3fd-11e6-9c43-71c501b7df96.jpg)

**Comment by Luke18033** [comment]
@LautaroL20 Why is this invalid?

**Comment by ZombiePwner1** [comment]
@Luke18033 He most likely used the wrong skybox.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Nope, i make sure to use the correct one, idk what was going on with this, but after re-installing some things it started working fine.
