### ISSUE TITLE
Just a question about Overgrown Exits.

### ISSUE THREAD

**Issue by FantomekYT** [TeamSpen210/BEE2-items#1213]
I heard that the issue with them is mispelled name. It should be `exit_stairs.vmf` but its `exit_stair.vmf` .
Is it possible to change that file name/names by yourself and not wait for another release? Since for me it seems very easy to just change 1 letter.

**Comment by ZombiePwner1** [comment]
Just rename it to exit_stairs.vmf i did the exact same thing to fix it.

**Comment by FantomekYT** [comment]
Where is that file tho.

**Comment by ZombiePwner1** [comment]
portal2/sdk_content/maps/instances/bee2/over/sp_elevator/elevator_exit

**Comment by ZombiePwner1** [comment]
@TheDarkBomber this is not a suggestion. It's a question.

**Comment by TheDarkBomber** [comment]
But it's a suggestion to rename `exit_stair.vmf` to `exit_stairs.vmf`, so it is.

**Comment by ZombiePwner1** [comment]
It will be fixed in the next prl it's a mistake @TeamSpen210 Made.

**Comment by TheDarkBomber** [comment]
It's already fixed/implemented for next release.
