### ISSUE TITLE
Implement Stylevar to disable Fast Reset

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#1217]
When Lautaro´s Protruding Pedestal Button is pressed, it will immediately un-press. The timer will continue to count down, but the button will remain pressable again during this time.

**Comment by Luke18033** [comment]
I can't figure out what's causing this, since both the regular Pedestal Button and Protruding Pedestal Button have "Prevent Fast Reset" disabled.

**Comment by LautaroL20** [comment]
> The button will remain pressable again during this time.

Thats because both the Valve´s Pedestal Button and mine have "Prevent Fast Reset" disabled.

**Comment by Luke18033** [comment]
That's not the point. Valve's version doesn't fast-reset. Your protruding button does.

**Comment by LautaroL20** [comment]
Both the PeTi pedestal and mine can be reset at the exactly same speed. If you are experiencing weird things that must be your files because this doesn´t happens to me. 
_________________________________________________________________________________________

GIF:
![GIF](https://cloud.githubusercontent.com/assets/12244376/21296392/7141c978-c549-11e6-9f6b-bd98b0dcad33.gif)

**Comment by LautaroL20** [comment]
Looks like that @TheDarkBomber Has nothing better to do than opening invalid issues. Please, go and play some Castlevania for nes....

**Comment by Luke18033** [comment]
@LautaroL20 You're on original clean. I'm on Clean. Would that make a difference?

**Comment by Luke18033** [comment]
Even if this isn't happening, I think it would be better to not have any pedestal buttons fast-reset.

**Comment by LautaroL20** [comment]
> You're on original clean. I'm on Clean. Would that make a difference? 

Not really. If that were the case, then we would have two diffenets Styles folder. Original Clean is merged into the clean folder. I dont think its a good idea to change the original fast-reset feature, so this must be an aditional Stylevar Option. 

 GIF:

![gif](https://cloud.githubusercontent.com/assets/12244376/21298924/31b2d226-c575-11e6-8b02-e838fb577c2a.gif)

**Comment by TeamSpen210** [comment]
This is how all timed buttons behave, as you can see from Lautaro's GIF. I think it's better to keep fast reset, it's very useful to avoid waiting around.

@TheDarkBomber stop switching back labels constantly please.
