### ISSUE TITLE
Is there currently an Input to Output item?

### ISSUE THREAD

**Issue by Byzarru** [TeamSpen210/BEE2-items#1219]
Is there an item currently in BEE2 that simply takes an input and gives an output? I'm using Laser Catchers and Emitters for this purpose (and have used cubes and buttons in the past) but this is driving my entity count too high (I'm working on a logic intensive map).

**Comment by Flametusk** [comment]
Are you talking about logic gates? Because they are in the default bee2 pallette.

**Comment by Byzarru** [comment]
No, I'm talking about an item that simply takes an input and output. Can the logic gates accept only one input?

**Comment by Flametusk** [comment]
One of them, in the other logic gates that aren't in the default, can, I believe. I think it's the XOR gate. It outputs if only one input is active.

**Comment by LautaroL20** [comment]
We don´t know what kind of intrincate connection are you trying to do, this would help a lot to reply your question.

**Comment by Byzarru** [comment]
I'll make up a scenario and post it later.

**Comment by Byzarru** [comment]
[Secret picture.](https://cloud.githubusercontent.com/assets/22107242/21297798/26917880-c54c-11e6-8c0f-9c323ea4c1b6.png) This is what I'm working on now, and how I'm using lasers.

**Comment by Luke18033** [comment]
How would this be useful?

**Comment by Flametusk** [comment]
For creating much more complex puzzles.

**Comment by Luke18033** [comment]
But you don't need it. Just connect the items directly. I guess it could be useful for going over the 8 connection limit, but other than that it's not very useful.

**Comment by Byzarru** [comment]
The point of the puzzle is that the correct plates are _not_ connected to the exit, but instead that the end result (everything is black) is true and so the exit opens.

**Comment by LautaroL20** [comment]
Well, i don´t think we are missing logical items we could use for any intrincate devices. Id suggest to check out the Beemod Wiki, there are very good information about this:

Logic Gates: https://github.com/TeamSpen210/BEE2-items/wiki/Logic-Gates

SR Latch: https://github.com/TeamSpen210/BEE2-items/wiki/SR-Latch

**Comment by Byzarru** [comment]
Of course, I can easily try this myself, but does AND or OR work with one input?

**Comment by TeamSpen210** [comment]
Use an AND gate for this, or an antline magnet.

**Comment by TheDarkBomber** [comment]
Logic Gates

**Comment by Byzarru** [comment]
I got it. It worked. My map compiles now. :p
