### ISSUE TITLE
Allow for 1980s cubes and buttons to use the old aperture models

### ISSUE THREAD

**Issue by Flametusk** [TeamSpen210/BEE2-items#1223]
It would work like the old aperture faith plates, which can change between gel and mechanical. Also, are there any other elements, in any style, that have multiple models like that?

**Comment by Byzarru** [comment]
All of the things. Rexaura items, Sendificator, all of the Standard items.

**Comment by Flametusk** [comment]
I mean variants in the same style, that when you right-click on the element in terms pallette editor, it allows for, for example, the old aperture faith plates to be either shaped repulsion gel, or prototype mechanical plates.

**Comment by Byzarru** [comment]
No, then. Stairs have the switch for behavior (either act as panels or a solid set of stairs when inactive), but that's it.

**Comment by Flametusk** [comment]
Well then, there should be more, such as the ability to change cubes in the 80s to use the old aperture models. Heck, if it included things like that for most elements, it could practically be a style creator without changing the style itself, which would still determine certain things, like entry/exit, and textures.

**Comment by Byzarru** [comment]
It would be interesting. I've made a similar argument before (#1073), but with crushers and flamethrowers in the 60s. 
On another note, does shaped gel change to a faith plate when connected to an input?

**Comment by Flametusk** [comment]
Nope. It acts as a flip panel.

**Comment by TeamSpen210** [comment]
There's a specific reason for the 1980s using modern cubes and buttons. This sign is present in those levels, and features those modern elements.
![img_2329](https://cloud.githubusercontent.com/assets/8453732/21330494/7713c73e-c689-11e6-827c-41aeb52774e7.PNG)
If you don't want those, use a different decade.

**Comment by Flametusk** [comment]
Well, really, it would make more sense to use the portal 1 models, then, even though that's not what it shows in the poster. Chronologically, it would be more accurate.
