### ISSUE TITLE
behold my idea for bts fizzlers

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#130]
i think bts fizzlers should use a variant of the underground fizzler model to look more like they where made for the BTS half fast etc. I have created this for the force field bts variant

![preview0013](https://cloud.githubusercontent.com/assets/11165643/10269124/ecbf67be-6a9a-11e5-9b60-386f02538fa4.jpg)

**Comment by Slartibarty** [comment]
Nice idea!
I'd like to see this implemented.

**Comment by TeamSpen210** [comment]
This doesn't make too much sense. BTS areas are modern - throughout the campaign maps there are plent of fizzlers, all using regular clean fizzlers. For BTS, I'm just going to surround them with a yellow-striped hazard texture.

**Comment by ellingtonisland** [comment]
ok i will change the force field model to look like the other ones in BTS...
