### ISSUE TITLE
contributions to bee2.4 to be completed by EllingtonIsland

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#133]
contributions to bee2.4 to be completed by Ellington Vengaboys Museum (Ellington Isle)
@TeamSpen210 and @BenVlodgi and anyone else, feel free to complete some of these yourself and check them off as you go along if you want to!

- [x] force field (green fizzler that blocks everything like a normal surface) (almost done)
- [x] liquid coloring excision field (original pink fizzler designed to properly replace crappy beta P1 like paint fizzler) (in progress)
- [ ] tripwire field (white fizzler that activates whatever it is connected to and acts like a one time button when a player walks through it)
- [ ] invisible trigger field (completely invisible trigger field used to trigger panels etc or anything)
- [ ] broken fizzler (a fizzler that tries to open its grid model, no field in it like the broken fizzler in the campaign, for looks only)
- [x] physics solidification field (custom navy blue fizzler that will solidify when a cube touches it. fizzles and resets portals, doesn't destroy cubes or turrets.)
- [ ] paint suspension fields (custom fizzlers similar to force fields, each have properties of their corresponding paint type of blue, orange, and white, each field uses custom texture and paint is rendered as invisible, uses paint sprayer to apply paint to it and white one is portable) (will need help on this one for sure)
- [x] cold light strip (needs to be re skinned by @TeamSpen210 once released) (near done)
- [x] cold and neutral square lights
- [ ] square hole in 1/8th thick block wall (seen in P1 in test above fizzler where glados says "this next test is impossible, make no attempt to solve it!")
- [ ] gravity cube (custom skinned blue cube that uses trigger to activate once picked up, once picked up uses thruster to make it fall to ceiling) (need help on this one)
- [ ] cutout tile like items to create retracting panels
- [x] chapter number and title item (self triggers)
- [ ] toggable light strips and square lights (a lot of re skinning needed, along with coding)
- [ ] trigger_auto item

**Comment by Slartibarty** [comment]
It would be nice to have the wall details and ceiling lights back, they work especially well on Overgrown style chambers.

**Comment by CrashingScience** [comment]
Make sure the terrorist sound us toggleable. Its funny but not serious for all maps.

Also i think tnt turrets is good with pneumatic vent.

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Any news on your items contributions? This post looks pretty old and outdated. If no news or just a simple reply by Ellingtonisland is maded during the next weeks, i might consider this dead and it should be closed.
