### ISSUE TITLE
bug: source of major goo pit leaks possibly found

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#134]
to reproduce the bug:

start a new clean style test chamber with entry and exit door 1, compile normal, entry door should open fine without white where thing rotates.
back in PTI create a 1x1 voxel wide pit (no goo) in the floor
recompile and when you go through the entry door as it opens you will see white where the thing in the middle of the door rotates indicating a leak.

also works with any size pit that is 1 voxel deep as long as it doesn't cover the entire room.

**Comment by harritron2k2** [comment]
Does it work in a 2 boxes deep pit? Sometimes it works for me randomly then I add items and it goes back to being bugged.

**Comment by ellingtonisland** [comment]
fixed
