### ISSUE TITLE
cube dropper issue

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#139]
discovered it with my careful eye!

![preview0056](https://cloud.githubusercontent.com/assets/11165643/11384476/1a4a46c0-92de-11e5-8dd6-9709815123db.jpg)

**Comment by jccreszMinecraft** [comment]
It could be a neat thing to do for, say, BTS or other themes, like adding pipes behind the dropper. TeamSpen has marked it as a bug though.

**Comment by TeamSpen210** [comment]
This is a bug - there's supposed to be regular ceiling tiles here (dynamically generated actually so they can randomly choose one of the ceiling textures). I might have frameless droppers in BTS or Art Therapy style.

**Comment by ellingtonisland** [comment]
@TeamSpen210 - as @jccreszMinecraft said, this feature could work well in wheatly style if the dropper is placed in a area with an entirly open ceining. all you have to do is find some way to get the logic involved that generates the open ceiling like the bottomless pit logic would to neatly and properly place diversity tubes in the ceiling and connect one to the dropper that would look nice and find a way to prevent instances from overlaying. make it so when you pressed the button you would see the next cube being caried through the tube in a open wheatly style.

**Comment by TeamSpen210** [comment]
There's lots of compatibility issues with changing ceilings like that. For example, players could place a light strip on the side of the dropper pillar - then it'd be floating. Even if that wasn't the case, the puzzle might require players place conversion gel on the side, and then put a portal there. It'd be impossible for me to detect that, so the style could end up breaking the puzzle.

**Comment by ellingtonisland** [comment]
@TeamSpen210 what i meant is if whatever you used to cut a hole in the ceiling was placed where a dropper would be, where the hole would be cut, the dropper would be connected to a diversity tube in the ceiling and the panels on it removed completely, there would be no portal surfaces of anykind where the hole was cut, if a lightstrip was placed where the hole would be you would need some logic to either remove it automatically, generate a comple error, or autoplace a few complete panels around the lightstrip (use the panel metal frames to connect the ceiling to it so will look nice)

and if the dropper was extended down so a pillar had portal surfaces etc or a lightstrip on it, the ceiling above would be the only part that would get cut out, you would see the diversity tube entering into the piller from the hole in the ceiling. here is a example using text

```
__________
 |  _______
 |  |
 |  | - vac tubes 
-|  |------------------  area of celing with hole in ceiling, this part only part removed
 |  |] piller with light or portal surface, this part not removed
 |  |
|    | - cube dropper
===
```

**Comment by TeamSpen210** [comment]
Yes, that could actually work nicely. I'm actually going to make the Cutout Tiles item also work on ceilings, which will extend up a block or so. I don't think I'll actually make the cubes travel through the pipe, but I'll generate the piping. (It'll use the alternate skin which hides the interior of the tube).

**Comment by ellingtonisland** [comment]
@TeamSpen210  in portal stories mel in a few of the clean chambers the cubes traveled through some clean glass pipes into the droppers, this would look nice in some styles...

**Comment by ellingtonisland** [comment]
fixed
