### ISSUE TITLE
List of Suggestions from Portal Stories Mel.

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#14]
well portal stories mel has released and i just finished it, here is a list of suggestions to import into the new bee2 directly from mel

- add voice lines for virgil
- add voice lines for aegis
- add new tommy gun turrets seen underground at beginning of mel.
- add mel as playable character
- import mel's portal gun as one of the usable portal gun models, other model should be potatos gun.
- for a type of 3d skybox for clean tests, that giant fan seen underground in portal 2 coop campaign does have a use after all as shown in one of the tests in mel.
- import custom music used in mel into music selection of new bee2

know of any other stuff from mel you can import into the new bee2?

**Comment by TeamSpen210** [comment]
* I can't add Mel or her gun in a workshop map.
* I'll keep the fan in mind for a potential BTS background model.
* The rest is all technically possible, although I might not be able to get closed captions on the voice lines. I'd want to get permission first from the original authors before adding it to the BEE2.

**Comment by ellingtonisland** [comment]
for the fan besides using it in a BTS style skybox model make a skybox with the same fan for wheatley or a clean style with bottomless pits too like it was in mel.

also no need for closed captions on the voice...

anything else you know from mel that can be added i forgot?

**Comment by Luke18033** [comment]
@TeamSpen210 Also add Mel Cave Johnson voicelines.

**Comment by ReikaKalseki** [comment]
Has there been any progress on this (namely getting permissions)? I would very much like the AEGIS voice lines.

**Comment by TeamSpen210** [comment]
The main problem with mod voicelines is I can't figure out a way to add them and get localised versions to work.

**Comment by ReikaKalseki** [comment]
I do not know enough about the internals to comment on that, but you *can* add them as English-only at first.

**Comment by Byzarru** [comment]
Subtitles and alternate tracks are the big issue. Adding the voicelines themselves are no problem. And I would very much want those tommy gun turrets. ;)
