### ISSUE TITLE
cut out tile suggestions for improvement

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#140]
the cut out tile needs to be vastly improved, the results it creates looks butt ugly right now

this is what they should really look like in overgrown, see if you can rework the logic so it would create something like this somehow and completely remove tiles from the center and form a procedurally generated path etc so it looks more smooth, also see if you can tilt some of the metal frames/tiles ect

![sp_a1_intro70002](https://cloud.githubusercontent.com/assets/11165643/11414961/322f91ea-93ca-11e5-868a-c12841850fce.jpg)

for the other styles such as wheatly you will need something like this that removes almost every tile except the frames.

![sp_a4_stop_the_box0000](https://cloud.githubusercontent.com/assets/11165643/11414985/8f4c2280-93ca-11e5-9094-9e6ea3fd837a.jpg)

also see if you can make it so we can place these on walls too, like the image above shows, maybe have some extend out or into the wall a bit randomly like the one in the middle you can see extended out in this image above. 

my suggestion is to create a new more extream version of this item for this purpose that removes all tiles except the frames depending upon the style. in overgrown it would remove most frames too.

**Comment by TeamSpen210** [comment]
The percentage chance that a tile will be present changes depending on style. In the Art Therapy or similar variations, there'll be very few tiles. I do want to do this sort of thing, I need to figure out the right algorithm to generate random shapes like this though.

**Comment by TeamSpen210** [comment]
The frames now tilt, and the floor base also now generates the white dirt randomly.
