### ISSUE TITLE
figured out how i will release my mods

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#145]
@TeamSpen210 and @BenVlodgi, i will release my mod packages to you that you need to include in bee2.4 through weebly since it will be easier than github. i have made a very early preview of the website that will release them and a few of them, link below. there's no mods up their yet, but their will be soon.

http://ellingtonsmods.weebly.com/

**Comment by LautaroL20** [comment]
Well, i guess unfortunately the elli´s mods project is dead or something, he didn´t publish an update since 2015 :(

**Comment by Luke18033** [comment]
Most of those items have already been implemented.

**Comment by Endermage77** [comment]
The gel suspension field sounds interesting, though.

The beep test sound sounds just like the evil sort of thing GlaDOS would implement to annoy test subjects.

**Comment by BenVlodgi** [comment]
@ellingtonvengaboysmuseum I'd suggest you release them on github.

**Comment by Luke18033** [comment]
Also, just to be clear, the LCEF is *not* the original paint fizzler. Still should be implemented though.
