### ISSUE TITLE
bottomless pit suggestions for fixes

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#149]
first off, good job getting this working!

![14491998520011](https://cloud.githubusercontent.com/assets/11165643/11582049/a102029e-9a17-11e5-89fa-2d09d8718ca6.jpg)

but their are some bugs with it and i have listed potentially the best way to fix them here if the coding can be done

first off making a 1 voxel deep hole in PTI with goo is the only to generate a pit, anything else than that generates a goo pit. 

thing is when you jump into the pit you die immediatly with no fade and a hard "clunk" due to the pit generating outside the map and the hole being only skybox at the bottom

now i may have the solution to this 

OPTION A: the deeper than 1 voxel goopit generator from 1 voxel pit option

1. when a 1 voxel deep goo pit is placed in map to form a hole in floor, have the compiler generate a pit thats several voxels deep that is part of the test chamber that the player is in (as if they made a deep hole in PTI to place goo in).

2. place skybox (invisible floor and walls) at the bottom of the pit and sides in styles that require it revealing the rest of the bottomless pit and 3d skybox.

3. place a fall kill for the player and fade to black about 5 voxels down into the deep hole that was generated as part of the test chamber the player will be in. 

4. add instances to the pit built into the chamber to spice it up like random broken panels around the edges and metal frames at the top of the pit, vactubes etc.

OPTION B: the goopit override method 

1. add option to bee2 for checkbox that says "replace goo with bottomless pit"

2. tell the player to make a very deep or the DEEPEST that PTI will allow possible area for a goopit in PTI

3. when the goo is placed in the deep hole have the map compile and generate the pit as normal filling the walls in certain styles like clean, overgrown, and wheatly with skybox after a certain point, but place a fall kill trigger and fade at the top of the pit (where the top of the goo would be) have the kill and fade trigger have a timed delay for kill and fade to black so the player falls into the pit. (the player should die and it should fade to black and restart before the player hits the invisible skybox at the bottom.

4. randomly place some instances like vac tubes in deep pit

either one will work, figure how to make goo, the light bridge and laser and funnel pass all the way through and into the skybox to make it look it's going down forever.

now some suggestions for pits

BTS - similar to the one in photo, make wall textures match and use and use fog to make it look like it fades to blackness
P1 - Incinerator or a deep pitch black hole (option to choose what 3d skybox determines pit, some styles like P1 and underground would have more than 1 3D skybox)
Wheatly - self explanatory
Clean - cleaner and less chaotic than wheatly
Overgrown - broken/tilted test chambers, debree, etc, similar to clean except with skylight holes and  debris everywhere, basically a big 3D overgrown skybox area.
underground - hole in floor to goopit in dome or open dome with deep dark or lighted cave.

**Comment by Stendec-UA** [comment]
Can I ask you how you did this pit?

More precisely which tools you use?

**Comment by TeamSpen210** [comment]
The pit is a 3D skybox made of various instances. The compiler figures out where the sides of the pit are, then generates instances in matching positions in the skybox room. The goo is switched to the `tools/toolsskybox` material and flattened to 1 unit thick. The cube-dissolving trigger is switched to a teleporter, configured so it teleports into the skybox room.

**Comment by ellingtonisland** [comment]
@TeamSpen210 you need to change something with the goo so it's more than 1 unit thick, my suggestion is it needs to be at least 15 units thick and have a short time delayed trigger kill and a fade to black at the very top (where the top of the goo would be) and make sure it's deep enough so when the player falls in it fades to black and the level restarts before they hit the tools/toolsskybox at the bottom, also you need to figure how to get lasers and lightbridges and paint to be able to pass though into the skybox

**Comment by ellingtonisland** [comment]
next release will vastly improve pits - case closed
