### ISSUE TITLE
reflection gel texture and splash bugs

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#155]
reflection gel shows purple splash effects when it hits something!

![preview0003](https://cloud.githubusercontent.com/assets/11165643/11614840/96b80c8c-9c1c-11e5-9179-91f35f0a153b.jpg)

Paints player and objects orange

![preview0006](https://cloud.githubusercontent.com/assets/11165643/11614841/9f950de6-9c1c-11e5-9b39-10f962406b83.jpg)

![preview0005](https://cloud.githubusercontent.com/assets/11165643/11614842/a15cbffc-9c1c-11e5-9145-e7fd5dd01c05.jpg)

is misalligned when applied to walls etc without dropper

![preview0004](https://cloud.githubusercontent.com/assets/11165643/11614844/ae5256c2-9c1c-11e5-9d9b-3594c427e92a.jpg)

**Comment by LautaroL20** [comment]
I really wish that @TeamSpen210 Fix also the Reflection Gel for BEE 2.2.5 wich still uses same skin as the Blue gel dropper and has a lot of issues.

**Comment by ellingtonvengaboysmuseum** [comment]
see more recent issue on this - case closed

**Comment by LautaroL20** [comment]
It would really be great if @TeamSpen210 could manage to pack the "Splash green particles" with the Reflection Gel, but he said its not possible or its pretty hard to do.

**Comment by ZombiePwner1** [comment]
Ellingtonvengaboysmuseum read the wiki about reflection gel. The reflection gel is bugged itself by valve it's not bee2. Valve has left it unfinished and due to that that's why it paints things orange etc. it's not bee2.

**Comment by ZombiePwner1** [comment]
The reflection gel will always be like that valve has made it so it paints things orange. It is not caused by BEEmod itself reflection gel is just very buggy.
