### ISSUE TITLE
P1 world portal light issue

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#156]
the images explain the following issue with the new 3D portal 1 strip lights

![preview0000](https://cloud.githubusercontent.com/assets/11165643/11619209/4c5d104a-9c73-11e5-8d15-f303fe9867e8.jpg)

![preview0002](https://cloud.githubusercontent.com/assets/11165643/11619214/51df6220-9c73-11e5-9ae6-1a5fd35fd866.jpg)

![preview0003](https://cloud.githubusercontent.com/assets/11165643/11619216/551771da-9c73-11e5-8f54-1649bbf28c18.jpg)

![preview0005](https://cloud.githubusercontent.com/assets/11165643/11619219/59e4eddc-9c73-11e5-9505-46a8b9626488.jpg)

![preview0008](https://cloud.githubusercontent.com/assets/11165643/11619223/5f29611a-9c73-11e5-80b9-7eb83a1f07af.jpg)

![preview0010](https://cloud.githubusercontent.com/assets/11165643/11619224/6253f6b6-9c73-11e5-8c27-4f2d05ed6c9e.jpg)

**Comment by TeamSpen210** [comment]
This is why I added a style property to disable them. It might be computer-dependent - try changing some of your graphics settings.

**Comment by ellingtonisland** [comment]
@TeamSpen210 - is not computer-dependent, results repeated on multiple computers, all come out the same. 

i know how to solve this problem once and for all, get rid of the portal 2 light strip from portal one style all together and instead you have to make a individual item for this like the square warm light with the 3 color variations of lights with each having enough variations for the holes to appear randomly placed.

**Comment by ellingtonisland** [comment]
this problem can be solved with my new suggestion for p1 lights, case closed
