### ISSUE TITLE
Portal 1 and Clean Style Rocket Turret is Bugged

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#157]
It is very slowly when detecting the player, and the misile goes too slow too.

![preview0009](https://cloud.githubusercontent.com/assets/11165643/11619237/7c4c8952-9c73-11e5-899d-903b5d667402.jpg)

**Comment by ZombiePwner1** [comment]
Seems the line is misplaced as well.
