### ISSUE TITLE
elevator out of alignment?

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#158]
portal 1 exit elevator 2

![preview0011](https://cloud.githubusercontent.com/assets/11165643/11619256/be5a1dbe-9c73-11e5-9b24-af65b1baa15e.jpg)

**Comment by TeamSpen210** [comment]
It's not out of alignment - the elevator is slightly shorter than the tube top and bottom. The floor of the elevator is flush with the tube model.
