### ISSUE TITLE
add voice line selection for multiverse cave

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#162]
implement voice line selection for multiverse cave

**Comment by TeamSpen210** [comment]
One or two multiverse Cave lines are used in the Cave quote packs. I'd prefer to leave it as it is now - the multiverse lines do have an order and storyline, so forcing one might not make sense.

**Comment by ellingtonisland** [comment]
problem with multiverse cave is if you delete your maps from the list and create a new one, the lines become random or start at a random place. this would be a good implementation...
