### ISSUE TITLE
item: voxel shaver

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#163]
@TeamSpen210 - if this is possible, create a item that like the flat block that instead of adding to it will remove 1/4, 1/2, or 3/4ths of the voxel from the side it is placed on the voxel from 

this would work well if you placed a fizzler between two voxels and wanted to create a 1/4th thick wall on each side of the fizzler

**Comment by jccreszMinecraft** [comment]
I've got an upcoming item that is a fizzler mounted on narrow brushes, and
essentially is a narrow fizzler just big enough to walk through.

On Wed, Dec 9, 2015 at 8:17 AM, ellingtonisland <notifications@github.com>
wrote:

> @TeamSpen210 <https://github.com/TeamSpen210> - if this is possible,
> create a item that will remove 1/4, 1/2, or 3/4ths of the voxel from the
> side it is placed on the voxel from
>
> this would work well if you placed a fizzler between two voxels and wanted
> to create a 1/4th thick wall on each side of the fizzler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/163>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!
