### ISSUE TITLE
cubes not being coated by conversion gel

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#166]
cubes are not being coated by conversion gel (may be the same in all styles)

![preview0041](https://cloud.githubusercontent.com/assets/11165643/11731650/f597761a-9f6a-11e5-8e39-7e2f0d17550f.jpg)

**Comment by TeamSpen210** [comment]
Conversion Gel doesn't coat cubes... it never has.

**Comment by TheReviewers** [comment]
@ellingtonvengaboysmuseum Even If It Did Get Coated, What Would It Do?

**Comment by Enterpise** [comment]
lol, thats true. This was a hilarious post.

**Comment by TheReviewers** [comment]
@Enterpise April Fools :P

**Comment by Konclan** [comment]
Um guys what about conversion gel on light bridges!

**Comment by ZombiePwner1** [comment]
Conversion gel is useless on light bridges.
