### ISSUE TITLE
Glass Panel causes "Failure to compile" in Overgrown Style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#168]
Could not open instance file `instances/BEE2/over/items/panel_clear.vmf`.

**Comment by Konclan** [comment]
When the overgrown theme no longer has missing textures, models, and instances and all music is properly packed in maps. Then it will be enough.

**Comment by TeamSpen210** [comment]
Fixed now. I actually had made the model for it, but never did anything with it..
