### ISSUE TITLE
overgrown leaks found

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#169]
exit door 1 - i think this leak is caused by the cutout tile because it only happens when they are placed in the map.

![preview0050](https://cloud.githubusercontent.com/assets/11165643/11732270/6e183ebc-9f70-11e5-9461-83df397228cb.jpg)

on cutout tile

![preview0052](https://cloud.githubusercontent.com/assets/11165643/11732273/75304366-9f70-11e5-8dd6-7b653fd254f2.jpg)

**Comment by LautaroL20** [comment]
At least in Single-Player mode, this no longer happens anymore.
