### ISSUE TITLE
cutout tiles z-fighting bug

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#170]
z-fighting happens on random cutout tiles and the ground "flickers"

![preview0064](https://cloud.githubusercontent.com/assets/11165643/11732286/96f7ddce-9f70-11e5-97a1-fd2f73874ebc.jpg)

**Comment by TeamSpen210** [comment]
I'm not sure what the issue is here.

**Comment by jccreszMinecraft** [comment]
He's talking bout z-fighting occurring. If you put 2 unconnected partial
tiles items next to each other, their cutout z-fights. with their neighbor.

On Thu, Dec 10, 2015 at 7:59 PM, TeamSpen210 <notifications@github.com>
wrote:

> I'm not sure what the issue is here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/170#issuecomment-163799602>
> .
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by LautaroL20** [comment]
Is this a bug or something? if its a bug, surely it got fixed since some pre-releases ago already.
