### ISSUE TITLE
add marker item to destroy walls and stuff where placed

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#172]
add a marker item that destroys walls based upon style where ever it is placed. 

would create destroyed walls in overgrown and wheatley for example

**Comment by TeamSpen210** [comment]
2 problems with this: I don't actually know which surfaces are inside or outside the map. If I did it randomly, it'd cause lots of leaks. (I have a solution for that, but I have to implement that first.) The other problem is that I can't just randomly decide to replace surfaces - it might be supporting a light strip or other item, or be an important surface. The surface the compiler decides to replace might be a surface which needs to be painted with gel, or a portal placed on.

**Comment by jccreszMinecraft** [comment]
Or what about adding a little marker item for the compiler? If placed on
the wall, it would destroy that wall.

On Thu, Dec 10, 2015 at 7:47 PM, TeamSpen210 <notifications@github.com>
wrote:

> 2 problems with this: I don't actually know which surfaces are inside or
> outside the map. If I did it randomly, it'd cause lots of leaks. (I have a
> solution for that, but I have to implement that first.) The other problem
> is that I can't just randomly decide to replace surfaces - it might be
> supporting a light strip or other item, or be an important surface. The
> surface the compiler decides to replace might be a surface which needs to
> be painted with gel, or a portal placed on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/172#issuecomment-163797967>
> .
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by Stendec-UA** [comment]
it is a good idea
