### ISSUE TITLE
Antline and Indicator Panel render order issue

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#175]
antline texture overlay issue in overgrown

![preview0092](https://cloud.githubusercontent.com/assets/11165643/11732936/1cd97a64-9f77-11e5-9599-a53d9ab1bc55.jpg)

**Comment by TeamSpen210** [comment]
I've partially fixed this, so it now only happens if you look at the sign from a fair distance away. It's not really that noticeable anymore.
