### ISSUE TITLE
T-Flip Flop Item

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#176]
we need the togglable pedestal button for autoportals

**Comment by TeamSpen210** [comment]
This would probably actually be a flip-flop logic item, since it's also useful with other items.

**Comment by ellingtonisland** [comment]
best if it be a T-Flip Flop

**Comment by ellingtonvengaboysmuseum** [comment]
added into next release - case closed
