### ISSUE TITLE
Item: Panels

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#178]
@TeamSpen210 - we have been needing this one for a long time and now that the compiler is different and can create random variants it should be easy to to create wall panels with random variants 

you would need two types

4 wall panels in a full voxel (would be random for variations) make it so a trigger can be connected to them, by default they would be left hanging until a trigger was set off and made them retract

a single wall panel, make it so it can be positioned similar to the laser except in the four corners of the voxel it is on, uses random variants too and connects to trigger

also make them be able to be connected to one another because pti items like buttons and triggers can only support a max of 9 connections

**Comment by TeamSpen210** [comment]
What would they actually do? You've defined how they position, but not what animations they should use, if they should have surfaces, what they should do in Old Aperture (which shouldn't have complex panel tech).

You also don't need to `@TeamSpen210` me in every comment - I get them regardless.

**Comment by ellingtonisland** [comment]
you would need to make more than one item for panels for this to work

first you would need seperate clean and overgrown variants as two seperate items for reconstructing. maybe use start reversed to make it a clean panel in reconstructing vs a overgrown panel so you have one item in bee2.4

for animations for the retracting panels, make them random via many random variants of the item.

then you would need three seperate items for the smaller panels that would retract. one would be a regular metal or plaster panel, one glass, and the other just a panel frame. you would need a clean and overgrown variant of this for the glass and plaster panels, maybe use start reversed for this to to determine if clean or overgrown.

one would be larger panels for reconstructing that would be clean and would rotate etc or their older counterparts would fall from the ceiling like seen in the advanced areal faith plates chamber. maybe use start reversed to make them clean vs overgrown.

another item would be panels that extend up from the floor and use very specific animations to create stairs etc, use start reversed to make them overgrown vs clean when it comes to reconstructing, 3 variants of one item which would be panel, glass, and just metal frame. maybe make them like the wall blocks to determine their height they will extend up to when activated.

you make this item not listed in bee2 for old aperture styles.

**Comment by ellingtonvengaboysmuseum** [comment]
if the cutout tile uses variations based upon instances in the next update - i might be able to create this item myself - case closed
