### ISSUE TITLE
signage test element listing overrides

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#179]
we also need some form of signage overrides to override the signage for test elements like crushers etc, but also lets see if we can figure out how to create custom images for signage and have them show in game

what we need is something in the compiler of each test element that tells the signage what test elements are in a map and if possible ability to put a custom image in that the compiler will see and place on the signage for custom test elements.

**Comment by TeamSpen210** [comment]
What sort of signage exactly? I can't modify the large test chamber number signs, they're coded into the game.

**Comment by ellingtonisland** [comment]
im talking about the test elements listed in the map shown on the signage, a way to choose what ones show in test chambers, currently crushers don't show in black when one is placed in map, also a way to have custom test element icons show up on the sign

![portal_2_level_warning_signs_by_eefi-d4itsd2](https://cloud.githubusercontent.com/assets/11165643/11759768/54ff0672-a051-11e5-80e6-ace6d3b508e8.png)

**Comment by Enterpise** [comment]
@TeamSpen210 - Just get rid that definitely from the Co-op / SP Entry. Because it sometimes shows completely wrong the name´s / Number of the Workshop map author. For example: "Perer´s chamber 58" and its just his 10th chamber release, and that really sucks.

**Comment by TeamSpen210** [comment]
It's not the author's number of chambers - it displays the number in your queue.
