### ISSUE TITLE
help needed: creating custom voice lines

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#181]
@TeamSpen210 - i need help to create some custom voice lines

i need to know the code for the config files to pack them and stuff and to have bee2 read the wav files

i am planning on creating some voice lines for a new core called "Ellington Vengaboys Museum Curator Core" who is pretty much an assistant to and "pet" of GLaDOS.

**Comment by TeamSpen210** [comment]
Voice lines are defined mainly in a config file, they don't really use many instances. See `packages/valve/clean_style/voice_line/clean.cfg` for an example. They also need the info.txt definition, it's similar to things like styles or music items though.

They have the basic form:

	"Quotes"
	{
	"quote_loc" "-3000 0 0"
	"Base"	"clean/base.vmf"
	
	"Group"
		{
		"Name"			"Entry"
		"Desc"			"On Entry"
		"Choreo_Name"	"@glados_enter"
		"Choreo_Loc"	 "-2984 0 0"
		"Quote"
			{
			"Priority"	"0"
			"Name"		"Section name"
			
			"Has"       "Bridge"
			"Has"       "OtherStuff"
			
			"Line"
				{
				"Name" 		"Federal Regulations"
				"ID"		"GENERIC_1"
				"Trans" 	"Federal regulations require me to warn you that this next test chamber... is looking pretty good."
				// One of these:
				"choreo"	"scenes/choreo/scene.vcd"
				"snd"       "path/to/wav/file.wav"
				"file"      "instance/to/use.vmf"
				// Added in the next release:
				"pack"
					{
					"file" "sound/path/to/file.wav"
					"file" "sound/path/to/file2.wav"
					}
				}
			}
		}
		
	"Group"
		{
		"Name"			"Exit"
		"Desc"			"On Exit"
		"Choreo_Name"	"@glados_exit"
		"Choreo_Loc"	 "-3016 0 0"
		"Quote"
			{
			...
			}
		}
	}
	
Leave the locations alone, unless you want to move the instances. The `Base` instance is always added, modify it as needed (it's just 2 logic_relays which get trigged from the styles). Each `Group` block will have 1 voice line chosen ultimately. Basically, the highest-priority `Quote` block is chosen that has its `Has` values satisfied, and then one of its `Line` blocks is randomly chosen. The three properties `choreo`, `snd` or `file` can be used to choose what's outputted - a logic_choreographed_scene, ambient_generic or func_instance. The `choreo_name` property is used to choose the name that's given to the first two - match this to the outputs in the base instance.

For the `Has` variables ('voice attributes') either open `Portal 2/bin/bee2/vbsp_config.cfg` and Control-F search for 'Has', or check the developer console log when compiling a map for the lists of those attributes. They're stuff like 'Bridge', 'PropulsionGel', 'BlueGel', 'CubeStandard', 'Cube', etc.

**Comment by ellingtonvengaboysmuseum** [comment]
i will reopen this when i start  to create custom voice lines - case closed
