### ISSUE TITLE
bug: paint gun activation field not working

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#187]
the paint gun activation field item is not working, does nothing when i connect it to a fizzler

![preview0129](https://cloud.githubusercontent.com/assets/11165643/11763608/d5025c14-a0df-11e5-81cb-5f5f3260df27.jpg)

**Comment by TeamSpen210** [comment]
The paint gun field is disabled in normal Portal 2, since there isn't a paint gun in the first place.

**Comment by Calgarry** [comment]
Got the same problem. What should i do against it???
