### ISSUE TITLE
Bug: Reflection Gel Error

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#19]
Reflection Gel has a texture Error and does not stick to surfaces

![preview0024](https://cloud.githubusercontent.com/assets/11165643/8397427/e35c3020-1d98-11e5-8d7e-1168d98ac1f0.jpg)

**Comment by ZombiePwner1** [comment]
The reflection gel texture errors aren't caused by bee2 valve probably most likely changed them before they left the community.
