### ISSUE TITLE
video screen issue

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#196]
is this on purpose in overgrown, sometimes it happens in clean too, along with the screen being the wrong size and then it will be stretched to wide or too narrow upon the next recompile. ps just call me "the great bee2 bug finding guy"

![preview0005](https://cloud.githubusercontent.com/assets/11165643/11768849/7af5724c-a1a7-11e5-8349-0d216db4aed0.jpg)

**Comment by jccreszMinecraft** [comment]
@ellingtonvengaboysmuseum 
Please calm down on the "bug" reports. Maybe friend TeamSpen on Steam, he's online a lot.
Yes, this is likely intended but the clean style no.

**Comment by Enterpise** [comment]
I can not be more agree with @jccreszMinecraft.
@ellingtonvengaboysmuseum. Our Feed is a complete mess!! Like jccresz said, you should add him.

**Comment by ellingtonvengaboysmuseum** [comment]
@jccreszMinecraft & @Enterpise 

teamspen210 has requested that i put bug reports on github individually instead of all of them under one topic, and it is better if they come through github instead of steam because he may miss a few on steam.

if you are tired of receiving notifications from the bug reports then follow the instructions and uncheck all the checkboxes in the notification center below shown in the image, you will have to log into github to check things instead of via email

![12132749_547988162021127_1000785718_n - copy](https://cloud.githubusercontent.com/assets/11165643/11771115/c139f980-a1d9-11e5-84d9-8eb1fadce4bc.jpg)
