### ISSUE TITLE
catwalk bug

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#202]
cubes fall though catwalks like the catwalk is on noclip for physics objects.

**Comment by jccreszMinecraft** [comment]
In other words, there only seems to be a player clip instead of a clip.

On Wed, Dec 23, 2015 at 8:02 PM, the great bee2 bug finder <
notifications@github.com> wrote:

> cubes fall though catwalks like the catwalk is on noclip for physics
> objects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/202>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by Enterpise** [comment]
Catwalk item is complete crazy, it acept inputs and when you build the chamber, the only visible thing on the map is the antline without any catwalk, here is an example:

![2015-12-23_00003](https://cloud.githubusercontent.com/assets/15699236/11996294/835b4746-aa3e-11e5-85b7-89f2d1f279c6.jpg)

**Comment by TeamSpen210** [comment]
That's not how you want to use it. Place 2 catwalk items, and join those with a connection. Then pieces will be generated to connect the two points. It's not a proper connection, I'm reusing that function to indicate what to connect. You'll want to turn off the antlines.

**Comment by Enterpise** [comment]
Oh, thanks for the info! I was too disoriented with this item.

**Comment by TeamSpen210** [comment]
@ellingtonvengaboysmuseum, which styles does this occur in? I can't replicate it.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - BTS, with bottomless pits with catwalks over them, place cube dropper right over middle of catwalk and drop cube on it, it should fall though into the pit

**Comment by ellingtonvengaboysmuseum** [comment]
fixed - case closed
