### ISSUE TITLE
bottomless pits more than 1 voxel deep

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#203]
bottomless pits need to be able to be more that 1 voxel deep when placed in PTI. 

also they need something so if they are deep in PTI they will generate wall and square frame instances in the map in PTI around edge of wheatley styled pits.

**Comment by harritron2k2** [comment]
Very nice idea!
I don't know if 3 will work because @TeamSpen210 said that he can't add instances outside of the chamber space because PTI can't handle it.

Maybe he can figure out a way.
For the pit trigger, create an env_fade then below the fade create a trigger_hurt.

**Comment by LautaroL20** [comment]
I think this is now fixed.
