### ISSUE TITLE
add Mel Turrets to retro styles in all games

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#205]
add the PS Mel Turrets to the retro styles in all games, not just aperture tag!!

**Comment by TeamSpen210** [comment]
The reason I'm not doing this is because I don't want to copy or pack the content of those mods (Aperture Tag or PS:Mel). I asked LPFreaky earlier, and she said that she'd prefer to keep them unique to those mods.
