### ISSUE TITLE
I run the BEE2 in the bin folder and then well, this happens:

### ISSUE THREAD

**Issue by BarbarianKabbage** [TeamSpen210/BEE2-items#206]
![2015-12-31 13_43_59-cx_freeze_ python error in main script](https://cloud.githubusercontent.com/assets/10360446/12068543/28699e5a-afc5-11e5-9341-5cf4232ac9e6.png)

**Comment by ZombiePwner1** [comment]
Wow your still using Windows XP? Damn I wanna get that OS again.
