### ISSUE TITLE
Zip files cannot open/be extracted

### ISSUE THREAD

**Issue by CrashingScience** [TeamSpen210/BEE2-items#208]
On trying to extract or even open even of the zip files inside packages I get the error:

Windows cannot complete the extraction.

The destination file could not be created.

**Comment by k0rny13** [comment]
Hello,

I confirm that last package for pre release 16 cant be extracted.

**Comment by ellingtonvengaboysmuseum** [comment]
use 7-zip, worked fine with me with 7-zip!

**Comment by k0rny13** [comment]
I use winrar..

**Comment by Venima** [comment]
@k0rny13 Use 7-zip then. It takes a minutes to install.. (when it tells you to restart, you don't need to).

I can also confirm 7-zip works.

**Comment by TeamSpen210** [comment]
I switched to using 'LZMA' compression a while back, since it does a better job at decreasing file sizes.I accidentally used it for the container zip as well, I'll use regular compression for the next release.

**Comment by BraveCaperCat2** [comment]
This issue seems to have reoccurred recently - probably for a different reason though and it could even just be windows being weird.
