### ISSUE TITLE
idea for "open enrichment sphere" box

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#210]
i have a idea for "open enrichment sphere" box

selecting it should make not just the 80's style have a open enrichment sphere, but all the underground styles, also see if you can program something into bee2 that depending upon the style this button will change to something like "skybox elevator or open elevator"

![preview0000](https://cloud.githubusercontent.com/assets/11165643/12158093/d591d744-b4a4-11e5-8709-e46bd159e3ff.jpg)

to give you a idea, the undergound generates the test chamber where it is visible from the elevator, checking this button would generate something simular in other styles and non underground ones would have a skybox around the test chamber and elevator part and you would need special elevator instances such as in clean they would have the top part removed and the video screens removed so you could see the outside parts of the facility around the test chamber. 

![preview0017](https://cloud.githubusercontent.com/assets/11165643/12158045/71d5035c-b4a4-11e5-9ba2-72682b1d5765.jpg)

also you should remove the goo pit that is in the elevator part in the open 80's sphere and extend the cave down deeper like a bottomless pit. and place a fade and kill trigger in the enrichment sphere because you could see out through the bottom too.

**Comment by TeamSpen210** [comment]
The reason there's a goo pit is to hide an issue with the collapsed sphere model. It's way too small, and only 1 half - the map uses two overlapping models to fill the gap. If the goo was any lower you'd be able to see the holes in the bottom half.

**Comment by ellingtonvengaboysmuseum** [comment]
won't work, case closed
