### ISSUE TITLE
leak in open enrichment sphere

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#212]
leak

![preview0017](https://cloud.githubusercontent.com/assets/11165643/12158203/cb15248c-b4a5-11e5-86cd-09252ddec83e.jpg)

also you should extend this down farther and make it a skybox to create skybox fog and make it look like a bottomless pit, remove the goopit near the elevator in the sphere so the player can see down into the pit too.

**Comment by TeamSpen210** [comment]
That's on purpose, the player can't see there from inside the sphere.

**Comment by ellingtonvengaboysmuseum** [comment]
not a leak, case closed
