### ISSUE TITLE
bug: catwalks won't extend down into goo

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#217]
bug: catwalks won't extend down into goo

![preview0037](https://cloud.githubusercontent.com/assets/11165643/12160020/cff1d5f8-b4b5-11e5-882f-4d506500dc67.jpg)

**Comment by TeamSpen210** [comment]
That's on purpose, catwalk items in goo get moved to the surface - that allows you to place corners on top of goo pits. You can see the support column under the corner.
