### ISSUE TITLE
upside down video screen

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#222]
this happened in overgrown

![preview0076](https://cloud.githubusercontent.com/assets/11165643/12180397/518c4e88-b54a-11e5-813b-178c8793aff6.jpg)

**Comment by TeamSpen210** [comment]
That's on purpose - the screens aren't working properly.

**Comment by LautaroL20** [comment]
Well, i think im not the only one getting confused with certain things on the overgrown style.
