### ISSUE TITLE
Portal 1: bottomless pit fog

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#226]
the portal 1 bottomless pit is near complete. but the bee2 compiler needs some specific commands added to it that depending upon the 3D skybox chosen from the editor, commands that override the color, and start and end distances of the fog used in the test chamber (not the fog used in the skybox) fix issues with fog. the second photo shows the problem with the fog that requires a override so the fog will blend properly

![preview0178](https://cloud.githubusercontent.com/assets/11165643/12219858/b6f43d24-b722-11e5-97cc-7a2614d68273.jpg)

![preview0179](https://cloud.githubusercontent.com/assets/11165643/12219862/d50552f8-b722-11e5-9776-acaccd1979c3.jpg)

**Comment by CrashingScience** [comment]
how do u use a p1 bottomless pit?

**Comment by TeamSpen210** [comment]
Ellingtonisland is working on his own bottomless pit, it's not publicly available.

**Comment by CrashingScience** [comment]
Ok

**Comment by ellingtonvengaboysmuseum** [comment]
fog blend fixed in next release - case closed
