### ISSUE TITLE
bug: getting two cubes out of a dropper in P1 (maybe other styles too)

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#228]
how to reproduce bug

place cube dropper 2 voxels above floor, place dropper reset pedistal button just below it.
when cube drops out grab it and hold it up against door as door closes, if cube gets stuck, dropper will generate two cubes

![preview0184](https://cloud.githubusercontent.com/assets/11165643/12222414/b3b80444-b789-11e5-9185-0965bf8fe135.jpg)

press button and first cube will fizzle and new one will drop, press button again and second glitch cube will drop too, both cubes will fizzle when destroyed. 

![preview0183](https://cloud.githubusercontent.com/assets/11165643/12222419/dcbdec46-b789-11e5-9c1b-5efcdfc799de.jpg)

**Comment by TeamSpen210** [comment]
This can actually be done with most of the Portal 2 droppers, including the BEE2 ones. Place the droppers higher up to stop players from doing it.

**Comment by ellingtonvengaboysmuseum** [comment]
fixed in next release - case closed
