### ISSUE TITLE
is there anyway to solve this?

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#230]
you got turrets and cubes to teleport into the pit... now 

is there anyway to pass lightbridges, lasers, paint etc into the pit, anyway what's so ever.

![preview0203](https://cloud.githubusercontent.com/assets/11165643/12222707/00709a82-b792-11e5-8696-7dc84c33d209.jpg)

**Comment by TeamSpen210** [comment]
Not really - it's not a good idea anyway. For bridges and funnels, if they could go into the pit you could stand/float on them and potentially escape the skybox room.
