### ISSUE TITLE
how will you create the retro style bottomless pit that's within a enrichment sphere

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#232]
how will you create the retro style bottomless pit that's within a enrichment sphere since there is a size limit to the enrichment spheres and PTI can make test chambers that are larger than the enrichment spheres there in.

**Comment by TeamSpen210** [comment]
I can recompile the sphere model to make it larger.

**Comment by ellingtonvengaboysmuseum** [comment]
ok... larger sphere, hope it looks nice

**Comment by ellingtonvengaboysmuseum** [comment]
knowing how this will happen now - case closed
