### ISSUE TITLE
need help with pit "support instance" and config just in case i use it

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#235]
i need help with the code for the bottomless pit config, just incase i use it, what is the exact code to get the support instances in and where do they get placed when the code is right.

**Comment by TeamSpen210** [comment]
Support instances are placed on top of some of other side instances randomly. They're not useful for BTS, but better for other styles where there's only wall at the top. You'd put pillar or truss models in the support instances, and get them placed around the pit so it looks like they're being held up.

**Comment by ellingtonvengaboysmuseum** [comment]
this will be looked into later when needed - case closed
