### ISSUE TITLE
help needed with some advanced bee2 mods

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#236]
i am planning to create toggle able light stripes and make some new bee2 items that will make them look nice in game when used. 

what program do i use to add a new skin to the light strips i need to add off and cold skins to some of them. 

what do i need to do to make items be able to be hooked up to a button or trigger in the config text files

what items do i use in hammer to create the darkness effect seen in the one BTS test chamber where the lights go out and wheatley turns on his flashlight. 

is there a way to create a item that will override the light values used for "pit_blend" upon activation

**Comment by TeamSpen210** [comment]
There isn't a way to override light_blend; regardless, the ambient light instances are much brighter than that. The way Valve did the brightness effect was to make two copies of the room, and teleport you into the dark one. To make darkness, you just need to not have light ents, turn them off, or use the `tools/blocklight` texture to stop light from reaching a room.

To make items have input or output, you need the `ConnectionPoints` section in editoritems to define antline positioning. (Copy from a similarly-shaped item.) For inputs, you need a `ConnectionCount` in the `Properties` block as well as an `Inputs` section. For outputs, you need an `Outputs` section. (Look at existing items for the syntax.) 

If you're trying to make toggleable lights, you'll really want to be using @names for the lights to limit the number of different light names. 

To change skins, you'll first need to extract the model files with GCFScape. Decompile them with Crowbar, and then you can edit the .qc file to add additional skins. Then recompile with Crowbar. For the textures, you'll need to extract the original VTF and VMT files, rename them, and modify the texture as needed with an image editor.
