### ISSUE TITLE
bug: tiny crack in fizzler fields

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#238]
tiny crack in fizzler fields, you need to look closely at the photo to see it. it's within the red circle... this happens on all fizzlers

![preview0233](https://cloud.githubusercontent.com/assets/11165643/12269891/8a3e83d8-b921-11e5-8677-7550a705d34b.jpg)

**Comment by ellingtonvengaboysmuseum** [comment]
will no draw fix this

**Comment by TeamSpen210** [comment]
This actually happens in Valve maps too - it's not really a BEE bug.

**Comment by TeamSpen210** [comment]
Note: This is fixed by compiler.
