### ISSUE TITLE
bug: videos getting compacted on elevator screens in clean style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#239]
videos are getting compacted on elevator screens in clean style

this happens with a lot of them.

![preview0272](https://cloud.githubusercontent.com/assets/11165643/12270636/08b07390-b925-11e5-9cdc-19bcd8cf918a.jpg)

**Comment by jccreszMinecraft** [comment]
Can confirm this isn't a one-off issue. Multiple compiles usually gets it
right but it never lasts.

On Tue, Jan 12, 2016 at 12:07 PM, the great bee2 bug finder <
notifications@github.com> wrote:

> videos are getting compacted on elevator screens in clean style
>
> this happens with a lot of them.
>
> [image: preview0272]
> <https://cloud.githubusercontent.com/assets/11165643/12270636/08b07390-b925-11e5-9cdc-19bcd8cf918a.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/239>.
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by TeamSpen210** [comment]
Every time you run a map, one of several scaling options is chosen. The script is based off of Valve's original one, I think this happens in the original PeTI elevator.

**Comment by ellingtonvengaboysmuseum** [comment]
the peti elevator is diffrent

**Comment by LautaroL20** [comment]
Well, it should be fixed now.
