### ISSUE TITLE
help needed putting output trigger in custom fizzler field

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#240]
i need help putting a output trigger in a fizzler field

this is my current code in the config file

```
"Conditions"
	{
	"Condition"  
		{ 
		"instance"	"instances/BEE2/clean/items/evm/pf_base.vmf"  
		"result"  
			{			
			"Pack" "PACK_EVM_PHYSICS_FIELD"
			"Pack" "PACK_BEE2_CUST_FIZZ_MDL"
			"Has"
				{
				"Fizzler"	"1"
				"Physics_Field"	"1"
				}
			"CustFizzler"
				{
				"ModelName"		""
				"UniqueModel"	"0"
				"Brush"
					{
					"Name"		"fizz"
					"Left"		"BEE2/fizz/evm/clean_pf_left"
					"Center"	"BEE2/fizz/evm/clean_pf_center"
					"Right"		"BEE2/fizz/evm/clean_pf_right"
					"Short"		"BEE2/fizz/evm/physics_field"
					"Keys"
						{
						"classname" 	"trigger_portal_cleanser"
						"Spawnflags" 	"1" // portals
						"solidity"		"1"
						"visible"		"1"	
						"usescanline"	"1"						
						"StartDisabled"	"0"
						}
					}
				"Brush"
					{
					"Name"		"freeze"
					"Left"		"BEE2/fizz/evm/clean_pf_left"
					"Center"	"BEE2/fizz/evm/clean_pf_center"
					"Right"		"BEE2/fizz/evm/clean_pf_right"
					"Short"		"BEE2/fizz/evm/physics_field"
					"Keys"
						{
						"classname" 	"func_clip_vphysics"
						"Spawnflags" 	"1" // players
						"solidity"		"1"
						"visible"		"1"	
						"usescanline"	"0"						
						"StartDisabled"	"1"
						}
					}
				"Brush"
					{
					"Name"		"clip"
					"Left"		"tools/toolsinvisible"
					"Center"	        "tools/toolsinvisible"
					"Right"		"tools/toolsinvisible"
					"Short"		"tools/toolsinvisible"
					"Nodraw"	        "tools/toolsinvisible"
					"Keys"
						{
						"classname" 	"func_clip_vphysics"
						}
					}
				"Brush"
					{
					"Name"		"freeze_trigger"
					"Left"		"tools/toolstrigger"
					"Center"	        "tools/toolstrigger"
					"Right"		"tools/toolstrigger"
					"Short"		"tools/toolstrigger"
					"Nodraw"	        "tools/toolstrigger"
					"Keys"
						{
						"classname" 	 "trigger"
						"Spawnflags" 	 "8" // cubes									
						"StartDisabled"	 "1"
						}
					}
				}
			}
		}
	}
```

you see where it says "freeze_trigger" in there, i want to know the exact code to put in to have that trigger send output to the freeze brush when a cube touches it along with a player physics brush to enable both of them when a cube comes in contact with the field, and also disable both if a cube is not touching the trigger in the field. 

when complete the field will solidify like ice when a cube touches it and even the player can walk on it if frozen over when a cube remains on it, upon picking up that cube if the cube doesn't touch it, it will return to normal state.

**Comment by ellingtonvengaboysmuseum** [comment]
is this the correct code for a trigger?

```
"Brush"
					{
					"Name"		"freeze_trigger"
					"Left"		"tools/toolstrigger"
					"Center"	"tools/toolstrigger"
					"Right"		"tools/toolstrigger"
					"Short"		"tools/toolstrigger"
					"Nodraw"	"tools/toolstrigger"
					"Keys"
						{
						"classname" 	"trigger_multiple"
						"Spawnflags" 	"10" // cubes									
						"StartDisabled"	"1"
						}
					"Outputs"
					{
					"CONNECTION_STANDARD"
						{
						"OnTouching"		"instance:freeze_on_logic;OnTrigger" // starts the freeze
						"OnNotTouching"		"instance:freeze_off_logic;OnTrigger" // stops the freeze
						}
					}
				}
```

**Comment by TeamSpen210** [comment]
CustFizzler doesn't have the capability for outputs on the triggers currently. I'll need to add it. One problem with that is that if the clips get enabled with while the player's in the field, they'll become trapped and won't be able to move. You probably actually want the vphysics clip to be always on, that way the cube can't get stuck. Then make the trigger slightly thicker with the `Thickness` option.

The property will be something more like:
```
"addout"
    {
    "Output" "OnStartTouch"
    "Target" "freeze_on_logic"
    "Input" "Trigger"
    }
```
That way you can specify every part of the outputs.

**Comment by ellingtonvengaboysmuseum** [comment]
what is the code for the thickness option

**Comment by TeamSpen210** [comment]
I will. Add a `"Thickness"` property to the `"Brush"` block, set to the desired width for a trigger. (They default to 2).

**Comment by ellingtonvengaboysmuseum** [comment]
what would a good thickness be? i want it so when the player comes within a voxel of the field with a cube it will activate the freeze effect

**Comment by ellingtonvengaboysmuseum** [comment]
how can i make a fizzler field light up when a player comes near it too like it does when a cube or turret comes near it that it's about to fizzle

**Comment by TeamSpen210** [comment]
That's a specially-coded feature of fizzlers - the best way to emulate it would be to create a second overlapping func_brush, with an additional texture and enable it with the clips.

**Comment by ellingtonvengaboysmuseum** [comment]
i just need a small part to light up, not the whole thing, like it does with cubes. i want it to do the same with players, is there a way to parent a brush to the player so when they come near it it lights up.
