### ISSUE TITLE
bugs that exist that still need to be fixed

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#242]
i am making a checklist of bugs / things that need to be fixed to get them more organized under one topic. orginal topics of these bugs closed - see closed topics for images if needed.

- [ ] the overgrown exit elevators need logic in them to restart the level to solve the problem of the player falling out of the elevator when it vanishes at end.
- [ ] track platform in overgrown is clean style
- [ ] reflection gel has the wrong splash effect and when applied doors and the player is orange
- [ ] default observation room in 60's style has leak
- [ ] rocket turrets are misaligned, also they misfire and bomb explodes right at turret. also same bug is in all styles!
- [ ] clean type of piston stairs used in overgrown
- [ ] missing asset error: Could not open instance file instances/BEE2/voice/ann_apoc/entry_jazz.vmf
- [ ] missing asset error: Could not open instance file instances/BEE2/over/items/panel_clear.vmf
- [ ] cutout tile causes leaks when more than two are connected together and they z-fight
- [ ] cutout tiles z-fight when more than two are connected together
- [ ] missing asset error: Could not open instance file instances/BEE2/50s/items/mech_plate_angled.vmf
- [ ] certain items like piston platforms and catwalks under goo placed in bottomless pits float in air. these items need something to generate a special piller when placed in bottomless pits
- [ ] instance collision sometimes happens in corner of bottomless pit with panel arms, this could be fixed by adding a |_ corner generator
- [ ] atlas portal gun is in wrong place
- [ ] fizzler fields have a tiny crack in field near fizzler model
- [ ] videos get compacted on elevator screens, this is NOT how they work in the original PTI
- [ ] the single panel in overgrown entry door 1 has clip enabled still when retracted into wall
- [ ] exit door in portal 1 style exit corridor 1 has leak
- [ ] 50's catwalk near exit is out of alignment by less than 1 unit
- [ ] upon compile p1 90 degree angled panel gives error is vbsp config, due to missing item
- [ ] being able to place rocket turret on bottom voxel of wall in portal 1 style causes a leak in exit door 1
- [ ] placing a unstationary scaffold in P1 style causes the following "Could not open instance file instances/BEE2/p1/items/track/bottom_grate.vmf"
- [ ] placing a victory lift in P1 style causes the following "Could not open instance file instances/BEE2/p1/items/pist_plat.vmf"
- [ ] paint fizzler model is wrong in P1 Style (will be fixed by me when i replace paint fizzler with liquid color excision field)
- [ ] standalone door is wrong type in P1 style
- [ ] HEP launcher and catcher are wrong type in P1 style
- [ ] unpublishing published test chamber from editor causes game crash

**Comment by TeamSpen210** [comment]
Please don't. It's better if they're seperate, especially since these have nothing to do with each other.
