### ISSUE TITLE
question: is it possible to create variations of each of the individual variations of the entry and exit corradors

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#243]
is it possible to create variations of each individual variation of the 7 entry and 4 exit corridors like you can do with items?

for example i want to create like 10 variations of the "right turn" corridor in clean style and these ten variations will have things changed like some square frames exposed, missing or glass panels, panels that retract in, etc.

**Comment by TeamSpen210** [comment]
Yes, but they won't appear in the compiler pane dropdown. Look at some of the overgrown items especially for examples - you want to use the `Random` or `Variant` results.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210  - they will not be listed in the drop down pane, they will be random variations of each of the 7 variations in the pane window, also see my issue on a water goo pit
