### ISSUE TITLE
help needed: creating new goo pit type

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#244]
i want to create new goo pit type that will replace the toxic sludge with a custom texture of clear water, how do i do that besides extracting the custom texture from source sdk. 

here is the basics of it

it will not hurt players and they will be able to swim through it
it will mainly be for a aesthetic effect
buttons will be able to be placed in it
there will be a variant with drain vents in the floor that uses trigger push to make cubes float on the surface
there will be four special variants besides the normal one with running water currents that will push the player in a certain direction if they fall in.
it will make turrets self destruct when they fall in
it will dissolve paint that comes into contact with it
in a custom freezer style with custom textures and everything i will create a frozen solid variant that will be slippery that the ice could be cracked and shattered on with a bomb from a bomb dropper. but don't go swimming in it!

**Comment by TeamSpen210** [comment]
* I can't really modify the goo item in any way, any custom ones export exactly the same. You'd need to place the goo item, then a second marker item.
* I can't prevent too from blocking everything from being placed in it
* Turrets are waterproof - try covering them in cleansing gel, or dipping them in the top of goo
* Paint is automatically blocked by water.

**Comment by ellingtonvengaboysmuseum** [comment]
there is no way to modify the texture the goo itself uses from the vbsp config or something. 

there is no way to change what the triggers in the goo do

the water pit will block paint like normal goo

**Comment by BenVlodgi** [comment]
@TeamSpen210 When compiling the map, do we have a copy of the puzzle file? If so, we could look for special goo items as flags.

**Comment by TeamSpen210** [comment]
Currently the compiler doesn't touch the p2c file. It'd be simple to parse it, but I'll need to do some tests to determine if Portal saves the puzzle to disk when compiling - if it doesn't, the puzzle and map might not match and cause issues.

**Comment by BenVlodgi** [comment]
@TeamSpen210 Good point.
Are there no artifacts left over from the puzzlemaker export from a custom goo item with the goo class in the vmf?

**Comment by TeamSpen210** [comment]
Just the normal brush and triggers, identical to the regular item.
