### ISSUE TITLE
help needed with modding the main game

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#245]
i am planning on creating a big mod for portal 2 that will get on steam one day like portal stories mel did

the mod is going to be called Portal: Past, Present, and Future

the main plot of the game will be about how glados secretly created atlas and p body and a new core obsessed with Vengaboys called "Ellington Vengaboys Museum Curator Core" as the core parts a time machine as a experiment to prove if parallel universes exist and the game will mainly involve a function that uses a timeline menu for time travel and how choices in certain levels will lead to and unlock alternate timelines and unlock different parts of that menu (similar to style of the Stanley Parable)

this is what i am going to need help with 

coding a new menu on the in level pause screen called "timelines" which will have selections that will unlock and show new options to access alternate timelines (levels) as the player progresses through the game. in game this menu will be explained as part of a device coded into the two robots that will allow them to travel back to a point when their time machine takes a snapshot of the current existing timeline. 

for example the first option on the menu will say "Time Travel Beginnings" and when the player gets to a certain part in the game that introduces time travel there will be two buttons, pressing one will send the player into a future map. the other will send them into the past. depending upon which one is pressed, the timeline menu will have a new item that will say something like "1940's timeline" for past and "GlaDoS Failure Timeline" for future and each time line will have choices that unlock newer timelines

i will paste the code for modifying the games menu's in here soon that i need help with

**Comment by TeamSpen210** [comment]
I don't think that sort of menu is possible. Regardless, this isn't related to the BEE2.
