### ISSUE TITLE
make entry and exit doors used in test chamber world portal doors to solve embedded voxel collision problem

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#247]
@BenVlodgi and @TeamSpen210 

teamspen210, i think ben will agree with me on this one... well 

if possible you guys need to make the entry and exit doors used in the test chamber world portal doors (the ones in the test chamber you edit in PTI, not the ones betwee the elevator and entry and exit corradors) and get rid of the large embedded 3x3 voxel

you should be able to pull off something with the entry and exit door simular with world portals like you did with the embedded fizzler

this will solve the problem of embedded voxels interfering on entry and exit corradors like in the image below

![preview0320](https://cloud.githubusercontent.com/assets/11165643/12342100/218f3672-baf5-11e5-83e1-6bbadc27395f.jpg)

also it will save cpu resources by getting rid of world portals in the overgrown entry and exit corradors that are used to make them appear larger and you will be able to combine them and make a large entry or exit corrador far away from the map voxels, you will need to do this in wheatly style if your entry or exit has a bottomless pit.

**Comment by TeamSpen210** [comment]
This is not a bug! Those 128x128x4 brushes form the floors, walls and ceilings of the blocks the corridor is embedded in. Your corridor is just too big for the space its supposed to fit in.
