### ISSUE TITLE
is a NOT has condition possible in the vbsp config for overlays

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#249]
is a NOT condition possible in the vbsp config for overlays

for example take a look at this code

```
"Conditions"
	{	
	"Condition"
		{
		"Priority"	"10"
		"instance"	"instances/BEE2/clean/elevator_sp/door_entrance_2.vmf"
		"Result"
			{
			"Condition"
				{
				"has"	"whiteGel"
				"Result"
					{
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/whitegel.vmf"
						}
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/tube.vmf"
						}
					"endCondition"	""
					}
				}
			"Condition"
				{
				"has"	"orangeGel"
				"Result"
					{
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/orangegel.vmf"
						}
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/tube.vmf"
						}
					"endCondition"	""
					}
				}
			"Condition"
				{
				"has"	"blueGel"
				"Result"
					{
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/bluegel.vmf"
						}
					"addOverlay"
						{
						"File"	"instances/BEE2/clean/elevator_sp/entrance_2/tube.vmf"
						}
					"endCondition"	""
					}
				}
			}
		}
	}
```

and then say where it says "has"     "whiteGel" 

is there a way to make the has use a NOT gate like condtion for example like "not has"      "whiteGel"

if we can pull this off this will work for controlling something in the entry and exit corridors with a wonderful idea i have

**Comment by TeamSpen210** [comment]
Yes. There are two ways to do it.

	"Condition"
		{
		"Not"
			{
			"Has" "whiteGel"
			}
		"Result"
			{
			....
			}
		}

You can surround the `has` flag in a `NOT` flag. 

	"Condition"
		{
		"Has"  "whiteGel"
		"Result"
			{
			...
			}
		"Else"
			{
			...
			}
		}

The results in the `else` block are run instead if the flags fail. 
Something to know: the `EndCondition` result aborts the entire condition block, so no other parts run. I used that in the original config to ensure only 1 tube is added.
