### ISSUE TITLE
verticle door vmf is corrupted

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#251]
when i downloaded your verticle door instance from github (vmf) because i wanted to see what it looked like, hammer hanged around 5% loading and froze, file is corrupted

**Comment by TeamSpen210** [comment]
If you're doing that via the website, did you make sure to download the correct version? You need to open the page, and then click on the 'raw' link to get just the file without the webpage parts.

**Comment by ellingtonvengaboysmuseum** [comment]
this is fine, case closed
