### ISSUE TITLE
using cutout tile in overgrown causes the following

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#265]
Could not open instance file instances/BEE2/logic/blocks/cutout_tile.vmf

**Comment by BenVlodgi** [comment]
what was the error?

**Comment by ellingtonvengaboysmuseum** [comment]
@BenVlodgi  -  

could not open instance file instances/BEE2/logic/blocks/cutout_tile.vmf 
was the error listed in the debug console in portal 2

**Comment by BenVlodgi** [comment]
@TeamSpen210 
Looks like a folder of instances was not committed, I'm thinking this one...
_packages\decoration\resources\instances/BEE2/logic/blocks/_
