### ISSUE TITLE
leak in overgrown and clean entrance 1

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#266]
leak in overgrown and clean entrance 1 in pre release 17

![preview0005](https://cloud.githubusercontent.com/assets/11165643/12703617/84034b40-c815-11e5-92f7-8d46b8e1ea15.jpg)

**Comment by BenVlodgi** [comment]
Looks like a linked portal isn't drawing

**Comment by LautaroL20** [comment]
This no longer happens on SP mode, at least in Clean Style. Overgrown Co-op still is causing some leaks though.
