### ISSUE TITLE
Couldn't find Trigger Once.vmf

### ISSUE THREAD

**Issue by xDadiKx** [TeamSpen210/BEE2-items#267]
Placed a trigger once block, tried to compile it, didn't work.

Loading F:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/logic/bee/trigger_once.vmf

I went to the file and it was right, there was no trigger_once.vmf

Same with trigger_multiple and autosave.

**Comment by BenVlodgi** [comment]
Thanks @xDadiKx 

This may be related to #265 where all the _logic/blocks_ instances were missing

@TeamSpen210 is there a folder missing somehwhere around _packages\decoration\resources\instances/BEE2/logic/_

**Comment by xDadiKx** [comment]
No problem. The logic folder is there, but it is missing few instances like the Trigger Once.

**Comment by TeamSpen210** [comment]
The missing instances are actually intentional - I'm generating the triggers using the compiler, to allow them to be resized. It's a bug with the compiler not doing that correctly. The various partial block items and cutout tiles also don't use instances, so they can automatically match the style.

**Comment by BenVlodgi** [comment]
That is awesome!
