### ISSUE TITLE
Warm Light Strip: over-saturated HDR lighting

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#274]
This happens at least in "Clean Style":

In the case of the ordinary "Light Strip", when you are approaching and moving away from it, brightness seems to be under control:

Ordinary "Light Strip" Brightness:

![light strip brightnes](https://cloud.githubusercontent.com/assets/12244376/12911575/45eb18e0-cef2-11e5-8f29-029c1d767a73.gif)

-------------------------------------------------------------------------------------------

But it is completely different for the "Warm Light Strip", you can clearly see how its brightness gets over-saturated when you are approaching and moving away from it. This couldn't be normal:

"Warm Light Strip Brightness:

![warm light strip brightnes](https://cloud.githubusercontent.com/assets/12244376/12911724/39120632-cef3-11e5-8d68-b80951e8f593.gif)

**Comment by TeamSpen210** [comment]
This effect is actually intentionally coded into the game engine. It simulates your eyes adjusting to different brightness levels. Both light types should have the same brightness; you can see the effect on the warm strips because the light colour constrasts with the cool ambient lighting.

**Comment by LautaroL20** [comment]
In that case, i suggest to make an alternate "Static Warm Light Strip" in wich this effect remains static as the Warm Light from the dinosaur "Bee2 Alpha 2.2.5".

**Comment by TeamSpen210** [comment]
It's not to do with the light strip itself - it's an effect with bright light sources. You might want to try different skybox settings - these also control this effect.

**Comment by LautaroL20** [comment]
Is somewhere this "Skybox setting" in the Bee2.4 interface? I wasn't able to find it.

**Comment by TeamSpen210** [comment]
It's one of the item selectors (where styles, music and voicelines are).

**Comment by LautaroL20** [comment]
I was testing all the Skybox settings available on the Bee 2.4 interface, and the most close for a static "Light Strip brightness", it was under the "Portal 1" Skybox, but then there is a problem with the Large Observation room and the Smallers, they brings a poorly brightness.

The solution for this:

i'd suggest to make a Special Skybox setting for Clean Style, in which it brings a "Static" brightness for Light Strips, at the same time that it does not interfer with "Observation rooms" by reducing its luminosity.
	
Ive taken two screenshots, one from the Bee 2.4 settings rendering, and another from the Bee2.2.5 Alpha:

1.
![2016-02-09_00016](https://cloud.githubusercontent.com/assets/12244376/12914477/2956bcbe-cf03-11e5-9d62-958e0b5cee63.jpg)
2.
![2016-02-09_00017](https://cloud.githubusercontent.com/assets/12244376/12914501/52604d64-cf03-11e5-975b-ba45c863043c.jpg)

**Comment by BenVlodgi** [comment]
This is not really the responsibility of the BEE2, if you want finite light settings, that should be something you develop in hammer. Most people never notice lighting, and they really wont notice static lighting. Additionally, the dynamic light affect is (as pointed out by Teamspen210) an intentional creation by the engine designers.

**Comment by LautaroL20** [comment]
So, i was checking the vmf file from the beemod 2.4 warm light strip, and it have 3 lights instead of one, and this was making to look over-saturate. Ill fix it myself.

**Comment by TeamSpen210** [comment]
The reason I changed that was to make the light cast more realistically - now it actually casts a more rectangular area, instead of being exactly the same in vertical and horizontal orientations.
