### ISSUE TITLE
Wrong placement effects on the "Custom Fizzlers" in all the Old Apertures Styles

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#276]
Screenshots showing this bug:

![2016-02-09_00011](https://cloud.githubusercontent.com/assets/12244376/12915236/99556614-cf08-11e5-88c0-7b4b2fcb79cc.jpg)

![2016-02-09_00012](https://cloud.githubusercontent.com/assets/12244376/12915242/a5e877a4-cf08-11e5-96cf-052df92f87c9.jpg)

**Comment by BenVlodgi** [comment]
texture stretching... but it looks pretty dope
