### ISSUE TITLE
CO-OP Exit Door from 70´s old aperture Has Visible "Nodraw"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#279]
In-Game Screenshot showing the bug, click on the pict to see in "Max Res"

![visible nodraw in the exit co-op door from 70 s old aperture](https://cloud.githubusercontent.com/assets/12244376/12937284/f1f0bcce-cf85-11e5-8853-9c32b64217fc.jpg)

**Comment by ZombiePwner1** [comment]
Where's the fizzler disappeared to?

**Comment by LautaroL20** [comment]
I think that this bug has been fixed already.

**Comment by ZombiePwner1** [comment]
Fixed.
