### ISSUE TITLE
SP Exit Door from 50´s Old Aperture becomes "Black" when player walks away from it

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#281]
Animated Gif showing the bug:

![50 s old aperture sp exit missing skybox](https://cloud.githubusercontent.com/assets/12244376/12937449/6b372f0e-cf87-11e5-9166-d3d404927968.gif)

**Comment by TeamSpen210** [comment]
Fixed by 0633e213f517298d34963419e0e14ed5e53f52fe.
