### ISSUE TITLE
60´s, 70´s and 80´s Old Apertures: SP Exit door "Dissapear" and becomes walkable 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#282]
Ive maded some gifs of how this bug affects the Single-Player exits, from the Old Apertures:

Exit door from 60´s Old aperture:

![60 s old aperture sp exit dissapear and becomes traspasable](https://cloud.githubusercontent.com/assets/12244376/12937641/71312d0e-cf89-11e5-922b-4548d1f3800b.gif)

Exit door from 70´s Old aperture:

![70 s old aperture sp exit dissapear and becomes traspasable](https://cloud.githubusercontent.com/assets/12244376/12937632/4c0d56a6-cf89-11e5-8a3d-199104100c6d.gif)

Exit door from 80´s Old aperture:

![80 s old aperture sp exit dissapear and becomes traspasable](https://cloud.githubusercontent.com/assets/12244376/12937670/cd237770-cf89-11e5-828d-d1091783c008.gif)

**Comment by TeamSpen210** [comment]
Fixed by 0633e213f517298d34963419e0e14ed5e53f52fe.

**Comment by LautaroL20** [comment]
Now there is only left one SP Exit door to fix, wich is from the 60´s Old Aperture, the post from this bug is here: https://github.com/TeamSpen210/BEE2-items/issues/381
