### ISSUE TITLE
[PRL22 Visual Bug] Circular Floor elevator becomes "Black" when elevator goes away

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#287]
Im not sure if this is related to any "Skybox Setting" but, when the elevator goes away, circular floor becomes totally black, instead of still keep some visibility.
![2016-02-10_00004](https://cloud.githubusercontent.com/assets/12244376/12938833/84830176-cf97-11e5-8d31-673df60d6684.jpg)

Here is an example of a circular floor still remaining visible even when elevator goes away:

![612879469_preview_2016-02-06_00009](https://cloud.githubusercontent.com/assets/12244376/12938866/e143ae38-cf97-11e5-926b-9608646c361d.jpg)

**Comment by ZombiePwner1** [comment]
That would be a shadow bug with the frames near the screens shadows can be disabled in the item on hammer.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Indeed, but fixed it.

**Comment by LautaroL20** [comment]
The fix for this is easier than i thought: 

Make sure that "elevator_roof_collar.mdl" have disabled all type of shadows in the hammer properties from the entrance_elevator.vmf instance.

**Comment by LautaroL20** [comment]
Added fixed label because this commit: " Fix elevator floor shadows"  "9065031"

Ref: https://github.com/TeamSpen210/BEE2-items/compare/dev

**Comment by TeamSpen210** [comment]
To refer to a commit, just paste the commit hash by itself:
9065031355ff0f970795c7f4ee5ac223bfaefb37
