### ISSUE TITLE
ben's diversity vent causes compile error

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#29]
ben's diversity vent causes compile error in clean default glados style.

[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198025151093\autosave.p2c
Ellington Isle unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198025151093\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198025151093\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198025151093\1435513334.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 92 (ms)

VBSP failed.

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Loading settings...
{}
Settings Loaded!
PeTI map detected!
Parsing Map...
Parsing complete!
Forcing elevator spawn!
1 1 0
Setting exit to 1
Setting entry to 1
Game Mode: SP
Is Preview: False
Checking Conditions...
Exiting empty condition!
Exiting empty condition!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
"instpart" is not a valid condition flag!
Starting catwalk generator...
Exiting empty condition!
Exiting empty condition!
Adding Singleplayer voice lines!
Adding Voice!
No Data!
Adding Portal Bumpers to fizzlers...
Done!
Map has attributes:  ['cubenotcomp', 'cubenotball', 'dualportalgun', 'cubenotfrank', 'standardcube', 'cubedropper', 'cube']
Style Vars: {'multiversecave': True, 'fixportalbump': True, 'unlockdefault': False, 'fixfizzlerbump': True, 'nomidvoices': False, 'doorcameras': True}
Global instances:  {'instances/BEE2/clean/global_ents.vmf'}
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
True
Glass inst NONE
Adding Goo Mist...
Done!
Editing Overlays...
Editing Triggers...
Editing Brush Entities...
Editing WorldSpawn
Saving New Map...
Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2014)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/bee/vent_end_white.vmf

VBSP failed! (1)

**Comment by seamuskills** [comment]
pr 27 still getting this issue 
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_APOC'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (116 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.vactubes.res_make_vactubes(): Markers: dict_keys(['vac8645', 'vac11706', 'vac22996', 'vac25713', 'vac30578', 'vac32107', 'vac34572', 'vac48579'])
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it55622', 'vac11706'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac22996', 'it55623'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac25713', 'it55624'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac30578', 'it55625'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'vac34572', 'it55626'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it55627', 'vac48579'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: {'it55628', 'vac32107'}
[INFO] cond.vactubes.res_make_vactubes(): Outputs: set()
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 3/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "DEADLY_NO_SAFETY"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/glados/prehub47.vcd"
 | 		"2" "npc/glados/prehub48.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 1/4 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_UNDESERVED"
 | 	"Choreo" "npc/glados/prehub32.vcd"
 | 	}
 |_

[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[INFO] vbsp.anti_fizz_bump(): Done!
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['goo', 'has', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubebutton', 'floorbutton', 'buttonacceptscube', 'deadly', 'turret', 'pack_p1_radio_clean', 'pelletcatcher', 'pellet', 'pelletlauncher', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=11947, misses=354, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': True, 'p1_ported_pgun': True, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': False, 'enableshapesignageframe': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/set_portalgun.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 8, 352.0: 1})
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[WARNING] vbsp.make_packlist(): Packlist "PACK_P1_BUTTON_SND" does not exist!
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_pgun_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/p1_physics_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/pellet_sounds.txt"
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_physics.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_player_portal2.txt"
[INFO] vbsp.make_packlist(): "-#scripts/game_sounds_weapons_portal.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fizz_side.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz_sides/side_color_FF0000.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/corner_floor.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/corner_wall.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/p1_antline_floor_double.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/p1_antline_wall_double.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/straight_floor.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/straight_wall.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/p1_pgun/v_portalgun_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_lfield/p1_lfield.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_lfield/p1_lfield.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/kb_mouse.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/kb_mouse.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/turret/turret_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/turret/turret_off_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/turret/turret_off_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/turret/turret_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/walllight_sheet.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/goo/beneath.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/goo/goo_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/goo/p1_goo.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/goo/p1_goo.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/goo/toxic_rep_flowmapr.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/laserplane.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001_gradient.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift001_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_cube.hdr.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_cube.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metal_lift_grad_mask.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/detail_concrete_03.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/metaldoor028a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/orange_noglow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/physring.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/physring.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/turret_off_eye.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/comball/comball.vtf"
[INFO] vbsp.make_packlist(): "materials/effects/eball_finite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/eball_infinite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/ball_catcher_clean.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/c_ball_launcher_clean.vmt"
[INFO] vbsp.make_packlist(): "materials/models/props/combine_ball_catcher_clean.vtf"
[INFO] vbsp.make_packlist(): "materials/models/props/combine_ball_launcher_clean.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/p1_pgun.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/p1_lfield.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/p1_metal_box.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/sign_frame_1_wback.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/cube_button.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/keyboard.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/mouse.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/obs_light.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/security_camera.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/turret_01.mdl"
[INFO] vbsp.make_packlist(): "models/effects/combineball.mdl"
[INFO] vbsp.make_packlist(): "models/props/clean/combine_ball_catcher.mdl"
[INFO] vbsp.make_packlist(): "models/props/clean/combine_ball_launcher.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/vactube_glass_bothsides/vactube_128_straight_glass.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/vactube_glass_bothsides/vactube_90deg_01_glass.mdl"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_rough_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:physics/metal/metal_box_scrape_smooth_loop1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/concrete4.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal1.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal2.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal3.wav"
[INFO] vbsp.make_packlist(): "precache_sound:player/footsteps/metal4.wav"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/set_p1_pgun.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/turret_dropper.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/claw_cable_lp.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/alyx_stunner2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/doorstop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/panel_turn.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/ambient.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_enter2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/pgun/portal_exit2.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/stair_stop.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate4.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate5.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_explosion2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_loop4.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Donahue\Downloads\bee\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)
