### ISSUE TITLE
Portal Gun Stand should create output

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#293]
As an idea for the mod, the portal gun should be edited to activate things once picked up off of its stand. Placing a trigger once does not work as it is bigger than the pickup range of the portal gun.

**Comment by BenVlodgi** [comment]
Good idea. 
A way to circumvent this is to shape the puzzle in a way that they can only continue by using the newly acquired gun.
An obstacle that couldn't have been overcome before.

**Comment by ellingtonvengaboysmuseum** [comment]
the portal detector would be a good trigger obstacle for this
