### ISSUE TITLE
implement portal 1 soundtrack into portal 1 style

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#295]
implement songs from the portal 1 soundtrack into the portal 1 style

yes, portal 1 does have it's own sound track!

can the source engine or game play back mp3's as music, if it can that would making compressing the music files easy.

https://www.youtube.com/watch?v=Kgny67NTtw0

**Comment by TeamSpen210** [comment]
I've actually done this for the next release already. The Source Engine can play MP3s, but they won't loop. I've firgued out a workaround for that though.
