### ISSUE TITLE
#

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#296]
I will start by exposing two issues related to the current "separated Co-op checkpoint" that should be prevented, and then expose some alternatives to fix these "issues", as well as a simple improvement option that this item did not have on the "Bee 2.2.5 alpha with addons".

All images were extacted from Bee 2 alpha since there are failures on Bee 2.4 respect to this item.

_______________________________________________________________________

1 -  On the gif adobe, we can see how one of the players can "Escape" from the closing of the glass pannels:

![gif](https://cloud.githubusercontent.com/assets/12244376/13204195/a4754e7a-d8a8-11e5-87be-a82d4e62e52c.gif)

2 -  Showing the possible stuck in case the map has some kind of "return" to the start area:

![possible stuck in case the map has a return to the start area](https://cloud.githubusercontent.com/assets/12244376/13204225/4b96caa8-d8a9-11e5-8e19-1bdab713d625.png)

--------------------------------------------------------

There is two simple alternatives to fix this "Possible escapement". On the first illustrative screenshot i show how to prevent this by adding 2 floor buttons, instead of having the current "Pedestal Timming buttons":

![2016-02-21_00004](https://cloud.githubusercontent.com/assets/12244376/13204255/0c587732-d8aa-11e5-85c0-ed72362cad50.jpg)

If you still want to keep the "Pedestal Timmer buttons", this simple alternative should prevent it:

![dgasasdgdg](https://cloud.githubusercontent.com/assets/12244376/13204291/04fe6db0-d8ab-11e5-9876-dae8a3a2138c.jpg)

----------------------------------------------------------------------------------------------

Improvement option that was not pressent on the separated checkpoint from the "Bee 2.2.5 alpha":

![2016-02-21_00003](https://cloud.githubusercontent.com/assets/12244376/13204301/6fd474f4-d8ab-11e5-9222-42c018c6a9f7.jpg)

**Comment by CrashingScience** [comment]
Cant they just use cameras instead of buttons?

**Comment by LautaroL20** [comment]
Well, i think the best choice would be reducing the "Timmer" from both Pedestal Buttons to 1 sec.
