### ISSUE TITLE
Suggestion: Handle 8 directions on Thin Black / White Wall

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#298]
The same eight rotations like the "Placeable Door" has, make it possible on Thin Walls too:

![8 directions](https://cloud.githubusercontent.com/assets/12244376/13229003/82ac4be2-d97d-11e5-9f7a-970bb4d917ea.jpg)

**Comment by TeamSpen210** [comment]
Unfortunately, glass-type items don't work with any other handle types.

**Comment by LautaroL20** [comment]
Alright, what about the Half-Width Triggers from issue #300?

**Comment by Endermage77** [comment]
Hasn't this already been done with normal glass?

**Comment by Luke18033** [comment]
No, actually the opposite - we've implemented Start Reversed on the 1/4 wall to swap it to the inner 4 positions, replicating this. Glass doesn't yet have this functionality.

**Comment by Endermage77** [comment]
Oh yeah...
