### ISSUE TITLE
new item 2: rotating laser

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#303]
i have a idea for another item that would make some good puzzles with lasers

it would be a laser that uses the input a/b system to control it, one input would turn it on or off, the other would rotate it in 90 degree increments. 

the idea is to use the model for the laser relay to shoot the laser out of it, maybe attach it to a arm so it could be extended up off the floor too. once configured it would use the input system to control it and it could rotate in 90 degree increments with input B. imagine a puzzle where you had to rotate the laser and fire it through a portal to a catcher to open a door, then behind that door you would press a button to rotate it again which would make it hit another catcher and open a second door. it could rotate 360 degrees in 90 degree increments.

**Comment by BenVlodgi** [comment]
the puzzle output of this is the same as having two laser emitters on a wall at different angles, then toggling their inputs
