### ISSUE TITLE
[suggestion] overgrown black wall variation

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#305]
I suggest that in overgrown style, some of black walls in test chamber can be replaced by broken walls or covered by branches and leaves.

**Comment by TeamSpen210** [comment]
The main reason I haven't done this sort of thing is that it could break puzzles - users might require conversion gel to be placed on a surface, or something of the like.

**Comment by Luke18033** [comment]
This should be implemented as a sort of expandable "broken wall" item. Not sure how this would work on other styles though.

**Comment by TeamSpen210** [comment]
Here's part of it implemented as the "[decoration](http://steamcommunity.com/sharedfiles/filedetails/?id=730418432)" feature. This allows basically whitelisting or blacklisting specific tiles to add decorations to, which then get added by the compiler. That way you can ensure portal spots aren't covered.

I still need to make this capable of hollowing and cutting out brushes, that will allow for many possibilities like large ceiling holes or wall damage.
