### ISSUE TITLE
texture overlap on flamethrower

### ISSUE THREAD

**Issue by CrashingScience** [TeamSpen210/BEE2-items#307]
![2016-02-29_00001](https://cloud.githubusercontent.com/assets/16468734/13400443/a9ccd340-deff-11e5-995c-bea3155436f7.jpg)

**Comment by CrashingScience** [comment]
also, the flame-thrower nozzels overlap, they could be slightly further apart.

**Comment by Konclan** [comment]
Hold on, I know this is old but where is there a flamethrower 0_0

**Comment by TheReviewers** [comment]
@Konclan  1960's Style Crusher

**Comment by Konclan** [comment]
Really?! why cant this just be an item?

**Comment by TeamSpen210** [comment]
This roof is a weird tessalation bug with VBSP, it should be fixed now.
