### ISSUE TITLE
Warm Square Light causes build error if placed on floor in Portal 1 style

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#310]
Specifically, while on the "building geometry" state. I would say that it seems the chamber wasn't structured properly to have a large hole in the floor, except both the Victory Lift and the Ditch work perfectly fine.

**Comment by TeamSpen210** [comment]
When placed on the floor, the Warm Square Light item gets a grating added to ensure you can't fall inside. That's what's producing the compile error (I mixed up some filenames).

**Comment by LautaroL20** [comment]
Already Fixed since some pre-releases ago.
