### ISSUE TITLE
P1 stairs cannot rise quick enough for timer

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#313]
http://i.imgur.com/l5wKksp.webm
Maybe a right-click option for them to pop up all together?

**Comment by xDadiKx** [comment]
Just put more time into the button.

**Comment by ncrecc** [comment]
If I want the stairs to be raised for 5 seconds, I should get the stairs being raised for 5 seconds. What I shouldn't get is the stairs slowly raising into place, and then dropping right back down before they're all the way up.

**Comment by TeamSpen210** [comment]
Something's messed up with that timing. They should actually pop up together.

**Comment by TeamSpen210** [comment]
Is this still occurring?
