### ISSUE TITLE
BTS bug

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#318]
![img](http://ww2.sinaimg.cn/large/0060lm7Tgw1f1n5ct4aoqj31hb0svtd7.jpg)
![img](http://ww4.sinaimg.cn/large/0060lm7Tgw1f1n5cw0th0j31hb0sw79b.jpg)
![img](http://ww4.sinaimg.cn/large/0060lm7Tgw1f1n5cwtwraj31hb0svgor.jpg)

**Comment by LautaroL20** [comment]
This bug was fixed since some pre-releases ago.
