### ISSUE TITLE
Suggestion: Black Wall randomly display a yellow wall.

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#319]
![img](http://ww3.sinaimg.cn/large/0060lm7Tgw1f1n5d0f9d7j30ku0i2411.jpg)
like this.

**Comment by TeamSpen210** [comment]
I can't do that, it'll break a lot of puzzles - that surface won't let you paint it properly, which is especially a problem with Conversion Gel.

**Comment by goodDOS** [comment]
@TeamSpen210 Can you add cameras, broken wall, yellow walls decorated with this type of item?

**Comment by Enterpise** [comment]
@goodDOS - There is already an item called "Cutout Tile" wich meets that funtion.
