### ISSUE TITLE
Cube Dropper doesn't use white tiles

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#32]
texture mismatch on cube dropper

![preview0029](https://cloud.githubusercontent.com/assets/11165643/8398046/5e6b3728-1daf-11e5-87e4-1764d35efe2a.jpg)

**Comment by TeamSpen210** [comment]
The cube dropper always uses black textures in the default PeTI and in the BEE2. I might be able to do some tricks to switch the instance as needed.
