### ISSUE TITLE
3d factory with clean style collocation very dark.

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#321]
![img](http://ww3.sinaimg.cn/large/0060lm7Tgw1f1n5d0vkogj30ok0gowlo.jpg)
3d factory with clean style collocation very dark. But with BTS collocation, it looks very natural, not very dark.

**Comment by goodDOS** [comment]
@TeamSpen210 Can you add cameras, broken wall, yellow walls decorated with this type of item?

**Comment by TeamSpen210** [comment]
With what item? Bottomless pits use the goo type, which only works on floors.

**Comment by goodDOS** [comment]
@TeamSpen210 I mean add cameras, broken wall, yellow walls item, allowing the player free to use.

**Comment by Enterpise** [comment]
@goodDOS Your sentence is not very clear, but respect to "Yellow walls item", there is already one called "Cutout Tile" since some Pre-releases ago.

@TeamSpen210 It requires some improvements in order to work better on Clean Style, because on this style, this item sometimes does not build in.

**Comment by goodDOS** [comment]
@Enterpise thanks
