### ISSUE TITLE
Wrong pallete icons: "Paint fizzler", "Force Deflection Field", "Compressed smoke field" and no models for custom fizzlers

### ISSUE THREAD

**Issue by Enterpise** [TeamSpen210/BEE2-items#322]
(Click to resize any images)

![wrong pallete icons](https://cloud.githubusercontent.com/assets/15699236/13558932/c0d3dfd4-e3eb-11e5-9f6f-27a4f7261cc5.jpg)

-----------------------------------------------------------------------------------

There is no models for the custom fizzlers:

![no custom models](https://cloud.githubusercontent.com/assets/15699236/13558917/76683558-e3eb-11e5-9ec4-5133b0e3e834.jpg)

**Comment by TeamSpen210** [comment]
Unfortunately I can't change the colour of the field the model emits, which is why there isn't a custom model for that.

**Comment by Enterpise** [comment]
Oh, thats a shame. But it is still possible to change the model for the flap frame as the death fizzler has?

**Comment by TeamSpen210** [comment]
That's changable, yes.

**Comment by CrashingScience** [comment]
Will the paint fizzler get a different texture, but leave in the current one for portal 1 style.

**Comment by ncrecc** [comment]
Isn't it already obvious the icons are placeholders?
