### ISSUE TITLE
[Suggestion] Marked Surface on Angled Panels

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#328]
It would be cool to have an Angled Panel version with a "Marked Surface" on Bee 2.4, I have seen this in many maps i've played:

![2016-02-11_00005](https://cloud.githubusercontent.com/assets/12244376/13690434/1bfb6f78-e70f-11e5-8091-61c9a427c498.jpg)

**Comment by TeamSpen210** [comment]
That's already done, all angled/flip panels switch to those textures. On the floor they use a checkerboard. In addition, placing a Faith Plate Target on angled/flip panels now displays properly.

**Comment by LautaroL20** [comment]
You are right. Sorry, i was probably confused with an old pre-release when this wasnt maded, or anything, because when the "pre-releases" comes out i did not usually tested the Angled Panels.
