### ISSUE TITLE
[New Style] Clean Cutout

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#329]
![20160925141256_1](https://cloud.githubusercontent.com/assets/12244376/19114731/a4631af8-8ae5-11e6-97fe-e17fe8d0dc1c.jpg)

![img](http://ww1.sinaimg.cn/large/0060lm7Tgw1f1u0wpnzdsj30ao05cmxj.jpg)

**Comment by LautaroL20** [comment]
Recently i have played an interesting chamber that had this idea, and it looks like a special Clean Cutout Style:

![20160925141256_1](https://cloud.githubusercontent.com/assets/12244376/19114779/d0443c1a-8ae5-11e6-9157-9773cfc25579.jpg)

**Comment by TeamSpen210** [comment]
That's basically Art Therapy, and what happens when you use cutout tiles.

**Comment by LautaroL20** [comment]
True, there would not be much difference between both styles, so this probably wouldn't worth.
