### ISSUE TITLE
Add 60s-80s enrichment spheres and corridors

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#33]
selecting open enrichment sphere causes this

![preview0030](https://cloud.githubusercontent.com/assets/11165643/8398137/a5482302-1db1-11e5-9cd6-bceeedd02356.jpg)

**Comment by TeamSpen210** [comment]
I haven't actually readded the corridors and spheres for 60s, 70s and 80s styles yet. That's actually the 50s sphere.
