### ISSUE TITLE
Glass panel BUG

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#330]
![img](http://ww3.sinaimg.cn/large/0060lm7Tgw1f1u0wzg7yaj30j20nmjyh.jpg)

**Comment by TeamSpen210** [comment]
Unfortunately this isn't really something I can fix - it's a bug with transparent texture sorting in the Source Engine itself.

**Comment by goodDOS** [comment]
![img](http://ww3.sinaimg.cn/large/0060lm7Tgw1f1u5ofelcnj308406yt9g.jpg)
@TeamSpen210 This glass panel no problem, is it possible to add this item?

**Comment by TeamSpen210** [comment]
I need to port that item from my original BEE2 addons.

**Comment by goodDOS** [comment]
@TeamSpen210 ok，thanks.

**Comment by Luke18033** [comment]
I think this is now being fixed
