### ISSUE TITLE
Draw bridge BUG

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#331]
![img](http://ww4.sinaimg.cn/large/0060lm7Tgw1f1u0wzcfokj30c40i4whn.jpg)

**Comment by TeamSpen210** [comment]
This isn't a bug, it's exactly what makes drawbridges different to normal panels - they're mounted on the side of a block instead of inside it. It's based on the panel in the center of `sp_a1_intro5`.

**Comment by goodDOS** [comment]
@TeamSpen210 Know, thank you.
