### ISSUE TITLE
Elevator Room BUG

### ISSUE THREAD

**Issue by goodDOS** [TeamSpen210/BEE2-items#332]
![img](http://ww1.sinaimg.cn/large/0060lm7Tgw1f1u0xnqrayg30ao0747wj.gif)
Floor very dark.

**Comment by LautaroL20** [comment]
Ive already reported this bug from some time ago. "SP Circular Floor elevator entrance gets "Black" in Clean and Overgrown Styles when elevator goes away." 

https://github.com/TeamSpen210/BEE2-items/issues/287

**Comment by LautaroL20** [comment]
This is a duplicate of https://github.com/TeamSpen210/BEE2-items/issues/287
