### ISSUE TITLE
Add custom music?

### ISSUE THREAD

**Issue by xDadiKx** [TeamSpen210/BEE2-items#335]
Is it possible to add custom music?

**Comment by TeamSpen210** [comment]
Yes, it should be fairly easy. Unzip a copy of the `p1_music` package, and edit that (you can leave it as a folder for easier editing). `info.txt` is where the items are defined - the `Soundscript` > `Base` value is the filename for the music track. `resources/BEE2/music` holds the icons, `resources/sound/` should hold a MP3 or WAV version of the music, and (optionally) you can put a 10 second WAV/OGG sample in `resources/music_samp/`. (The files can go in subfolders of these, you just need to specify that in `info.txt`.

**Comment by xDadiKx** [comment]
Alright thanks.

**Comment by LautaroL20** [comment]
Well, this actually should have been an "Enhancement". I also want to add custom music under a Bee 2.4 option.
