### ISSUE TITLE
[PRL19 Bug] Signage item not building in the map if "start inverted" and "start enable" are dissabled, or if just start inverted is only selected.

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#338]
If both "start inverted" and "start enabled" are dissabled, this does not building in, or if just start inverted are only selected:
![gta](https://cloud.githubusercontent.com/assets/12244376/13730036/9115a0f2-e922-11e5-92a8-a7cb4d1b6fdb.jpg)

**Comment by TeamSpen210** [comment]
This is intentional. If the timer is set to 'infinite' no icon is shown (cube-dropper, dots, etc). If "Start Enabled" is off no arrow is added. If both are off that means nothing ends up getting added.
