### ISSUE TITLE
[Bug] Portal 1 Style: No sounds effect on the Weighted Button and Pedestal Buttons

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#349]
This happens in P1 Style.

**Comment by TheReviewers** [comment]
@LautaroL20 Strange.. I Have The Sounds Perfect

**Comment by LautaroL20** [comment]
@TeamSpen210 - Did you fix this bug already?

**Comment by LautaroL20** [comment]
@TheReviewers - Good for you, but this happens for me and i am really good at knows how to install the things well.

**Comment by TheReviewers** [comment]
@LautaroL20 Depends if You Have portal 1 , before i installed portal 1 , i had this bug

**Comment by ZombiePwner1** [comment]
It doesn't matter if u have P1 installed or not the sound for the buttons sometimes the sound breaks for the buttons it has been on and off for me so been working at points and not working.
