### ISSUE TITLE
Fresh Install -> Game Finding

### ISSUE THREAD

**Issue by BenVlodgi** [TeamSpen210/BEE2-items#35]
Suggestions:
Allow user to load the BEE2 without choosing a game (LEFT TO IMPLEMENT).

Give option to scan computer for all supported games. Then let them add the games they want (IMPLEMENTED).

Bug: 
Conditions: On a fresh install of the BEE2.4
Trigger: Press e[X]it button on the the dialog that asks you to locate the portal2.exe
Result: In continues to the file choosing dialog
(FIXED).

Bug:
Conditions: On a fresh install of the BEE2.4 
Trigger: Closing the portal2.exe locating dialog
Result: Python complains and crashes
(FIXED).

**Comment by ellingtonvengaboysmuseum** [comment]
fixed - case should be closed

**Comment by Konclan** [comment]
Has this been implemented fully yet?

**Comment by LautaroL20** [comment]
This has been posted into the worng section, this page is for Items only. On the other hand, almost all these things have been implemented, exept for "allowing BEE2.4 to load without choosing the game".
