### ISSUE TITLE
[PRL19 Bug] Portal 1 Style: Insane Low Quality on the "Deadly Goo" Texture

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#350]
I have a fine grapich card (GTX 750Ti) wich handles Portal 2 in maximun settings, so this may not be due to my configuration. This item "Deadly Goo" has an insane low quality texture, very similar to goldsource games:

![goo](https://cloud.githubusercontent.com/assets/12244376/13730460/ac7fdd88-e92e-11e5-8ff6-04b142996f64.jpg)

**Comment by TeamSpen210** [comment]
This texture is ported from Portal 1, and doesn't use the better Water shader added in Portal 2. It's about the same as the original Portal.
