### ISSUE TITLE
[Bug] Old Aperture "Spike Crusher" is Buggy as Hell

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#355]
They cross the metal support texture, and only kills the player if this touch the spike at a closely distance, since the crusher does not oscillate well due to it's bugginess:

![gif 4](https://cloud.githubusercontent.com/assets/12244376/13730674/110e9320-e934-11e5-84f8-7043bbeba943.gif)

**Comment by TeamSpen210** [comment]
Fixed a long time ago.
