### ISSUE TITLE
Checkpoint, Separated Checkpoint, and Chamber lock Placement Issues

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#357]
I never understood how the cooperative checkpoints nor chamber lock were supposed to be placed. I tried everything I could to make it work. Ranging from making room for the volume behind the occupied spot, and filling in the space. Even moving items out of the way didn't turn out as I had hoped. So I need some help here. Oh, and the chamber lock model in the editor shows up as an error.

**Comment by jccreszMinecraft** [comment]
To place the co-op checkpoints there needs to be a gap of about 4 blocks for the separated checkpoint and 5 blocks for the normal checkpoint.

**Comment by TeamSpen210** [comment]
The occupied area should be filled in, but the doors should be exposed to air - there should be a solid wall 5 blocks thick between the two sides, with the checkpoint item placed on top. The SP checkpoint is 1 block thick.

**Comment by LautaroL20** [comment]
Well, I think that @TeamSpen210 had clarified your doubt on the issue.
