### ISSUE TITLE
List of Glados Voicelines and Signage Options

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#358]
The title sums the request up, but I find it useful for there to be a display of signs to choose from in the item selection. You could look at the sign's number, then set the timer to the desired sign. Same with the glados voice line item, once it's added. Hopefully with some sort of mechanism that when you select reversed, the timer swaps to other sets of voice lines. Or maybe to set disabled.

**Comment by TeamSpen210** [comment]
Which kind of signage (test chamber ones, or the square icons)? The latter are available in Pre-Release 19, via the 'Signage' item. Just set the timer option to choose.
