### ISSUE TITLE
New Item Ideas

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#360]
What About You Adding Stuff Like: Vault Doors, 3 Different Versions , Weighted Is Small Vault : 5 Voxels Up
Cube Is Bigger, 10 Voxels High
And Sphere Is Huge, Idk How Big. 

Another Idea Is Elevator, Its Like Piston Platform, But Like The Exit Elevator, Goes Up Or Down.

Final Idea : ROOMS, Core Transfer Room, Neurotoxin Tube Room, Tube Rides, And Some Other Stuff, You Can Make Hammer In PTI For People Who Dont Know How TO Use Hammer :D 
Also The Template Room, Start Enabled Or Disabled :3 Pls Teamspen Add One OF MY Ideas :3

**Comment by xDadiKx** [comment]
Some of those like the Elevator may be complex to code in and possibly hard, including the vault door.
Core Transfer Room is likely impossible and neurotoxin is already an item in an addon that may be added to the BEE.

**Comment by TheReviewers** [comment]
Though I Meant, Neurotoxin Generator, The Destroyable Giant Tube Room

**Comment by TheReviewers** [comment]
Also, Ben Is Good, He Can Make A Simple Elevator, :D

**Comment by xDadiKx** [comment]
Ah, I see what you mean.

But it's too big for the in-game editor, but they can always make one that is small.
The only problem is, once the generator is destroyed, the neurotoxin might not stop due to code complex and stuff.

**Comment by TheReviewers** [comment]
oh ok, well how did he make the shredder, its like 20 floor areas XD

**Comment by TheReviewers** [comment]
bigger than the vault

**Comment by TheReviewers** [comment]
hello?

**Comment by xDadiKx** [comment]
I don't think it's that big :P

**Comment by TheReviewers** [comment]
it is :3 , the vault is like, 34 wall tiles high, :3 still easy

**Comment by xDadiKx** [comment]
Also it would be pretty useless.

**Comment by xDadiKx** [comment]
If they find out to extend the map limit, it wouldn't.
The map limit is pretty small and wouldn't able to make a good chamber.

**Comment by TheReviewers** [comment]
lel it isnt useless, its a big door, rather than placing 10000000 panels to cover something XD

**Comment by TheReviewers** [comment]
add me on steam we can discuss, : The Reviewer

**Comment by xDadiKx** [comment]
Alright, why would it be useful?

**Comment by TheReviewers** [comment]
add me?

**Comment by xDadiKx** [comment]
?

**Comment by TheReviewers** [comment]
ben made co op door thingy , its as big as the vault, and you can place a million of them without lag

**Comment by TheReviewers** [comment]
add me on steam : The Reviewer

**Comment by TheReviewers** [comment]
tell me when you adde me

**Comment by xDadiKx** [comment]
But why am I going to add you now? xD

**Comment by TheReviewers** [comment]
ok then,

**Comment by TheReviewers** [comment]
one sec

**Comment by TheReviewers** [comment]
how are you going to make your maps more epic, and hide big stuff behind walls, VAULTs,
How Are You Gonna Made Your Map More Epic And Move Quickly, ELEVATORS

**Comment by TheReviewers** [comment]
its a good idea

**Comment by xDadiKx** [comment]
I agree with the elevators
but with the vaults, what would you hide?

**Comment by TheReviewers** [comment]
a big test chamber

**Comment by xDadiKx** [comment]
![20160314185723_1](https://cloud.githubusercontent.com/assets/13087761/13756195/abeaa54a-ea16-11e5-92ca-9cd9d0e19595.jpg)

Those buttons are almost the same size of the vault.
* It would need some space for the opening door.

**Comment by LautaroL20** [comment]
@TheReviewers - Ehmmm...... How old are you, buddy?

**Comment by TheReviewers** [comment]
Lauto? why do you want to know.

**Comment by TheReviewers** [comment]
dadikk just a little smaller

**Comment by xDadiKx** [comment]
A little smaller? I think you are.

**Comment by xDadiKx** [comment]
What do you mean little smaller?

**Comment by TheReviewers** [comment]
The Vault XD

**Comment by TheReviewers** [comment]
hello?

**Comment by LautaroL20** [comment]
@TheReviewers - Well, my gmail notifications has becomed a mess with lot of notifications. At the first i thought they were "Bug reports" but when i check them i saw a tons of "childhood" conversation (Please do not offence).

**Comment by TheReviewers** [comment]
gmail does notifications of this?

**Comment by LautaroL20** [comment]
Yes :(

**Comment by TheReviewers** [comment]
oh god im spammed ;-;

**Comment by TheReviewers** [comment]
not everything needs to be bugs, i really want that damn elevator already ;-;

**Comment by TheReviewers** [comment]
beemod is broken and i cant use it ;-; anyone has this!!?

**Comment by TheReviewers** [comment]
it shows some kind of logs near the loading then it crashes :(

**Comment by TheReviewers** [comment]
you got that?

**Comment by TheReviewers** [comment]
ok i already fixed it :dancers:

**Comment by TheReviewers** [comment]
does it work on aperture tag :(?

**Comment by xDadiKx** [comment]
LautaroL20 are you calling me a child?

**Comment by TheReviewers** [comment]
OH F**K YE, THEY ADDED 4000 DEGREES KELVIN SONG

**Comment by TeamSpen210** [comment]
What purpose would these serve? Perhaps the vault door would be useful, but the others aren't really. (There's only one vault door size anyway.) I'm not going to just add bits of the campaign into test chambers - the BEE2 isn't aiming to replace Hammer, you still should use that for story maps.

**Comment by TheReviewers** [comment]
teamspen210, do you close every discussion?

**Comment by TheReviewers** [comment]
also, i thought there was the yellow, and blue one.

**Comment by TheReviewers** [comment]
an elevator could serve, maybe traps? elevator to water, and you must jump out while door is open

**Comment by TheReviewers** [comment]
or moving through test chambers

**Comment by xDadiKx** [comment]
Did you read TeamSpen210's reply? He won't add anything from the story/campaign. The purpose of in-game editor is to create test chambers, not stories.

**Comment by TheReviewers** [comment]
-_- Vaults Are Not Story Mode Items, Like That He Cant Add , Doors, Fizzlers, Or Any Other Item XD. I Seriously Want A Damn Vault , Or Any Huge Panel, Or Something To Hide A Big Map :_:

**Comment by TheReviewers** [comment]
why is it written in such hand writing?

**Comment by TheReviewers** [comment]
-- Is it true
