### ISSUE TITLE
People With No Skill In Hammer Deserve More

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#363]
Wouldn't It Be Nice If The People Who Have No Skill In Hammer, Still Have All They Need To Make A Hammerish Map. Id Really Like To See The Workshop Filled With Bee2/Hammer Maps, All United :3

**Comment by TheReviewers** [comment]
The People Who Dont Know How To Use Hammer Should Still Have, Living Panels/ Crushers/ Shredders etc...

**Comment by xDadiKx** [comment]
Hammer isn't hard.

Just got to learn from videos.
The more you watch and repeat videos, the more you will learn.

**Comment by TheReviewers** [comment]
i know, im talking bout begginers who want to make good maps too :(,  i feel so bad for them

**Comment by TeamSpen210** [comment]
That isn't what the PeTI or BEE2 is for - it's for helping design better puzzles, as well as switching up the styles to make maps more interesting to look at.

**Comment by TheReviewers** [comment]
Ok :3
