### ISSUE TITLE
[Suggestion] Co-op exit: Prevent "TeamMate" to open "Exit Tube" from each other 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#367]
Im not sure if this is a bug, but anyways it should not be possible. GIF:

![gif](https://cloud.githubusercontent.com/assets/12244376/13754891/71b65d84-e9f7-11e5-92ac-08576660b49b.gif)

**Comment by SpyyZ158** [comment]
I am sure it's even on original Coop .

**Comment by LautaroL20** [comment]
Ive tested this in another P2 build and you are right. I will edit this as a "Suggestion".

**Comment by TeamSpen210** [comment]
This is behaviour in all the coop exits. The door closes when the right player enters, but opens if the other player is nearby. I think this is to allow doing gestures or the like, as well as ensuring the other player can't get stuck inside the assembler.

**Comment by LautaroL20** [comment]
Ah, that clarifies this.
