### ISSUE TITLE
[Bug] Overgrown Style: "Ditch item" is missing its overgrown variant.

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#371]
1:
![screen1](https://cloud.githubusercontent.com/assets/12244376/13755938/4bf2427a-e9fc-11e5-84bf-d7dd3eb5a6e5.jpg)
2:
![screen2](https://cloud.githubusercontent.com/assets/12244376/13756034/b8bbf824-e9fc-11e5-8245-6f006855791b.jpg)

**Comment by ZombiePwner1** [comment]
I think this has been fixed.
