### ISSUE TITLE
[Bug] 60´s Old Aperture: Co-op exit door missing door frames

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#377]
GIF:
![gif3](https://cloud.githubusercontent.com/assets/12244376/13758768/d80a8c6a-ea09-11e5-9553-58bacb9d0eb7.gif)

**Comment by TeamSpen210** [comment]
Actually, this is because the door framing brushes are missing. The nodraw is because an areaportal is closed when the door finishes closing, to stop the game rendering the test chamber (reducing graphics load).

**Comment by LautaroL20** [comment]
This is fixed.
