### ISSUE TITLE
50´s Old Aperture: SP Exit corridor becomes "Black" when the player walks away from it

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#378]
GIF:
![gif4](https://cloud.githubusercontent.com/assets/12244376/13759156/c05fad46-ea0b-11e5-9c19-3f5aafe2e56d.gif)

**Comment by Luke18033** [comment]
@LautaroL20 Looks like the world portal closing. I don't think that should be happening at all.

**Comment by LautaroL20** [comment]
This is fixed.
