### ISSUE TITLE
[Bug] 60´s Old Aperture: Entry worldportal needs clips in corridor

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#382]
GIF:
![gif7](https://cloud.githubusercontent.com/assets/12244376/13760044/e910b51a-ea0f-11e5-8ef9-eb5b7cff463c.gif)

**Comment by TheReviewers** [comment]
where is the gif?

**Comment by LautaroL20** [comment]
@TheReviewers - Well, it may take some seconds to load depending on how good or poor is your internet connection.

**Comment by TeamSpen210** [comment]
This is because there's a worldportal right between the door, and the lobby room. When you approach that side you're teleported inside the wall, and then are hurt since you're inside a solid object. You then get pushed out. This just needs some more player clips to stop you acessing that side.
