### ISSUE TITLE
BEE2 NOT WORKING!!!!

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#383]
So I Installed The New Update And New Beemod Just Like Always, But I Seem To Always Have a build error. Whatever Style, Music, Or Anything, Its Always A Build Error. Teamspen pls fix!?

**Comment by Enterpise** [comment]
Oh boy, please calm your tities!!!

**Comment by TheReviewers** [comment]
i wanna see the new signage thingy ;-;

**Comment by TheReviewers** [comment]
and the epic ass 4000 degrees song in my map ;-;

**Comment by TeamSpen210** [comment]
Open your developer console, and copy the error message here.

**Comment by TheReviewers** [comment]
VRAD failed.

[I] vrad: BEE2 VRAD hook started!
[I] vrad: Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad: Loading Settings...
[I] vrad: Config Loaded!
[I] vrad: Written new soundscripts_manifest..
[I] vrad: Files to pack:
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun.vmt"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun.vtf"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_blue.vmt"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_blue.vtf"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_exponent.vtf"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_glass.vmt"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_glass.vtf"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_normal.vtf"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_orange.vmt"
[I] vrad:  # "materials/bee2/models/p1_pgun/v_portalgun_orange.vtf"
[I] vrad:  # "materials/bee2/models/props_p1/walllight_sheet.vmt"
[I] vrad:  # "materials/bee2/models/props_p1/walllight_sheet.vtf"
[I] vrad:  # "materials/bee2/p1/light_recessedcool_glow.vmt"
[I] vrad:  # "materials/bee2/p1/metalwall048b_lrg.vmt"
[I] vrad:  # "materials/bee2/p1/metalwall048b_lrg.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_lrg_dx8.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_lrg_height-ssbump.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_lrg_normal.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_med.vmt"
[I] vrad:  # "materials/bee2/p1/metalwall048b_med.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_med_dx8.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_med_height-ssbump.vtf"
[I] vrad:  # "materials/bee2/p1/metalwall048b_med_normal.vtf"
[I] vrad:  # "materials/bee2/p1/modular_wall_light.vmt"
[I] vrad:  # "materials/bee2/p1/obs/detail_concrete_03.vtf"
[I] vrad:  # "materials/bee2/p1/obs/metaldoor028a.vmt"
[I] vrad:  # "materials/bee2/p1/obs/metaldoor028a.vtf"
[I] vrad:  # "materials/bee2/p1/obs/observation_tilefloor001a.vmt"
[I] vrad:  # "materials/bee2/p1/obs/observation_tilefloor001a.vtf"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001a.vmt"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001a.vtf"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001a_normal.vtf"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001b.vmt"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001b.vtf"
[I] vrad:  # "materials/bee2/p1/obs/observationwall_001b_height-ssbump.vtf"
[I] vrad:  # "materials/bee2/p1/overlay_light_gradient.vtf"
[I] vrad:  # "models/bee2/p1_pgun.dx90.vtx"
[I] vrad:  # "models/bee2/p1_pgun.mdl"
[I] vrad:  # "models/bee2/p1_pgun.vvd"
[I] vrad:  # "models/bee2/props_p1/door_frame_thick.dx90.vtx"
[I] vrad:  # "models/bee2/props_p1/door_frame_thick.mdl"
[I] vrad:  # "models/bee2/props_p1/door_frame_thick.phy"
[I] vrad:  # "models/bee2/props_p1/door_frame_thick.vvd"
[I] vrad:  # "models/bee2/props_p1/obs_light.dx90.vtx"
[I] vrad:  # "models/bee2/props_p1/obs_light.mdl"
[I] vrad:  # "models/bee2/props_p1/obs_light.phy"
[I] vrad:  # "models/bee2/props_p1/obs_light.vvd"
[I] vrad:  # "models/bee2/props_p1/security_camera.dx80.vtx"
[I] vrad:  # "models/bee2/props_p1/security_camera.dx90.vtx"
[I] vrad:  # "models/bee2/props_p1/security_camera.mdl"
[I] vrad:  # "models/bee2/props_p1/security_camera.phy"
[I] vrad:  # "models/bee2/props_p1/security_camera.sw.vtx"
[I] vrad:  # "models/bee2/props_p1/security_camera.vvd"
[I] vrad:  # "scripts/bee2_snd/p1_pgun_sounds.txt"
[I] vrad:  # "scripts/bee2_snd/portal_sounds.txt"
[I] vrad:  # "scripts/vscripts/bee2/change_model.nut"
[I] vrad:  # "scripts/vscripts/bee2/set_p1_pgun.nut"
[I] vrad:  # "sound/bee2/music/p1/4000_degrees_kelvin.mp3"
[I] vrad:  # "sound/bee2/p1/garage_stop1.wav"
[I] vrad:  # "sound/bee2/p1/pgun/ambient.wav"
[I] vrad:  # "sound/bee2/p1/pgun/portal_enter1.wav"
[I] vrad:  # "sound/bee2/p1/pgun/portal_enter2.wav"
[I] vrad:  # "sound/bee2/p1/pgun/portal_exit1.wav"
[I] vrad:  # "sound/bee2/p1/pgun/portal_exit2.wav"
[I] vrad:  # "sound/bee2/p1/wall_move5.wav"
[I] vrad:  # "sound/music\sp_a3_speed_ramp_z1.wav"
[I] vrad:  # "sound/music\sp_a3_speed_ramp_z1b.wav"
[I] vrad:  # "sound/music\sp_a3_speed_ramp_z1c.wav"
[I] vrad:  # "sound/music\sp_a3_speed_ramp_z1d.wav"
[I] vrad: Injected files:
[I] vrad:  # "scripts/game_sounds_manifest.txt"
[I] vrad:  # "scripts/BEE2_generated_music.txt"
[I] vrad: Packing Files!
[W] vrad: "bee2/scripts/vscripts/bee2/change_model.nut" not found! (May be OK if not custom)
[W] vrad: "bee2/sound/music\sp_a3_speed_ramp_z1d.wav" not found! (May be OK if not custom)
[W] vrad: "bee2/sound/music\sp_a3_speed_ramp_z1b.wav" not found! (May be OK if not custom)
[W] vrad: "bee2/materials/bee2/p1/obs/observationwall_001a_normal.vtf" not found! (May be OK if not custom)
[W] vrad: "bee2/sound/music\sp_a3_speed_ramp_z1c.wav" not found! (May be OK if not custom)
[W] vrad: "bee2/sound/music\sp_a3_speed_ramp_z1.wav" not found! (May be OK if not custom)
[I] vrad: Injecting "scripts/game_sounds_manifest.txt" into packfile.
[I] vrad: Injecting "scripts/BEE2_generated_music.txt" into packfile.
[I] vrad: Packing complete!
[I] vrad: Using automatic screenshot!
[I] vrad: Screenshot "..\portal2\screenshots\config" too old (63 days, 15:20:23.837759)
[I] vrad: No Auto Screenshot found!
[I] vrad: Cleaning up screenshots...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vrad.py", line 837, in <module>
  File "vrad.py", line 826, in main
  File "vrad.py", line 698, in mod_screenshots
PermissionError: [WinError 5] Access is denied: '..\\portal2\\screenshots\\config'

**Comment by TeamSpen210** [comment]
Turn off 'clean screenshots' in the compile pane, that will allow the BEE2 to run until I fix this bug.

**Comment by TheReviewers** [comment]
ok thx :DD

**Comment by TheReviewers** [comment]
nope, still a build error in the test chamber ;-;

**Comment by Enterpise** [comment]
Calm your tities, boy. This is just a "pre-release".

**Comment by TheReviewers** [comment]
goddammit kid, i hate titties ;-;
