### ISSUE TITLE
[Bug] In Co-op mode, afther reaching the final elevators, testing doesn't restart, and it "Ends up getting Stuck Forever" into the "Elevator Hole" in all the Old Apertures

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#393]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/13782671/d1c6f2a6-eaa6-11e5-8065-77eaa4d2782b.gif)

**Comment by ZombiePwner1** [comment]
All of the sounds stop working as well other than the gesture wheel sounds.
