### ISSUE TITLE
Excursion Funnel Pushing Error

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#396]
![20160315174351_1](https://cloud.githubusercontent.com/assets/17092818/13798660/dddcd9aa-ead5-11e5-8c6a-374f6b8fe137.jpg)
Placing the Excursion Funnel creates a compile error.
![20160315174357_1](https://cloud.githubusercontent.com/assets/17092818/13798668/edc5a892-ead5-11e5-9e7e-de5e9f624dfd.jpg)

**Comment by Enterpise** [comment]
Thats strange, ive placed two Tractor Beams, even on inverted polarity and it worked for me, in all the styles.

**Comment by MrKrunk** [comment]
Well then I guess it's an issue with the pushing funnel.

**Comment by LautaroL20** [comment]
This is by far already fixed.
