### ISSUE TITLE
Broken Rocket Turret

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#397]
![20160315174716_1](https://cloud.githubusercontent.com/assets/17092818/13798722/523d1148-ead6-11e5-8ac5-6816d3cbf74d.jpg)
All styles show something similar to this error. Also plays the explosion soundwhen the player touches the item. For example, the 60's style shows an empty hole, and repeatedly plays the explosion sound.
The laser is also stuck in the position seen in the image above.

**Comment by Enterpise** [comment]
Thats not about "Un-styled". It is just the rocket turrent not packing in the map.

**Comment by LautaroL20** [comment]
Rocket turrent not being visible is fixed since some pre releases.
