### ISSUE TITLE
Portal 1 Observation Rooms provide little to no light

### ISSUE THREAD

**Issue by MrKrunk** [TeamSpen210/BEE2-items#399]
![20160315181653_1](https://cloud.githubusercontent.com/assets/17092818/13799204/947d7d82-eada-11e5-9398-209115d37ec9.jpg)
The small room provides only an extremely small amount of lighting for chambers. ^
The medium sized room's light is off. The light should be closer to the room. v
![20160315181703_1](https://cloud.githubusercontent.com/assets/17092818/13799232/c9c55f0a-eada-11e5-89a0-8b8cd68b714b.jpg)

**Comment by LautaroL20** [comment]
This is fixed now.
