### ISSUE TITLE
bottomless pit camera and visible obs room bug

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#400]
@TeamSpen210 and @BenVlodgi - remove or stiffen up that cable on the p1 camera big time, when it falls into a pit, the cable gets flung around like mad and goes crazy, also i think i have just created a template for clean and Wheatley pits to make your job easier.

![preview0119](https://cloud.githubusercontent.com/assets/11165643/13801199/14ff2354-eb06-11e5-8a52-2ba32c033ebd.jpg)

![preview0123](https://cloud.githubusercontent.com/assets/11165643/13801200/17f38bc2-eb06-11e5-9f0f-1a2b122df4b4.jpg)

inside of floor obs room visible in pit

![preview0109](https://cloud.githubusercontent.com/assets/11165643/13801224/51c002c2-eb06-11e5-99d5-31a7717e21ea.jpg)

**Comment by Enterpise** [comment]
"The cable goes crazy", ive laugh a lot xD.

**Comment by TeamSpen210** [comment]
I'll add some IO to kill the cable when the camera teleports. The obs room can't really be fixed, the proper solution is to lower the goo so the skybox surface isn't above it. Normal geometry always appears above skybox geometry, which is one of the issues with using this technique.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - i may have just found a solution to the observation room problem if it's placed on the floor or ceiling etc, use a world portal for the window etc and place the actual room far away from the map or skybox, it should not show up then!

**Comment by TeamSpen210** [comment]
I can't use worldportals like that - there's a limit of 4 portals being rendered at the same time.

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 - i know, make the floor and ceiling obs rooms 1 voxel in size only, you also have to make it so we can make bottomless pits deeper, and have walls opened up, figure out a way to make it so one part is deeper in the pit than the other too such as some of the pillars you see in Wheatley.
