### ISSUE TITLE
[Bug] Missing "Catwalk Model Texture" on the "Clean Style In-Game editor" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#404]
![missing texture](https://cloud.githubusercontent.com/assets/12244376/13851804/47fa0880-ec3e-11e5-9d63-949c88df86a6.jpg)

**Comment by TheReviewers** [comment]
And Portal 1 Style

**Comment by TeamSpen210** [comment]
This has the same cause as #407 - I was working on improving the appearance of gratings, but missed copying the texture files.

**Comment by ZombiePwner1** [comment]
Fixed.

**Comment by Luke18033** [comment]
404: Issue not found.

**Comment by LautaroL20** [comment]
Well, it was fixed a long time ago.

**Comment by Luke18033** [comment]
I know that, I was just commenting on the fact that this is issue 404.
