### ISSUE TITLE
Missing Grating Texture

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#407]
![20160317130740_1](https://cloud.githubusercontent.com/assets/12244376/13852940/4977de12-ec43-11e5-82c1-43f995614eb7.jpg)

**Comment by ZombiePwner1** [comment]
Lautaro why have u been offline????

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I have been busy, we can talk on Steam when i get online.

**Comment by ZombiePwner1** [comment]
K well I was starting to worry since I miss talking with u. Plz be online by the time I get home from my training after school.
