### ISSUE TITLE
[Bug] Co-op Exit door can be activated by "Going through the Back" in 70´s Old Aperture

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#409]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/13855039/3ecdb4d2-ec4d-11e5-98ce-8b52d00e29cb.gif)

-------------------------------------------------------------------------------------------------------------------

Feel free to call me "The Second Grat Bee2 BugFinder" ;D

**Comment by TheReviewers** [comment]
You Are Too Much Into Finding Bugs, Take A Break Dude.

**Comment by LautaroL20** [comment]
@TheReviewers - Oh boy, you are too late, i already finish the bug report some days ago...

**Comment by TeamSpen210** [comment]
Should now be fixed.
