### ISSUE TITLE
[BUG] Connecting triggers together to make it larger, gives build error.

### ISSUE THREAD

**Issue by xDadiKx** [TeamSpen210/BEE2-items#410]
As seen in this picture, all of those triggers are connected to each other.
![20160317191630_1](https://cloud.githubusercontent.com/assets/13087761/13858105/03ad129e-ec75-11e5-86fc-c68ce627641e.jpg)

Here is the error from the console
Ohix unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF F:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 41 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr19 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "F:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "F:/Games/Valve/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.catwalks: Starting catwalk generator...
[I] cond.core: Exiting empty condition!
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3653, in main
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 471, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 339, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 328, in test_result
  File "F:\Git\BEE2.4\src\conditions\resizableTrigger.py", line 99, in res_resizeable_trigger
  File "F:\Git\BEE2.4\src\vmfLib.py", line 1573, in remove
  File "F:\Git\BEE2.4\src\vmfLib.py", line 286, in remove_ent
ValueError: list.remove(x): x not in list
Ohix unpaused the game

**Comment by LautaroL20** [comment]
Did you turn on "Developer 2" in the console?

**Comment by xDadiKx** [comment]
How do you turn it on?

**Comment by TeamSpen210** [comment]
You just want to connect 2 together (left and right). I'll fix the crash though.

**Comment by LautaroL20** [comment]
@xDadiKx 

1. Standing on the In-game editor, open up developer console
2. Writte "Sv_cheats 1", and then writte "Developer 2"
3. Writte (If you want) clear, this will clear all the unnecesary data from console log
4. Start building your map and wait for the failure to compile, then check for the full bug log in the console

**Comment by xDadiKx** [comment]
But it just gives me a build compile error, so it's not really a crash.

**Comment by LautaroL20** [comment]
If im not wrong, what "Developer 2" does, is bring with much more accurately the cause of the "There was an error building the chamber" with precise defective items references.

**Comment by LautaroL20** [comment]
I guess this was fixed since some pre-relases ago.

**Comment by xDadiKx** [comment]
Wait? How did you close **my** issue? Sorry, I wasn't here for a long time, Is it a new update or something to this web?

**Comment by ZombiePwner1** [comment]
Lautaro luke and i have collaborator perms we can add labels and close issues.
