### ISSUE TITLE
Disabling "rail oscillate" on track platform causes the track to disappear

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#412]
![](http://i.imgur.com/gfBwkFq.gif)

**Comment by TeamSpen210** [comment]
That's an intentional bit of behaviour on the part of Valve. Oscillating platforms can start in the middle of a track, but non-oscillating platforms must start at an end. The track resets to ensure the non-oscillating platform isn't placed in the middle of a track.
