### ISSUE TITLE
[Suggestion] Add "early start" option to autoportals

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#413]
As of right now, it seems that the autoportals always have a small delay between their input and their actual activation. The reasoning behind this is unclear, but regardless it would be nice if an option was added to autoportals to make them instantly open up when triggered.

**Comment by TeamSpen210** [comment]
That small delay is necessary. In the delay period a command is issued to shut all open autoportals of the same colour. Really weird things happen if two same-coloured portals are open at the same time.
