### ISSUE TITLE
[Suggestion] Neurotoxin or any other death counter and a monitor.

### ISSUE THREAD

**Issue by towergame** [TeamSpen210/BEE2-items#415]
So I had this idea of 4 elements:
Kill trigger(If triggered it kills the player if he is in the trigger)
Timer(Shows a countdown until it triggers something)
Neurotoxin tube(It's a tube that emits neurotoxin particles) - *Already going to be implemented*
Monitor and a camera(You place a camera and a monitor so you can see yourself or something else)

**Comment by ellingtonvengaboysmuseum** [comment]
neurotoxin was created already, he just has to reimplement it.

**Comment by TheReviewers** [comment]
What About a tube ride? To Go In and ItS a quick transport :dash:

**Comment by LautaroL20** [comment]
@towergame - Kill Triggers is not a good idea, since we have already Laser Fields, Deadly Goo, and Death Fizzlers. I guess some beginner mappers could do an aphocalypse use of something like a "Kill trigger" if this were maded.

As for the Neurotoxin and monitor it will come eventually i guess.
