### ISSUE TITLE
[BUG] Portal 1 Angled Panels Dont Work

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#417]
So Basically , If You Try To Connect Any Button Or Catcher Or Anything to Move A Panel, It Gets a Build error ;-; halp

**Comment by ZombiePwner1** [comment]
This is still going around in prl 21.5 It will be fixed in the next update.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/414
