### ISSUE TITLE
Entry Lightstrips does not "Blink" alongside the smalls powercuts in "Overgrown Style"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#420]
In order to make it more realistic, it would be good if these cold lightstrips from the entrance of Overgrown style, could "Blink" alongside these small "Powercuts". In case of not being possible to make lightstrips of the entrance to "Blink" together due to some "Source engine limit", i suggest to get rid of these "Small power cut resplendence" because it looks completely "Unreal":

![gif2](https://cloud.githubusercontent.com/assets/12244376/13938343/c7874782-efab-11e5-9423-581bfb324a30.gif)

**Comment by TeamSpen210** [comment]
Ok. Unrelated question: why do you quote random words?

**Comment by LautaroL20** [comment]
Idk, maybe to highlight certain words, because my english level is not the best. Ill not doing that in the future if you want.

**Comment by LautaroL20** [comment]
This is literally impossible to do..... Case closed.

**Comment by TeamSpen210** [comment]
I actually just removed the flickering.

**Comment by Konclan** [comment]
Actually there is a flickering light in chapter 8 chamber 12. I don't know what it is exactly but I'm sure you could use it somehow http://theportalwiki.com/wiki/Portal_2_Chapter_8_Test_Chamber_12

**Comment by LautaroL20** [comment]
Hey konclan, nice to see you back :)

**Comment by Konclan** [comment]
I've been around, just not contributing because I haven't been able to play portal 2 thus I can't help find / solve problems making me useless to this community.
