### ISSUE TITLE
Will Some Items Be Re-Added

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#421]
I Really Want Some Items Back i.e. Shredders,Neurotoxin,Retractable Buttons....

I Would Also Really Appreciate If You Added Decorative Items I.e Wall Feature,Living Panels...

Thank You In Advance.

                                  -The Reviewer

**Comment by TheReviewers** [comment]
AND INCINERATOR

**Comment by LautaroL20** [comment]
I find the Neurotoxin and Incinerator actually pointless (This is just a personal opinion). But the Wall Feature, Living Pannels and much other items are something im really exited to use on Bee2.4.

**Comment by TheReviewers** [comment]
The Incinerator Is Needed. ( Especially For A Person Who Ports PETI Maps To Hammer)

**Comment by TeamSpen210** [comment]
Porting PeTI maps to hammer is a bad idea. The map format and intrrnals are terribly convoluted, and actually in many cases you'll be unable to run the map successfully without some modifications VRAD performs.

**Comment by TheReviewers** [comment]
I Know, But Triggers Are So Much Easier To Use In Beemod.

**Comment by TheReviewers** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=632919228 Ported To Hammer For Extra Effects

**Comment by towergame** [comment]
I disagree with Incinerator and Neurotoxin being useless. Incinerator could be useful for making the player to not use a cube or a sphere to make the puzzle more complicated. Neurotoxin is really good for rush parts, like really. You can make the player think forward and set everything up before neurotoxin starts flowing. If you pair it with a trigger that disables it, you can do a lot of power with it. Living panels would be good too. I would also like a monitor, but it's probably too hard to implement in PeTI.

**Comment by TheReviewers** [comment]
The Monitor Was There In The Old Beemod, So It Can Be Re-added :DD

**Comment by Luke18033** [comment]
All of these items are already going to be re-added. (#95)

**Comment by hop193** [comment]
The Monitor is Re-Added. 👍

**Comment by LautaroL20** [comment]
Lol, that was since a long time ago.

**Comment by Luke18033** [comment]
@TheReviewers I think triggers are easier to make in Hammer, actually.
