### ISSUE TITLE
Large Observation Room features no support for being put on the floor/ceiling, unlike regular Observation Room

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#422]
If you want to put it in the floor, you have to use the original glitch (click on it's icon while it's over the desired surface), and it cannot be put in the ceiling at all.
It also doesn't feature a custom layout for being put in the floor, obviously.

**Comment by LautaroL20** [comment]
Why do you want Observation Rooms on the ceilling / Floor? That looks terrible.

**Comment by ncrecc** [comment]
For whyever tSpen put it in.

**Comment by ncrecc** [comment]
Who said I did?

**Comment by TeamSpen210** [comment]
The reason I haven't done this is mainly because of Old Aperture Large Observation Grates - they won't make much sense in the floor.
