### ISSUE TITLE
More Styles?

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#423]
Are There Gonna Be Any More Styles Than This, Cause I Would Like Something like:
Portal 1 BTS Style, Its A Red Looking Map,
And Incinerator Style.
Etc....

Ps: Will You Add Pistons From Portal 1 To Walk On?

**Comment by TeamSpen210** [comment]
There will be other styles, I'm not going to work on those until I have ported across more items though. Art Therapy and Refurbished style still needs to be ported from the original BEE2, and then probably Wheatley and Reconstructing styles.

**Comment by ncrecc** [comment]
As of right now, the plans for future styles can be found [here](https://github.com/BenVlodgi/BEE2.4/blob/master/dev/Style%20Hierarchy.pdf).
