### ISSUE TITLE
[Question] Are u able to add the large faithplates to the puzzlemaker and make them customizable?

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#425]

**Comment by TeamSpen210** [comment]
Yes. I'm probably adding them in the next version. What do you mean by 'Customisable' (beyond what the normal plates do)?

**Comment by ZombiePwner1** [comment]
What i mean by customisable i mean like if a button is connected to it u need to have a cube on it for the faith plate to work and the regular faith plates don't have this.

**Comment by TeamSpen210** [comment]
I've done that for the large faith plates, but I still need to add it to the regular ones.

**Comment by Konclan** [comment]
This wasn't fixed yet though...

**Comment by TeamSpen210** [comment]
The item's in the last update.
