### ISSUE TITLE
[Question] BTW TeamSpen210 how would if its possible how would i create my own adhesion gel? cause if its possible i can perhaps put it in testchambers thru hammer

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#426]

**Comment by TeamSpen210** [comment]
You can't really. Adhesion Gel was replaced by Reflection Gel during the Peer Review update. To get the gel, set the Paint Type option on an `info_paint_sprayer` to '1'. Reflection Gel has all the implemented functionality of Adhesion Gel (counteracting the effect of Propulsion Gel-covered cubes).

To do anything more, you'll need to use lots of scripts and entities to track the locations of Adhesion Gel blobs, determine which surfaces they've painted, then figure out a way to simulate rotating the player and physics objects. It's not an easy task. [Felix Griffin](https://www.youtube.com/watch?v=DJ24Mh9H5Mw) was working on a version, although his I believe works by having the entire map parented to an entity, and then rotating that around the player.

**Comment by ZombiePwner1** [comment]
O: Still even i did want to make it idk were i would start and how to get the purple textures in

**Comment by ZombiePwner1** [comment]
And Felix Griffin uses hammer notepad i dont even know where to find that

**Comment by TeamSpen210** [comment]
It's just the title of his videos, he's just using the normal Hammer.

**Comment by ZombiePwner1** [comment]
o i just wish someone could teach me how to make this ive been wantign to play with this gel ever since i heard of it isnt there someone that can teach me how to do all that?

**Comment by ZombiePwner1** [comment]
BTW in the next update can u fix up the cat walks in the clean styles the cat walks bottom texture is pink and black check boards however in the underground the catwalks have their bottom textures  redendered correctly and they dont appear in-game if u place them down and go in-game they wont appear anywhere in the chamber.

**Comment by ZombiePwner1** [comment]
And there is a bug with the reflection gel if u right click on the dropper go to gel type and hover your mouse out of it the game will crash.

**Comment by TeamSpen210** [comment]
I can't fix that. There's a reason why there's bold black-on-white text in the item description explaining that.

In regards to the catwalks, have you read the item description? You need to connect two items together to generate a catwalk.

**Comment by ZombiePwner1** [comment]
k

**Comment by ZombiePwner1** [comment]
Well forget adhesion gel: speaking of gels is it possible for me to create my own custom gels?

**Comment by ZombiePwner1** [comment]
Such a gel that makes u freeze for abit or hurts u or something

**Comment by ZombiePwner1** [comment]
BTW is it possible for me to create my own custom gels like for example: a gel that slows u down or kills or can be used to power up things

**Comment by xDadiKx** [comment]
It should be, but that would be extremely hard to code.

**Comment by TeamSpen210** [comment]
No, you can't make new gels really. Some of the invalid paint type values sort of work, but you need to then build functionality using Hammer items. You have to also only use paint bombs, since sprayer paint isn't detectable via triggers.

**Comment by ZombiePwner1** [comment]
Well i want to make my own gel so if anyone can teach me how to do it i'd be happy

**Comment by ZombiePwner1** [comment]
o why must everything be impossible to make.

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
p

**Comment by Luke18033** [comment]
@TeamSpen210 You could fix the Reflection Gel crash by making all 4 gel types on the item Reflection Gel.

**Comment by TeamSpen210** [comment]
No I can't. The gel item is actually 2 - the dropper, and the splat. The reflection gel item is the splat version. It's hardcoded to generate the default dropper, so if I made them all reflection gel you wouldn't be able to use any of the others. I think perhaps the crash occurs when it tries to deselect the '5th' radio button.
