### ISSUE TITLE
[Bug] Texture Overlap on the Warm Light Strip

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#432]
This does not happens everytime, but sometimes when i build a map in Clean Style, this Light can get texture overlap. 

-------------------------------------------------------------------------------- 

![warm](https://cloud.githubusercontent.com/assets/15699236/14067176/f1174358-f434-11e5-9160-c74a3a502324.jpg)

**Comment by TheReviewers** [comment]
What Wall Are You Using? Doesnt Look Like Clean

**Comment by xDadiKx** [comment]
It is clean...

**Comment by TeamSpen210** [comment]
This is really actually a bug with the actual compiler and engine, I don't really have the capability to fix this easily.
