### ISSUE TITLE
[Discussion] Update: Add on for the vines for overgrown theme released for beta testing! My tubes add on will be released soon aswell.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#433]
Update: Hey guys i'm back with an update for the vines add on so the add on is finished and ready for beta testing download here: http://www.yourfilelink.com/get.php?fid=1194102

Updated instances: http://www.yourfilelink.com/get.php?fid=1194834   Vine_1.vmf
Vine_2.vmf:  http://www.yourfilelink.com/get.php?fid=1194835
Vine_3.vmf:  http://www.yourfilelink.com/get.php?fid=1194836

Now considering this is in beta they might be possible bugs if u guys encounter any let me know and i will fix them for the next update. Note do not use button 2 as button 2 is currently bugged.

Known issues:
Button 2 is not placing the ceiling vines correctly.

How to install:

Step 1 download the file obviously.

Step 2 Go to werever you have your bee 2.4 installed

Step 3 go inside the file and click on the packages folder not the winrar packages the regular packages file.

Step 4 Drag the winrar add on in there.

Step 5 Your done head into bee2.exe and a new row of buttons should be in the pallet list.

**Comment by ZombiePwner1** [comment]
Now guys some of u may want this but i cant release it yet having a few issues with it ATM but once its fully functional and working ill plan to release a beta version for it or so.

**Comment by TheReviewers** [comment]
link download for addon

**Comment by TheReviewers** [comment]
also the vents are gud idea, butt butt butt. https://github.com/BenVlodgi/BEE2.4/issues/260

**Comment by ZombiePwner1** [comment]
Like i said i'm not releasing the link for the add on until i get the vines fixed to place on the walls once that's done ill be releasing a download link for BETA.

**Comment by ZombiePwner1** [comment]
And yes don't worry ill be making vents as an add on aswell so once the vines are fully functional and working ill start working on vents.

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
I also read ur comment for breakable tubes yes i will be adding that with gel flowing through them
and the tube u have to break to get a cube.

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
And ill most likely be making 2 addons for the tubes with is 6 cosidering i can 3 models each so there will be some different models

**Comment by ZombiePwner1** [comment]
;

**Comment by ZombiePwner1** [comment]
/

**Comment by ZombiePwner1** [comment]
d

**Comment by TheReviewers** [comment]
how to download addons anyway?

**Comment by TeamSpen210** [comment]
If someone makes an addon, you can just copy the zip file into the `packages/` folder.

**Comment by LautaroL20** [comment]
@TeamSpen210 - lol, i already asked how to install an addon but you said it was not easy since the compiler commands have changed a lot.

https://github.com/BenVlodgi/BEE2.4/issues/262#issuecomment-201708120

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
TheReviewers the addon wont be released until i can get the vines correctly placed so ur gonna have to wait.

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
![preview0000](https://cloud.githubusercontent.com/assets/18079316/14094784/299e2fb8-f58c-11e5-940a-30db34491970.jpg)

**Comment by ZombiePwner1** [comment]
![preview0000](https://cloud.githubusercontent.com/assets/18079316/14094789/3a39ac6c-f58c-11e5-9b89-eaf9235471be.jpg)

**Comment by ZombiePwner1** [comment]
![preview0000](https://cloud.githubusercontent.com/assets/18079316/14095581/6538ce22-f594-11e5-902a-3f70d9b64b4f.jpg)









Preview of a propulsion gel dropper

**Comment by ZombiePwner1** [comment]
Add on for the vines released. Download above.

**Comment by TheReviewers** [comment]
where to place the instances?

**Comment by TheReviewers** [comment]
nevermind.

**Comment by ZombiePwner1** [comment]
Enjoy it!.

**Comment by ZombiePwner1** [comment]
Let me know if u experience any issues

**Comment by TheReviewers** [comment]
Error Rebuilding puzzle :(

**Comment by ZombiePwner1** [comment]
O:
 What happened there?. If u know how to turn the console on then let me know what the error is.

**Comment by TheReviewers** [comment]
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/over/items/zp/vine_1.vmf

**Comment by ZombiePwner1** [comment]
d

**Comment by ZombiePwner1** [comment]
Ahhh k i will fix that look thru the hammer folders to see if the zp file is there for overgrown

**Comment by TeamSpen210** [comment]
In your vines package, you should put a copy of the instances in `resources/instances/over/items/zp/`. That way the BEE2.4 will automatically extract the instances to the right place.

**Comment by ZombiePwner1** [comment]
k the vine instances are updated

**Comment by ZombiePwner1** [comment]
d

**Comment by TheReviewers** [comment]
cant you just do what @TeamSpen210  does, and place everything in one file -.-

**Comment by ZombiePwner1** [comment]
i will next time

**Comment by ZombiePwner1** [comment]
Anyways did the new VMF's work?

**Comment by TheReviewers** [comment]
ofcourse not, another build error -.-

**Comment by TheReviewers** [comment]
Whats new?

**Comment by BenVlodgi** [comment]
You should make a repository for your items package, and release it the same way TeamSpen210 does
