### ISSUE TITLE
[Suggestion] Make Square Light and LightStips items to not occupy space behing the wall (Useful for cool placement)

### ISSUE THREAD

**Issue by Enterpise** [TeamSpen210/BEE2-items#435]
Make Lighting items to not occupy space like you did with the Half Wall. And it will be useful for cool placements. If possible do this also for the Small Observation room too.

This is annoying, isnt it:

![20160328165608_1](https://cloud.githubusercontent.com/assets/12244376/14088867/36ae7f98-f508-11e5-978e-d9789e815be8.jpg)

![20160328170814_1](https://cloud.githubusercontent.com/assets/15699236/14088953/ac763eb4-f508-11e5-827b-48b48fbb80a1.jpg)

And this could be the benefit if you do this suggestion:

![2016-02-29_00001](https://cloud.githubusercontent.com/assets/15699236/14089102/760aec48-f509-11e5-87d0-6291b8dc39ab.jpg)

**Comment by TheReviewers** [comment]
True :(

**Comment by TeamSpen210** [comment]
I can't do this. It's not possible to change light strip collision (which don't occupy wall-space anyway). Warm square lights do actually occupy significant space in the wall, so I can't change that.
