### ISSUE TITLE
help needed with hammer

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#44]
i need help, how do i fix this

-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"

-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbs
p.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C
:\Users\Cam\Desktop\1950timetravel\resources\instances\50s\sphere_sp\elevator_en
trance.vmf"
-------------------------------------------------------------------------------

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is ""
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 1730, in main
Exception: No map passed!
Finished. Press a key to close.

**Comment by TeamSpen210** [comment]
Ok, the problem is that your map isn't in sdk_content and my VBSP replacement can't understand that.
Change vbsp and vrad in Hammer > tools >options > build programs to vbsp_original.exe and vrad_original, and then it should compile fine. I'll fix the BEE VBSP and VRAD in the next release.
