### ISSUE TITLE
Portal 1 Full Style

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#440]
Like, Umm.. Jump Height, Movement Speed, Physics, All Ported From Portal 1 ( Including Models )
Pls @TeamSpen210 And @BenVlodgi I Know You Guys Can Do It. I Trust You
                                                                                                  Sincerely 
                                                                                                               -The Reviewer <3

**Comment by TheReviewers** [comment]
And Portal 1 Chell

**Comment by TheReviewers** [comment]
Ps : And Turret

**Comment by CrashingScience** [comment]
The inside of p1 turret is solid white instead of yellow

**Comment by CrashingScience** [comment]
Now ive just had a thought, i think p1 and p2 run on different vertions of
the source engine.

**Comment by TeamSpen210** [comment]
Um, I can't do that. You very much overestimate what you can do with a workshop map - I can't port Portal 1's entire physics engine version. If you want that, play Portal 1.

**Comment by TheReviewers** [comment]
They Still Can Change The Gravity And Scripts And Such, To Change It

**Comment by TheReviewers** [comment]
XD

**Comment by TeamSpen210** [comment]
No, I can't change the actual gravity.

**Comment by TheReviewers** [comment]
Oh Well

**Comment by TheReviewers** [comment]
I Guess You Can Atleast Add The Turrets
