### ISSUE TITLE
Choreo Box Idea

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#442]
What About, A Choreo Box For A Character.
For Example:
Voice: Glados
Choreo Box : Announcer

Glados: Sorry About The Mess, Ive Really Let The Place Go Since You Killed Me....
Announcer: Sarcasm Self Test Complete
Glados : Oh Good

**Comment by TheReviewers** [comment]
Yes Yes I Know My Ideas Suck, But You Can Try Something Similar

**Comment by LautaroL20** [comment]
I think that would be pretty hard to do, and if its doable it could cause tons of bugs on the voicelines.
