### ISSUE TITLE
Issues with Flamethrower

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#443]
Flamethrowers have no editor model
![20160330180434_1](https://cloud.githubusercontent.com/assets/16567080/14160471/2e53f0e4-f6a2-11e5-86c1-39cd38f5bcb5.jpg)
Their kill trigger is only 1 unit tall so having them below grates does not effect you
![20160330180542_1](https://cloud.githubusercontent.com/assets/16567080/14160473/36685bee-f6a2-11e5-8a3c-fe81d0e79716.jpg)

**Comment by Luke18033** [comment]
Flamethrower?

**Comment by TeamSpen210** [comment]
1960's crusher variant.

**Comment by LautaroL20** [comment]
Its fixed now.
