### ISSUE TITLE
Bee2 not working

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#444]

**Comment by xDadiKx** [comment]
How is it not working?

**Comment by xDadiKx** [comment]
So am I going to stare at this screen till death? Or will I get a reply?

**Comment by TheReviewers** [comment]
build error

**Comment by xDadiKx** [comment]
Can you post the information from your console?

**Comment by TheReviewers** [comment]
you read console language?

**Comment by TheReviewers** [comment]
?

**Comment by Konclan** [comment]
What seems to be causing the problem, What style are you using. You need to give more information then it just doesn't work

**Comment by LautaroL20** [comment]
@TheReviewers - Just open up developer console, enable sv_cheats 1, and then write Developer 2, The full log displaying the complete compile errors should be there, copy paste it here.

**Comment by TheReviewers** [comment]
i dont know how to close issue

**Comment by TheReviewers** [comment]
The Reviewers Closed Issue

**Comment by Konclan** [comment]
Well that was pointless :p

**Comment by LautaroL20** [comment]
But did you finally solve your "Build error"? You will going to close your issue without giving final conclusion / Feedback about it......... so I think i will start ignoring / Unsubsribe from @TheReviewer´s posts then.

**Comment by TheReviewers** [comment]
yes i did solve it, my internet was broken for a while and i didnt have time to write that i already solved it, i solved it btw...

**Comment by TheReviewers** [comment]
@LautaroL20 Why Did You Ever Subscribe To My Posts....

**Comment by TheReviewers** [comment]
thank you teamspen
