### ISSUE TITLE
[Suggestion] Overgrown Style: Implement option on the Large Observation to have "Permanent Lighting Witouth Shutdowns"

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#445]
The large observation room from Overgrown Style starts to get annoying when they keep turning on and off, can you make an option for that so we can have a permanent static lighting without annoying shutdowns?

**Comment by LautaroL20** [comment]
Wich style are you using? That only happens in Overgrown style i think, but it is part of the choreo.

**Comment by Konclan** [comment]
In the overgrown style, the large observation room's light turns on and off at random making loud noises.

**Comment by Konclan** [comment]
I don't think its part of the choreo box, its just a generic sound and light

**Comment by LautaroL20** [comment]
@Konclan - This is indeed part of the choreo, but still its an annoyiance that should be fixed by adding an aditional option of "Start ennabled" or so, so we can get a permanent static lighting witout shutdowns.

**Comment by LautaroL20** [comment]
This is pretty easy to do. You only have to get rid from the "Logic_Timer" that is associated with the env_projectexture and ambient_sounds. Then youll get a nice permanent observation lighting without shutdowns.

**Comment by TeamSpen210** [comment]
Actually I'll probably make the observation rooms permanently off (but still producing light).

**Comment by LautaroL20** [comment]
Fixed via: e821b68e9a89a1dcd80bda5d8b3a692d6d8ba7d7
