### ISSUE TITLE
[Lighting Items] Variants: Square Cold Light and Square White Light 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#448]
I suggest to implement the Square Cold Light, and Square White Light (the ordinary Lightstrip colour). This will brind the mappers more options to contrast areas with these lighting variations and it will make maps to look more interesting. 

Having the option to change these Square Light variations alongside with the current Square Warm Light, via context menu like a floor button.

---

![lightcold](https://cloud.githubusercontent.com/assets/12244376/14304509/cd3aa96e-fb89-11e5-8a07-17f30eedae1a.jpg)
![light](https://cloud.githubusercontent.com/assets/12244376/14304523/dd849726-fb89-11e5-8312-1dbb0d0f47a4.jpg)

**Comment by Konclan** [comment]
Wasn't there a Beta screenshot of the PeTI with a 3x1 observation room with bendies in it?

**Comment by Konclan** [comment]
Never mind, it was 4x1 observation room http://media.steampowered.com/apps/portal2/media/map_editor_02.jpg

**Comment by LautaroL20** [comment]
@Konclan - The second screenshot from my post was a concept art i maded for TeamSpen210 respect on how good would be to have extra otions under a "Dropdown bar menu" to short the items into the Bee2.4 interface. For more details about this, check this post: https://github.com/BenVlodgi/BEE2.4/issues/212
