### ISSUE TITLE
Rattman Den Maker Suggestion

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#450]
Its An Item With a Button Timer Thingy, That Allows You To Place Rattman Graffiti, Portal 2 And Overgrown Style Use The Portal 2 Den Graffiti, And Portal 1Style Uses The Portal 1 ( obviously )
And 1950 Uses a custom graffiti made by teamspen :D

**Comment by TeamSpen210** [comment]
Ratman dens don't make any sense in Art Therapy or Clean styles - they were built after Doug Ratmann was wandering the facility, so there won't be any dens. 1950s era rooms were sealed long before Ratmann, so he didn't have access to them (although I could replace it with offices or employee rooms with posters).

Part of the thing about Ratmann dens are the BTS environment - just having graffiti randomly on a test wall wouldn't make any sense, and would look horrible.

**Comment by TheReviewers** [comment]
not on a test wall -.-, put a small hole in a wall, make it look like a den, put some posters. @TeamSpen210 be creative dude, its just a game

**Comment by Konclan** [comment]
I do like the suggestion, though I feel like dens are not something you find just in a wall. They are usually behind angled panels or in broken observation rooms. also how big would they be? would they be as big as say a large observation room?

**Comment by TheReviewers** [comment]
thats what i mean!

**Comment by TheReviewers** [comment]
also @TeamSpen210  we dont know the full story of rattman, we can just assume that he wasnt in the 1950's era.

**Comment by Konclan** [comment]
Actually we do know the full story of Doug Rattman, there are comics

**Comment by TheReviewers** [comment]
do we know rattmans age, how old has he been in aperture, is he a relative to cave johnson etc.

**Comment by Konclan** [comment]
http://half-life.wikia.com/wiki/Doug_Rattmann

**Comment by Konclan** [comment]
Its also theorized that in the rattmann's secret message, he says "uncle johnson" and talks about how mesa stole the borealis. So its possible doug was working in old aperture

**Comment by TheReviewers** [comment]
it sounds like uncle johnson, but its not 100%

**Comment by Konclan** [comment]
Well, thats why I said "theorized", but yeah its not 100%
