### ISSUE TITLE
Mid Chamber Dialogue Doesnt Work

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#453]
Wheatley Doesnt Say The Boxes Legs Speech, Glados Doesnt Comment On Fizzling Cubes etc..

**Comment by Konclan** [comment]
Just as a general question, why do you capitalize everything?

**Comment by TheReviewers** [comment]
Does Everyone Have To Ask, I Do It Because I Like It

**Comment by Konclan** [comment]
Ok, I was just wondering lol

**Comment by LautaroL20** [comment]
Very probably fixed long time ago, since i can heard glados talking when a cube gets fizzled.
