### ISSUE TITLE
1950's era cutout tile

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#454]
It Can Be Replaced With... Wait For It.............CAVES, Put It On The Wall For The Silver Cave Texture, Floor,Cieling, ANYWHERE!

**Comment by TeamSpen210** [comment]
That doesn't really make sense. The current Old Aperture styles are inside enrichment spheres, so there isn't any cave walls accessible. I might in the future though make a cave version of the Old Aperture styles, with tunnels and bottomless pits.

**Comment by Konclan** [comment]
Maybe you could make an old aperture bts them.
