### ISSUE TITLE
Port Portal 1 Style Elevator texture

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#456]
There Are 2 Things That Bother Me With The Portal 1 Elevator:

1. The Aperture Logo Is Not Bright Shiny Blue

2. The elevator  Door Doesnt Close When you exit the elevator

**Comment by TeamSpen210** [comment]
In Portal 1, the elevator doesn't close immediately when you exit either. If you walk into the corridor a little further it'll close.

**Comment by TheReviewers** [comment]
@TeamSpen210 And The Logo?

**Comment by TeamSpen210** [comment]
I'll investigate that.

**Comment by TheReviewers** [comment]
ill send you a pic

**Comment by TheReviewers** [comment]
https://www.google.com.eg/search?q=portal+1+elevator&biw=1366&bih=643&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjCzazzuv3LAhXEiCwKHeBoCaYQ_AUIBigB#imgdii=6MRB6ax2KsIumM%3A%3B6MRB6ax2KsIumM%3A%3BplCBMqTnQJbCEM%3A&imgrc=6MRB6ax2KsIumM%3A this is how it should look like

**Comment by Konclan** [comment]
I looked at the picture then saw a picture next to it, now I really want an elevator like this http://media.moddb.com/images/mods/1/21/20161/sp_enceladus_map_030050.jpg

**Comment by TeamSpen210** [comment]
The elevator texture is actually the exact same.

**Comment by ZombiePwner1** [comment]
The logo's brightens may be abit different because portal 1 style doesn't have light coming through the floor unlike in the 1st game itself.
