### ISSUE TITLE
New Item : Invisible Light

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#458]
It Works Just Like A Lamp, But It Doesnt Take Space So You Can Place It Anywhere.

Weighted is normal 

Cube Is Warm

Sphere Is Cold

**Comment by TeamSpen210** [comment]
The PeTI already actually adds ambient lighting entities to keep the map bright. If you want light, place a light. I'm not adding magic invisible things.

**Comment by TheReviewers** [comment]
@TeamSpen210 i was working on a map in overgrown, i placed over 50 lightstrips, and the map was still dark, explain this :3

**Comment by Luke18033** [comment]
@TeamSpen210 But triggers are "magic" and invisible...

**Comment by TeamSpen210** [comment]
Not really. The explanation would be motion detectors in doors, or position tracking via cameras. Doors already have motion tracking all the time, including in Old Aperture.
