### ISSUE TITLE
3d Skybox idea

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#46]
behold what could work as a 3d skybox for the overgrown style so we can have proper overgrown bottomless pits. Use this as a template to create a overgrown 3d skybox!

![sp_a1_intro10000](https://cloud.githubusercontent.com/assets/11165643/8456464/9b2d81a8-1fd9-11e5-8cbb-79dcce2172aa.jpg)

![sp_a1_intro10001](https://cloud.githubusercontent.com/assets/11165643/8456466/9dd629c8-1fd9-11e5-9d61-adc063a1cd91.jpg)

**Comment by TeamSpen210** [comment]
This isn't really the overgrown style. It's specifically the Extended Relaxation Vault. I probably will do something sort of similar, just without all the relaxation chambers.
