### ISSUE TITLE
[Bug] Piston Plataform is also literally "Dead"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#462]
Doesn't matter if a connection is set or not. The Piston Platform will remain "Dead". (This bug happens in the current Prl 19).

Additional details: The only way to get it working is to connect a infinite pedestal button and then come in to the platform.

-------------------------------------------------------------------------------------------
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/14402939/e9a07fe2-fe19-11e5-9335-45a624da8c6b.gif)

**Comment by TeamSpen210** [comment]
This isn't a bug. I changed the functionality to allow for some additional arrangements. The 'auto-start' option turns on and off the player-detector. If the detector is enabled, all inputs must be enabled and the player must be present for it to move (like the platforms in Portal 1). With it unchecked, it doesn't detect the player, and requires inputs to do anything.

**Comment by ZombiePwner1** [comment]
Yo teamspen u able to come online?

**Comment by LautaroL20** [comment]
@TeamSpen210 - Okay, but there is still a piston plataform on bee2.4 similar to the original PeTi one?

**Comment by TeamSpen210** [comment]
The new platform has all the same features as the original PeTI item - it has 4 modes, whereas the original only has 2:


Auto-Drop | No input | Input 
----- | ------ | -----
:ballot_box_with_check: | Player only (PeTI) | Player and input
:negative_squared_cross_mark:  | No movement | Input only (PeTI)

**Comment by TheReviewers** [comment]
@LautaroL20 Read The Description Of The Item Next Time ;)

**Comment by LautaroL20** [comment]
@TeamSpen210 - In that case i still should keep learning how this re-worked item works, i think i had been totally confused by its new funtions. If i made some puzzles concept i can´t handle with these newer changes, ill ask your help via Steam.

**Comment by TheReviewers** [comment]
@LautaroL20 Did You Know If You Dont Connect Anything To A Angled Panel, It Becomes Static?

**Comment by LautaroL20** [comment]
@TheReviewers - Actually the Peti original piston plataform worked slightly different, with connections or withouth them. So i don't understand why you are trying to look that arrogant....

**Comment by TheReviewers** [comment]
@LautaroL20 Arrogant?

**Comment by TheReviewers** [comment]
i was just telling you a feature :(
