### ISSUE TITLE
Long Lightstrip 

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#463]
http://steamcommunity.com/sharedfiles/filedetails/?id=662064557

A Long Lightstrip That Occupies 2 Blocks?

**Comment by LautaroL20** [comment]
It would be really cool to have three Stretching LightStrips variations and change them via button type context menu. I heard say TeamSpen210 this cannot be made in other styles. But i think at least would be good to have these Stretching LightStrips in the Clean Style.

**Comment by ellingtonvengaboysmuseum** [comment]
not going to happen, @TeamSpen210 said he is not going to implement the longer versions since their buggy.

**Comment by LautaroL20** [comment]
Oh, what a pity : /

**Comment by TeamSpen210** [comment]
The main issue is that the Clean longer lightstrip models look terrible - they're very stretched looking. I also can't make it actually collide, so the extra parts can pass through things and won't block antlines.

**Comment by Konclan** [comment]
A long light strip is just two short lightstrips XD
