### ISSUE TITLE
reflection gel still has bug

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#47]
purple reflection gel? 

also is this a sign that you're also implementing sticky gel.

![preview0042](https://cloud.githubusercontent.com/assets/11165643/8456571/4cf31efc-1fda-11e5-9f83-b677a72ffc5c.jpg)

**Comment by TeamSpen210** [comment]
This is a bug, it's just a wrongly set number in editoritems. Carl did include textures for purple gel, which is why it looks like this. It won't actually work though - it just crashes you when you walk on it.
