### ISSUE TITLE
Glados Portal 1 Voice Lines Idea

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#470]
Yes @TeamSpen210 I Know You Probably Wont Add Portal 1 Voice Lines, But Whats Gonna Be The Voice Of P1 Chambers, Here Are Some Ideas:

Entry:

Generic : 
http://i1.theportalwiki.net/img/e/e5/GLaDOS_00_part1_entry-1.wav

http://i1.theportalwiki.net/img/d/d0/GLaDOS_05_part1_entry-1.wav

High Energy Pellet:
http://i1.theportalwiki.net/img/3/34/GLaDOS_09_part1_entry-1.wav

http://i1.theportalwiki.net/img/6/64/GLaDOS_03_part1_entry-2.wav

http://i1.theportalwiki.net/img/b/b1/GLaDOS_03_part2_entry-1.wav

Deadly Goo: 
http://i1.theportalwiki.net/img/5/5d/GLaDOS_04_part1_entry-1.wav

Upgrading To Dual Portal Device :

 http://i1.theportalwiki.net/img/3/3c/GLaDOS_07_part1_get_device_component-1.wav

http://i1.theportalwiki.net/img/7/76/GLaDOS_08_part1_entry-1.wav

Companion Cube: 
http://i1.theportalwiki.net/img/6/6e/GLaDOS_13_part1_pickup-1.wav

EXIT : 

Generic : 

http://i1.theportalwiki.net/img/a/af/GLaDOS_01_part2_success-1.wav

http://i1.theportalwiki.net/img/4/41/GLaDOS_15_part1_into_the_fire-5.wav

Deadly : 
http://i1.theportalwiki.net/img/7/73/GLaDOS_04_part1_success-1.wav

High Pellet : 

http://i1.theportalwiki.net/img/2/2a/GLaDOS_03_part1_success-1.wav

Companion Cube : 
http://i1.theportalwiki.net/img/2/22/GLaDOS_13_part1_middle-2.wav

**Comment by Konclan** [comment]
"Please be careful".. I think there needs to be another line with that XD

**Comment by TheReviewers** [comment]
@Konclan Up To Teamspen To Decide

**Comment by TeamSpen210** [comment]
I'd like to add Portal 1 voicelines, but currently it can't be done. I could pack the sounds fine, but I can't make them switch properly for different language settings. Not everyone speaks English.

**Comment by CrashingScience** [comment]
As a kind of compromise, altough it would be more difficult, you could make
the p1 voice lines as a seperate download and we install them manually.

**Comment by TeamSpen210** [comment]
Making different language versions isn't the problem - I could probably program the BEE2 to detect Portal 2's set language and copy over the appropriate files. The problem comes when downloading off the Workshop - it needs to match the language of the person who downloaded it, otherwise the language switch will be very jarring.

**Comment by Enterpise** [comment]
To everyone who want @TeamSpen210 to make this, please understand this is not a Portal 1 simulator into BEE2, this is just a Style like any other, that just changes textures and some small voicelines. If you really want to feel it more like Portal 1, just play the damn Portal 1 game and youll listen all voicelines you want.  

But please, people... just stop asking @TeamSpen210 to make a Portal 1 simulator into BEE2, he already said this could ending very messy, if anyone still feels have not played enough Portal 1, go and play it again but stop this shit of pushing developers to make a P1 Simulator. 

The Developers of BEE2 has already a MASSIVE LIST OF BUGS left to fix and many suggestions much more interesting than stupid voicelines, so i preffer developers to focus on fixing these current issues.

**Comment by Konclan** [comment]
It's not like we are forcing him to do any of this, teamspen could just say f it I'm done at any point. We are suggesting future ideas for when teamspen has time to work on these things. Also it's not portal 1 simulator, it's just a style which we would like the portal voicelines to appear in for the aesthetic purpose. We would live without it. So don't get mad when all we do is want an improvement on a feature. (Plus PeTI is a lot easier than making portal 1 maps)

**Comment by TheReviewers** [comment]
@Enterpise ... Portal 1 Doesnt Have Custom Map Creator -.-

**Comment by TheReviewers** [comment]
@Konclan You Are Gud :3

**Comment by TheReviewers** [comment]
Teamspen And Enterprise Hate Me, Case Closed

**Comment by Konclan** [comment]
Also @Enterprise, you shouldn't get so upset over an idea, @TheReviewers even states at the beginning of the suggestion "I know you probably won't add Portal 1 voice lines... But here is some ideas". I feel like you overreacted a bit :/

**Comment by Enterpise** [comment]
@TeamSpen210, @Konclan, @TheReviewers  - Maybe I have not given me understand well, i am mostly against adding stupid Portal 1 voice lines which that could ending up very messy, because it could not be switched between different voice translations, so, exepting voicelines, every suggestion / Ennhancement is totally welcome for BEE2.

**Comment by TheReviewers** [comment]
@Enterpise @TeamSpen210 Still Hate Me Though XD

**Comment by TheReviewers** [comment]
@TeamSpen210 Then Make Custom Voice Creator, Download Voice From Portal wiki, Add It To Beemod, Spanish People Can Add Spanish Voice Lines, Russians Can Add Russian etc.. Yes People Will Probably Spam Random Useless Voice lines, But Valve Can Ban Such Chambers

**Comment by Enterpise** [comment]
@TheReviewers - Forcing people to listen others voicelines languages, for example, English voicelines for a Japanese player, or Spanish voicelines for a German player, or Russian voicelines for English players will sounds like an ABERRATION.

**Comment by TheReviewers** [comment]
@Enterpise You Have No Idea How Many Maps Do This!
