### ISSUE TITLE
Spawn Points And Exit Points

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#471]
It would Be Cool To Have Something Like A Save Point, But For Spawning, Remove The Entry/Exit Door, Add A Spawnpoint, And Enjoy :D

**Comment by Konclan** [comment]
So basically a spawn point you can place anywhere in the map, I think something like that may encourage people to place spawn points over water or something unless it can only be placed on the floor of a solid tile (like a super button) Also would it have the animation of you getting up like after the fall in the start of the chapter "The Fall". Idk this item doesn't really have a use though

**Comment by Konclan** [comment]
Also why would you remove the exit door? How would people beat the map then. Plus it seems really strange to have people start in the middle of a chamber

**Comment by TheReviewers** [comment]
@Konclan To Start A Map At A Faith Plate, Or Not To Go To Stupid Elevator, Like In Portal 1 , The Loading Screen In Escape 1 Is Not An Elevator, I Like That . @TeamSpen210 Please Make This For GLaDOS

**Comment by TeamSpen210** [comment]
I'd prefer to implement floor/ceiling entry/exit doors - BenVlodgi/BEE2.4#32. The problem with this spawn point is that it wouldn't make sense in most cases - you wake up, but how did you get into the map in the first place? The BTS corridors you spawn in always have a door at the beginning and end, to indicate where you came from.
