### ISSUE TITLE
BTS Observation Room [Small]

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#472]
The Title Says Its A Test Chamber, All I See Is Lights From An Obs Room,

**Comment by Konclan** [comment]
Maybe instead of a test chamber you can have a window to an office, would make it a lot easier

**Comment by TheReviewers** [comment]
@Konclan Did You Know, I Had Literally TERRABYTES, Of Emails Today, I Spent 2 Hours Reading Them :(

**Comment by TheReviewers** [comment]
@TeamSpen210 Why is it labeled FIXED, when it should be labeled, fixed for next release?
is 20 out already?!

**Comment by TeamSpen210** [comment]
I renamed that label to make it a bit shorter
