### ISSUE TITLE
Portal 1 Cube Dropper

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#473]
So, Well When A Cube Drops, You Cant Pick It Up Until It Touches Something Solid, In Other Words, You Cant Pick Up Cubes Mid Fall, Cube Falls To Goo, Puzzle Broken. Fix Please!

**Comment by Luke18033** [comment]
Why do you make every word capital?

**Comment by Konclan** [comment]
Doesn't everyone want to know XD

**Comment by TheReviewers** [comment]
@Luke18033 Thats my style of writing
