### ISSUE TITLE
When Does The Next Pre-Release Come?

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#478]
Isnt Every Pre Releas Supposed To Come In Like, A Month Or So!?

**Comment by LautaroL20** [comment]
TeamSpen210 will not going to release the Prl20 until he fixes at least a good part of the reported bugs. It does not make sense to release something that does not fix the current bugs.

**Comment by TheReviewers** [comment]
@LautaroL20 Stop Reporting Bugs Then :D

**Comment by Konclan** [comment]
We have to report bugs lol, if not then hows this mod supposed to improve

**Comment by TheReviewers** [comment]
@Konclan new release or i kill myself

**Comment by Konclan** [comment]
Don't joke about that dude

**Comment by SpyyZ158** [comment]
Chill guys

**Comment by TheReviewers** [comment]
@Konclan About What?

**Comment by TheReviewers** [comment]
@Konclan I dont Think You Know What Im Going Through.

If You Want To Know, Here Is A Summary:

You, @LautaroL20 , @BenVlodgi , @TeamSpen210 Are My Only Friends, Literally, I have NO OTHER Friends, Not In Real Life, Not On Internet, Thats Why I Always Talk Alot. Im So Lonely I Dont Care About Death.

**Comment by TeamSpen210** [comment]
I've been busy with a bunch of other things recently. I'll be fixing a bunch of bugs, then releasing the next version.

**Comment by TheReviewers** [comment]
@TeamSpen210 Estimated Time Of Release?
