### ISSUE TITLE
How to make custom pit?

### ISSUE THREAD

**Issue by corrupt21** [TeamSpen210/BEE2-items#481]
I have all my vmf's ready but I want to know how to do this. I know you need a custom skybox but I cannot find the skybox folders. And another question is this even possible?

**Comment by TeamSpen210** [comment]
Check the [BTS](https://github.com/TeamSpen210/BEE2-items/tree/master/packages/styles/bts_style) package. You'll want to make a copy of `info.txt` as well as the `skybox` folder, then put both into a folder inside `packages`. Delete everything out of `info.txt` except for the `skybox` block, as well as the `ID` values at the top. Change all the names how you want, and change the file paths in the `skybox/`config. You can put multiple duplicate lines for different variants - one will be randomly chosen. If you put a blank instance nothing will be added, so you do that if you only want instances sometimes.
