### ISSUE TITLE
[Question] Overgrown Exits

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#482]
Are The Overgrown Exits Supposed To look like The Clean Ones?

They Are Really Similar

**Comment by TeamSpen210** [comment]
Overgrown exits should all have collapsed ceilings, plants and debris.

**Comment by TheReviewers** [comment]
@TeamSpen210 No no no no no no. i meant to ask if they are supposed to like like the clean ones but in overgrown!!!

**Comment by TheReviewers** [comment]
remove dat labels!!!

**Comment by TheReviewers** [comment]
@TeamSpen210 umm...

**Comment by TeamSpen210** [comment]
Ah. Overgrown style is supposed to look like wrecked Clean style.

**Comment by TheReviewers** [comment]
@TeamSpen210 What Entrance Is Flooded Supposed To Be?

**Comment by TeamSpen210** [comment]
They don't really actually match the layouts of the Clean ones, I made each from scratch.

**Comment by TheReviewers** [comment]
@TeamSpen210 Will You Make More, Please!
