### ISSUE TITLE
[Help] Need Help at editing pedestal_button.vmf, i can't get rid from the "Pedestal Block".

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#485]
I am trying to make a set of addons for Bee2 with Hammer, i started watching some tutorials but still i am a noob. Well, here is the issue i am having, and any help on this will be really appreciated.

The issue i am having is at trying to edit "Pedestal_button.vmf" from the P2 instances. I can't get rid from the "Pedestal Block", because Hammer does not shows it on any of the Grids / Camera Views.

Here is a Hammer screenshot in where it seemed this pedestal block does not exist (Click to HD):
![hammer](https://cloud.githubusercontent.com/assets/12244376/14695954/4a8bcd20-074d-11e6-9d6e-54aa13dd2edf.jpg)

But the truth is this pedestal block does exist, so i was wondering if this is because Hammer is not showing certain hidden things on the grid, or this is related to the "Editoritems" configuration, i was wondering what is causing this annoying pedestal block to exist??? In-Game screenshot result:

![20160420221359_1](https://cloud.githubusercontent.com/assets/12244376/14696053/4febef10-074e-11e6-9ad5-32d22b3467f9.jpg)

**Comment by TeamSpen210** [comment]
The button pedestal is actually generated by the editor directly, like other wall surfaces (so it can use correct wall textures). Remove the `"ItemClass" "ItemPedestalButton"` line to disable it, the button class doesn't do anything else special.

**Comment by LautaroL20** [comment]
@TeamSpen210 Thank you so much! Afther finish making this set of addons , i will give it to you via Steam, so you can put it into the Bee2.4 to make available to everyone.
