### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#486]
VBSP failed.

[I] vbsp: BEE2.4.0pr19 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: GooDebris: 0/0 locations
[I] cond.catwalks: Starting catwalk generator...
[I] cond.core: Exiting empty condition!
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] cond.core: Exiting empty condition!
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: ['quote_loc', 'base', 'quoteevents', 'midchamber', 'group', 'group']
[I] voiceLine: No responses data..
[I] voiceLine: Line "The Future Starts With You" is disabled..
[I] voiceLine: Line "Animal Kings" is disabled..
[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Technical Difficulties'), Property('ID', 'ENTRY_GEN_TECH_DIFF'), Property('Trans', 'Announcer: We are currently experiencing technical difficulties due to circumstances of potentially apocalyptic significance beyond our control.'), Property('Trans', 'Announcer: However, thanks to Emergency Testing Protocols, testing can continue. These pre-recorded messages will provide instructional and motivational support, so that science can still be done, even in the event of environmental, social, economic, or structural collapse.'), Property('File', 'ann_apoc/entry_tech_diff.vmf')])
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"Name" "Technical Difficulties"
 | 	"ID" "ENTRY_GEN_TECH_DIFF"
 | 	"Trans" "Announcer: We are currently experiencing technical difficulties due to circumstances of potentially apocalyptic significance beyond our control."
 | 	"Trans" "Announcer: However, thanks to Emergency Testing Protocols, testing can continue. These pre-recorded messages will provide instructional and motivational support, so that science can still be done, even in the event of environmental, social, economic, or structural collapse."
 | 	"File" "ann_apoc/entry_tech_diff.vmf"
 | 	}
 |_

[I] voiceLine: Line "You May Now Re-Enter" is disabled..
[I] voiceLine: Line "Write Down Your Results" is disabled..
[I] voiceLine: Line "Evacuation Preparation" is disabled..
[I] voiceLine: Chosen: Property('Line_SP', [Property('Name', 'Technical Difficulties'), Property('ID', 'EXIT_GEN_TECH_DIFF'), Property('Trans', 'Announcer: Good!'), Property('Trans', 'Announcer: Because of the technical difficulties we are currently experiencing, your test environment is unsupervised.'), Property('Choreo', 'ann_apoc/exit_tech_diff.vmf')])
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"Name" "Technical Difficulties"
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Trans" "Announcer: Good!"
 | 	"Trans" "Announcer: Because of the technical difficulties we are currently experiencing, your test environment is unsupervised."
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 |_

[I] voiceLine: Mid quotes: []
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: N, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: 
[I] cond.core: Style Vars:
[I] cond.core: Global instances: 
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/glass_player_clip.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[I] vbsp: "materials/BEE2/overgrown/glass.vmt"
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: "sound/BEE2/p1/charge_pgun.wav"
[I] vbsp: "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2015)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/logic/bee/trigger_once.vmf

VBSP failed! (1)

**Comment by LautaroL20** [comment]
You are missing the "trigger_once.vmf" file on your "/BEE2/logic/bee/" folder. That is causing the compiling error.

**Comment by TeamSpen210** [comment]
That's not actually the problem - triggers don't use instances any more to allow them to be resized.

**Comment by Konclan** [comment]
Huh, did not know that, then again I don't know a lot about how this mod works :P

**Comment by TheReviewers** [comment]
happens if you place shutdown delayer, overgrown

**Comment by LautaroL20** [comment]
Fixed a long time ago.
