### ISSUE TITLE
Adding rexaura music and items?

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#489]
I saw in some of the changes that there was the additions of icons from the rexaura mod (Coincidentally I just discovered this mod recently). Is it for just music or are you adding the items as well?

**Comment by SpyyZ158** [comment]
Oh wow, I forgot about this one mod.

**Comment by TeamSpen210** [comment]
I will be adding music and items.

**Comment by Konclan** [comment]
This was more of a question then a suggestion

**Comment by TeamSpen210** [comment]
A list of the items is at #490.

**Comment by Konclan** [comment]
Alright
