### ISSUE TITLE
some insight into portal 3

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#491]
here are some insights into portal 3 from a friend of mine working on the DEV team of portal 3

- it will have four single player campaigns and a multiplayer campaign.
- the first single player campaign will be with chell outside the facility.
- the three single player campaigns will be with the two robots and a GLaDOS robot
- the multiplayer campaign will be with the two robots or 1 robot and glados
- part of the game will be about what happens after chell left the facility
- the other part with the robots will be about time travel
- the game has many alternate endings
- portal 3 will be harder than the first two with many puzzles near the end that take at least a hour each for a smart person to solve.
- the game will have 150 test chambers in just one of the robot single player campaigns
- of those 150, several will have to be unlocked by making "choices", the game no longer just involves "thinking with portals"
- there will be many new test elements including proper liquid physics and clear water
- GLaDOS is returning along with the announcer and cave johnson and even Wheatley (he will not reveal how Wheatley gets back)
- GLaDOS is no longer the main antagonist
- GLaDOS gets her own robot suit like p-body and atlas and even her own single player campaign
- the game is getting a complex PTI editor with many styles and bottomless pit generation too

**Comment by Konclan** [comment]
Lolwut?

**Comment by LautaroL20** [comment]
Not trolling??? If this is true, then i think I'll run a marathon from Argentina to the USA.

**Comment by LautaroL20** [comment]
If you wanted to test some reactions, then you made it with me.

**Comment by TheReviewers** [comment]
@LautaroL20 If Its True, I Guess We Have To Wait.. But if it is...... @ellingtonvengaboysmuseum Tell me about portal 4 :3

**Comment by Enterpise** [comment]
Oh Dude, please do not make off topic post, this page is only related to the BEE2 Issues ONLY. If you want to post off topic shits like this, go and post it into another place. I dont understand why @TeamSpen210 did not close this shit already.

**Comment by TheReviewers** [comment]
@Enterpise Why do you have to swear alot :(

**Comment by CrashingScience** [comment]
I played portal 3 demo. I got stuck when i accedently went through the fake
door after the main door was blocked by gabe newels weight and after
solving the made up test chamber, had to fight the speculation core.
Unfortunately after that i ended up in the room of annoying things that
people want to be in games but arent, and i cant find an escape.

**Comment by TheDarkBomber** [comment]
There is no way of knowing if this is real or not, until somebody opens the box. Or installs the game.

**Comment by Luke18033** [comment]
@CrashingScience If you really did, then give me the link.

**Comment by CrashingScience** [comment]
> I played portal 3 demo. I got stuck when i accedently went through the fake
door after the main door was blocked by gabe newels weight and after
solving the made up test chamber, had to fight the speculation core.
Unfortunately after that i ended up in the room of community invented items. There were about 50 different test elements that did not work together properly and I just kept dying.<

I didnt actually have portal 3, its a sarcastic joke about the fact that there isnt even any leaked info, and there are so many fake theories which all say different things.

**Comment by Luke18033** [comment]
Lol I can comment here

**Comment by ZombiePwner1** [comment]
What was the point of this issue?

**Comment by LautaroL20** [comment]
@ZombiePwner1 - It was ellington trying to cheat some pepole with a fake "internal Valve source" about a supposed "Portal 3" in development.

**Comment by ZombiePwner1** [comment]
I could tell since portal 3 will never come people just make fake videos.

**Comment by Luke18033** [comment]
I don't think Valve is going to make a sequel to Portal 2. I think they would make a prequel to Portal (like Portal 2 was originally going to be), if anything.
