### ISSUE TITLE
[PRL21.5 Bug] Trigger Once do not trigger Logic gates

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#493]
A trigger once hooked up to a not gate will not deactivate the not gate.

**Comment by Konclan** [comment]
![20160423143252_1](https://cloud.githubusercontent.com/assets/16567080/14763638/dac3b4ba-0960-11e6-8e00-4d2b64b0c32e.jpg)
![20160423143235_1](https://cloud.githubusercontent.com/assets/16567080/14763639/df7f8ef2-0960-11e6-8ed3-bb4070f9224b.jpg)
![20160423143242_1](https://cloud.githubusercontent.com/assets/16567080/14763640/e24995d8-0960-11e6-80a5-9ca6cfb0e431.jpg)

**Comment by Konclan** [comment]
Actually testing more, it seems triggers don't effect any logic gate

**Comment by LautaroL20** [comment]
I will want to test if this is fixed in some minutes.

**Comment by TeamSpen210** [comment]
There is a bug here which I've fixed in my dev builds.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Thanks for saving time!

**Comment by LautaroL20** [comment]
> There is a bug here which I've fixed in my dev builds.

Added fixed label!
