### ISSUE TITLE
New Item, Music Changer

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#497]
So, You Can Choose 3 Music

Example

1. Jiggle Bone
2. 4000 Degrees
3. Subject Name Here
Then You Have An Item

Weighted is 1

Cube is 2 
etc...

Use a trigger to activate  music, to add a dynamic feel, to when you enter a chase scene, or when you are about to go to fire pit ( portal 1 )

**Comment by TheReviewers** [comment]
@TeamSpen210 Please Add It, Its Really Needed

**Comment by Konclan** [comment]
This wouldn't really work because there is a limit to how many selections the item can have, also it doesn't really make sense to have the music change mid chamber.

**Comment by TheReviewers** [comment]
@Konclan Run away scenes, when in bts especially, or fire pit

**Comment by LautaroL20** [comment]
@TeamSpen210 - This idea would really fit very well, but only between the PeTi songs only. Because, alternating through other different songs for example, (Aperture tag with a Peti, or P1 songs) ain't good.

**Comment by TeamSpen210** [comment]
This isn't needed really - for most songs it wouldn't make sense to swap, and for those that do you really need the fine-grained control Hammer gives you - you're not making "chase scenes" in the PeTI, you really need story elements like voice lines and style swaps to make that work.

**Comment by TheReviewers** [comment]
@TeamSpen210 Nu, Its needed for parts like the fire pit

**Comment by BenVlodgi** [comment]
@TheReviewers 
It's a pretty simple instance to make, you should try your hand and making new items

**Comment by TheReviewers** [comment]
@BenVlodgi 
I Should make new items? XD
