### ISSUE TITLE
Bts Gel Crashes Game

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#498]
When activating gel, it crashes the game

**Comment by Konclan** [comment]
Is there a crash report?

**Comment by TheReviewers** [comment]
@Konclan How can i see the console when the game crashes (shuts down)

**Comment by Konclan** [comment]
There is usually a crash report text file generated in the portal 2 folder somewhere

**Comment by LautaroL20** [comment]
Ive already reported this bug long time ago: https://github.com/TeamSpen210/BEE2-items/issues/347

**Comment by TheReviewers** [comment]
@LautaroL20 you said reflection, but it happens on all

**Comment by LautaroL20** [comment]
@TheReviewers - It is not my case, i tested all the gel droppers but it only crashes with "Reflection Gel".

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/347
