### ISSUE TITLE
questions for teamspen related to bottomless pits

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#499]
questions for teamspen related to bottomless pits related to the next release

- [ ] did you implement the code to make sure a support is placed under a pillar, corner, or three sided piece no matter what if supports are used

- [ ] did you fix the camera fall cable bug

- [ ] have you implemented the player teleports and the ability to make a pit deeper?

if so i will be able to release my p1 prototype bottomless pit to you after some bug fixes.

**Comment by TeamSpen210** [comment]
I haven't implemented any of these yet.
