### ISSUE TITLE
question about unlock default items

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#51]
I have a question about the unlock default items function

if you made a custom test chamber exit elevator with all the correct logic and code for PTI, could I pull it into the palette of bee2 and unlock the default items and delete the original exit door in pti and replace it with that new one in the palette and have the map compile properly?

if this works I have a few suggestions for exit elevators to make style transitions. add the following if this works
- some kind of transition from clean to overgrown - and back
- use a observation room with broken glass in either clean or overgrown to make a transition to the BTS style - and back (we may need a overgrown type BTS style too)
- some kind of transition from Clean and/or BTS to underground - and back

**Comment by TeamSpen210** [comment]
This is possible, but I don't think I'll make it. The PeTI doesn't really work too well for story maps (you can't reorder maps in the queue, there's no guarantee you've played earlier maps) so it's better to just do that off-camera. If I was to do it, there's potentially dozens of combinations I'd need to make.
