### ISSUE TITLE
Bugs From Pre Release 20

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#510]
No Test Chamber Can Build
Faith Plate/ Retract Button have same icon

No Rexaura Music

No Customizable Tubes

Pre Release 20 Is A Virus :D XD

**Comment by ellingtonvengaboysmuseum** [comment]
which anti-virus are you using? prob false positive...

**Comment by TheReviewers** [comment]
@ellingtonvengaboysmuseum Does pre-release 20 work for you?

**Comment by Konclan** [comment]
I reported these problems already
BenVlodgi/BEE2.4#302
BenVlodgi/BEE2.4#303
BenVlodgi/BEE2.4#304

**Comment by TeamSpen210** [comment]
The vactubes and music should be fixed now with the pr20.5 packages. For the pedestal button, it does actually have the icons; you might need to uncheck 'preserve resources' in the settings.

**Comment by LautaroL20** [comment]
This is fixed.
