### ISSUE TITLE
Original Clean Style roof bug

### ISSUE THREAD

**Issue by xDadiKx** [TeamSpen210/BEE2-items#512]
![20160502085754_1](https://cloud.githubusercontent.com/assets/13087761/14949733/3233cde0-1044-11e6-8938-56270c83b296.jpg)

I think this only happens in the original clean style and I didn't edit the chamber at all.

**Comment by TeamSpen210** [comment]
That'll be a typo in the configured material name.

**Comment by Konclan** [comment]
Will you release a hotfix for this update or should we just downgrade to 19 in the meantime

**Comment by Enterpise** [comment]
@Konclan This Pre release should be recalled to bug simulator 2016. Personally i will downlgrade to 19 without doubt. This latest release 20 was somewhat premature.
