### ISSUE TITLE
Prl20 Bug: Angled panel does not have "Markered Surface" into the Original Clean Style

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#514]
![20160502055250_1](https://cloud.githubusercontent.com/assets/12244376/14951053/aa63bdc4-102c-11e6-9670-a8d23cdf352f.jpg)

**Comment by TeamSpen210** [comment]
That's on purpose. It's "original" Clean, they don't have market textures on the panels.
