### ISSUE TITLE
[Suggestion] Add lighting to the metall hollows from Clean And Overgrown Angled Panels

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#515]
![20160502060116_1](https://cloud.githubusercontent.com/assets/12244376/14951103/fbf0dc08-102c-11e6-8e1b-a2816b31565a.jpg)

**Comment by TeamSpen210** [comment]
It's still there, turn on `mat_fullbright` to disable lighting. It's just that there's no light under there.

**Comment by LautaroL20** [comment]
Yep indeed, its there but it shouldn't happen anyways. It reminds me the bug of the circular floor  elevator getting black when it flies away.

**Comment by LautaroL20** [comment]
Updated: This only happens when using a static angled pannel (Without connections).

**Comment by LautaroL20** [comment]
I fixed it myself by adding a simple light to the hollow:
![20160916064757_1](https://cloud.githubusercontent.com/assets/12244376/18582464/af8e06c2-7bdb-11e6-8bf3-8e2cb4d642a9.jpg)

In-game results:

![20160916064757_1](https://cloud.githubusercontent.com/assets/12244376/18582457/9b17fa18-7bdb-11e6-9ad7-34052b920f31.jpg)

**Comment by LautaroL20** [comment]
This is not a bug because it probably was intentional to save some entities, its now a suggestion.
