### ISSUE TITLE
Prl20 Bug: Flip Panel is missing its "Black Metal Surface" when its placed on floor, into the Original Clean Style

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#516]
![20160502061952_1](https://cloud.githubusercontent.com/assets/12244376/14951384/ea122198-102e-11e6-92ba-be5d056954bc.jpg)

**Comment by TeamSpen210** [comment]
This is a duplicate of #512.

**Comment by Luke18033** [comment]
@TeamSpen210 This isn't a duplicate really, one is a ceiling and one is a flip panel.

**Comment by TheReviewers** [comment]
@Luke18033 Same texture

**Comment by TeamSpen210** [comment]
It is actually, they both read the same wrong config entry.
