### ISSUE TITLE
Suggestion: Implement a "Curved Vactube"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#519]
When i was testing the recent added Vactubes i noticed something strange, and it was there is missing a "Curved Vactube":

![tube](https://cloud.githubusercontent.com/assets/12244376/14952646/6b674ddc-1038-11e6-88cb-5634df3cea3a.jpg)

**Comment by TeamSpen210** [comment]
Place two, and connect them with antlines so a single bend is needed. A curved tube will then generate.

**Comment by TheReviewers** [comment]
Nice Drawing

**Comment by TheReviewers** [comment]
@LautaroL20 That moment when a suggestion... becomes a question!
