### ISSUE TITLE
Vactubes Show A Error When Published... Even for people who have bee2

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#524]
http://steamcommunity.com/sharedfiles/filedetails/?id=677286760  

:( Please Fix ;-;

**Comment by TheReviewers** [comment]
@TeamSpen210

**Comment by TheReviewers** [comment]
By The Way The Screenshot Is Of An Upcoming Map...

**Comment by LautaroL20** [comment]
This is fixed now.
