### ISSUE TITLE
[Question] Is it possible for a floating Trigger Once/Multiple/Autosave

### ISSUE THREAD

**Issue by xDadiKx** [TeamSpen210/BEE2-items#525]
What I mean is that they could float in the air without any of the supports/blocks. Something like that in the picture.
![20160502160323_1](https://cloud.githubusercontent.com/assets/13087761/14957873/a5caafe0-107f-11e6-9a76-ecdca2b4d6d5.jpg)

**Comment by Konclan** [comment]
Why would you need a floating trigger?

**Comment by xDadiKx** [comment]
Sorry for late reply, it could be useful to trigger things in mid-air.

**Comment by BenVlodgi** [comment]
The PTI doesn't allow this, if you export your map and compile it manually, it will work.

**Comment by xDadiKx** [comment]
Oh man, too bad. :(
