### ISSUE TITLE
New Style Concept (Please Add It)

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#527]
Alright... So Here It Is

Pic 1 : 
![sasa](https://cloud.githubusercontent.com/assets/17834689/14959129/30349ebc-108e-11e6-94a1-1c18b2a9c298.jpg)

Pic 2 : 
![portalgun](https://cloud.githubusercontent.com/assets/17834689/14959136/3b0a72ee-108e-11e6-8b3f-7719dbe665fd.jpg)

Pic 3 : 
![portal 1](https://cloud.githubusercontent.com/assets/17834689/14959153/494fc49e-108e-11e6-9e52-80064661e3e8.jpg)

Signages And Cubes And Catchers  Should Be Used From Pic 2

PGun And Autoportals ( @TeamSpen210  I Know You Have The Model Because ive seen it in the old bee2) From Pic 1 

Antlines And Pellet Emitter From Pic 3

Sorry If Its A Bit Messy

**Comment by BenVlodgi** [comment]
Its just an unpolished version of Portal.
You could create your own version of this style if you have the resources, then publish it for others to use

**Comment by Konclan** [comment]
I love those swirly portals in picture 1, stupid x-box :(

**Comment by Konclan** [comment]
https://www.youtube.com/watch?v=zsdigEaRdLw

**Comment by TheReviewers** [comment]
@BenVlodgi Where are the style creation tutorials

**Comment by TheReviewers** [comment]
@Konclan Xbox isnt stupid.. it cant handle it

**Comment by Konclan** [comment]
Exactly, If they didn't make portal 1 for x-box we would have the beautiful swirly portals

**Comment by Konclan** [comment]
According to valve, modding is as easy as five steps https://developer.valvesoftware.com/wiki/Create_a_portal_2_mod

**Comment by TheReviewers** [comment]
@Konclan Can i have a video tutorial :3

For Styles Specifically

**Comment by Konclan** [comment]
Idk how to do styles, I was just poking fun at the so called valve tutorial on how to make a mod

**Comment by TheReviewers** [comment]
@TeamSpen210 @BenVlodgi Should i close this?

**Comment by TeamSpen210** [comment]
The problem is that I don't actually have the resources for a lot of this - I have the autoportal texture, but the other things aren't in Portal 1 to use. You also can't change things like portal effects very easily.

**Comment by Konclan** [comment]
Actually I'm looking into the swirly portal effect and trying to see if it is possible to implement it into portal 2

**Comment by ZombiePwner1** [comment]
I'd love to see this in bee2
