### ISSUE TITLE
Prl20 Bug: Cube Dropper "Becomes Crazy" when cube is pulverized by a Button connection

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#529]
When a cube is pulverized by any kind of Button connection, its dropper goes "Crazy", and it never stops from keep pulverizing it over and over again:

GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/14961319/584e0290-106f-11e6-8c38-41eb232f8bd8.gif)

**Comment by Konclan** [comment]
So the cube dropper keeps respawning the cube without an input, well release 20 is broken as all hell :(

**Comment by Enterpise** [comment]
LOL, i think you found a bug hehe

**Comment by TheReviewers** [comment]
@Enterpise Whats so funny?

**Comment by Konclan** [comment]
yeah this needs to be fixed immediately

**Comment by Konclan** [comment]
Aha, if you turn Auto-respawn cube off, it works fine

**Comment by TeamSpen210** [comment]
I broke a bit of the dropper logic. For auto-respawning cubes they trigger the dropper whenever dissolved. When pressing the button it also dissolves the already dropped cube, which tells the dropper to 'respawn' the cube again.

**Comment by LautaroL20** [comment]
Fixed.
