### ISSUE TITLE
bts style works but needs improvements

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#53]
the catwalks work perfectly, but the bottomless pit needs improvements, the fall before death needs to be deeper and walls need to look better around the pit.

![preview0060](https://cloud.githubusercontent.com/assets/11165643/8529693/30b50e4e-23ea-11e5-9f07-9dbd4ba2e6db.jpg)

you have a leak

![preview0057](https://cloud.githubusercontent.com/assets/11165643/8529716/5f53418a-23ea-11e5-8005-50591dcbbe65.jpg)

also i want to be able to place bottomless pits on walls and ceilings to make a fully open test chamber!!

**Comment by TeamSpen210** [comment]
You need to choose the Factory skybox to actually have a bottomless pit. That's basically goo. The "leak" is because there isn't a proper BTS "entry elevator", I'm working on that now. It won't be a goo item, but I'll add something to allow you to see skybox in areas other than the floor.

**Comment by ellingtonisland** [comment]
i did select factory skybox, it's bugged

**Comment by ellingtonisland** [comment]
i selected factory skybox, this is still what it looks like!

![preview0082](https://cloud.githubusercontent.com/assets/11165643/8558949/1fe5a168-24d6-11e5-8e3d-cec32d1cc16e.jpg)
