### ISSUE TITLE
add the piston platform logic to vactubes in the editor

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#534]
add the piston platform logic to vac tubes in the editor so we can extend them out from the walls etc.

**Comment by Konclan** [comment]
Perhaps it can generate a support so that it's not just floating in the air

**Comment by TeamSpen210** [comment]
Unfortunately I can't add piston platform options as well as the 'button type' property. It'd also probably end up looking very weird, with long supports. If you use the antline-system to link them, vactubes can run very long distances in mid-air quite well.
