### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by dunkler-schatten** [TeamSpen210/BEE2-items#539]
Thank you all for your hard work on this Portal Mod.
But i miss few items from the old version.

I miss so much:
Bumbleball (Droper)
Bumbleball Floor Button
Punt Cube
Futbol
Cube Cleaner
Breakable Glass
Cube Transmuter

would be interesting:
Catapult Cube
Portal Deflection Cube
Bombe 
Timer
TNT Turret
Caged Turret
Caged Reflection Cube
World Portal Door
Turret Droper
Toggleable Faith Plate
Diagonal Laser/Pellet Emitter
Angled Light Bridge  
Piston Laser Relay
Glass with Hole (round and for Cube)
Retractable Floor Button

is it planned for Bee2.4 ?

By the way.
A possibility in the game (time portal?) For example. could switch ingame between 60s and Overgrown? 
But only an idea
Thanks to read. :-)

![620_screenshots_20160503213538_1](https://cloud.githubusercontent.com/assets/18405990/15008372/25f64d62-11e0-11e6-843a-2e51352b97b4.jpg)

**Comment by LautaroL20** [comment]
It looks like youre new here. TeamSpen210 will port all items from the orignal Addons pack of Bee2.2.5 Alpha to the newer Bee2.4.

 He even maded a post listing all the implemented and to-be implemented items, you can check them here: https://github.com/TeamSpen210/BEE2-items/issues/95

**Comment by dunkler-schatten** [comment]
Oh very thanks for your answer.
And yes i'am new here.
And my English is.... not really good. :-/ 

Cool Have a nice Day.

**Comment by Konclan** [comment]
You can close the issue if you think it is done with the Close Issue button

**Comment by gamerscruffy** [comment]
Remember the uh, animal king item aswell? heh

**Comment by ZombiePwner1** [comment]
The animal King didn't work in the original bee mod.

**Comment by TeamSpen210** [comment]
It's also kind of weird in a test chamber or wherever, it really needs some sort of explanation...

**Comment by Luke18033** [comment]
Explanation: The multiverse!

**Comment by LautaroL20** [comment]
Ah, let me retract about my 2016´s years comment..... And Spencer will efectively port all their  items from his original Addons Pack. I was probably confused with the default Bee2.2.5´s Original items.

**Comment by Endermage77** [comment]
The animal king would make a nice prop for putting on monitors.

**Comment by jb0lt** [comment]
I'm just looking at old issues, and singing turrets as a voice option with monitors displaying the animal king would be amazing
