### ISSUE TITLE
[Missing Audio] There is missing voice file for turrets in clean style.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#540]

**Comment by TeamSpen210** [comment]
What missing audio? How do you get it to play?

**Comment by Luke18033** [comment]
*no response*

**Comment by ZombiePwner1** [comment]
I don't know if this is in prl 21 but this was for prl 20.

**Comment by LautaroL20** [comment]
Well, i guess this is not anymore with the Prl21.
