### ISSUE TITLE
[Bug] Large faithplates have diff model when on and off.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#545]
When the faith plate is disabled it has glass on-top of it:

http://steamcommunity.com/sharedfiles/filedetails/?id=678865484  

When its enabled it doesn't have any glass on-top of it:

http://steamcommunity.com/sharedfiles/filedetails/?id=678865514

**Comment by TeamSpen210** [comment]
I found the fix for this, it's a change in the model qc which fixes the texture sorting. (The glass was sometimes being drawn behind the solid parts, instead of in front.)
