### ISSUE TITLE
Visible nodraw below P1 chamberlocks

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#546]
![20160319104410_1](https://cloud.githubusercontent.com/assets/19228201/15081195/90944dd0-1376-11e6-8fa7-f33e22d89c80.jpg)

In P1 style, in Aperture Tag, there is a nodraw visible below the second door in the ChamberLock item. The screenshot is from Pr19, but it is still there in Pr20. I haven't tested this in P2, but I'm assuming it will happen in both games.

**Comment by Konclan** [comment]
Stop closing it, it will be closed once the update is released
