### ISSUE TITLE
[Suggestion] Music Switcher

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#550]
I want to make an Aperture Tag map using the "Dead Test Subject" music track. Because the music is exactly 50 seconds and doesn't loop, the music would need to start exactly when the neurotoxin timer (#547) starts. In order to do this I would need a music changer. Next to the Music setting in Compile Options, there would be a small button like the Voice Line Chooser. In this menu, you could set 28 tracks to switch between. Track 1 would always be the starting music. If a track was set to Random PeTI, then it would play a random PeTI track every time the music was switched to. Then, in the game, you would use a pedestal button timer to select which music to switch to (Infinity=default music, 30=track 28). When activated, the music will switch to this. There could also be multiple effects you could choose, such as Fade Out and Switch Instantly.

**Comment by TheReviewers** [comment]
@TeamSpen210 I cant believe this teamspen >:( i already suggested it and you didnt liek it

**Comment by TheReviewers** [comment]
@TeamSpen210 :c

**Comment by TeamSpen210** [comment]
The problem with music changing is that it really doesn't make a lot of sense, since you don't have the ability to do things like choreo lines, setpieces or other things to further a story. Without that music swaps doesn't make sense, and would be quite jarring.

**Comment by TheReviewers** [comment]
@TeamSpen210 You added the label -.-

**Comment by Konclan** [comment]
The problem with this is that
1. there is a limit to how many tracks you would be able to choose
2. Custom tracks such as rexaura would need to be packed always or there would need to be some complex workaround (I don't exactly know how BEE2.4 packs custom stuff)

**Comment by TeamSpen210** [comment]
The packing of resouces isn't an issue, I can make it determine which tracks are used and only pack those. I'm not really going to implement this though, due to the above reasons.

**Comment by Luke18033** [comment]
So why couldn't you also add choreo lines?

**Comment by TeamSpen210** [comment]
I don't have any good ideas for a way to make that work properly if you then change the voiceline that's exported. There aren't really any voicelines that match across all the characters.

**Comment by Luke18033** [comment]
How about a music toggle which turns the music on/off? Would that make any more sense?

**Comment by TeamSpen210** [comment]
It would,  although I'm not sure why you'd want that.

**Comment by Luke18033** [comment]
@TeamSpen210 I said it in the original comment, it's for the Ap Tag Dead Test Subject map, but I could probably just open the map with Hammer or create a custom item.

**Comment by Endermage77** [comment]
Would this be viable now with the ICP?
You could simply pick and choose which musics or voicelines you want available and there you go.
