### ISSUE TITLE
Vactube Loop

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#551]
When creating a vactube that loops, the vactube does not generate. If this is intended, can you add it to the description of the vactube?

**Comment by TeamSpen210** [comment]
It's not really intended, but a consequence of the way the code is written. I'm not sure how useful a completely closed vactube is anyway - it'd just be decorative, you couldn't get anything inside it (unless you pre-spawn cubes inside or something.)

**Comment by Konclan** [comment]
Yeah that's what I was doing, placing items in a vertical vent

**Comment by Konclan** [comment]
All I had to do for the solution was place the entrance and exit next to eachother
