### ISSUE TITLE
[Suggestion] Allow linking together seperate cubes and droppers

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#556]
Make Cubes to have a custom initial orientation and automatic respawning system if the cube gets destroyed, by making the cube to accepts inputs and outpusts.

A Cube output will tell the Dropper for a respawn signal when it get destroyed.
A Cube imput will make it fizzle if the cube was also connected to the dropper.

I am making this suggestion because recently i have tried a Steam Wokshop Guide on this, and let me say it worked like a charm without causing minor issues: 

Original guide on how this is supposed to work, here:
https://steamcommunity.com/sharedfiles/filedetails/?id=157595314

![cube](https://cloud.githubusercontent.com/assets/12244376/15094180/0b051656-1473-11e6-92fe-029a8e98829e.jpg)

**Comment by Konclan** [comment]
I don't think this would work, the physics when dropping the cube would be random and wouldn't allow for the orientation to be 100% correct, maybe there can be an item that snaps a cube to an orientation when a cube falls into it

**Comment by TeamSpen210** [comment]
That's what the global cube dropper item system is for. Unfortunately there are some bugs with allowing cubes to accept inputs or outputs, so I might do it a different way - give them both a timer, droppers with the same timer value link together.
