### ISSUE TITLE
BEEMOD Door has no style variants

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#557]
So the doors that u can place are the portal 2 styled doors in-game yet they have the portal 1 model in the editor. With portal 1 style

------
* [X] Old Aperture
* [x] Overgrown
* [x] Portal 1
* [x] BTS

**Comment by Luke18033** [comment]
Wait, how do you do those checkboxes?

**Comment by xDadiKx** [comment]
- [ ]

**Comment by TeamSpen210** [comment]
* [ ] unchecked item
    * [x] checked item

[See here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)
