### ISSUE TITLE
make vactube rides use point_viewcontrol

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#562]
give a option to choose if vactubes can transport players, then 

make vactube rides use path_corner, point_viewcontrol for the camera and a track and teleport the player model to the other end of the tube.

**Comment by TeamSpen210** [comment]
I don't think I'll do this, it overcomplicates the vactubes substantially. I'll want to force crouching or something similar instead.
