### ISSUE TITLE
[Suggestion] BTS BEEMOD Door

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#563]
In BTS style, BEEMOD Doors (and maybe chamberlocks) should have an option so that, when activated, they will only open when a player walks up to them. This could be the "Start Reversed" option in the editor.

**Comment by Konclan** [comment]
Wait what? Can you give a picture of what you mean?

**Comment by Luke18033** [comment]
Nevermind, you can do this with triggers.
