### ISSUE TITLE
[Suggestion] Custom Aperture Tag Paint Fields

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#565]
If possible, Aperture Tag Paint Fields should have an option to choose any gel types instead of just jump and speed. Maybe instead of the enabled/reversed toggle it could have two timers to choose the paint type:
Infinity=no paint for this mouse button.
3=Bounce
4=Speed
5=Reflection
6=Erase
7 or higher=would be used for custom gels if they were added later on.
Conversion gel wouldn't be an option because it would be useless since portals can't be placed by the player (without the console anyway).

**Comment by TeamSpen210** [comment]
A couple problems with this:
* I can't add more than one copy of the timer property to an item.
* The paint gun model shows blue and orange paint inside it, which is completely inaccurate for this (I can't change it properly.)
* Other gel colours really don't have much use when shot from the gun.

**Comment by Luke18033** [comment]
Actually, erase gel would have a use, because you can get rid of paint. Not sure about reflection gel though. Also, I already knew you wouldn't be able to cange the paint gun model, my idea was just o change the paint types that were fired.

**Comment by Luke18033** [comment]
@TeamSpen210 I thought you could have two timers was because I saw a video of the education version and there was two timer-like options on the faith plate so I thought timers worked the same way. I guess not though.

**Comment by TeamSpen210** [comment]
That's specially coded in by Valve for that version.

**Comment by ZombiePwner1** [comment]
If this was possible conversion gel would have a use in coop since p-body has a portal gun.
