### ISSUE TITLE
Portal 1 Exit Frame editor model missing

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#566]
When the P1 exit has no connections or is set to start enabled:
![20160512141227_1](https://cloud.githubusercontent.com/assets/19228201/15230902/e72f3918-184c-11e6-9aa4-dc3a30c06c86.jpg)
When it has a connection:
![20160512141857_1](https://cloud.githubusercontent.com/assets/19228201/15230909/f24a4bb2-184c-11e6-942f-2a7e0b8421ac.jpg)
This did not happen in Pr19, so I'm assuming this has to do with the new editor model?

**Comment by TeamSpen210** [comment]
That would be the model, which I apparently didn't actually include in the files.

**Comment by TheReviewers** [comment]
@TeamSpen210 Guess What! I see it fine, no bugs

**Comment by Luke18033** [comment]
@TheReviewers Do you have the original BEE2 or Pr19?

**Comment by TheReviewers** [comment]
@Luke18033 Both

**Comment by Luke18033** [comment]
The bug doesn't happen in Pr19, that's why. Now that I think about it the original BEE2 didn't change editor models depending on the style, so that wouldn't have made a difference.

**Comment by Luke18033** [comment]
@TheReviewers Btw. I only use Pr20 for finding bugs, I use Pr19 for actual chambers.

**Comment by TeamSpen210** [comment]
Could you click the 'Reset Package Caches' button in the BEE2 options, and re-export?

**Comment by Luke18033** [comment]
Nope, didn't help.

**Comment by LautaroL20** [comment]
This is fixed since a time ago.
