### ISSUE TITLE
Energy Pellets don't fizzle cubes

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#567]
I don't know if you can edit the properties of the high energy pellet or cubes to make this possible, but a lot of energy pellet tests can be broken with cube deflection and some luck. Possibly destroy the energy pellet when it hits the cube as well unless its when its on a cube stabilizer (when you add it)

**Comment by TeamSpen210** [comment]
I'll be adding this feature with a style var in the Rexaura package. Those maps have that exact behavior, it's pretty simple.

**Comment by TeamSpen210** [comment]
Added in 882057362d59f2e96aacf4d9e5cc8b179a2d3527.

**Comment by Luke18033** [comment]
I think @Konclan was suggesting the opposite - make cubes destroy pellets. How about make it a drop-down to choose what happens when a pellet hits a cube: "Do nothing", "Destroy the cube", "Destroy the pellet", and "Destroy both"?
