### ISSUE TITLE
Will later versions of the BEE2.4 not allow certain items on certain styles?

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#568]
In the original BEE2 and the Addons, it was not possible to put certain items on the pallete on certain styles (e.g. no vactubes in 1950s), and they will be removed if you switched from another style (e.g. switching from Clean to Overgrown will remove vactubes from the pallete). I thought this was very annoying, and I was wondering, "Will the BEE2.4 do this in the future?"

**Comment by TeamSpen210** [comment]
No, I specifically coded the BEE2.4 to ensure this isn't the case. It will do something like use Clean style in 1950s if no others are available. You can turn on a setting to make it display in the log all the instances where this currently occurs.
