### ISSUE TITLE
1970s won't compile.

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#570]
Style: 1970s
Music: Random PeTI
Voiceline Pack: Clean Glados
Skybox: Clean
~~Elevator Video:~~
Items in Chamber: Default Items

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 39 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Generating responses data..
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_6"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard06.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual', 'observationgrate', 'obsworldportal']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2085, misses=260, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'fixfizzlerbump': False, 'nomidvoices': False, 'bee_show_trigger': False, 'multiversecave': False, 'unlockdefault': True, 'allowgoomist': True}
[I] cond.core: Global instances: {'instances/BEE2/70s/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Clumping: 256 clumps (+ 0 special)
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/underground_woodwall003c.vmt"
[I] vbsp: "materials/BEE2/world/underground_hotsurface.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Could not open instance file instances/bee2/70s/sphere_sp/no_exit_door.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

A bit of a side fact: I was actually trying to compile this to report another issue that the Conductive Plate editor model or pallete texture doesn't change according to style, but then I ran into this compile error!

**Comment by TeamSpen210** [comment]
Connect something to the exit door, and it'll stop the error. I forgot an instance file.

**Comment by corrupt21** [comment]
This pre-release should have been released on april 1st

**Comment by TheReviewers** [comment]
@corrupt21 not funny... >_<

**Comment by Luke18033** [comment]
Portal 1? This is 1970s!

**Comment by Luke18033** [comment]
@TeamSpen210 Please fix this! 1970s is my favorite Style!

**Comment by Luke18033** [comment]
@TeamSpen210 What file is it? I might be able to copy it from Pr19.

**Comment by TeamSpen210** [comment]
It's not in PR19, I added it in PR20. [Here's the file](https://github.com/TeamSpen210/BEE2-items/raw/master/packages/styles/oldAp/resources/instances/70s/sphere_sp/no_exit_door.vmf).

**Comment by Luke18033** [comment]
Am I supposed to be downloading this? Because there's no download button and "Save as..." in the right-click menu savs it as .txt

**Comment by TeamSpen210** [comment]
VMF files are text, just rename it.

**Comment by LautaroL20** [comment]
This is fixed now.
