### ISSUE TITLE
1960s won't compile.

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#571]
Style: 1960s
Music: Vit Order 2
Voice Pack: 60's Cave
Skybox: Sphere Interior
~~Elevator Video:~~
Items in Chamber: Entrance, Exit, Large Observation Room (default chamber)

Luke18033 unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 44 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"Name" "Peanut Water Blood"
 | 	"Bullseye" "cave_a3_transition01_dummy"
 | 	"Choreo" "npc/cavejohnson/misc_tests25.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Done!
[I] vbsp: Adding Portal Bumpers to fizzlers...
[I] vbsp: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['observationgrate', 'spawn_dual', 'obsworldportal']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2097, misses=259, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'unlockdefault': True, 'fixfizzlerbump': True, 'nomidvoices': False, 'bee_show_trigger': False, 'multiversecave': False, 'allowgoomist': True, 'retro_voice_pre_line': False}
[I] cond.core: Global instances: {'instances/BEE2/50s/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Clumping: 160 clumps (+ 0 special)
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/underground_woodwall003c.vmt"
[I] vbsp: "materials/BEE2/world/underground_hotsurface.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/60s/sphere_sp/entry_corridor_1/no_orangegel.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

Luke18033 unpaused the game
Luke18033 unpaused the game
Luke18033 unpaused the game

**Comment by TeamSpen210** [comment]
This is quite strange, since that instance should be in the packages already.

**Comment by LautaroL20** [comment]
This is fixed now.
