### ISSUE TITLE
More Missing Icons

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#572]
I have found more missing icons! The missing icons are: 60's Small Observation Grate, Locked Pedestal Button and Paint Fizzler (which I reported before).
![20160514105746_1](https://cloud.githubusercontent.com/assets/19228201/15269946/ad091df8-19c3-11e6-8aec-a1a723018499.jpg)
Unfortunately, I can't seem to compile any 60's tests (#571) so I don't know how these look ingame.

**Comment by TheReviewers** [comment]
Locked pedestal button? whats that

**Comment by Luke18033** [comment]
Old aperture retractable button.

**Comment by Luke18033** [comment]
I'm going to merge this with the first missing icons issue.
