### ISSUE TITLE
Old Aperture catwalk stair handrails not connecting

### ISSUE THREAD

**Issue by TeamSpen210** [TeamSpen210/BEE2-items#573]
_From @TheReviewers on May 15, 2016 11:36_

http://steamcommunity.com/sharedfiles/filedetails/?id=684973667

_Copied from original issue: BenVlodgi/BEE2.4#334_

**Comment by TeamSpen210** [comment]
_From @Konclan on May 15, 2016 12:7_

This doesn't seem to be the correct screenshot

**Comment by TeamSpen210** [comment]
_From @TheReviewers on May 15, 2016 12:28_

@Konclan Whoops

**Comment by TeamSpen210** [comment]
_From @Luke18033 on May 15, 2016 17:21_

So...where's the right one?

**Comment by TeamSpen210** [comment]
_From @Luke18033 on May 15, 2016 17:25_

You should post things related to styles at TeamSpen210/BEE2-items.

**Comment by TeamSpen210** [comment]
_From @TheReviewers on May 15, 2016 17:36_

Steam is down for maintenance in my country, cant access store, screenshots, community or anything   :(

**Comment by TeamSpen210** [comment]
_From @Luke18033 on May 15, 2016 17:56_

@TheReviewers I was able to look at your list of screenshots, is it the one of the tiny missing peice of the railing?

**Comment by TeamSpen210** [comment]
_From @TheReviewers on May 15, 2016 18:12_

Yes

**Comment by TeamSpen210** [comment]
_From @Luke18033 on May 15, 2016 18:13_

That just looks like a bug with the model.

**Comment by TeamSpen210** [comment]
_From @xDadiKx on May 15, 2016 18:15_

This is it then.
You can edit the description with the right screenshot, the link is right below my text.
http://steamcommunity.com/sharedfiles/filedetails/?id=684973667

**Comment by TeamSpen210** [comment]
The problem is that the stair models all have an inbuilt end piece, so they don't actually connect to other catwalk models. I'll switch it to a custom model.

This would also affect the other decades.

**Comment by TeamSpen210** [comment]
_From @Luke18033 on May 16, 2016 16:7_

@TeamSpen210 Shouldn't this be on BEE2-items?

**Comment by Luke18033** [comment]
@TeamSpen210 This should be a Valve-bug shouldn't it?

**Comment by TeamSpen210** [comment]
Not exactly, they made all the variants of stairs they actually needed for the maps. Actually I fixed it by changing the catwalk layout slightly, so I could add the 'end' models between the stair and walkway.
