### ISSUE TITLE
[New Item] Player Only Button

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#575]
It would be a square button with a pair of footprints on it. It would be smaller than normal buttons, and would have a "Button Type" property. Weighted would be a normal red button which can be pushed by any player, Cube would be a blue Atlas-only button and Sphere would be an orange P-Body-only button.

**Comment by Konclan** [comment]
Duplicate of #457

**Comment by Luke18033** [comment]
@Konclan Woops, although you didn't mention Atlas- or P-Body-only buttons.

**Comment by Konclan** [comment]
You can add a comment to that issue instead of making a new one

**Comment by Luke18033** [comment]
I didn't know there was another issue on the same thing, I just had this idea for a player-only button, so I created a new issue for it.
