### ISSUE TITLE
When Building a puzzle in co op... everything is shiny?

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#578]
http://steamcommunity.com/sharedfiles/filedetails/?id=683347049

**Comment by TheDarkBomber** [comment]
Doesn't look shiny.

**Comment by Konclan** [comment]
Looks like a missing cube map or something

**Comment by Luke18033** [comment]
I think it's the cube dropper.

**Comment by Konclan** [comment]
no, cube map.. It's a hammer thing

**Comment by BenVlodgi** [comment]
either missing cubemaps or the cubemaps didn't get built

**Comment by TheReviewers** [comment]
It happened only once


just a bug
