### ISSUE TITLE
Cleansing Gel Balls Work Like A Security Camera?

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#579]
When looking at a cleansing gel ball, you can see the other persons view!
http://steamcommunity.com/sharedfiles/filedetails/?id=689268572
http://steamcommunity.com/sharedfiles/filedetails/?id=689268490

**Comment by TheDarkBomber** [comment]
I don't think it is BEE2.4 thing. I think it is Portal 2 thing, since Valve created that item.

**Comment by Konclan** [comment]
It probably has something to do with split screen and the game using the second players view to calculate what the water should distort, shouldn't happen in normal coop

**Comment by TheDarkBomber** [comment]
@Konclan 

But water is VALVE.

**Comment by TeamSpen210** [comment]
Yes, this would be a Valve bug. I doubt I could do anything to fix it. It probably wouldn't happen in  regular coop, which is why they wouldn't have noticed it.

**Comment by TheDarkBomber** [comment]
Change the bug label to valve-bug label.

**Comment by TheReviewers** [comment]
@BenVlodgi The was a valve-bug label... and i never knew about it?

**Comment by BenVlodgi** [comment]
I just saw it on the list, never noticed it before either

**Comment by TheDarkBomber** [comment]
It used to be called "wontfix"
