### ISSUE TITLE
Original Clean won't compile

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#582]
Using recommended settings on Original Clean
Didn't modify the chamber at all.

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 40 (ms)
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: RAND
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Adding Portal Bumpers to fizzlers...
[I] vbsp: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2209, misses=252, maxsize=256, currsize=252)
[I] cond.core: Style Vars: {'fixfizzlerbump': True, 'unlockdefault': True, 'bee_show_trigger': False, 'multiversecave': False, 'nomidvoices': False, 'allowgoomist': False}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_rand.nut"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | material "metal/black_ceiling_metal_001c" not found.
 | Material not found!: metal/black_ceiling_metal_001c
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 474 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (0) (467326 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Compacting texture/material tables...
 | Reduced 2457 texinfos to 429
 | Reduced 45 texdatas to 40 (1291 bytes to 1149)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     (  7956 / 65536 )
 | nummapbrushes:    (  1262 /  8192 )
 | nummapbrushsides: ( 10924 / 65536 )
 | num_map_overlays: (     2 /   512 )
 | nummodels:        (    40 /  1024 )
 | num_entities:     (   282 / 16384 )
 | 
 | 2 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (75250000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 7709B8F0
 | CDynamicFunction: Closing library 'Kernel32.dll' (75250000)
 |_

[I] vbsp: VBSP Done!
[I] vbsp: Retrieved counts: {'entity': ('282', '16384'), 'brush': ('1262', '8192'), 'overlay': ('2', '512')}
[I] BEE2_config: Saving changes in config "C:\Users\Luke18033\Desktop\BEE2.4_pr20_win\config/compile.cfg"!
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3860, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3627, in run_vbsp
  File "C:\Python34\lib\shutil.py", line 229, in copy
  File "C:\Python34\lib\shutil.py", line 109, in copyfile
Permissio

**Comment by TheDarkBomber** [comment]
I've heard about that. I think it is to be fixed for next release. For now, use Clean style.

**Comment by Luke18033** [comment]
@TheDarkBomber That's the thing, I need a picture of Original Clean for the wiki.

**Comment by TheDarkBomber** [comment]
@Luke18033 

Then IDK how to fix it.

**Comment by Luke18033** [comment]
By the way, are you on [Gitter](https://gitter.im/BenVlodgi/BEE2.4) yet?

**Comment by TheDarkBomber** [comment]
@Luke18033 

I didn't know about Gitter.

**Comment by Luke18033** [comment]
@TeamSpen210 Hold on, did I get the entire log? Why does it say "Permissio" at the bottom?

**Comment by TeamSpen210** [comment]
You didn't, but you did get the line describing where the error occurred. You might want to go to your sdk_content folder, uncheck readonly if it's checked, then go in the security tab and grant your username Full Control. (For some reason the compiler was denied permission to copy the BSP file back after the compilation.)

**Comment by Luke18033** [comment]
In Pr21 I have no problems, so this is fixed.
