### ISSUE TITLE
Resizeable World Portal Re-Post

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#583]
So, the last time I tried to post this issue, it turned into an argument about Hammer, so here it is again:

Here are three (3) screenshots to show what I mean:
![20160516113859_1](https://cloud.githubusercontent.com/assets/19228201/15301084/d3804dbe-1b60-11e6-9d8e-ca1c0dab520d.jpg)
I forgot to say in the screenshot that "Start Reversed" will simply put the portal facing outwards instead of inwards. There will be a rotation handle to decide which direction it rotates.
![20160516121548_1](https://cloud.githubusercontent.com/assets/19228201/15301091/d8d81f4e-1b60-11e6-81af-a5c3fdb8ec81.jpg)
In order for this to work, the button would probably have to be connected to both ends of the portal. There would also be a "start enabled" option to make the portal start on.
![20160516114101_1](https://cloud.githubusercontent.com/assets/19228201/15301095/dc4faebc-1b60-11e6-881e-7e14a317f00d.jpg)
If the screenshot above didn't really make it clear, the logic gates won't be part of the editor model either. I'm only using them so that I can have antilines running between the glass.

**Comment by Luke18033** [comment]
From @TeamSpen210:

I could use glass like this. Three problems:

- Worldportals are very processor-intensive, and would likely cause FPS issues if you made them very large.
- If more than 4 portals are visible onscreen, the game's renderer glitches and all kinds of weirdness happens. This basically limits you to 1 portal in Coop, and maybe more in SP. That slot is taken up by the observation room in Old Aperture, so you're very limited. Careful geometry placement can avoid this, but that's not something I expect most users to do.
- Glass isn't just rectangular - wall blocks can be used to split it up, or make other strange shapes. Worldportals need to be rectangular, and wouldn't be placeable in these situations.

**Comment by Luke18033** [comment]
Another problem is the world portal light holes in P1.

**Comment by Luke18033** [comment]
That also explains why you can see through the walls in my Aperture Tag for Portal 1 maps, because they use a lot of worldportal lights. I'm probably going to update them with regular lights once Pr21 is out.

**Comment by Luke18033** [comment]
@TeamSpen210 Fixes:

Don't generate worldportals into the compiled chamber if:

They are too big.
There are too many in one area.
They are split apart by walls.
These requirements could be shown in the right-click menu for the worldportal.

**Comment by TheDarkBomber** [comment]
2 portals of different sizes can connect in Hammer, so, it would work.

**Comment by BenVlodgi** [comment]
Don't need multiple issues for the same thing
