### ISSUE TITLE
More items!

### ISSUE THREAD

**Issue by QuantiX999** [TeamSpen210/BEE2-items#586]
Please, **add tspenAddons** for BEE 2 **into BEE 2.4!**

**Comment by xDadiKx** [comment]
They are.

**Comment by TheDarkBomber** [comment]
That will be done.

**Comment by Luke18033** [comment]
This is already being done #95.

**Comment by Luke18033** [comment]
It looks like your new here. All of the tspenAddons items will eventually be added into the BEE2.4. You should probably close the issue now using the *Close Issue* button down below.
