### ISSUE TITLE
Old Aperture Turrets

### ISSUE THREAD

**Issue by CrashingScience** [TeamSpen210/BEE2-items#588]
Its been mentioned a lot before but I will open it as an issue so it can be listed and monitored.
Valve was lazy using defective turrets in the old aperture, but it kind of made sense because they were actually put there by the workers in suspended animation. In aperure tag and portal stories mel this turret model was used:

![image](https://cloud.githubusercontent.com/assets/16468734/15607915/2a69101a-240e-11e6-837d-277d8d30c1f3.png)

This is much better and lore-friendly. I would like this to be avaliable in the BEE2.4

**Comment by TheReviewers** [comment]
Teamspen contacted lpfreaky about it.

Teampen wont add it because lpfreaky would like it to only be in ap tag/Ps mel

**Comment by TheReviewers** [comment]
:(

**Comment by TheReviewers** [comment]
basically no

**Comment by Luke18033** [comment]
Then why did it say in one of the changelogs that old aperture uses ps:mel turrets since the resources are available?

**Comment by TheReviewers** [comment]
If you use bee2 in ap tag, there will be the old turrets

**Comment by CrashingScience** [comment]
Ok,shame

**Comment by Luke18033** [comment]
So, shouldn't this be closed?
