### ISSUE TITLE
have dual portal gun when blue portal gun is in map

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#59]
have dual portal gun when blue portal gun is in map, this needs to be fixed, whats the use of the single portal gun and auto portals if you have the dual portal gun right off the bat.

![preview0002](https://cloud.githubusercontent.com/assets/11165643/8559323/aab6fece-24d9-11e5-961a-fe82d54091f5.jpg)

**Comment by TeamSpen210** [comment]
In this case, you should get an orange-only gun. I'm going to add the portalgun logic into VBSP itself, instead of doing it via conditions (although I can do it with just those).
