### ISSUE TITLE
[Suggestion] Timed Triggers

### ISSUE THREAD

**Issue by QuantiX999** [TeamSpen210/BEE2-items#590]
What about triggers with timers? For example, in race maps, when you start and touch the trigger, the door will be opened for nine-nine-nine-nine-ni [bzzt]. Oops. Also a visible timer item for the trigger would be cool!

**Comment by TeamSpen210** [comment]
You can use the 'deactivation delayer' for this - connect to a Trigger Multiple, and the output will stay on for the specified time after you leave the trigger.

**Comment by TheReviewers** [comment]
@TeamSpen210 what about a trigger that works like a pedestal button, it can be used multiple times, and is timed

**Comment by Luke18033** [comment]
@TheReviewers That's a trigger multiple.
