### ISSUE TITLE
[Bug] P1 GlaDOS voice lines do not work in portal 1.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#595]

**Comment by TheReviewers** [comment]
P1 Glados has not been added yet :)

**Comment by TheReviewers** [comment]
you can close this now

**Comment by Luke18033** [comment]
Will P1 GLaDOS ever be added?

**Comment by TeamSpen210** [comment]
Currently I don't think so.

**Comment by CrashingScience** [comment]
Ahh, the language barrier. So annoying.

**Comment by Luke18033** [comment]
@TeamSpen210 You can have different versions of P1 GLaDOS in different languages.

**Comment by Enterpise** [comment]
@Luke18033 This has been discussed several times long before you came here....And it is a terrible idea to force the workshop community to listen english, chinese, or german voicelines for people who speaks different languages. This is the big problem of the Portal 1 style.
