### ISSUE TITLE
Bug: the custom fizzler error room

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#6]
the following screenshot speaks for itself

![preview0016](https://cloud.githubusercontent.com/assets/11165643/8022440/98364d06-0c9f-11e5-813f-21a18118985e.jpg)

**Comment by TeamSpen210** [comment]
I must have forgotten to add the custom fizzler model to the package.

**Comment by TheReviewers** [comment]
Ahhhh. Remmember when this was relevant?
