### ISSUE TITLE
[PRL21.5 Bug] Original Clean Style Roof: It isn't using the Original PeTi Texture

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#600]
![20160625021837_1](https://cloud.githubusercontent.com/assets/12244376/16354877/9aebea6e-3a7b-11e6-801b-d26b6c19b3e1.jpg)

**Comment by Luke18033** [comment]
That looks normal...

**Comment by TeamSpen210** [comment]
The original actually uses the floor texture on the ceiling, which is pretty silly.

**Comment by Luke18033** [comment]
@TeamSpen210 Does the BEE2 do the same?

**Comment by LautaroL20** [comment]
@Luke18033 @TeamSpen210 

Ahhh guys, it seems i am the only who knows the appearance from the original PeTi Textures, or someone are needing a pair of glasses (Please do not offence).

Take a look at the following screenshots, i hope this will clean for once all the doubts about how the original PeTi ceilling looks, click any screen to get HD view:

1 - TeamSpen210 comment:

![ghitub comment](https://cloud.githubusercontent.com/assets/12244376/16360721/c04ddddc-3b46-11e6-9eb3-ada28aa69d3a.png)

2 - Names from the textures we are talking about (Taked from Hammer):

![hammer textures](https://cloud.githubusercontent.com/assets/12244376/16360722/067df49a-3b47-11e6-8d39-c13ce251f068.png)

3 - This is the proof that "Bee Prl21.5" isn't using the orignal PeTi ceilling texture by comparing them.

![comparision](https://cloud.githubusercontent.com/assets/12244376/16360727/44ebf77c-3b47-11e6-9dbc-8d9ff104303a.png)

Even with all these proofs, you don't have to believe on me, so, just play some random PeTi workshop maps, so you can check this for yourselves.

**Comment by Luke18033** [comment]
@TeamSpen210 Is there a file we can change to fix this until Pr22?

**Comment by TeamSpen210** [comment]
It's not modification-prevention. The BEE2 checks the modification date on zips to determine whether to re-extract all the resources. Try deleting the cache/ folder, or checking its security settings.

**Comment by LautaroL20** [comment]
Issue was fixed.
