### ISSUE TITLE
[PRL21.5 Bug] 60´s Old Aperture: It plays GlaDos VoiceLines instead of Cave´s ones.

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#601]

**Comment by Luke18033** [comment]
Were Cave's voicelines actually selected in the BEE2?

**Comment by Luke18033** [comment]
@LautaroL20  @ZombiePwner1 I don't think this is a bug, Cave's voicelines probably weren't selected.
