### ISSUE TITLE
[PRL21.5 Bug] Clean and Overgrown Styles: The "Space" Elev Video Animation is bugged

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#602]
Gif:
![gif](https://cloud.githubusercontent.com/assets/12244376/16355209/45ea9870-3a86-11e6-8937-bcdc187ff6d9.gif)

Feel free to call me the Second Great Bee2 bug finder ;)

**Comment by TheDarkBomber** [comment]
Valve Bug?

**Comment by TeamSpen210** [comment]
It's not intended as an elevator video, so probably. I can't really do anything to fix it, since you can't pack videos. It actually looks like a z-fighting issue; elevator videos often end up with sorting bugs.

**Comment by TeamSpen210** [comment]
See issue #40 too.
