### ISSUE TITLE
[Bug] Futbol Spawner/Socket Goes Crazy

### ISSUE THREAD

**Issue by Hyperosious** [TeamSpen210/BEE2-items#603]
![futbolgoingcrazy](https://cloud.githubusercontent.com/assets/6967523/16358476/52d41b80-3b0b-11e6-9e84-ca3c6cbbedc9.gif)

I found this rather hilarious actually. This happend in regular clean style. Not original.

**Comment by xDadiKx** [comment]
Hahaha xD I love this bug.

**Comment by Hyperosious** [comment]
@xDadiKx So do I. It's ridiculous.

**Comment by TheReviewers** [comment]
I feel bad for teamspen ;-;

**Comment by xDadiKx** [comment]
:D

**Comment by TeamSpen210** [comment]
What are the settings on this? How do you trigger it?

**Comment by Hyperosious** [comment]
@TeamSpen210 Default settings for futbol. These settings for the style etc:
![b53ebfaccd33d5191e754981bb21c4b9](https://cloud.githubusercontent.com/assets/6967523/16359456/e397e608-3b2c-11e6-9e1c-5156352a4a33.png)
I was messing around with styles before this so I'll see if changing the skybox does anything.

**Comment by Hyperosious** [comment]
This still occurs even if the skybox is default. I'll test in other styles now.

**Comment by Hyperosious** [comment]
It happens in overgrown too. Here's a screenshot of the futbol settings:
![dafc66ce31c24f8a6a2e40e87c9a6bbd](https://cloud.githubusercontent.com/assets/6967523/16359499/8eb791a4-3b2e-11e6-926c-d276a67f2095.png)
It happens when you have the futbol spawner settings on default.
Here's also a gif of the bug happening in overgrown:
![236df03e8474631cb427f5b71a006ad3](https://cloud.githubusercontent.com/assets/6967523/16359508/0af1328e-3b2f-11e6-95c3-70e402c0f04b.gif)

**Comment by BenVlodgi** [comment]
you can see the two balls spawning and destroying each other

**Comment by Hyperosious** [comment]
I just noticed that now. We've found our problem.
