### ISSUE TITLE
[PR21.5] Publish Error - "couldn't read 1447381339.prt"

### ISSUE THREAD

**Issue by Sarcastic-Fantastic** [TeamSpen210/BEE2-items#604]
Hi, been using this mod for a while and finished my chamber today. I have been building the chamber many times in Pre-Release 18, but when it came to publishing it failed. I downloaded the latest release and package release (Pre-Release 21.5 and package 21) and after some trial and error got the chamber to compile. However I still can't publish it. This is a chamber with clean style, clean skybox, Wheatley voice lines, "TEST" music and "Menu:Space" elevator video. [Here](http://steamcommunity.com/sharedfiles/filedetails/?id=710726910) is an image of the error screen and console. The last few lines in the console say:

 `VVIS Failed`

`Valve Software - vvis.exe (Aug 26 2015)`
`4 threads`
`reading d:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1447381339.bsp`
`reading d:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1447381339.prt`
`LoadPortals: couldn't read d:\program files (x86)\steam\steamapps\common\portal`
`2\sdk_content\maps\1447381339.prt`

I looked at the log file for 1447381339 and compared to other logs it looks fairly different. [Here](http://pastebin.com/FEDeLAgH) is a paste of 1453223855.log (A random numbered log I picked from `D:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps`) and [here](http://pastebin.com/FEDeLAgH) is a paste of 1447381339.log (the log with the same numbering as the .prt file which might be causing issues). Also it might be important but 1447381339.prt doesn't exist, so maybe that's why "it can't read it".

Another area of enquiry was 1447381339.filelist.txt (paste available [here](http://pastebin.com/L35giZML)). It contains crushers and catwalks, and so does my test chamber. I tried removing either crushers or catwalks but it still failed to publish. The other relevant files I haven't mentioned are 1447381339.bsp and 1447381339.vmf.

Finally I looked at preview.log. It contains a lot of the errors in the numbered log but one thing that stuck out to me was `entdata               [variable]      544438/393216   (138.5%) VERY FULL!`. I don't know if this could be the issue, as I did manage to build the chamber many times without any sign or warning of entity limit errors. The chamber is very large so I guess this was to be expected, and it would be a shame to have to cut parts of it out.

Anyway let me know if I can help further in anyway, thank you for taking a look at the issue :).

**Edit:** I made a blank chamber with the same export options as above, placed a catwalk and crusher in it and it got to the stage where I could successfully publish it. So... not sure what the problem could be,.

**Comment by TeamSpen210** [comment]
You'll basically need to give me a copy of your map file (the VMF) to allow figuring out where the issue is. This kine of error is often due to the exact layout of your map and the items in it. Friend me on Steam if you don't want to make the map files public, or talk on Gitter.

**Comment by Sarcastic-Fantastic** [comment]
Alright sure thing, although I can only find p2c and bsp files (which I'm pretty sure are the maps, just not vmf). Is there a specific location I should be looking?

**Comment by TeamSpen210** [comment]
`D:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps`.

**Comment by Sarcastic-Fantastic** [comment]
I'm guessing it's the same number as before. I've friended you on steam and I'll send you a link.
