### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Shooba** [TeamSpen210/BEE2-items#606]
When I download it and put in in portal 2, nothin happends?

**Comment by xDadiKx** [comment]
Can you please explain more?
Also you don't need to put it in your Portal 2 folder

**Comment by CrashingScience** [comment]
You dont put anything in portal 2 folder.Download the main folder. Then put the paclages folder inside this.Now inside the same folder there is a folder called bin. Inside bin is the .exe file. Run this and you will be prompted to navigate to your portal 2 .exe. select this and everything should work.
