### ISSUE TITLE
Overgrown Style: Small Observation is "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#609]
When building a map using Overgrown, the small observation room is from Clean Style:

![20160710193647_1](https://cloud.githubusercontent.com/assets/12244376/16716572/c98073d8-46d6-11e6-9154-2cb67649bc51.jpg)

If this report is a duplicate from any other (altough i did not find any similar), just close it.

**Comment by ZombiePwner1** [comment]
Strange I looked in the VMF and it was styled.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - That means nothing. If the "Info.txt" does not have the exact code to pack the file, it will not work.

**Comment by LautaroL20** [comment]
@TeamSpen210 - I was wodering if i could add the "Fixed Label" to this. Will the small observation going to be styled for next release?

**Comment by ZombiePwner1** [comment]
It will be fixed lautaro why wouldn't TeamSpen fix it?

**Comment by TeamSpen210** [comment]
It's not fixed, so don't add the fixed label.

**Comment by LautaroL20** [comment]
Sorry, it seems that i need to relax a bit. Btw this is the only bug that stops me from releasing one of my Overgrown maps.

**Comment by ZombiePwner1** [comment]
You don't need to use small observation rooms if u don't want to u can try some other sources of lighting.

**Comment by ZombiePwner1** [comment]
You don't need to use small observation rooms if u don't want to u can try some other sources of lighting.

**Comment by LautaroL20** [comment]
Since the latest pre release includes the styled VMF file from this, the only thing left to do is putting a small thingy into the info.txt from the "Overgrown pakage". I was able to fix this myself, and this are the exact code lines it must have:

"Item"
{
"ID" "ITEM_SECONDARY_OBSERVATION_ROOM"
"Version"
{
"Styles"
{
"BEE2_OVERGROWN" "obs_room"
}
}
}

**Comment by LautaroL20** [comment]
Fixed via: 7e45c3a94cee0286ee4d7cf9e0689809bca8bc73
