### ISSUE TITLE
overgrown elevator clip glitch

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#61]
overgrown elevator clip glitch

![preview0004](https://cloud.githubusercontent.com/assets/11165643/8559746/88f7bb52-24de-11e5-86b8-51816d50a9dc.jpg)

**Comment by Konclan** [comment]
How does this bug happen?

**Comment by LautaroL20** [comment]
How to replicate this bug in game? This is probably fixed since some Pre-releases ago.
