### ISSUE TITLE
[Prl21.5 Bug] Overgrown Style: Laser Relay causes "Failure to compile" (Log included)

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#611]
Screenshot from the map that caused the failure:

![20160711152820_1](https://cloud.githubusercontent.com/assets/12244376/16742106/a5be53a6-477c-11e6-9168-190db887f53d.jpg)

_______________________________________________________________________________

Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (9,8,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 155 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr21 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.core: GooDebris: 1/8 locations
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[W] cond.core: "skipCondition" is not a valid condition result!
[W] cond.core: "skipCondition" is not a valid condition result!
[W] cond.core: "skipCondition" is not a valid condition result!
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['gel', 'orangegel', 'geldropper', 'laserrelay', 'cubereflection', 'reflectiongel', 'greygel', 'spawn_dual', 'cubedropperlessreflection', 'goo', 'deadly', 'fizzler', 'laser', 'cube', 'laseremitter', 'bluegel', 'bouncegel', 'lasercatcher', 'speedgel']
[I] cond.core: instanceLocs cache: CacheInfo(hits=18216, misses=307, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'allowgoomist': True, 'unlockdefault': False, 'bee2_goo_debris': True, 'rexcubepelletfizzle': False, 'multiversecave': False, 'fixfizzlerbump': False, 'bee_show_trigger': True, 'nomidvoices': False}
[I] cond.core: Global instances: {'instances/BEE2/logic/reflection_precache.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_oran.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_cube.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_blue.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_ref.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/items/cube/cache_reflect.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/grate_player_clip.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/clean_dropper_grey.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/clean_dropper_grey.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/laser_receptacle_rusty.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/laser_receptacle_rusty.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/reflecto_cube_dirty_bounce.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/reflecto_cube_dirty_speed.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/wall_glass_rusty.vmt"
[I] vbsp: "materials/BEE2/overgrown/broken_indicator.vmt"
[I] vbsp: "materials/BEE2/overgrown/broken_indicator.vtf"
[I] vbsp: "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[I] vbsp: "materials/BEE2/overgrown/broken_indicator_corner.vtf"
[I] vbsp: "materials/paintblob.vmt"
[I] vbsp: "materials/paintblobs/blob_surface_grey.vtf"
[I] vbsp: "materials/paintblobs/blob_surface_purple.vtf"
[I] vbsp: "materials/paintblobs/blob_surface_stick.vmt"
[I] vbsp: "models/BEE2/props_ingame/dropper_grey_clean.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/dropper_grey_clean.mdl"
[I] vbsp: "models/BEE2/props_ingame/dropper_grey_clean.phy"
[I] vbsp: "models/BEE2/props_ingame/dropper_grey_clean.vvd"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dest.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dest.mdl"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dest.phy"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dest.vvd"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.mdl"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.phy"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.vvd"
[I] vbsp: "models/BEE2/props_ingame/reflection_cube_rusty.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/reflection_cube_rusty.mdl"
[I] vbsp: "models/BEE2/props_ingame/reflection_cube_rusty.phy"
[I] vbsp: "models/BEE2/props_ingame/reflection_cube_rusty.vvd"
[I] vbsp: "particles/paint_bomb_fx_reflect.pcf"
[I] vbsp: "particles/paint_splats_fx_reflect.pcf"
[I] vbsp: "scripts/vscripts/BEE2/change_models.nut"
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: "materials/BEE2/overgrown/screens/elevator_video_overlay3.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "E:\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "E:/Steam/steamapps/common/Portal 2/portal2/" "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: E:\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/items/laser/relay_center_com_var2.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

**Comment by LautaroL20** [comment]
Ive done some extra playtests and this happens when you place a "Laser Relay".

**Comment by Luke18033** [comment]
This is a duplicate of BenVlodgi/BEE2.4#364.

**Comment by LautaroL20** [comment]
Alright then.
