### ISSUE TITLE
[Addon] Slow crusher and crusher pads.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#612]
Slow crushers would be a nice feature and the crusher pads would be placeable on the floor walls ceiling to make crushers look nice when they crush on it

**Comment by Luke18033** [comment]
Both of these were in tspen-addons, which are already going to be implemented #95.

**Comment by ZombiePwner1** [comment]
I know but i want these nice items to return

**Comment by Luke18033** [comment]
You could have commented on the original post, saying that you wanted these to be implemented soon.

**Comment by Luke18033** [comment]
Why is this not closed?
