### ISSUE TITLE
[Prl21.5 Bug] Overgrown Style: a "Mysterious Dark Model" appears when Placing a Cube Dropper at the edge of the roof

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#614]
![20160714032718_1](https://cloud.githubusercontent.com/assets/12244376/16830723/f8512ac0-4976-11e6-86de-cdcbb25c4ca5.jpg)

**Comment by TeamSpen210** [comment]
Cube dropper models are normally actually bigger than the 1-block size. The clean dropper has an alternate model for the PeTI which is smaller, but that doesn't exist for the wrecked one. So I added that model to hide the missing geometry around the top of it. I'll change the lighting position.

**Comment by LautaroL20** [comment]
There is also another small problem with this, and it is "Antlines" that are being "Hidden" making the indicators / Symbols impossible to see because the already mentioned Misterious Dark Model.

**Comment by TeamSpen210** [comment]
I need to rescale the dropper model, so the top part isn't needed at all.
