### ISSUE TITLE
Cube Droppers and Auto Portals cause compile failure

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#615]
## Cube dropper log

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 40 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr21 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Using random SP Exit (2)
[I] vbsp: Using random SP Entry (5)
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Generating responses data..
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_4"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard23.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"Name" "We Have Warehouses"
 | 	"OnlyOnce" "1"
 | 	"Choreo_Name" "@voice_cube_dest"
 | 	"Choreo" "scenes/npc/glados/fizzlecube06.vcd"
 | 	"Choreo_Name" "@voice_cube_redrop"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/fizzlecube06.vcd"
 | 		"2" "scenes/npc/glados/fizzlecube03.vcd"
 | 		}
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: End-commands: 
[I] voiceLine: Done!
[I] vbsp: Adding Portal Bumpers to fizzlers...
[I] vbsp: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['cubedropperstandard', 'cubestandard', 'cube', 'spawn_dual', 'cubedropper']
[I] cond.core: instanceLocs cache: CacheInfo(hits=3158, misses=277, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'allowgoomist': False, 'doorcameras': True, 'rexcubepelletfizzle': False, 'nomidvoices': False, 'bee_show_trigger': True, 'unlockdefault': True, 'multiversecave': False, 'fixfizzlerbump': True}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/clean/items/cube/dropper_respawn.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

**Note that "dropper_respawn.vmf" becomes "dropper_no_respawn.vmf" when auto-respawn is disabled.**
## Auto Portal log

Luke18033 unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198067086340\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198067086340\autosave.p2c
Luke18033 unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 39 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr21 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Using random SP Exit (2)
[I] vbsp: Using random SP Entry (5)
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: Generating responses data..
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_4"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard23.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Adding Portal Bumpers to fizzlers...
[I] vbsp: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: N
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['orangeportal', 'autoportal', 'spawn_single', 'orangeportalspawner']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2839, misses=275, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'fixfizzlerbump': True, 'doorcameras': True, 'nomidvoices': False, 'allowgoomist': False, 'rexcubepelletfizzle': False, 'multiversecave': False, 'bee_show_trigger': True, 'unlockdefault': True}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/clean/items/bee/autoportal.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

I don't know whether or not this happens on other styles, I haven't tried it yet.

**Comment by ZombiePwner1** [comment]
Because the instances are missing u need to add the instances

**Comment by Luke18033** [comment]
@ZombiePwner1 I know that, I've used Hammer before...

**Comment by Luke18033** [comment]
The thing is, how do 3 instances which were in Pr20 go missing in Pr21?

**Comment by nockscitney** [comment]
I think it's more than 3 instances.  I exported a map to hammer the other day and was missing Floor Buttons, 1/4 Blocks, segment_panels (something to do with windows), so i think there is more than just the items listed above.

**Comment by Luke18033** [comment]
At this point I think we would be better off using Pr19!

**Comment by TeamSpen210** [comment]
@nockscitney, those instances aren't supposed to exist. They're replaced by the compiker with brushes customised for the position. You want to edit `sdk_content/maps/styled/preview.vmf`, not use `puzzlemaker_export`. These two instances are new, the items used different filenames in PR20.

**Comment by Luke18033** [comment]
@TeamSpen210:
> replaced by the compiker

lol you mean compiler?

**Comment by LautaroL20** [comment]
Cube droppers and Autoportals does not causes failures anymore.
