### ISSUE TITLE
[Bee2.4 Library.zip] The fixed "Library.zip" causes "Areaportal Leaks" on the Entrance, Doors, and DeadlyGoo

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#617]
This only happens on the following Styles: Clean, Original Clean, and Overgrown style.
Here are the screenshots from the Entrance, Doors and Goo, being affected by this bug:

_________________________________________________________________________________________
![20160717202003_1](https://cloud.githubusercontent.com/assets/12244376/16904312/de781546-4c69-11e6-824e-c3b673d8d5bb.jpg)
![20160717202016_1](https://cloud.githubusercontent.com/assets/12244376/16904319/fb213696-4c69-11e6-9582-06918e230023.jpg)
![20160717204701_1](https://cloud.githubusercontent.com/assets/12244376/16904332/2d4011b0-4c6a-11e6-89d9-7478024abca2.jpg)
![20160717201946_1](https://cloud.githubusercontent.com/assets/12244376/16904334/3c0f6be6-4c6a-11e6-98ea-4cfa06b9dde2.jpg)

**Comment by ZombiePwner1** [comment]
Caused from editing a map from bee 2.5.5 in bee2.4

**Comment by LautaroL20** [comment]
Afther studying this leak bug, i have come to the conclusion that this is caused by using a p2c file from the old bee2.2.5 on the new Bee2.4. Since this file have all the old folders references that Bee2.4 does not uses anymore, then the leaks will occur.
