### ISSUE TITLE
[Prl21.5 Bug] Overgrown Style: Button Pedestal is Unstyled

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#618]
![20160717202127_1](https://cloud.githubusercontent.com/assets/12244376/16904339/741c805a-4c6a-11e6-9c2a-77e81aa421c4.jpg)

**Comment by ZombiePwner1** [comment]
That's easy to fix just make it used thru hammer and add some plants to it.

**Comment by Luke18033** [comment]
@LautaroL20 What is that behind the button?

**Comment by TeamSpen210** [comment]
Looks like goo, but bugged due to some leak somewhere.

**Comment by LautaroL20** [comment]
@Luke18033 - Those are areaportal leaks that not only affects goo, but doors, and corridors from the entrance door. You can see the bug report for it, here: https://github.com/TeamSpen210/BEE2-items/issues/617

**Comment by ZombiePwner1** [comment]
It,s from editing a map from bee2.5.5 in bee2.4

**Comment by ZombiePwner1** [comment]
Well seems teamspen fixed it issue can close now.
