### ISSUE TITLE
[Prl21.5 Bug] BTS Style: The "Light Strip PeTi Model" is showing as a "Blue Error"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#619]
![20160717205419_1](https://cloud.githubusercontent.com/assets/12244376/16904356/ae29d31a-4c6a-11e6-8a31-1e3231062af7.jpg)

**Comment by Luke18033** [comment]
Speaking of Blue Errors, for some reason Portal 1 (actual portal 1, not style) displays as a Red Error now, even though for so long I thought it was blue.

**Comment by ZombiePwner1** [comment]
Well portal 1's engine is different compared to portal 2's if I'm correct

**Comment by TeamSpen210** [comment]
The model is `error.mdl`, I don't know why Valve updated it particularly.

**Comment by ZombiePwner1** [comment]
Well your able to fix it aren,t u?

**Comment by TeamSpen210** [comment]
Yes, just commenting on the blue/red difference.

**Comment by Luke18033** [comment]
@TeamSpen210 Where can I access Portal 2's model files in windows explorer? I have tried going to `c:\program files (x86)\steam\steamapps\common\portal 2\update\models` and other folders, but they just don't exist (even tried pasting into address bar, but still nothing).

**Comment by TeamSpen210** [comment]
They're packed into the VPK files in portal2/, portal2_dlc1/, and portal2_dlc2. Open the _dir.vpk file with GCFScape. That's where you find all the resources.

(The reason it's done this way is to speed up game loading. Hard drives are very slow at moving around to read lots of small files, so all the game content is packed into one large file chunk. It also allows updating files without needing to delete old ones.)
