### ISSUE TITLE
[Bug] if u place the paint gun activation field in a certain spot near a fizzler the game crashes.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#628]
I think it happens on a block if placed directly near the edge.

**Comment by TeamSpen210** [comment]
Can you take a screenshot of the exact positioning?

**Comment by ZombiePwner1** [comment]
I can't since the game crashes when it's put on the exact position.

**Comment by ZombiePwner1** [comment]
No matter what the options are u have on it. It will crash your game. I'll get a screenshot.
