### ISSUE TITLE
clean panel type in overgrown

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#63]
clean panel type in overgrown

![preview0006](https://cloud.githubusercontent.com/assets/11165643/8559922/985eda92-24e0-11e5-890c-b830b7dc89c5.jpg)

**Comment by TeamSpen210** [comment]
This isn't actually a bug. It's slightly than the other textures, it's just there to provide more variety. Some parts of overgrown maps aren't damaged completely.
