### ISSUE TITLE
Chasing Laser

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#630]
A laser which follows the player around the map, which could be toggled on and off by inputs. Start Enabled determines whether or not the item starts on, and Start Reversed determines whether or not the laser instant-kills the player. A timer could also be used to determine the speed (Infinite = Very slow, 30 = Always caught up).

**Comment by ZombiePwner1** [comment]
I don't know how well this would go. Something like this was added during the beta stages of portal during the battle between GLaDOS and it didn't go well.

**Comment by Luke18033** [comment]
@ZombiePwner1 I know, I've seen The Unseen History of Portal

**Comment by TeamSpen210** [comment]
What purpose would this serve, othe than being annoying? I can't see you being able to activate relays or catchers with it. Additionally the instant-kill option is very buggy.

**Comment by Luke18033** [comment]
@TeamSpen210 IK it's very buggy, that's why it is only on chasing laser item, not regular laser.

**Comment by Luke18033** [comment]
Just an idea, might make for a cool boss battle though.

**Comment by TeamSpen210** [comment]
That really has nothing to do with a test chamber.
