### ISSUE TITLE
Make observation rooms take up less space behind the wall.

### ISSUE THREAD

**Issue by Luke18033** [TeamSpen210/BEE2-items#631]
A lot of the time I notice that some items (specifically observation rooms and entry/exit doors) take up huge amounts of space behind the wall, even when some of the space is unused in the compiled map.

As seen here, the large observation room takes up a massive 2x4x3 voxel area behind the wall.
![20160727074127_1](https://cloud.githubusercontent.com/assets/19228201/17179485/4e20f550-53ce-11e6-98c6-e54d3a8af00e.jpg)

However, in the compiled map you can easily see that the observation room is no more than 1x2x1 voxels.
![20160727074425_1](https://cloud.githubusercontent.com/assets/19228201/17179589/9e9518e0-53ce-11e6-9edd-bec84496e1a0.jpg)

Also, in Old Aperture, the observation room is just a grating with a world portal, and shouldn't take up any space behind the wall.

**Comment by TeamSpen210** [comment]
Actually, both those items do use all the space. The sides of the embed section get thin walls added to make up floors/walls/ceilings. If the observation room was to be smaller, it would stick into the room and conflict with the room's walls. Additionally, the frame model will conflict with a wall if the sides are made visible.

For the corridors, Clean style might not use the whole space but other styles definitely do. I ensure the embed sections don't change for different styles, so you can switch styles without getting placement errors.
