### ISSUE TITLE
[PRL21.5 Bug] 50´s Old Aperture Large Observation "Becomes Nodraw" when it gets duplicated

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#634]
This happens when you duplicate it with ctlr+c, it seems it gets leaked for no reason into the old aperture: 

![20160729191835_1](https://cloud.githubusercontent.com/assets/12244376/17265010/a0c78914-55c1-11e6-800b-3e845e3ff9a5.jpg)

**Comment by LautaroL20** [comment]
Edited: This happens only when you duplicate the large observation on the old aperture.

**Comment by TeamSpen210** [comment]
This is because they both are trying to connect to the same world portal and are failing. Don't do that, in all styles they won't work that well if duplicated (and the same goes for the entry/exit corridors.

**Comment by LautaroL20** [comment]
When i duplicate the Large Observation on Clean Style, it doesn´t get leaked. So i think it gets leaked only in the Old Aperture.

**Comment by LautaroL20** [comment]
Well, then we will have be satisfied with using only one Large Observation when using Old Apertures then.

**Comment by TeamSpen210** [comment]
It won't leak in Clean, but the `env_projectedtexture`s in the rooms wilk conflict with each other, so only one will activate.

**Comment by ZombiePwner1** [comment]
I did this in 60's style and only the duplicated observation room failed to load the main one was working completely fine.
