### ISSUE TITLE
[PRL21.5 Bug] 80´s Old Aperture: the SP Entrance Door becomes "Nodraw" when closing

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#636]

**Comment by TeamSpen210** [comment]
The timing's off a bit. All the doors have areaportals like this, so the room isn't getting rendered when you can't see it.

**Comment by LautaroL20** [comment]
My own post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/379
