### ISSUE TITLE
[PRL21.5 Bug] BTS Style: Faith Plate "Target" shows as a "white square"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#637]
![20160729201611_1](https://cloud.githubusercontent.com/assets/12244376/17265939/8dc11a8a-55c9-11e6-81bb-3b31a7d5534c.jpg)

**Comment by ZombiePwner1** [comment]
This also happens when you put a large faith on another large faith plate target.

**Comment by LautaroL20** [comment]
Seems that my own post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/346
