### ISSUE TITLE
[PRL21.5 Bug] Old Apertures: The "Broken Enrichment shpere" is not shwing up by default

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#638]
![20160904194736_1](https://cloud.githubusercontent.com/assets/12244376/18234378/705182a0-72d9-11e6-8f6a-45c7ee1e7293.jpg)

**Comment by Luke18033** [comment]
@TeamSpen210 "Stylevar" label was more intended for new stylevars, however, it's actually a good idea to use it for bug reports too.

**Comment by LautaroL20** [comment]
Okay, always thought it was a default thing, now looking between the stylevar properties, there is an option to have this feature but then its still missing decorative things like tubes and other stuff:
![20160904194736_1](https://cloud.githubusercontent.com/assets/12244376/18234378/705182a0-72d9-11e6-8f6a-45c7ee1e7293.jpg)

**Comment by ZombiePwner1** [comment]
why the heck is there a light bridge in the picture?

**Comment by LautaroL20** [comment]
That must be a decorative stuff that TeamSpen added for the stylevar, but its not showing up wich is a bug.

**Comment by TeamSpen210** [comment]
In the spheres stuff shows up depending on what's in the map, those things should show up if you have the relavant items. In this case there's several things in 80's Open style:

* Gel tubes - Blue/Orange/White/Reflection/Water (the one in the screenshot is for Conversion Gel).
* Light Bridge beaming into chamber (the idea is that there'd be mirrors inside to redirect it out of the projectors).
* Laser shot into the building near the entrance.
* Pellets fired into the building near the exit.
* Air-conditioning vents if vactubes are present.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Ah, that makes sense then. For a moment i thought it was a bug that was causing certain things to not shows up. I like your idea.

**Comment by TeamSpen210** [comment]
Which idea?

**Comment by LautaroL20** [comment]
The fact that in the spheres, certain stuff will shows up depending on what items are in the map.

**Comment by TeamSpen210** [comment]
Carl Kenner is the one who originally implemented that. Eventually it'd be good to add similar things to other styles.

**Comment by LautaroL20** [comment]
That sounds good, as for the BTS Style, it would be good to shows up gel tubes on the start window area from the entrance:

![20160904141049_1](https://cloud.githubusercontent.com/assets/12244376/18237146/4b90b1ae-7304-11e6-9438-473bb9954b2e.jpg)

**Comment by ZombiePwner1** [comment]
Those area portal leaks need to be fixed in BTS entry 1
