### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: Sphere Button causes "Failure to compile" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#639]
Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (10,15,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 217 (ms)

VBSP failed.

[I] vbsp: BEE VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] brushLoc: Analysed map, filling air... (107 starting positions..)
[I] brushLoc: Air filled!
[I] cond.core: Checking Conditions...
[I] cond.core: GooDebris: 0/1 locations
[I] cond.catwalks: Starting catwalk generator...
[I] cond.catwalks: Connections: {<srctools.vmf.Entity object at 0x0000000004FFDE48>: [False, False, False, False], <srctools.vmf.Entity object at 0x0000000004FFDD68>: [False, False, False, False], <srctools.vmf.Entity object at 0x0000000004FFDB70>: [False, False, False, False], <srctools.vmf.Entity object at 0x0000000004FFDC88>: [False, False, False, False], <srctools.vmf.Entity object at 0x0000000004FFDBA8>: [False, False, False, False], <srctools.vmf.Entity object at 0x0000000004FFDBE0>: [False, False, False, False]}
[I] cond.catwalks: Markers: {'catw53': <srctools.vmf.Entity object at 0x0000000004FFDE48>, 'catw49': <srctools.vmf.Entity object at 0x0000000004FFDBA8>, 'catw50': <srctools.vmf.Entity object at 0x0000000004FFDBE0>, 'catw51': <srctools.vmf.Entity object at 0x0000000004FFDC88>, 'catw48': <srctools.vmf.Entity object at 0x0000000004FFDB70>, 'catw52': <srctools.vmf.Entity object at 0x0000000004FFDD68>}
[I] cond.catwalks: Finished catwalk generation!
[I] cond.core: Mat: anim_wp/framework/squarebeams, replacement: anim_wp/framework/squarebeams_rusty_01
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[W] cond.core: "skipCondition" is not a valid condition result!
[I] vbsp: Elevator type: RAND
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: Adding quote: "Line_SP"
 |  {
 |  "ID" "ASBESTOS_SPHERE_SP"
 |  "Bullseye" "cave_bomb_flings_entrance"
 |  "Choreo" "npc/cavejohnson/misc_tests08.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Adding quote: "Line"
 |  {
 |  "ID" "HAPPY_FACE"
 |  "Bullseye" "cave_bomb_flings_entrance"
 |  "Choreo" "npc/cavejohnson/misc_tests10.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 |  {
 |  "ID" "CAVE_LOITER"
 |  "Quote_Name" "@cave_catwalks"
 |  "Bullseye" "cave_crazy_box_2nd_chamber"
 |  "Choreo"
 |      {
 |      "1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 |      "2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 |      }
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual', 'goo', 'deadly', 'cubebutton', 'floorbutton', 'cube', 'bouncegel', 'ballbutton', 'buttonacceptscube', 'funnel', 'laserrelay', 'deathfizzler', 'panel', 'paintfizzler', 'glass', 'fizzler', 'geldropper', 'bluegel', 'laser', 'fr_mif', 'cubedroppersphere', 'piston', 'faithplate', 'fr_fdf', 'weightedbutton', 'laseremitter', 'lasercatcher', 'catapult', 'faith', 'cubesphere', 'cubedropper', 'gel', 'buttonacceptsball', 'excursionfunnel', 'laserfield', 'pistonplatform', 'fr_csf']
[I] cond.core: instanceLocs cache: CacheInfo(hits=17375, misses=312, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'retro_voice_pre_line': False, 'multiversecave': False, 'bee_show_trigger': True, 'allowgoomist': True, 'rexcubepelletfizzle': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'bee2_goo_debris': True}
[I] cond.core: Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_blue.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_cube.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/bullseye/bullseye_glow.vtf"
[I] vbsp: "materials/BEE2/bullseye/white_floor_tile_dirty.vmt"
[I] vbsp: "materials/BEE2/bullseye/white_floor_tile_dirty.vtf"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_clean_center.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_clean_left.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_clean_right.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_clean_short.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_center.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_left.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_right.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_fdf_center.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_fdf_left.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_fdf_right.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_mif_center.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_mif_left.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_mif_right.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/compressed_smoke_field.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/force_deflection_field.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/matter_inquisition_field.vmt"
[I] vbsp: "materials/BEE2/fizz/fourthreaper/player_clip_electric.vmt"
[I] vbsp: "materials/BEE2/glass_player_clip.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base_world.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow_world.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_catapult1_world.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_catapult2_world.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_catpult1.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_catpult2.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/black.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/laser_receptacle_rusty.vmt"
[I] vbsp: "materials/BEE2/models/props_ingame/laser_receptacle_rusty.vtf"
[I] vbsp: "materials/BEE2/models/props_ingame/wall_glass_rusty.vmt"
[I] vbsp: "materials/bee2/blend_concrete_dirt.vmt"
[I] vbsp: "models/BEE2/props_ingame/cust_fizz.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/cust_fizz.mdl"
[I] vbsp: "models/BEE2/props_ingame/cust_fizz.phy"
[I] vbsp: "models/BEE2/props_ingame/cust_fizz.vvd"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.dx90.vtx"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.mdl"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.phy"
[I] vbsp: "models/BEE2/props_ingame/lasers/relay_dirty.vvd"
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_rand.nut"
[I] vbsp: "materials/BEE2/overgrown/screens/elevator_video_overlay2.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "E:\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "E:/Steam/steamapps/common/Portal 2/portal2/" "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: E:\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/over/items/button/ball_white_var1.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

**Comment by Luke18033** [comment]
This has been fixed.
