### ISSUE TITLE
wrong type of piston platform in overgrown

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#64]
wrong type of piston platform in overgrown

![preview0007](https://cloud.githubusercontent.com/assets/11165643/8559929/b2de56fe-24e0-11e5-80e9-96637b7eaeb6.jpg)

**Comment by ellingtonisland** [comment]
will be fixed eventually

**Comment by TeamSpen210** [comment]
Don't close issues unless it's actually been fixed, please.
