### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style Death Fizzler Frame have "Purple Light Colur" instead of "Red"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#641]
It should have "Red lights" on its frames instead of "purple light"

![20160729221201_1](https://cloud.githubusercontent.com/assets/12244376/17267229/741931ce-55da-11e6-9906-1d4827c4c88a.jpg)

**Comment by TeamSpen210** [comment]
It's like that because it's emitting both red and blue fields, but I could switch it to red only.

**Comment by Luke18033** [comment]
@TeamSpen210 Maybe make the light change color depending on which is active, and change to purple when both are active.

**Comment by TeamSpen210** [comment]
That's what it was like. I switched it to show red when both are active, blue/red when only one is active, and not change when turned off.

**Comment by LautaroL20** [comment]
Issue was fixed.

**Comment by TeamSpen210** [comment]
I prefer to leave issues open, so people can more easily see known bugs that will be fixed in the next release. With the commit messages, it auto-closes once the change is released.
