### ISSUE TITLE
[PRL21.5 Bug] Laser Emiter and Catcher from Portal 1 Style are missing its "Rusty Plate" inside its socket

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#648]
![20160729215631_1](https://cloud.githubusercontent.com/assets/12244376/17267628/7f37771e-55e4-11e6-9b7a-4c0397346617.jpg)

**Comment by TeamSpen210** [comment]
This is actually intentional, to match things like piston platforms. I might go use custom models though to extend the pipes further down.
