### ISSUE TITLE
[PRL21.5 Bug] Bottomles Pit "kills the player too fast" when he falls in, making it to look "Unreal"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#651]
GIF:
![gif](https://cloud.githubusercontent.com/assets/12244376/17271699/19a88e86-5659-11e6-993f-7b0af75809b3.gif)

**Comment by TeamSpen210** [comment]
This is intentional. The bottomless pit is an illusion - it's not part of the map so you can't pass into it. The nex release will allow making the pit area taller, which will make it more realistic.
