### ISSUE TITLE
[Suggestion] Overgrown Style: Implement option on the Large Observation to have "Permanent Lighting Witouth Shutdowns"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#652]
I know its a part of the overgrown choreo that the obeservation room turns on and off every time, but id preffer to have it static, because it starts to get annoying when it turns off.

**Comment by Luke18033** [comment]
This is a good idea, it gets very annoying with the observation room turning on/off constantly.

**Comment by TeamSpen210** [comment]
I think I'm going to just remove it entirely.

**Comment by ZombiePwner1** [comment]
The sound and lighting could be reduced as well if you want to do that.

**Comment by TeamSpen210** [comment]
Specifically, I'll be making the observation rooms either always on or off, or maybe off but with sunlight streaming in.

**Comment by ZombiePwner1** [comment]
Having sun light come through would be better actually.

**Comment by LautaroL20** [comment]
Seems that my post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/445
