### ISSUE TITLE
[Suggestion] Make the Togleable Faith Plates to using "Yellow Indicators" when it gets "Ennabled" instead of "Cyan colour" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#655]
This will gonna make it much easier to understand when it gets ennabled by any connection, and prevents people to get confused (as me) instead of using the actual "Cyan colour" wich confuses.

![20160802202725_1](https://cloud.githubusercontent.com/assets/12244376/17349198/3dbc0a50-58f2-11e6-81e8-ced482f960e3.jpg)

**Comment by TeamSpen210** [comment]
The problem is that this would then be inconsistent with normal plates, and the one time when they're off in the game it's yellow.

**Comment by LautaroL20** [comment]
It is already inconsistent with the Antlines colour when it gets ennabled, and therefore it could confuse some player´s mind. Personal opinion is that it should give more importance to the Antline´s ennabled colur.

**Comment by Luke18033** [comment]
I agree that this would match up with antlines better, however I also agree that this does not match up with faith plates in the main game. Maybe this should be an option on faith plates (Start Reversed works almost perfectly here)

**Comment by TeamSpen210** [comment]
Perhaps I'll make a different skin for it, so when off it's grey/off. That would eliminate the confusion.

**Comment by LautaroL20** [comment]
That sounds good.

**Comment by TeamSpen210** [comment]
I figured out a better idea for Clean/Overgrown plates - they now just flash between the two colours when off, and stay blue when on.

**Comment by LautaroL20** [comment]
Thats actually a good idea!
