### ISSUE TITLE
[New item] 4 cube dropper.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#658]
A cube dropper that drops 4 cubes as seen in one of the coop chambers with a dropper dropping 4 balls.

**Comment by ZombiePwner1** [comment]
This could be great to use in test chambers that only use 4 cubes and having all 4 coming from one dropper would be better than using different droppers in different locations.

**Comment by TeamSpen210** [comment]
Once I re-add the Global Cube Dropper, you can use that to do this.
