### ISSUE TITLE
Funny art therapy bug.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#665]
![image](https://cloud.githubusercontent.com/assets/18079316/17477567/8d8250d0-5d98-11e6-9e7c-ebdb2e4d6683.png)

Giant metal beam on the left in goo pit.

**Comment by TheDarkBomber** [comment]
You shouldn't really need to report bugs about unfinished styles. The majority of bugs will be fixed once the style is complete.

**Comment by ZombiePwner1** [comment]
Yes i know it's just a funny bug i found while testing art therapy.
