### ISSUE TITLE
[Bug] Bee2.4 does not pack the Aperture Tag songs when building a map

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#666]
Add a separated "Special Package" on the Download page, so poeple who can´t afford the AT Purchase, will have the chance to pack these songs using beemod.

**Comment by TeamSpen210** [comment]
Currently this doesn't actually work. I need to make them copy the sounds from Aperture Tag to the base Portal 2.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Please consider the chance of doing a special "Separated Package" containing the songs from Aperture Tag, in order people that can not afford the purchase of AT will have at least the chance to using these songs when bulding maps with Bee2.4

**Comment by ZombiePwner1** [comment]
If you add aperture tags code to portal 2's gameinfo.txt then the music will play. This is a workaround for now.

**Comment by LautaroL20** [comment]
But that only works if you have purchased Aperture Tag. Me and many other people who can not affor the purchase from AT, or just does not likes it because it is pretty much different from what the Original Portal 2 is, we deserve the chance of having a "Separated Package" on the download page from Bee2.4.

**Comment by ZombiePwner1** [comment]
Well that's fine then since some of the music is quite good.

**Comment by LautaroL20** [comment]
Anyways i think this is another issue that shoul be maded standalone, ive maded it here: https://github.com/BenVlodgi/BEE2.4/issues/382

**Comment by LautaroL20** [comment]
Im thinking on buying AT just for songs, did you added the logic to copy the sounds from AT to the base P2 foldr?

**Comment by TeamSpen210** [comment]
Yes. Additionally it also works for PS:Mel, and disables the packages when the mod isn't found. Just ensure the folder is next to the Portal 2 folder.

**Comment by LautaroL20** [comment]
I have it in my library now. And i will be installing it when PRL23 comes out so i can use AT songs.
![aperture tag](https://cloud.githubusercontent.com/assets/12244376/19226924/7f322930-8e88-11e6-96e3-b1a0b845da16.png)

**Comment by hop193** [comment]
Issue #666, eh?

**Comment by LautaroL20** [comment]
Yep, satan was here....

**Comment by iEnderMan06** [comment]
spookeh
