### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: Laser Field Frames are being packed as a "Red Bug" on published maps.

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#672]
Feel free to call me the Second Great Bee2 Bug Finder :D
_______________________________________________________________________________

Screenshot:
![20160810184331_1](https://cloud.githubusercontent.com/assets/12244376/17572442/f0b76fda-5f2a-11e6-83a1-a567fdebc2c4.jpg)

**Comment by TeamSpen210** [comment]
Specifically that would be because the model is packed, but the textures aren't. I made a fizzler model which lets you tint the emitter light to any colour, but not tint the model itself. That's used to give a dirty laserfield emitter, as well as other item types.

**Comment by ZombiePwner1** [comment]
Lol a red fizzler model. Would be a great touch for laser fields.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - No it wouldn´t.... It looks ugly and people will always see it as a bug.

**Comment by ZombiePwner1** [comment]
Come on  iwas just joking

**Comment by TheDarkBomber** [comment]
The red fizzler model would actually be a good touch for laser fields.

**Comment by ZombiePwner1** [comment]
I already said that.

**Comment by LautaroL20** [comment]
Well, everyone have different tastes, some are good ones and others are terrible. But glad to see this texture bug was fixed.

**Comment by ZombiePwner1** [comment]
Issue is fixed issue closed

**Comment by ZombiePwner1** [comment]
Doesn't matter if they have bee installed or not I got the same error when playing someone's map.

**Comment by LautaroL20** [comment]
Thats pretty strange, i have a 100% clear P2 install and the others with beemod. The one with Bee2.4 installed never shows up this error since it have the missing files. You must be using the one with Bee2.2.5
