### ISSUE TITLE
[PRL21.5 Bug] 50´s, 60´s, 70´s and 80´s Old Apertures: All of them plays "Oh Fliderstricks, Whats now" when getting out from CO-OP Start Spawn

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#679]
This happens only on published maps, and this are the setting ive used to building the co-op maps:

![beemod](https://cloud.githubusercontent.com/assets/12244376/17597804/e64ed44a-5fcd-11e6-8b94-72f6a98b7fc0.png)

**Comment by ZombiePwner1** [comment]
Look in the console and try find what's missing.

**Comment by LautaroL20** [comment]
The full Log is now in the description.

**Comment by ZombiePwner1** [comment]
The missing item variant goes for missing sounds as well and if it plays oh fiddlesticks then it's a missing sound.

**Comment by ZombiePwner1** [comment]
Seems your missing a cavejohnson voice line most likely.

**Comment by TeamSpen210** [comment]
Actually that always appears. What music are you using? That's the problem.

**Comment by LautaroL20** [comment]
It should be noted that this only occurs when playing a "Published Co-op old aperture map". And i always used "Suggested Settings" on all of them, here is a pict of the current configuration:
![beemod](https://cloud.githubusercontent.com/assets/12244376/17597804/e64ed44a-5fcd-11e6-8b94-72f6a98b7fc0.png)
