### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: It plays "Oh Fliderstricks, Whats now" on published CO-OP map (Log Included)

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#681]
SV_StartSound: player/footsteps/metal2.wav not precached (0)
SV_StartSound: player/footsteps/metal3.wav not precached (0)
SV_StartSound: player/footsteps/metal4.wav not precached (0)
(24.23) output: (trigger_once,) -> (@relay_spawn_on_entrance,Trigger)()
(24.23) output: (trigger_once,) -> (@music,FireUser1)()
Removing from action list: (trigger_once,) -> (@music,FireUser1)
(24.23) output: (trigger_once,) -> (@relay_lights_on,Trigger,1.0)()
(24.23) input : @relay_spawn_on_entrance.Trigger()
(24.23) output: (logic_relay,@relay_spawn_on_entrance) -> (@command,Command)(cl_drawhud 0)
(24.23) output: (logic_relay,@relay_spawn_on_entrance) -> (@command,Command,0.0)(cl_drawhud 1)
(24.23) output: (logic_relay,@relay_spawn_on_entrance) -> (@command,Command,0.0)(jpeg)
(24.23) input : @music.FireUser1()
(24.23) output: (ambient_generic,@music) -> (@music,FireUser1,274.0)()
(24.23) output: (ambient_generic,@music) -> (@music,PlaySound)()
(24.23) input : @command.Command(cl_drawhud 0)
(24.23) input @music: @music.PlaySound()
CSoundEmitterSystemBase::GetParametersForSound:  No such sound music.BEE2
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
Can't use cheat cvar cl_drawhud in multiplayer, unless the server has sv_cheats set to 1.
(24.25) input <NULL>: @command.Command(jpeg)
Wrote 'screenshots/mp_coop_Portal1Style0002.jpg':  6.22 MB (1920x1080) compresssed (quality 90) to 205.79 KB
(24.27) input <NULL>: @command.Command(cl_drawhud 1)
Can't use cheat cvar cl_drawhud in multiplayer, unless the server has sv_cheats set to 1.
SV_StartSound: player/footsteps/metal1.wav not precached (0)
SV_StartSound: player/footsteps/metal4.wav not precached (0)
(25.23) input <NULL>: @relay_lights_on.Trigger()
(25.23) output: (logic_relay,@relay_lights_on) -> (orl4-light_observation_room,TurnOn)()
(25.23) output: (logic_relay,@relay_lights_on) -> (orl4-flashlight,TurnOn)()
(25.23) output: (logic_relay,@relay_lights_on) -> (orl4-light_switch_sound,PlaySound)()
(25.23) input @relay_lights_on: orl4-light_observation_room.TurnOn()
(25.23) input @relay_lights_on: orl4-light_observation_room.TurnOn()
(25.23) input @relay_lights_on: orl4-flashlight.TurnOn()
(25.23) input orl4-flashlight: InstanceAuto2-light_exit_area.TurnOff()
(25.23) input @relay_lights_on: orl4-light_switch_sound.PlaySound()
(25.25) input @relay_lights_on: @relay_lights_on.EnableRefire()
SV_StartSound: player/footsteps/metal3.wav not precached (0)
SV_StartSound: player/footsteps/metal2.wav not precached (0)
SV_StartSound: player/footsteps/metal3.wav not precached (0)

**Comment by TheDarkBomber** [comment]
That voice line plays when a sound file is missing and that missing sound file is played.

**Comment by LautaroL20** [comment]
I know that, but the question is wich file is causing this.
