### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: CO-OP Exit Door has a "Blue Error on it" and its frames are "Nodraw" on published maps

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#682]
This happens when you play a published map using Co-op. Screenshot:

![20160811000555_1](https://cloud.githubusercontent.com/assets/12244376/17577803/6ba753a4-5f58-11e6-8a5e-95426c2a42d6.jpg)

**Comment by ZombiePwner1** [comment]
Well seems TeamSpen has alot of stuff to fix in P1 style.

**Comment by TeamSpen210** [comment]
That would be the ported frame model, which needs to be packed. The nodraw is supposed to be there - those surfaces would be covered normally, and so shouldn't be rendered.

**Comment by LautaroL20** [comment]
Issue was fixed.

**Comment by ZombiePwner1** [comment]
Why are u reopening this @TeamSpen210 Issue is fixed when next release comes out.

**Comment by TeamSpen210** [comment]
I want to keep issues open untilthe fix is actually released, that way it's easier to tell when a bug is already known and fixed.

**Comment by ZombiePwner1** [comment]
Alright then.
