### ISSUE TITLE
[PRL21.5 Bug] Portal 1 Style: a "Mysterious Thingy" is next to the "Eye Camera" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#683]
![20160811000619_1](https://cloud.githubusercontent.com/assets/12244376/17577895/49f350ae-5f59-11e6-9ae1-7b95d2b9fba3.jpg)

**Comment by ZombiePwner1** [comment]
Well who knows wtf this is.

**Comment by LautaroL20** [comment]
@ZombiePwner1 Thats the reason why the title says "A misterious Thingy".

**Comment by TeamSpen210** [comment]
Oh, the camera models mustn't be packing. There's a ported copy of the P1 camera which is being used here, and extra `env_sprite` is needed to position it in the correct place (since the original light doesn't appear correctly).
