### ISSUE TITLE
[Enhancement] Add Portal Stories Mel Music in a Separated Standalone Package.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#685]
Add Portal Stories Mel Music on a Separated Standalone Package.

**Comment by LautaroL20** [comment]
Aperture tag music also should be added.

**Comment by ZombiePwner1** [comment]
Aperture tag music already is added.

**Comment by LautaroL20** [comment]
Well, for some reason beemod does not want to pack it on builded maps.

**Comment by ZombiePwner1** [comment]
That's because it's not packed into P2 yet it's only packed for aperture tag.

**Comment by ZombiePwner1** [comment]
https://github.com/TeamSpen210/BEE2-items/issues/666

**Comment by ZombiePwner1** [comment]
I've got the music working because i'm loading aperture tag's music through portal 2's GameInfo.txt

**Comment by SpyyZ158** [comment]
duplicate of https://github.com/BenVlodgi/BEE2.4/issues/292

**Comment by LautaroL20** [comment]
@SpyyZ158 True.
