### ISSUE TITLE
[Bug] Coop BTS exit is "Out Of Control"

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#694]
![20160815180227_1](https://cloud.githubusercontent.com/assets/18079316/17661613/d4c8d264-6312-11e6-93f6-55da502fb46e.jpg)

Same thing happens when connected to a button but more bugged.

![20160815181236_1](https://cloud.githubusercontent.com/assets/18079316/17661821/19860baa-6314-11e6-8775-e30d28bc1aa7.jpg)

**Comment by LautaroL20** [comment]
The co-op BTS Exit is literally out of control if i have to judge that screenshot.

**Comment by ZombiePwner1** [comment]
Lautaro come online

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/341

**Comment by Nikita74Russian** [comment]
omg BTS is so freaking crazy
