### ISSUE TITLE
[PRL21.5 Bug] Chamberlock´s Light Strip and Fizzler placements aren´t "Centered"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#695]
It should be in the "Middle Half". But currently this is how it looks:

![20160815075817_1](https://cloud.githubusercontent.com/assets/12244376/17662733/274795c0-62be-11e6-8830-9b3ec4cc757a.jpg)

**Comment by TeamSpen210** [comment]
How are they misaligned? They aren't centered, yes but they are aligned to the 4x4 grid. (Note that door frames are 3/4 of a 1/4 grid large, so it's a bit odd looking but they are aligned.

**Comment by LautaroL20** [comment]
Ther aren´t missaligned, i think ive used the wrong word in this case. I wanted to say that they re not "Centered", but the fact that they are aligned to the 4x4 grid does make sense too.

**Comment by BenVlodgi** [comment]
Why doesn't the door frame take up the whole 32 units?

**Comment by TeamSpen210** [comment]
It's just how thick P2 doors are. 24 units makes it look nicest - 32 works, but the rims around the doors are really thin and don't stick out much. Valve uses 24 usually.

**Comment by BenVlodgi** [comment]
I've never seen 24 unit walls for doors before.
