### ISSUE TITLE
[PRL21.5 Bug] Chamberlock is missing its "PeTi Model" into the editor from "Original Clean"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#696]
The original clean editor model from Chamberlock is missing:

![20160815191110_1](https://cloud.githubusercontent.com/assets/12244376/17681430/156770ce-631c-11e6-8e4a-1f3525607b24.jpg)

**Comment by ZombiePwner1** [comment]
Have u checked other styles to make sure it isn't missing it's model? Other than art therapy.

**Comment by LautaroL20** [comment]
My own post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/501
