### ISSUE TITLE
[Question] How to prevent "Bottomles Pit" to override "DeadlyGoo" and using both into the same map

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#699]
When i tried to use DeadlyGoo into a simple boxel it got replaced for a "Mini Bottomles pit". Is it possible to use Pit and DeadlyGoo without causing replace each other?

___________________________________________________________________

This was supposed to be a DeadlyGoo but got replaced for a "Mini Pit":

![20160730131141_1](https://cloud.githubusercontent.com/assets/12244376/17694555/c8b4c452-637a-11e6-841c-fae5f12dc4ed.jpg)

**Comment by ZombiePwner1** [comment]
You can't have goo and a pit at the same time only one can be chosen if you have a mini pit just change the skybox.

**Comment by LautaroL20** [comment]
Okay.

**Comment by TeamSpen210** [comment]
Actually, you can have both. It'll work a bit better in the next release, but bascially the bottom-most block in the map is converted to a bottomless pit. Just make the pit deeper, so the goo pit is higher up. (This ensures you don't have a pit above another room or something.
