### ISSUE TITLE
1960s/1950s Themes Fail to Compile

### ISSUE THREAD

**Issue by DrMeepster** [TeamSpen210/BEE2-items#701]
The error only happens when there are buttons in the map.
Error Log:

VBSP failed.

[I] vbsp: BEE2.4.0pr21 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting Coop Exit to 2
[I] vbsp: Game Mode: COOP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: NONE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: Adding quote: "Line_Coop"
 | 	{
 | 	"ID" "CAVE_OWN"
 | 	"Quote_Name" "@cave_pre_enter"
 | 	"Bullseye" "cave_a3_03_lift_shaft"
 | 	"setstylevar" "retro_voice_pre_line"
 | 	"EndCommand"
 | 		{
 | 		"Input" "FireUser1"
 | 		"Target" "@cave_enter"
 | 		"Delay" "0.1"
 | 		"Only_Once" "1"
 | 		}
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_intro03.vcd"
 | 		"2" "npc/cavejohnson/fifties_intro04.vcd"
 | 		}
 | 	}
 |_

[I] voiceLine: End-commands: <Output> OnCompletion -> @cave_enter -> FireUser1 after 0.1 seconds (once only)
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"Name" "Invisible Lasers"
 | 	"Bullseye" "cave_a3_03_dummy"
 | 	"Choreo" "npc/cavejohnson/misc_tests06.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "BOX_STUFF"
 | 	"Bullseye" "@cave_exit_lift"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_complete09.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_complete03.vcd"
 | 		"3" "npc/cavejohnson/fifties_fifth_test_complete08.vcd"
 | 		}
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Done!
[I] cond.core: Map has attributes: ['deadly', 'laser', 'fizzler', 'observationgrate', 'faithplate', 'bouncegel', 'catapult', 'bluegel', 'laserfield', 'faith', 'deathfizzler', 'pedestalbutton', 'obsworldportal']
[I] cond.core: instanceLocs cache: CacheInfo(hits=10594, misses=279, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'allowgoomist': True, 'nomidvoices': False, 'unlockdefault': False, 'rexcubepelletfizzle': False, 'fixfizzlerbump': False, 'retro_voice_pre_line': True, 'bee_show_trigger': False, 'multiversecave': True}
[I] cond.core: Global instances: {'instances/BEE2/50s/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Clumping: 540 clumps (+ 0 special)
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/50s/arrow_blue.vmt"
[I] vbsp: "materials/BEE2/50s/arrow_blue.vtf"
[I] vbsp: "materials/BEE2/50s/indicator_broken_1.vmt"
[I] vbsp: "materials/BEE2/50s/indicator_broken_2.vmt"
[I] vbsp: "materials/BEE2/50s/indicator_norm_1.vmt"
[I] vbsp: "materials/BEE2/50s/indicator_norm_2.vmt"
[I] vbsp: "materials/BEE2/blob_surface_bounce.vmt"
[I] vbsp: "materials/BEE2/bullseye/testchamber_mark.vtf"
[I] vbsp: "materials/BEE2/bullseye/under_metal_wall.vmt"
[I] vbsp: "materials/BEE2/bullseye/under_plywood.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_old_center.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_old_left.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_old_right.vmt"
[I] vbsp: "materials/BEE2/fizz/LP/death_field_old_short.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Could not open instance file instances/bee2/50s/items/button/pedestal_base_inf.vmf
 | 
 |_

[E] vbsp: VBSP failed! (1)

**Comment by ZombiePwner1** [comment]
Well ur missing instancs that's why it's failing.

**Comment by TheDarkBomber** [comment]
It says that the error is that the variable "$envmap" has multiple definitions in the VMT file for metal_underground_wall_metal004_a_bottom. This could be affecting why it could not open the pedestal_base_inf file. It doesn't say it's missing, it says it couldn't be opened.

**Comment by ZombiePwner1** [comment]
Well it's either that or the instance is missing entirely

**Comment by ZombiePwner1** [comment]
No if the instance is missing it will always say Could not open instance file. So the whole instance is missing entirely.

**Comment by TheDarkBomber** [comment]
Actually, "Could not open" means it couldn't load. This could be because that it is dependent on metal_underground_wall_metal004_a_bottom. 50s buttons are embedded.

**Comment by ZombiePwner1** [comment]
well it's either the texture u mentioned or it's a missing instance look thru the folder for it.

**Comment by TeamSpen210** [comment]
That envmap error is Valve's fault, it's always there, and can be ignored... It's probably the button instance, 50s has a slightly different base compared to 70s.

**Comment by DrMeepster** [comment]
I checked my instance folder, and there was no pedestal_base_inf.vmf.

**Comment by ZombiePwner1** [comment]
See i was correct missing instance.

**Comment by TeamSpen210** [comment]
It's not a missing instance actually, it's a bug with a condition running on the wrong item. That's fixed now though.
