### ISSUE TITLE
[PRL21.5 Bug] 80´s Old Aperture: Something "Weird" is happening with the "Death Fizzler Emancipation Textures" for people who do not have Beemod installed

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#706]
![20160819005900_1](https://cloud.githubusercontent.com/assets/12244376/17798662/94aad90e-65a9-11e6-9550-c05612bfc5b0.jpg)

**Comment by ZombiePwner1** [comment]
LOL what on earth is happening here?

**Comment by TeamSpen210** [comment]
It'd be a missing texture for the shader, so it doesn't render right.
