### ISSUE TITLE
more wrong types of items in overgrown

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#71]
* [ ] Funnel

![preview0000](https://cloud.githubusercontent.com/assets/11165643/8560515/87e23302-24e6-11e5-86d5-6940de7c7b25.jpg)

* [x] light bridge

![preview0001](https://cloud.githubusercontent.com/assets/11165643/8560518/8c02f9da-24e6-11e5-9f45-90104181a662.jpg)

* [ ] glass panel

![preview0002](https://cloud.githubusercontent.com/assets/11165643/8560520/9075acb0-24e6-11e5-9409-b7b5b879488c.jpg)

* [ ] Pedestal Button

![preview0004](https://cloud.githubusercontent.com/assets/11165643/8560523/9ba44f6a-24e6-11e5-9792-4ca79f056c25.jpg)

* [x] texture error with laser field

![preview0006](https://cloud.githubusercontent.com/assets/11165643/8560530/a976106a-24e6-11e5-8971-089924bfcec3.jpg)

**Comment by ellingtonisland** [comment]
will be fixed eventually

**Comment by Konclan** [comment]
How will you do overgrown funnels?

**Comment by TeamSpen210** [comment]
I've started reskinning models with a `$detail` texture, which makes tem look like they have dirt/scratches on them. I'll also probably alter the animation to stutter and start/stop sometimes.

**Comment by ZombiePwner1** [comment]
I think all of these are fixed
