### ISSUE TITLE
[PRL22 Bug] Overgrown Style: It plays "Oh Fildersticks Whats Now" if "Future Starter" or "Tech Difficulties" were choosen

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#710]
This only happens when you play the published map. The bug will never occur during playtesting preview mode.

**Comment by LautaroL20** [comment]
This is caused by using specific overgrown traks.

**Comment by LautaroL20** [comment]
"Future Starter" and "Tech Difficulties" both causes this issue. The only way to prevent this to happen is using other style songs.

**Comment by LautaroL20** [comment]
Was it found the cause for this bug? I had to publish my first overgrown chamber without using overgrown song because of this :(

**Comment by LautaroL20** [comment]
Damn, my english is in serious trouble, it is *It was found the cause for this bug*....I guess ill try improving my english next time.

**Comment by LautaroL20** [comment]
Important note about this bug is that only happens when you play the published map. The bug will never occur during playtesting preview mode.

**Comment by TeamSpen210** [comment]
Figured out why this happens - essentially, VRAD was treating published maps as 'Hammer' ones, due to a mixup in the internal logic.

**Comment by LautaroL20** [comment]
Oh, i thought it was something to do with the manifest file. Well, pretty nice to know you have found the real cause for this.

**Comment by TeamSpen210** [comment]
The sound manifest is still generated for Hammer maps if set in the packing list. What isn't generated is the soundscript for music.
