### ISSUE TITLE
[Suggestion] Overgrown Style: Make "Antlines" use more "Dead Sections"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#716]
This is how actually they looks with the PRL21.5, they almost does not uses dead sections:

![20160821004453_1](https://cloud.githubusercontent.com/assets/12244376/17835244/38e5ebb8-6739-11e6-903b-0238889bda52.jpg)

**Comment by TeamSpen210** [comment]
Actually, Overgrown style is set to have the same chance as 1950s style.

**Comment by LautaroL20** [comment]
During my traveling love with Overgrown Style, i noticed that the current death sections chances are well balanced in the bee2.4 compiler, because having more death sections will make them more difficult to see by players when solving "X" puzzle. Case closed.
