### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: The "Piston" of the platform is not using "Solid Collisions"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#717]
![20160821004116_1](https://cloud.githubusercontent.com/assets/12244376/17835245/40318558-6739-11e6-8cd8-26aebd3d1585.jpg)

**Comment by Luke18033** [comment]
Piston models don't have collision in the first place. For my Hammer map I'm working on, I'm using cylinder nodraw brushes, but there might be a better way to do it.

**Comment by TeamSpen210** [comment]
Indeed. In the instances, the collisions come from the `func_movelinears` that do the moving.

**Comment by Luke18033** [comment]
Oh, really? In my map I'm working on I used a func_tracktrain for the platform collision and nodraw func_brushes parented to the func_tracktrain for piston collision. Also, what kind of collision do static pistons use?

**Comment by TeamSpen210** [comment]
Nodraw `func_detail`.
