### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: Floor is using some "Clean Tiles"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#720]
![20160821024837_1](https://cloud.githubusercontent.com/assets/12244376/17835620/8e7592e2-674b-11e6-921e-2fe568054f8f.jpg)

![20160821020215_1](https://cloud.githubusercontent.com/assets/12244376/17835622/b32bc214-674b-11e6-8bb7-a7fc27ac5761.jpg)

**Comment by TeamSpen210** [comment]
This is intentional, but rare. It's supposed to simulate different amounts of destruction and whatnot, with some undamaged areas.

**Comment by LautaroL20** [comment]
*Intentional*
