### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: CO-OP Exit 4 has a light strip "Becoming Nodraw"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#721]
![20160821031604_1](https://cloud.githubusercontent.com/assets/12244376/17835682/d4b28b3c-674d-11e6-81e7-41e0f0e8ef46.jpg)

**Comment by ZombiePwner1** [comment]
Fixed it.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - The "fact" that you fixed it yourself in your own PC/Laptop does not mean that you have to add the "Fixed label". Until i see a "Comit Reference" to the issue showing it got fixed, we can not add the Fixed label.

**Comment by ZombiePwner1** [comment]
I'll get the VMF to @TeamSpen210 once I get home.

**Comment by TeamSpen210** [comment]
What would be good is for you to fork the repro, and just do a pull request. That way you can directly do a commit, and it'll actually show up as you authoring the change.

**Comment by ZombiePwner1** [comment]
K

**Comment by ZombiePwner1** [comment]
Why does it look like the cube apps are missing in the picture?

**Comment by LautaroL20** [comment]
Oh, i think thats because i have played this using a published map. When you load a published BSP file, it always missing cubemaps until you writte into the console "Buildcubemaps".
