### ISSUE TITLE
[PRL21.5 Bug] Overgrown Style: The Coop Spawn´s wall is not well justified

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#724]
![20160821015835_1](https://cloud.githubusercontent.com/assets/12244376/17835850/3bab66e0-6755-11e6-9460-6d5e054088d8.jpg)

**Comment by TeamSpen210** [comment]
It's actually interesting the corridor walls. To fit in the space, they actually need to be rescaled and squished very slightly.

**Comment by ZombiePwner1** [comment]
I've fixed this well kinda.
