### ISSUE TITLE
how do i get a new style listed here?

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#74]
how do i get a new style listed here?

![new bitmap image](https://cloud.githubusercontent.com/assets/11165643/8561616/2077c47e-24f6-11e5-9d87-cc7e55b1117f.jpg)

**Comment by TeamSpen210** [comment]
You'll need to make a new package, with a style block in the info.txt file. Extract the contents of the overgrown package into a folder (name doesn't matter). Delete all the files except for the styles/ folder, and the info.txt file. In the info.txt file, delete everything except for the Style section and the name/ID fields at the beginning. Then go change all the values as you please. A style requires a folder inside styles/, with an items.txt and vbsp_config.cfg file (copy out of an existing style). Icons should be a 96x96 png file in resources/bee2/styles/ in your package subfolder.

**Comment by ellingtonisland** [comment]
i did all that, it's not showing up

**Comment by ellingtonisland** [comment]
here's the info.txt from my custom style, what's wrong with it

<code>
"ID"		"BEE2_SOTA"
"Name"		"Sota Style"

"Style"
	{
	"ID"			"BEE2_SOTA"
	"Authors"		"EllingtonIsland"
	"Folder"		"sota"
	"Icon"			"styles/sota.png"
	"Name"			"State of the Art"
	"ShortName"		"S.O.T.A"
	"Base"			""
	"Has_Video"		"0"
	"Description"
		{
			"Line"		"State of the Art Clean style. Created by glados for new tests, features darker black walls, smooth white walls."
			"Line"		"Also features elevators with glass replacing video screens showing the BTS area's of the facility."
		}
	"Suggested"
		{
		"Quote"		"BEE2_GLADOS_CLEAN"
		"Music"		"VALVE_PETI"
		"Skybox"	"VALVE_BLACK"
		"Goo"		"GOO_NORM"
		}
	}

"QuotePack"
	{
	"ID"			"BEE2_GLADOS_CLEAN"
	"File"			"sota"
	"Name"			"GLaDOS (Clean)"
	"ShortName"		"GLaDOS"
	"Group"			"GLaDOS"
	"Icon"			"voices/glados.png"
	"Authors"		"Carl Kenner, TeamSpen210"
	"Description"	"GLaDOS narrating test subject's trips through fully-modern and pristine test environments."
	}

"StyleVar"
	{
	"ID"		"DoorCameras"
	"Enabled"	"1"
	"Name"		"Door Cameras"
	"Style"		"BEE2_sota"
	}
	
"Item"
	{
	"ID" "ITEM_OBSERVATION_ROOM"
	"NeedsUnlock"	"1"
	"Version"
		{
		"Styles"
			{
			"BEE2_sota"	"obs_room"
			}
		}
	}
	
"Item"
	{
	"ID" "ITEM_ENTRY_DOOR"
	"NeedsUnlock"	"1"
	"Version"
		{
		"Styles"
			{
			"BEE2_sota"	"entry_door"
			}
		}
	}
	
"Item"
	{
	"ID" "ITEM_EXIT_DOOR"
	"NeedsUnlock"	"1"
	"Version"
		{
		"Styles"
			{
			"BEE2_sota"	"exit_door"
			}
		}
	}
	
"Item"
	{
	"ID" "ITEM_COOP_ENTRY_DOOR"
	"NeedsUnlock"	"1"
	"Version"
		{
		"Styles"
			{
			"BEE2_sota"	"coop_spawn"
			}
		}
	}
	
"Item"
	{
	"ID" "ITEM_COOP_EXIT_DOOR"
	"NeedsUnlock"	"1"
	"Version"
		{
		"Styles"
			{
			"BEE2_sota"	"coop_exit"
			}
		}
	}
	
"SkyBox"
	{
	"ID"			"VALVE_BLACK"
	"Name"			"Darkness"
	"Group"			"2D"
	"Icon"			"BEE2/black_96.png"
	"Material"		"sky_black"
	"Config"		""
	"Authors"		"Valve"
	"Description"	"Pure black darkness. Nothing to see here."
	}

"Music"
	{
	"ID"			"VALVE_PETI"
	"Name"			"Random PeTI (Robot Waiting Room)"
	"ShortName"		"Random PeTI"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/peti.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"The original PeTI music."
		"Line"	"Randomly chooses between Robot Waiting Room 1-5 and '7'."
		}
	"Soundscript"	"music.pti_b1_001"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_1"
	"Name"			"Robot Waiting Room 1"
	"ShortName"		"Robo Room 1"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		"Line"	"This track is similar to the 1950s music tracks."
		}
	"Soundscript"	"music.ctc_b1_001"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_2"
	"Name"			"Robot Waiting Room 2"
	"ShortName"		"Robo Room 2"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		}
	"Soundscript"	"music.ctc_b1_002"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_3"
	"Name"			"Robot Waiting Room 3"
	"ShortName"		"Robo Room 3"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		}
	"Soundscript"	"music.ctc_b1_003"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_4"
	"Name"			"Robot Waiting Room 4"
	"ShortName"		"Robo Room 4"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		"Line"	"This track is similar to the 1950s music tracks."
		}
	"Soundscript"	"music.ctc_b1_004"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_5"
	"Name"			"Robot Waiting Room 5"
	"ShortName"		"Robo Room 5"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		"Line"	"This track is similar to the 1950s music tracks."
		}
	"Soundscript"	"music.ctc_b1_005"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_6"
	"Name"			"Robot Waiting Room 6"
	"ShortName"		"Robo Room 6"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in the Cooperative Testing Hub, and PeTI levels."
		"Line"	"This track is similar to some of the BTS tunes."
		}
	"Soundscript"	"music.mp_coop_lobby_2_c7"
	}

"Music"
	{
	"ID"			"VALVE_ROBO_ROOM_PTI"
	"Name"			"Robot Waiting Room '7'"
	"ShortName"		"Robo Room '7'"
	"Group"			"PeTI / Robo Room"
	"Icon"			"music/robo_room.png"
	"Authors"		"Valve"
	"Description"
		{
		"Line"	"One of several tracks played in PeTI levels."
		"Line"	"This track does not appear in the original game soundtrack."
		"Line"	"It features horns and xylophone-like instruments."
		}
	"Soundscript"	"music.ctc_b1_006"
	}
</code>

**Comment by TeamSpen210** [comment]
You'll want to delete everything after the "style" block, since otherwise the BEE2 will stop (you can't have two things with the same ID). Surround the "Item" values in an "Override" block, that will tell the BEE2 to add those style versions to the items. You'll need to copy the items/ subfolder out of clean_style too for items.

**Comment by ellingtonisland** [comment]
this is new code, it's still not showing!!

<code>

"ID"		"BEE2_sota"
"Name"		"Sota Style"

"Style"
	{
	"ID"			"BEE2_sota"
	"Authors"		"EllingtonIsland"
	"Folder"		"clean"
	"Icon"			"styles/sota.png"
	"Name"			"State of the Art"
	"ShortName"		"S.O.T.A"
	"Base"			"clean"
	"Has_Video"		"0"
	"Description"
		{
			"Line"		"State of the Art Clean style. Created by glados for new tests, features darker black walls, smooth white walls."
			"Line"		"Also features elevators with glass replacing video screens showing the BTS area's of the facility."
		}
	"Suggested"
		{
		"Quote"		"BEE2_GLADOS_CLEAN"
		"Music"		"VALVE_PETI"
		"Skybox"	"VALVE_BLACK"
		"Goo"		"GOO_NORM"
		}
	}

"Overrides"
	{	
	"Item"
		{
		"ID" "ITEM_OBSERVATION_ROOM"
		"NeedsUnlock"	"1"
		"Version"
			{
			"Styles"
				{
				"BEE2_clean"	"obs_room"
				}
			}
		}
	
	"Item"
		{
		"ID" "ITEM_ENTRY_DOOR"
		"NeedsUnlock"	"1"
		"Version"
			{
			"Styles"
				{
				"BEE2_clean"	"entry_door"
				}
			}
		}
	
	"Item"
		{
		"ID" "ITEM_EXIT_DOOR"
		"NeedsUnlock"	"1"
		"Version"
			{
			"Styles"
				{
				"BEE2_clean"	"exit_door"
				}
			}
		}
	
	"Item"
		{
		"ID" "ITEM_COOP_ENTRY_DOOR"
		"NeedsUnlock"	"1"
		"Version"
			{
			"Styles"
				{
				"BEE2_clean"	"coop_spawn"
				}
			}
		}
	
	"Item"
		{
		"ID" "ITEM_COOP_EXIT_DOOR"
		"NeedsUnlock"	"1"
		"Version"
			{
			"Styles"
				{
				"BEE2_clean"	"coop_exit"
				}
			}
		}
	}
</code>

**Comment by TeamSpen210** [comment]
Where is the info.txt file? It should be along the lines of `BEE2/packages/ell_sota/info.txt`. (To [add code](https://guides.github.com/features/mastering-markdown/) on github, use  \`\`\` before and after the code, instead of \<code\> tags).

**Comment by ellingtonisland** [comment]
what are you using to ".zip" these package files, i tested it with extracting the overgrown style zip and recompressing it with the windows build in at to zip and the recompressed version didn't show up under bee2.

**Comment by ellingtonisland** [comment]
see issue with zip files...
