### ISSUE TITLE
[PRL21.5 Bug] 60´s Old Aperture: A "Mysterious Portal Gun" is on the SP Entrance Door´s Floor 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#748]
![20160829151346_1](https://cloud.githubusercontent.com/assets/12244376/18062292/98df306e-6dfc-11e6-82a4-118e15b95693.jpg)

**Comment by ZombiePwner1** [comment]
If you put auto portals in the map and pick up that portal gun it's a orange only gun.

**Comment by TeamSpen210** [comment]
Indeed, it's an unused leftover from the BEE2.2.5.
