### ISSUE TITLE
issue with bee2 package zip files

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#75]
what are you using to ".zip" the package files, the reason my style isn't showing up i think is something to do with the compression. i tested it by extracting the overgrown style zip and then recompressing it with the windows build in add to compressed zip folder in windows 8.1 and the recompressed overgrown style didn't show up under bee2 styles list.

**Comment by TeamSpen210** [comment]
I actually use a python script to zip all the packages. Try zipping it with 7-zip, setting the compression type to "deflate". You can also leave it as an uncompressed folder, the BEE2 will read those fine.

**Comment by ellingtonisland** [comment]
you will have to release that python zipping script as a exe in the next release and test it before you release it, nothing but your original script you used is working when i try to rezip the overgrown style to test the problem, i think this is why my new style wasn't showing up. doesn't work at all with 7zip or windows zip utility.

**Comment by TeamSpen210** [comment]
How are you zipping your files? The info.txt file needs to be in the root of the zip file (not in a subfolder). For 7-zip, you want to select the info.txt file, the styles/ folder, (any others) and right-click > 7-zip > save as zip.

**Comment by ellingtonisland** [comment]
ok, that fixed it!!

**Comment by titchdownunder** [comment]
Bee2 packages 4.32.0 is this the same as 4.32.3 as splash screen does not change when i installed new packages
