### ISSUE TITLE
[PRL21.5 Bug] 50's Old Aperture: Death field is using wrong side textures

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#751]
![20160830192256_1](https://cloud.githubusercontent.com/assets/18079316/18087505/26446398-6ee8-11e6-9ffe-562fc9b0c6c5.jpg)

**Comment by TeamSpen210** [comment]
This might be fixed - I found that the side textures were reusing the Clean settings instead of Old Aperture ones.

**Comment by LautaroL20** [comment]
If it was using clean settings, then it means that this is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/706
