### ISSUE TITLE
introducing State of the Art style

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#76]
i have created new style i call State of the Art. where can i send you the zip file of it since it won't let me here. this zip file needs to be decompressed into a folder to work with bee2. i need you to fix some stuff in this style.

here is a description and some photo's.

this style prominently features darker black wall panels. you can see the difference in these two photo's here.
![preview0011](https://cloud.githubusercontent.com/assets/11165643/8584858/3ee64080-25a9-11e5-898a-15b2acd02075.jpg)

![preview0009](https://cloud.githubusercontent.com/assets/11165643/8584842/08697b3a-25a9-11e5-80b4-958b28156b02.jpg)

glados just finished building these tests, they feature large square black and white panels since they were built new from scratch and not like reconstructing with variants of panels. 

![preview0010](https://cloud.githubusercontent.com/assets/11165643/8584867/502798ee-25a9-11e5-8712-71d9281c07fd.jpg)

you can see the laser field texture matches.

![preview0012](https://cloud.githubusercontent.com/assets/11165643/8584871/5600e5ae-25a9-11e5-88f4-bf40702662af.jpg)

features of this style and what it needs to be

- suggested music = TEST
- suggested narrator = Glados
- elevators of this style have video screens and ceiling removed and glass walls in them replace the video screens allowing you to see through to the BTS of facility and test chamber from outside, a catwalk over a bottomless pit leads into the test chamber (i need you to build these elevators)
- features bottomless pit and wall holes to bottomless pit, but unlike clean or wheatly pit, this one looks well built and proffessional and is outlined by a warning texture that is at the top 1/8th first PTI voxel of the pit below is a few panel frames around edge of pit or hole in wall.
- the 3D skybox for this style should have many variants and also show test chambers that match this style and everything in it here should look very professionally built.
- uses darker black walls which are square, and also uses mainly square white walls. 
- features less panel variations due to glados just finishing constructing these tests
- observation room should be a array of those lights seen in underground shining into test chamber with big hole in wall with warning texture around edge of hole. (make lights white)

i need you to do work on this style and do things to it such as correct the black texture on most items like the funnel and change it to the darker variant and build the elevators i just described for this style. correct the missing item assets in it and include the version of this style i just made in your next release of bee2 once you tell me where to send the zip.

**Comment by awesomedoctorx3** [comment]
why was this ever scrapped? I like it.

**Comment by BETTEREXTENEDEDITORMOD** [comment]
i think because it's a copy of #1977
