### ISSUE TITLE
help needed with state of the art style

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#77]
i need some help with the state of the art style, specifically what to put in the info file for

- the suggested music to be "TEST"
- the suggested narrator to be "Glados"
- the suggested skybox to be "black"

have all this work without creating duplicates in the selection menu's

**Comment by TeamSpen210** [comment]
You need to add a Suggested block, with the IDs of those things. TEST is defined in extras/music, and the others are defined in the clean_style package.
