### ISSUE TITLE
[PRL21.5 Bug / Crash] Bee2.4 is not leaving Hammer to get started

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#771]
Recently i installed Authoring tools for bee2.4 (I had it long time only on the Bee2.2.5 P2 Build), and this is what happens when i try to launch it:

GIF:

![gif](https://cloud.githubusercontent.com/assets/12244376/18233180/36d71544-72b6-11e6-8857-4b30d118c22d.gif)

**Comment by LautaroL20** [comment]
Damn, this is happening because "STEAM" seems to have deleted almost the entirely folders from the Portal 2 folder when i uninstalled authoring tools to re-install it again. Valve seriously needs to fix A LOT OF THINGS!

But im glad to say i have backups from the original P2 folders, so take that, valve >:D

**Comment by TheDarkBomber** [comment]
Here's a tip: Extract the PeTi map by using sdk_content/maps/styled/preview.vmf. Puzzlemaker Export doesn't work with BEE2.4.

**Comment by LautaroL20** [comment]
Ehmmm wut? I  wasn´t trying to export / editing any PeTi map. I just wanted to install P2 Authoring Tools in one of my Portal 2 folders, and during the procces of uninstall-install, Steam deleted many folders from the game. Thats what happened, Valve should really take care about these things....

**Comment by TheDarkBomber** [comment]
You said you installed it for BEE2.4.

**Comment by LautaroL20** [comment]
@TheDarkBomber - I mean the P2 Folder wich i have associated with Bee2.4. I edited the post to have it more understable.

**Comment by TheDarkBomber** [comment]
That would be the same Portal 2 folder as usual.

**Comment by LautaroL20** [comment]
No, i don´t think its good to having the same Portal 2 folder for different versions of Beemod. Thats why i have two P2 Installs on differents places.

**Comment by TheDarkBomber** [comment]
No. You're supposed to use the same folder.
