### ISSUE TITLE
Player Start and End Points

### ISSUE THREAD

**Issue by Byzarru** [TeamSpen210/BEE2-items#780]
I would like to suggest "Player 1 Start," "Player 2 Start," and "Player End" items for the mod. These items would be alternative to the doors and would allow for custom level entries for test chambers that do not use the entry/exit doors.

Player 1 Start would appear in the editor as a green model of Gordon Freeman, like in Hammer. The model would then be able to be rotated 360 degrees (like turrets). Player 1 will spawn in the voxel, facing the proper direction, when the map is loaded.

Player 2 Start would appear as an orange model of Gordon Freeman, to match P-Body's color. Ideally, Player 2 would spawn in the same way. (Is it even possible to make two different spawn points?)

Player End would appear as a red sphere with a white "X" in the middle. The map ends when the player enters the voxel Player End occupies. Player End could also be activated and deactivated, but would default to "start enabled".

**Comment by TeamSpen210** [comment]
Something similar has been suggested before. I don't think this is a good idea though - it looks really unprofessional when you spawn in the middle of nowhere, or the level randomly ends at a location.
