### ISSUE TITLE
[Bug] Camera item isn't disabled like normal door cameras

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#785]
![20160910160545_1](https://cloud.githubusercontent.com/assets/18079316/18409017/89876022-7771-11e6-8877-26d599d5b0b5.jpg)

**Comment by TeamSpen210** [comment]
Yes, that's intentional. It's always pointing at a specific target, and if you have a screen the video will show up there.

**Comment by Luke18033** [comment]
If you want the camera to be facing down, place the target on the floor right below it.

**Comment by TheDarkBomber** [comment]
@Luke18033 I don't think a "works as intended" label is necessary.  I think this issue should be invalid.

**Comment by TeamSpen210** [comment]
It's kinda both...

**Comment by TheDarkBomber** [comment]
I think "works as intended" should be renamed to "intentional"

**Comment by LautaroL20** [comment]
@TheDarkBomber - Done!

**Comment by Luke18033** [comment]
@TheDarkBomber Yes, that is a good idea.
