### ISSUE TITLE
Is it possible to make "Open broken ceillings" with BEE2.4?

### ISSUE THREAD

**Issue by Kenkenkon** [TeamSpen210/BEE2-items#786]
I've played a test chamber made by my friend and I saw this:
![screen shot 2016-09-07 at 9 04 28 pm](https://cloud.githubusercontent.com/assets/21965054/18410630/026a00f0-773e-11e6-9f62-fadbc47f7617.png)

Is it possible to do in BEE2 without use of authoring tools?

**Comment by TheDarkBomber** [comment]
No.

**Comment by LautaroL20** [comment]
@Kenkenkon - What style is that?

**Comment by LautaroL20** [comment]
Something similar was almost to be implemented with the PRL22, but unfortunately TeamSpen210 decided to not included it yet :(

**Comment by Kenkenkon** [comment]
I dont know the style, but it seems to be clean, but not like BEE2, a more "clean" style than the BEE2 clean.
