### ISSUE TITLE
help needed with custom music

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#79]
i need some help creating a test chamber with custom music. here's what i need to do.

- convert the music file i am going to use to proper format (what i need to do it and stuff)
- add the custom song to the list of songs in bee2.
- have it play in the test chamber
- have packrat compile the song into a map so others will have the files needed for it.
- this is what the custom audio is - (https://www.youtube.com/watch?v=n7cAyZ8jXfs&noredirect=1)
(glados will play this to troll players)

**Comment by TeamSpen210** [comment]
All sounds need to be a WAV file. For the specifics, google how to add a looping sound to a Source game. To add music to the BEE2, you just need a definition in an info.txt file in a package. Look at the clean_style package for example. The file path for the sound should go in the 'Soundscript' property (slightly misleading name). Pakrat should pack it automatically.

**Comment by ellingtonisland** [comment]
i want to include the music file (i am calling it the buzzer) itself in the package and everything so you can release it with bee2 and have it work with anyone who has the Buzzer package, how do i do that?

**Comment by TeamSpen210** [comment]
Put files in a folder in resources/ (in this case resources/sounds) and it'll be automatically copied into the game. Any icons for the BEE2 must go in resources/BEE2/. Instances go in resources/instances, which get copied to sdk_content/maps/instances/BEE2/.

**Comment by ellingtonisland** [comment]
i have a wave file called "uvb76.wav" now

now tell me exactly what you would type into the config file and stuff for uvb76.wav as a example if you where to add this as custom music to the game and have the wav file included in a package  because i am like beavis (from beavis and butthead) when it comes to programming and scripts. 

i need a complete template with correct code and correct sample directories and everything because i suck so much at programming.

**Comment by TeamSpen210** [comment]
Your info.txt file should be something like this:
```
"ID"		"ELL_UVB_76_PAK"
"Name"		"UVB 76"

"Music"
	{
	"ID"			"ELL_UVB_76"
	"Name"			"UVB #76"
	"Icon"			"music/ell/uvb76.png"
	"Authors"		"EllingtonIsland"
	"Description"	"A song called UVB # 76."
	"SoundScript"	"music/ell/uvb76.wav"
	}
```
Put the sound file in `resources/sounds/music/ell/uvb76.wav`. A 96x96 icon should go in `resources/BEE2/music/ell/uvb76.png`. Look at the extras/music package, since that's nothing but music tracks.

**Comment by ellingtonisland** [comment]
COOOL, this will troll players in game so bad when they go into a test chamber and hear "That"... !!

https://www.youtube.com/watch?v=-2EKWgTNEYU

**Comment by ellingtonisland** [comment]
ok i need your help again, i did everything i was supposed to, i put beginning and end cues in the wave file with goldwave and put everything into the text file and directories, but it doesn't play in my test chamber when i test it!

this is the info file

"ID"        "UVB_76_PAK"
"Name"      "UVB 76"

"Music"
    {
    "ID"            "UVB_76"
    "Name"          "The Buzzer"
    "Icon"          "music/uvb76/uvb76.png"
    "Authors"       "EllingtonIsland"
    "Description"   "A Strange Dull Monotonous Buzzing Noise."
    "SoundScript"   "music/uvb76/uvb76.wav"
    }

**Comment by ellingtonisland** [comment]
see update
