### ISSUE TITLE
[Prl22 Visual Bug] Overgrown Large Observation: "vines_128_128_halfdry01.mdl" is "Crossing the floor"- It needs to be raised up a few grids up

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#792]
![20160910212602_1](https://cloud.githubusercontent.com/assets/12244376/18414417/5e35d4f4-779d-11e6-931a-8583b90bda80.jpg)

**Comment by TheDarkBomber** [comment]
I think it's fine like that.

**Comment by ZombiePwner1** [comment]
That chair needs a overgrown model.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - What is needing overgrown models are Cube and Shpere Buttons, i wonder why valve didnt make them.

**Comment by ZombiePwner1** [comment]
It's valve you know why. They abandoned us P2 fans

**Comment by TeamSpen210** [comment]
Valve generally didn't make resources for things they didn't need/use. Cube/Sphere buttons never appear in SP maps, and Coop maps all must have been modified to allow for the Coop bots afterwards. (Those buttons I think are always on clean bases).
