### ISSUE TITLE
Partial Blocks "GOES TOTALLY CRAZY" resetting on each loading, afther previewing the map and whats more, even when you close your eyes >:(

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#793]
Hi,

With the 22nd release, the partial blocks have picked up an annoying new feature; they no longer remember their positions, and constantly reset to a centered alignment. At least they do remember their type, though. It will do this whenever a chamber is loaded, after doing a playthrough of a map and returning to the editor and whenever copying a block to a different square. This means you have to readjust the positions of all of them before any compile, which can be really quite annoying. But for the chamber I'm currently building I have to stick with release 22 because of the laser relay bug in overgrown maps in release 21.

Partial blocks have with the latest realease also started to complain about crashing with laser emitters, if placed on the same block, say on the floor. In release 21 this was possible.

Speaking of overgrown; the latest releases have multiple selections for skybox choices, and the default value for an overgrown map is Overgrown Sunlight. And indeed, in many overgrown maps, letting the sunlight in through the roof would be a nice feature - very much so on the map I'm currently working on. But I've been unable to find a way to actually make the roof let the skybox through. Is there any way of doing this with these releases of Beemod? Beemod 2.2.5 had an item called Skybox in it, which for whatever unfortunate reasons was not available for Overgrown style, though, but this one is not available in 2.4. And if there isn't a way to utilize the skybox, why so many choices for which style you prefer?

**Comment by cartman1337** [comment]
After some more editing on my work-in-progress chamber, I've realized that they don't reset upon load or after returning to the editor after a runthrough of the test, but rather whenever you start editing the chamber again; adding or modifying items, adding or removing space (+/-), and so on. When editing, suddenly you'll find all your partial blocks reset to a centered position. They always start in a centered position when copying too, unlike before.

**Comment by cartman1337** [comment]
Another observation I just made is that the blocks will reset into a position that is actually impossible to get if you use the slider to decide a position. The partial blocks, like light strips are placeable in 8 different positions; extreme left, left, right, extreme right, extreme front, front, back and extreme back. When the partial blocks reset, they end up in a position between left and right or front and back, depending on the orientation. Once you start using the slider, you cannot go back to the dead-center position they faultily reset to, again and again.

**Comment by LautaroL20** [comment]
Yep, and it is literally being a pain in teh ass for me too.

**Comment by LautaroL20** [comment]
Any way we can fix this ourselves? This has gone even worst, it also gets resetted even when you re compiling the chamber......

Ill check if this is related to the editoritems code.

**Comment by LautaroL20** [comment]
@cartman1337 - "CanAnchorOnBarriers" "1" and "CanAnchorOnGoo" "1" is causing partial blocks to get resetting.

FIX: Deleting both lines from the Partial block item code solves this bug, you can edit it by open the "editoritems.txt".

If you re-export the pallete using Bee2.4 it will break the fix, so you might open the style package you´re using and edit the same txt file there.

**Comment by LautaroL20** [comment]
*blocks.zip package.

**Comment by cartman1337** [comment]
Wonderful!

It would be nice if the blocks didn't crash with goo, though. I don't see a reason why they should crash. Angled blocks can be put in goo. What would I need to change/add in said txt-file to remove the crash?

**Comment by LautaroL20** [comment]
@cartman1337 - That is a little bit complex, but if you play enough atention when editing, you can make it Goo placeable :)

You have to get rid of the following lines, wich are located near the end of the item code:

			"OccupiedVoxels"
				{
				"Voxel"
					{
					"Pos" "0 0 0"
					"CollideType" "COLLIDE_PHYSICS"
					"CollideAgainst" "COLLIDE_NOTHING"
					"Surface"
						{
						"Normal" "0 0 1"
						}

_______________________________________________________________________________

The end part of the partial block code must be like this:

					"Name" "instances/BEE2/logic/blocks/128x32x32_black.vmf"
					"EntityCount" "0"
					"BrushCount" "1"
					"BrushSideCount" "6"
					}
				}
			"TargetName" "bl"
			"Offset" "64 64 64"
			}
		}

**Comment by Luke18033** [comment]
The strange thing is, I'm having the same issue with BEE2.2 P1 fizzlers.
