### ISSUE TITLE
[Bug] portals can be placed on this texture.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#805]
![20160912181206_1](https://cloud.githubusercontent.com/assets/18079316/18432434/84e42ab0-7914-11e6-8a7c-d6a6caefaa37.jpg)

**Comment by TheDarkBomber** [comment]
That's a valve bug, and should be closed.

**Comment by TeamSpen210** [comment]
It's Valve's fault, but I can fix it...
