### ISSUE TITLE
Overgrown Style Goo Debris, is there a set limit of goo?

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#813]
Is there a set limit of how many blocks can have goo before Goo Debris stops appearing? I'm working on a map with a lot of goo/water, and to begin with debris would show up, but as the chamber grew larger, and the sea of goo with it, I'm now getting no goo debris at all. If there's a limit I've exceeded, I'd like to know what it is, and if it can be increased for a later build?

**Comment by TeamSpen210** [comment]
There shouldn't, the generated number should be in proportion to the number of tiles.

**Comment by cartman1337** [comment]
Has it been addressed for the next release, then?
