### ISSUE TITLE
[Bug] Middle Window not working with Sendificator

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#823]
The Sendificator is supposed to be able to send cubes through windows, as long as the laser points through it. The windows in the Middle Window blocks, even though they are more than wide enough to get a cube through, and the laser itself correctly shines through the window, seems to be considered a stationary wall by the Sendificator, i.e. the cube ends up outside the Middle Window instead of inside. If set up to "start reversed" (grating instead of window), the cube will end up inside. But the Sendificator should be able to send through it, also with the window/glass setting.

**Comment by ZombiePwner1** [comment]
How does the sendificator even work?

**Comment by LautaroL20** [comment]
When activated, it teleports cubes to the end of an attached laser beam.
