### ISSUE TITLE
[PRL22 Visual Bug] Original Clean: Large observation room is using "Wall texture" on its "Roof"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#825]
![20160914022806_1](https://cloud.githubusercontent.com/assets/12244376/18501002/7a283e94-7a23-11e6-87ca-9933ce66a8db.jpg)

**Comment by TeamSpen210** [comment]
There isn't an actual ceiling texture, that's actually what Valve uses most of the time.

**Comment by cartman1337** [comment]
How do you guys get into the observation rooms?

**Comment by TeamSpen210** [comment]
`noclip`.

**Comment by TheDarkBomber** [comment]
This is a valve bug then.

**Comment by LautaroL20** [comment]
@TheDarkBomber - No, it is not. I will show a screen from the original PeTi observation roof. It hadn´t a wall texture on it.

**Comment by LautaroL20** [comment]
The original observation roof texture:

![20160914223332_1](https://cloud.githubusercontent.com/assets/12244376/18535584/b228737e-7acb-11e6-8ee7-243eef230116.jpg)

**Comment by TeamSpen210** [comment]
There's actually a better tile texture for the obs rooms, which weirdly isn't used in PeTI but is in the campaign maps I've checked: 
![observation_tileceiling001a](https://cloud.githubusercontent.com/assets/8453732/18577729/ff3f9af2-7c2e-11e6-97e0-8b3ed5401469.png)

**Comment by LautaroL20** [comment]
That texture looks good.
