### ISSUE TITLE
[Bug] BTS A mysterious white texture is in corridor 2

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#826]
![20160914202152_1](https://cloud.githubusercontent.com/assets/18079316/18511920/1c780284-7ab9-11e6-8d44-023d05ca671d.jpg)

**Comment by LautaroL20** [comment]
It seems that for some "Mysterious" reason that BTS Texture did not get packed...

**Comment by TeamSpen210** [comment]
Actually that's just a model, but lit way too brightly.
