### ISSUE TITLE
[PRL22 Bug] Overgrown Style: "elevator_exit.vmf" is missing "walkway_destroyed_64a.mdl", wich should be associated with "@exit_lower_elev"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#829]
This can cause players to fall in a small precipice there before reaching the exit elevator, and therefore this could induce in some players to give a "Thumbs down" to the creator:

![20160915222246_1](https://cloud.githubusercontent.com/assets/12244376/18573250/1392a680-7b98-11e6-9164-a312ddf77cdb.jpg)

**Comment by TheDarkBomber** [comment]
Are you using the right preview map? It should be the preview map from maps/styled.

**Comment by LautaroL20** [comment]
Yes.

**Comment by LautaroL20** [comment]
@TheDarkBomber  - Although it is taken from hammer, you can launch beemod, then set for Exit Corridor N°3 and you can check that the report is leight...

**Comment by TheDarkBomber** [comment]
Post an in-game screenshot.

**Comment by LautaroL20** [comment]
If you really care, test the bug yourself, not my problem if you do not trust me.

**Comment by TheDarkBomber** [comment]
No, post an IN-GAME screenshot.

**Comment by LautaroL20** [comment]
No, the screenshot actually shows the exact same bug.

**Comment by TheDarkBomber** [comment]
Still.

**Comment by cartman1337** [comment]
I had to check this out for myself. Published a private mini-test in Overgrown style, with exit corridor 3 (I had to publish to check it, because the chamber will restart even when removing the option "resart when reaching exit in BEE2.exe" - that's a bug you could look at), and playing it I found out that exit corridor 3 is perfectly safe.
![Safe ground](http://i.imgur.com/yeUfLqm.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 seems you and @TheDarkBomber hate each other.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - lol i do not hate anyone, why would you say that? Id say this isn´t a "Missing item variant" because its not about somehting being unstyled. On the other hand, it looks like you didn´t test this bug yourself. 

@cartman1337 - Theres is not a stylevar option explicitly called "resart when reaching exit ". There are only two about this, and they´re: "Spawn at entry door" or "Spawn at elevator", you might want to choose the second one if you want to get rid from the restarting process when reaching the exit door during previewing mode.

@TeamSpen210 - Afther reading some comments here, i came to the conclusion that i had to give this a re-test, and the final results are that this bug report is legit, on both Previewing and Published, this bug will occur in the exact same way. 

@TheDarkBomber - Here is your precious "Long awaited in-game screenshot", taken during the re-testing process:

![20160915222246_1](https://cloud.githubusercontent.com/assets/12244376/18573250/1392a680-7b98-11e6-9164-a312ddf77cdb.jpg)

**Comment by ZombiePwner1** [comment]
I have used this corridor and I thought that there wasn't mean't to be a walkway @LautaroL20

**Comment by LautaroL20** [comment]
Well, i was thinking the same until i decided to check between the old Bee2.2.5 Alpha instance files to see if this was intended, but during the bee2.5.5 playtesting process, i saw that "walkway_destroyed_64a.mdl" was there. 

BTW, you can take hammer screenshots by pressing the key "Print SysRq", then paste it in Paint to save it.

**Comment by TeamSpen210** [comment]
The walkway should be there unless the BTS exit is used - in that case you walk through the wall to the elevator.

**Comment by TheDarkBomber** [comment]
@LautaroL20 There is an option called "Resart when reaching exit". Do you have the [PR22 compiler](https://github.com/BenVlodgi/BEE2.4/releases)?

**Comment by LautaroL20** [comment]
@TheDarkBomber - Yes, i guess all of us downladed the exact same version afther PRL22 came out, otherwise i could not report bugs with the title "[PRL22 Bug]".

**Comment by ZombiePwner1** [comment]
@LautaroL20 what u doing? Where did u go? Missing walkway tho is abit weird.
