### ISSUE TITLE
add more entrance and exit types to ALL styles

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#83]
add more entrance and exit types to ALL styles. this will take you a long time

maybe like 15-20 variations of exit/entrance per entrance and per exit so no two styles have a similar elevator entrance or exit.

**Comment by TeamSpen210** [comment]
Um, no. The corridor instances took the majority of the time when I was making the Overgrown style. I've already got to remake some of the Old Aperture hallways (they're just retextured Clean ones), and I'm not doubling the number of corridors in the mod. I'm happy to accept contributions, and I might do some random overlays in some corridors (so dirt or furniture changes slightly).
