### ISSUE TITLE
[Suggestion] Make the "Pedestal Button" to not interfere with any items

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#831]
Pretty much useful when you want to place glass in front of it:

![20160916062012_1](https://cloud.githubusercontent.com/assets/12244376/18581286/4957f7dc-7bd6-11e6-8668-8e149498b64f.jpg)

**Comment by TheDarkBomber** [comment]
That is impossible without making it interfere with other items.

**Comment by cartman1337** [comment]
Use the Retractable Pedestal Button for this. It places on a more centered position, which allows glass to be added on all sides of it. If you start your Retractable Pedestal Button enabled, it will look pretty much exactly like a normal Pedestal Button, except for the slightly different position on the floor.

![Retractable Pedestal Button and Glass](http://i.imgur.com/xozEo21.jpg)

**Comment by TeamSpen210** [comment]
This is probably doable, the 4-way positioning doesn't require any special-casing item classes.

**Comment by LautaroL20** [comment]
The small and largue observation room, at least for clean style, can also be arranged so that it does not require extra blocks than its needed, i done this on my editor and no bugs were found.

**Comment by LautaroL20** [comment]
@TeamSpen210 Map Editor + In-Game results screen:
![observation](https://cloud.githubusercontent.com/assets/12244376/18605615/ad6e7ae8-7c6c-11e6-8ea0-74bef5715971.png)

**Comment by TeamSpen210** [comment]
Try recessing the walls around sides of the room.

**Comment by LautaroL20** [comment]
Im aware that it causes textures overlaps on windows frames in the only case that wall is recessed. Pls do not offence, but unless you´re a 7 years kid who decided to play with the PeTi editor, no one would publish an averration like that on the workshop (Well, i want to believe). So, this could provide big benefits as you saw in the screen from adobe.

**Comment by TeamSpen210** [comment]
First I might modify those models to allow it. Although I won't be changing the item - Clean doesn't need the space, but most other styles do. Additionally Clean Obs rooms on ceilings do use the whole space.

**Comment by TeamSpen210** [comment]
I've had a fiddle with this, it doesn't seem possible to change the collide type to allow the glass without allowing buttons to be placed inside everything else too.
