### ISSUE TITLE
[PRL22 Bug] "CanAnchorOnGoo 1" and "CanAnchorOnBarriers 1" Causes the "Partial Blocks" to resetting every time

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#836]
FIXED CODE:

					}
				}
			"MovementHandle" "HANDLE_8_POSITIONS"
			"OccupiesVoxel" "0"
			}
		"Properties"
			{
			"ButtonType"
				{
				"DefaultValue" "0"
				"Index" "0"
				}
			"StartReversed"
				{
				"DefaultValue" "0"
				"Index" "1"
				}
			}
		"Exporting"
			{
			"Instances"
				{

**Comment by LautaroL20** [comment]
I can confirm that these lines: "CanAnchorOnBarriers" "1" and "CanAnchorOnGoo" "1"  (Wich should be from the Barrier item only) is causing partial blocks to get resetting.

 FIX: Deleting both lines from the Partial block item code solves this bug.

**Comment by TeamSpen210** [comment]
Those lines allow the blocks to be placed on glass, and on top of goo. Oh well, the random repositioning is unacceptable.

**Comment by LautaroL20** [comment]
My post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/836

**Comment by TeamSpen210** [comment]
This is 386...

**Comment by LautaroL20** [comment]
lol, it looks like i need glasses, that happens when you try to do a fast copy&paste. My post is a duplicate of: https://github.com/TeamSpen210/BEE2-items/issues/793

I promise grabbing my glasses next time ;)
