### ISSUE TITLE
help needed with custom music not playing in map

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#84]
ok i need your help again, i did everything i was supposed to, i put beginning and end cues in the wave file with goldwave and put everything into the text file and directories, but it doesn't play in my test chamber when i test it! is there something i need to do in hammer. tell me if i do and how i locate the file that is outside hammer in hammer if needed.

this is the info file

"ID" "UVB_76_PAK"
"Name" "UVB 76"

"Music"
{
"ID" "UVB_76"
"Name" "The Buzzer"
"Icon" "music/uvb76/uvb76.png"
"Authors" "EllingtonIsland"
"Description" "A Strange Dull Monotonous Buzzing Noise."
"SoundScript" "music/uvb76/uvb76.wav"
}

**Comment by TeamSpen210** [comment]
Don't close an issue and open a new identical one, it's pointless. 

Open any map in Hammer, then press Ctrl-Shift-S. Switch the sound type to Raw, and type the sound name into the 'filter' to see if it's recognised. (Do you have 'Preseve Game Directories on? If you do, you'll need to manually copy the sound into the P2 folders.) You might also want to open `sdk_content/maps/styled/preview.vmf`, and look near the entry elevator for an ambient_generic. (Select the elevator and press H to hide it temporarily.) Press the 'play' button in the entity properties to see if the path is correct, and use the browse button to find the correct one if it's not.

**Comment by ellingtonisland** [comment]
it's not showing up in hammer, preserve game directories is unchecked. it appears to be something with the file format, it's showing up in bee2, but it doesn't work in portal 2, what format must these files be in exactly when it comes to hertz frequency and stuff like that

48000 hertz
wav file
with start_cue and end_cue
if i am correct?

**Comment by TeamSpen210** [comment]
If it's not showing up, that probably means it's not in the game directory. Check `Portal 2/bee2/sounds/music/uvb76/`, is it in there?

**Comment by ellingtonisland** [comment]
it appears to be in the proper location of "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bee2\sounds\music\thebuzzer\thebuzzer.wav"

hammer isn't seeing it at all

it's in 44100hz format with time cues made by goldwave named "start_cue and end_cue"

it was converted and edited with audacity before goldwave.

here is my current info file for it, is something missing?

"ID"        "EI_MUSIC_PAK"
"Name"      "EI Music Pak"

"Music"
    {
    "ID"            "THE_BUZZER"
    "Name"          "The Buzzer"
    "Icon"          "music/thebuzzer/thebuzzer.png"
    "Authors"       "EllingtonIsland"
    "Description"   "A Strange Dull Monotonous Buzzing Noise that repeats itself endlessly."
    "SoundScript"   "music/thebuzzer/thebuzzer.wav"
    }

here are the folder directories of the package itself

C:\Users\Cam\Desktop\BEE2.4.0pr7\packages\thebuzzer\resources\BEE2\music\thebuzzer/thebuzzer.png

C:\Users\Cam\Desktop\BEE2.4.0pr7\packages\thebuzzer\resources\sounds\music\thebuzzer\thebuzzer.wav

i want to figure out what's wrong with this @TeamSpen210 so i can get it fixed and going so we could troll Ben Vlodgi with a test chamber that has this "strange monotonous dull buzzing sound" playing in it to test custom music working with the bee2

**Comment by TeamSpen210** [comment]
Use a 'sound' folder instead of 'sounds', whoops.

**Comment by ellingtonisland** [comment]
now it's registering under hammer, time to test in portal 2 when fireworks video conversion is complete!

**Comment by ellingtonisland** [comment]
@TeamSpen210 

let me know if bee2 compiled custom music correctly in this test: you should hear a very annoying dull buzzing sound! copy this url into the steam user workshop in pti and subscribe http://steamcommunity.com/sharedfiles/filedetails/?id=479849172

**Comment by ellingtonisland** [comment]
@TeamSpen210  - the audio plays in test chamber now, but it doesn't repeat itself endlessly, how do i fix this?

i used goldwave to create time cues.

**Comment by TeamSpen210** [comment]
You need to add loop points, not start/end cues. It's the red buttons in Waveosaur.

**Comment by ellingtonisland** [comment]
@TeamSpen210 - thats what i did with wavosaur and it's still not looping, it plays in the test chamber for a bit then stops. the audio file is about 30 seconds long.

**Comment by ellingtonisland** [comment]
found the source of the problem, you will have to go through ALL your elevators and change this flag under the ambient_generic

![image](https://cloud.githubusercontent.com/assets/11165643/8636087/cb0d8f9e-281c-11e5-9aff-e4bfc2213bf0.png)

**Comment by TeamSpen210** [comment]
That is set correctly. The ambient_generics are actually generated by VBSP directly, look in the entry elevator. I believe the flag doesn't actually change whether or not an audio track loops, it does it regardless. Make sure the file in the package has the loop points (it'll overwrite the one in Portal 2/bee2/ on export).

**Comment by ellingtonisland** [comment]
thats what said i did with wavosaur and it's still not looping, it plays in the test chamber for a bit then stops. the audio file is about 30 seconds long. i have tried loops with a start and end, and start only with no end loop and nothing works...

**Comment by ellingtonisland** [comment]
@TeamSpen210   can you tell me exactly what format it has to be saved in with wavosaur ect because i have tried to create start and end, start only, and end only loop points with wavosaur and nothing is working and it won't loop, i have tested it by unchecking the isnotlooped flag in hammer multiple times and still its not looping. i think this may some kind of genuine bug here with the bee or the compiler were dealing with here.

**Comment by TeamSpen210** [comment]
The 'is not looped' flag is always unchecked when the BEE injects the ambient_generic. Just clicking the red 'L' button in Waveosaur should work. Double-check that the file in the package has the loop points, as well as the one in the Portal 2 folder. If you can hear it I'm pretty sure the format would be correct.

**Comment by ellingtonisland** [comment]
@TeamSpen210 - i checked both locations, it shows its looped in wavosaur at both locations
![image](https://cloud.githubusercontent.com/assets/11165643/8638655/0adc5da8-2890-11e5-955b-72f98e6dad01.png)
![image](https://cloud.githubusercontent.com/assets/11165643/8638658/25ddafee-2890-11e5-938a-b66a5604503c.png)
but still it only plays for a short time and then stops at the end. do you see if anything is wrong in wavosaur with these screenshots?

**Comment by ellingtonisland** [comment]
@TeamSpen210 it appears to be a bug with the map compiler or something because it cuts off right in the middle of buzzing in the map and the loop points in the file are between the buzzes. can you give me your email address or something so i can i send you the uvb76 package and i will let you fiddle with it and see if you can get it working. if you do show me what you did!

**Comment by ellingtonisland** [comment]
@TeamSpen210 this appears to be a bug with the map compiler or something because the music cuts off right in the middle of buzzing in the map and the loop points in the file are between the buzzes. i have checked if the files in both the package and bee2 resources file under the portal file have loop points and they do. can you give me your email address or something so i can i send you the uvb76 package and i will let you fiddle with it and see if you can get this working. if you do show me what you did!
