### ISSUE TITLE
[PRL22 Valve Bug] Source engine renders "Black_wall_metal_005b_vertex" as a "Black Shadow"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#847]
This only happens when you finish solving a puzzle, then you reach the exit door and it will appear

FIX: Set the exit broken ceilling tiles to some other overgrown texture.

![20160920121701_1](https://cloud.githubusercontent.com/assets/12244376/18676594/83ae7f74-7f2c-11e6-92be-ec6ef87b6edf.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 Chat with me and this shadow error is caused by the frames shadows not being disabled.

**Comment by LautaroL20** [comment]
Sure :)

**Comment by LautaroL20** [comment]
No, this is not a problem of squarebeams, its a problem with the func_details tiles textures, for a mysterious reason, they always renders totally black in one face.

**Comment by LautaroL20** [comment]
Afther lot of playtesting between hammer and P2, the conclusion is that this is a valve bug where Source engine renders "Black_wall_metal_005b_vertex", this bug doesnt happen every time, but the fix for this is setting to another overgrown texture.

FIX: Set the exit broken ceilling tiles to some other overgrown texture.

**Comment by LautaroL20** [comment]
I have set exit_corridor3 to another ceilling tiles texture, and voila:

![20160920121701_1](https://cloud.githubusercontent.com/assets/12244376/18676614/9237b1b4-7f2c-11e6-88b6-f2525982eb65.jpg)

**Comment by TeamSpen210** [comment]
Oh, woops. You don't want to use vertex textures. Also don't add the fixed label until it's in the repro.

**Comment by ZombiePwner1** [comment]
@LautaroL20 vertex textures are horrible to use since they cause horrible shadows or lighting.
