### ISSUE TITLE
Triple Wallpipes need interior models

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#848]
![20160919171306_1](https://cloud.githubusercontent.com/assets/12244376/18665053/c049c906-7efb-11e6-9b9d-77181e4c1ffc.jpg)

**Comment by ZombiePwner1** [comment]
That's the model itself valve didn't make insides for them since they knew weren't mean't to be visible.

**Comment by TeamSpen210** [comment]
Yes, I need to make a reskin of them with a `$nocull` material, so you can see the inside as well.

**Comment by cartman1337** [comment]
Are those pipes even in Beemod?

**Comment by LautaroL20** [comment]
@cartman1337 - I am a beemod mapper, all the screenshots you see on all my post are from P2 using Bee2.4

**Comment by cartman1337** [comment]
That brings me to the next question; HOW do you get those pipes in?

**Comment by LautaroL20** [comment]
They re a model that Valve used for some of the random entrance corridors from overgrown style.

**Comment by TeamSpen210** [comment]
Valve didn't make these corridors...

**Comment by LautaroL20** [comment]
Ah, well i was almost to say valve or TeamSpen, but its an unfinished model, it looks like that cartman1337 want them to be a Bee2.4 addon.

**Comment by cartman1337** [comment]
Well, yeah. That, and other things that are for decoration only, to make tests more visually interesting, would be a welcome extension.

**Comment by LautaroL20** [comment]
@TeamSpen210 - If you reskin to make them inside viewable, they will fit pretty well with "info_particle_system" to add water loss effects. And the best, it will be an exlusively Bee2.4 stuff (Unless people steal the instance).
