### ISSUE TITLE
Deflection Cubes

### ISSUE THREAD

**Issue by jccreszMinecraft** [TeamSpen210/BEE2-items#85]
Is there any way to separate the logic for the deflection cubes from the instance used in PTI? I'm using them in a hammer map and wish to reduce the entities by singling them out. Possibly send me a instance?

**Comment by TeamSpen210** [comment]
The deflection cube instances shouldn't really have anything PeTI-specific. You should be able to copy the logic room out of global_ents, all the logic is there (except I think there's a logic_auto output in the main room you'll need to copy as well. I don't really have much to do with the Deflection cubes, they're made by Felix Griffin. Just so you know, they have a major bug where you can 'activate' them by shooting through any object (including solid wall).

**Comment by jccreszMinecraft** [comment]
Yes, i know. you've told me before ;)
