### ISSUE TITLE
[PRL 22 Bug] Signage item not being packed in Old Aperture 70s style

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#853]
Can anyone tell what any of these signs are supposed to tell (one of every type from 3 to 18)?
![Useless signage in the 70s](http://i.imgur.com/9enxxjj.jpg)

Signage works well in the other Old Aperture styles, but it's completely useless in the 70s style.

A closer look. All the different signs use exactly the same texture.
![Closer look](http://i.imgur.com/BoSiG9o.jpg)

**Comment by LautaroL20** [comment]
It looks like that the signage item are not being packed for the 70´s old ap.
