### ISSUE TITLE
[Bug] Conductive Plate not textured (multiple styles)

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#857]
In a map I'm working on, I added Conductive Plates. I was working in 70s style, and there they texture like this:
![70s off](http://i.imgur.com/ATYT553.jpg)

It looks nice, and gives a sense of this square being something to pay notice to. When activated, it also makes a nice sound, and another sound when de-activated. Activated it looks like this:
![70s on](http://i.imgur.com/UWRZtO5.jpg)

I decided to check my map out in other styles. In 50s and 60s style, the Conductive Plates looked the same. However, in EVERY other style, they are not textured at all!

Here it is in BTS mode:
![BTS](http://i.imgur.com/Hr8QGG4.jpg)
(Does anyone have any idea why this map is getting goo instead of bottomless pits, by the way? It's working in other maps.)

Clean:
![Clean](http://i.imgur.com/5slxvRd.jpg)

Original Clean:
![Original Clean](http://i.imgur.com/ZPZbsQ9.jpg)

Overgrown:
![Overgrown](http://i.imgur.com/ECEboRY.jpg)

Portal 1:
![P1](http://i.imgur.com/t0VnQHl.jpg)

80s:
![80s off](http://i.imgur.com/jHgL5pa.jpg)
(I also got massive color bleed instead of goo on this map in 80s mode, as you can see, but I'm opening that as a separate issue)

If I had been playing a map with these, not knowing about them, I would never have guessed that these were actually buttons, though the ant-lines might have helped. Had there been no signage at all, no-one could possibly guess that this was a button. It also makes no sounds in these modes.

Finally, this is what they look like "activated" in the other modes (exemplified by 80s style). At least they do issue proper output.
![80s on](http://i.imgur.com/L2lDmZL.jpg)

I am guessing the styles for the 50s, 60s and 70s are more in line with the intention for this item. They certainly need SOME kind of texture in the other styles as well...

**Comment by TeamSpen210** [comment]
This would have the same underlying issue as #853 - overlays aren't being added properly. It should look like the editor model, with a glowing blue/orange symbol on the plates.
