### ISSUE TITLE
[Enhancement] Overgrown Style: Implement "Brown Catwalks" (219 182 162 R.G.B) on catwalk item, the entrance and exit aswell

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#859]
219 182 162 RGB

![over](https://cloud.githubusercontent.com/assets/12244376/18769153/fc2b35c0-8100-11e6-9968-954f25279af9.png)

**Comment by ZombiePwner1** [comment]
How did u change them brown?

**Comment by LautaroL20** [comment]
Via the properties from the model itself, see this screenshot:

![catwalk](https://cloud.githubusercontent.com/assets/12244376/18769248/e95f62d0-8101-11e6-98df-f1fd539c9414.png)

**Comment by ZombiePwner1** [comment]
Ahh yep.

**Comment by ZombiePwner1** [comment]
Rusted catwalks are good but i feel it's better to use underground walkways since they are already rusted.

**Comment by LautaroL20** [comment]
I do not think so, since "Overgrown Style" is basically a clean style, but in damaged version. It isn´t nice to merge items from other styles.

**Comment by ZombiePwner1** [comment]
well in my maps i use underground hand rails since i don't really like the clean ones.

**Comment by LautaroL20** [comment]
Well, thats your taste, but Beemod should not be based always on "Tastes", it must respect all the styles. Thats why i do not like the idea of having in original clean, the corridors that still are not using its original ceilling texture.......

**Comment by ZombiePwner1** [comment]
Well i wanan chat. And i do like those brown walkways. Just needs abit more of a rusty feel.

**Comment by TeamSpen210** [comment]
That looks nice! I might just recompile the models with a `$detail` setting maybe, so it's got better rust effects.
