### ISSUE TITLE
[PRL22 Bug] Bee2.4 is making the custom thumbnails to get "Deform dimensions" compared to the original file

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#862]
Comparision between a self-made force thumbnail and hows bee2.4 prl22 sets the custom thumbnail:

![rusty laser chamber bee2 4 deformation pict](https://cloud.githubusercontent.com/assets/12244376/18805945/e22c6e54-81f1-11e6-9040-04afff0429e1.png)

Original thumbnail is about: 1280x720 pixels.

**Comment by TeamSpen210** [comment]
The code resizes them to the same ratio as Valve's, but that is clearly not needed. I'll switch it to leave it the original size.

**Comment by TeamSpen210** [comment]
Now fixed. Alternately, once you have selected 'Custom', overwrite `config/screenshot.jpg` with an image of your choice. That's all the application does, and that's only when you actually browse for a file.

**Comment by cartman1337** [comment]
Are you sure it's not the other way around? I tried to force a self-made thumbnail once, and got the black borders on it. Every time I let Bee2.4 set the thumbnail automatically, it looks fine.

**Comment by LautaroL20** [comment]
@cartman1337 - Yes, i am.
