### ISSUE TITLE
[Question] Fizzler placements

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#863]
The fizzler/laser-field looks like it has 4 different positions in either horizontal or vertical alignments, but the two middle selection marks both leave the fizzler in the same position (centered). I'm wondering, is this a bug, or is it intentional?

![Fizzler middle-](http://i.imgur.com/icD9QVc.jpg)
![Fizzler middle+](http://i.imgur.com/wk6x87o.jpg)

**Comment by ZombiePwner1** [comment]
It's intentional it just switches sides that's all.
