### ISSUE TITLE
[Bug] Doors don't block tractor beams.

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#871]
Doors currently do not interfere with Tractor Beams when locked. This is contrary to the behavior of the built in Exit doors, which will block any Tractor Beams pointing towards the door once locked, even those that do not use portals to point the beam on it. To me it makes more sense that a locked door is indeed tightly locked, and that it should block a Tractor Beam, the same way glass does.

The picture below shows that the Tractor Beam currently transports through a locked door. This is not an Exit chamber, although it has been made to look as one... The beam originates from behind the door in the back of the picture; I'm looking backwards in terms of the beam's transportation direction.
![Tractor beam active through locked door](http://i.imgur.com/8hzfn5Q.jpg)

**Comment by TeamSpen210** [comment]
Yes, that does make more sense. I'll need to add some more clips to block it.

**Comment by ZombiePwner1** [comment]
Well seems the door is invisible for the beam which explains why it goes through.

**Comment by LautaroL20** [comment]
Thats an awesome find! I will test if Light Bridges / Funnels still can go trhough Overgrown Doors.

**Comment by TeamSpen210** [comment]
Overgrown doors = Clean doors, they're identical (but match the wall textures set by the style). The other styles already have this fixed.

**Comment by LautaroL20** [comment]
Ok.
