### ISSUE TITLE
[PRL22 Visual Bug] Clicking the "Refresh compile progress bar" does not clear it

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#872]
![compile options](https://cloud.githubusercontent.com/assets/12244376/19012155/21be6c2a-8783-11e6-81c5-dd1b904dd759.png)

**Comment by TeamSpen210** [comment]
What do you mean? What happens is that after each compile the numbers are written to a file. That's read when you start the BEE2, and when you press that button. For it to change you'll need to keep the app open, start Portal 2, compile, then Alt-Tab back and refresh.

**Comment by LautaroL20** [comment]
Oh, then i probably misunderstood how it works in the beginning. It makes sense now, case closed.
