### ISSUE TITLE
Overgrown Style: Placing 6 or more Laser Emmiters causes problems on the Lighting and Textures from the "Small And Large Observation Rooms"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#873]
I just placed 6 centered laser emmiters in the wall, and this caused problems on the obervation rooms, maybe a Valve bug? Hope its fixeable, see these two screenshots:

![20161001031539_1](https://cloud.githubusercontent.com/assets/12244376/19012228/e22f6a3e-8785-11e6-8ed2-23e70c8c9ba2.jpg)
![20161001031557_1](https://cloud.githubusercontent.com/assets/12244376/19012233/f2093caa-8785-11e6-8bd3-f390e16f5be8.jpg)

**Comment by TeamSpen210** [comment]
This is an interesting little issue. There's a limit of 4 switchable lights applied to one brush face. Lasers use those to enable/disable a glow around them, so the many emitters hit the limit and cause lighting issues.

**Comment by LautaroL20** [comment]
It is stange that in Clean Style there is not any limit. The lasers limit ammount is pretty small in Overgrown, there is any way to increment it to a major number? Having it very limited isn´t good :(

**Comment by TeamSpen210** [comment]
It's going to be fixed by removing the random flickering obs rooms.

**Comment by LautaroL20** [comment]
Thats weird, because i already removed the logic_timer that makes it to get off and on, on both observations, so i doubt that the bug is caused by the observation itself. Whats more, i tried using the clean instance of the large observation and it happens the exactly same when using some laser emmiters.

**Comment by TeamSpen210** [comment]
It's actually a problem with the lasers - they didn't have falloff set, so the light brightness was casting forever.

**Comment by LautaroL20** [comment]
Is this fixed for the other styles aswell? Id notice this happens in clean style too.

**Comment by TeamSpen210** [comment]
Clean Style has the fallback set, so it shouldn't happen there.

**Comment by LautaroL20** [comment]
![20161103004729_1](https://cloud.githubusercontent.com/assets/12244376/19956041/72e24386-a166-11e6-9606-2e0d09b25c49.jpg)

**Comment by TeamSpen210** [comment]
What's wrong in this screenshot.

**Comment by LautaroL20** [comment]
Lighting problems in the observation room due to lasers. But ill try re-installing the valve´s items package.

**Comment by ZombiePwner1** [comment]
I can see the problem in that picture since the light in the observation room is a lot darker.

**Comment by LautaroL20** [comment]
Glad to know i didnt broken anything, tried using a 100% New installation from beemod, and i can confirm that lasers makes clean observation rooms to get lighting problems too.

![20161103021450_1](https://cloud.githubusercontent.com/assets/12244376/19956552/a769173c-a16c-11e6-8f7d-1f561dc9bac7.jpg)
