### ISSUE TITLE
Reflection Gel Dropper´s Model becomes "Invisible" in the editor

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#875]
![20161027040808_1](https://cloud.githubusercontent.com/assets/12244376/19757864/b1d0c04c-9bfb-11e6-9ebe-e913a4574081.jpg)

**Comment by LautaroL20** [comment]
Your fix probably would´t be actually solving the issue for next release. Ive replicated your "fix" by using the correct model name "paint_dropper_editor_grey", but now something mysterious happens:

![20161027040808_1](https://cloud.githubusercontent.com/assets/12244376/19757864/b1d0c04c-9bfb-11e6-9ebe-e913a4574081.jpg)

**Comment by TeamSpen210** [comment]
Did you rename the vvd, vtx files as well? I might need to recompile it if it doesn't show up correctly.

**Comment by LautaroL20** [comment]
Yes. I wonder why it becomes invisible, since it worked well on Bee2.2.5. Did you modify the PeTi editor?
![models](https://cloud.githubusercontent.com/assets/12244376/19772044/5316557c-9c3b-11e6-97c5-b1bb5d2b1ea5.png)

**Comment by ZombiePwner1** [comment]
Maybe it's a incorrect name since if it was the model file then the models textures would be missing.

**Comment by TeamSpen210** [comment]
The lines always come right from the ceiling, you can see that in the Old Aperture models too (which have that spot visible). The issue would be with one or more of the files being missing, which means the model loads (doesn't become the blue error), but doesn't actually have any triangles to draw.

**Comment by LautaroL20** [comment]
It looks like you´ve fixed it.
