### ISSUE TITLE
[Bug] Overgrown style: compiled Reflective Cubes reverses editor direction

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#881]
In Overgrown Style a Reflective Cube will point a laser pointed at it in the opposite direction of what the editor marker is set up for. This can be a real pain in tests where a Reflective Cube is locked away somewhere, and is meant to reflect a laser pointed at it in a specific, pre-set direction, where you currently have to either guess the angle opposite of what you mean, or use a ruler or something on your screen to guide you to the correct opposite direction for a correct compile.

That was complex to explain. I'll let these pictures do the talking.

A Reflective Cube set up in the editor to point like this...
![Reflective Cube in editor](http://i.imgur.com/3jlwNY4.jpg)

...will in all other styles show up correctly, like this (here in 60s mode):
![Reflective Cube in other styles](http://i.imgur.com/xQ3g09U.jpg)

...while in Overgrown Style it shows up like this:
![Reflective Cube in Overgrown style](http://i.imgur.com/ytttf2F.jpg)

**Comment by ZombiePwner1** [comment]
Instance for it in overgrown must be messed up.

**Comment by TeamSpen210** [comment]
Indeed, the cube in the instance was facing the wrong direction.
