### ISSUE TITLE
[PRL22 Visual Bug] 80´s Old Aperture: The SP Exit corridor N°2 is missing its "Projectexture" on its (despite redundancy)...Projector

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#885]
![20161003075635_1](https://cloud.githubusercontent.com/assets/12244376/19036353/c9ec8fee-8945-11e6-96b4-6e24d90708b9.jpg)

**Comment by ZombiePwner1** [comment]
It's not on you silly person.

**Comment by LautaroL20** [comment]
This is a bug actually, why its being displayed the "Aperture Logo" and what is generating it?

**Comment by ZombiePwner1** [comment]
That's part of the whiteboard model.
