### ISSUE TITLE
implement option to export (dump) compiled finished test chambers as bsp

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#886]
implement a option to export (dump) compiled finished test chambers as bsp because if your making the bottomless pit code generate them like what valve does with them, eventually the bee2 could be polished up enough to assist in creating test chambers for a portal 2 mod because most people don't like / don't know how and won't want to learn how to use hammer...

**Comment by TeamSpen210** [comment]
This won't work. After compilation, you can't rename BSPs, so you'd only be able to export one map for your 'mod' this way. In addition, it's not useful - you can already dump all the packed files you need, and if you can't compile and pack files into a map you won't be able to do everything else needed to make a sourcemod. Furthermore, something like that needs Hammer to be any good - you need control over choreo lines, and to make story-focused maps to further the plot. A pile of unconnected and unrelated chambers wouldn't be that good.
