### ISSUE TITLE
[PRL22 Bug] Old Aperture: Cave johnson lines do not stop when another one starts, becoming into a "Crazy Cacophony" that can make you go crazy

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#889]
This is probably a Valve bug, for example, when a Johnson line starts playing, then you enter into the exit and another Johnson line starts playing above the another one, this becomes into a "Crazy Cacophony" that can make you go crazy. (Hope it is not due I'm using the Spanish version). 

Unrelated thing: I do not recommend install the new GeForce experience 3.0, it is the apocalypse. I had to downgrade to the previous version to being able to record the video from below.

VIDEO: https://youtu.be/NfM9QgEYBVo

**Comment by ZombiePwner1** [comment]
That's not a valve bug it's a trigger when you made the second one play you activated the trigger for it.

**Comment by TeamSpen210** [comment]
There isn't a nice way to fix this for Cave Johnson, due to the exact way his lines are done. Just don't make chambers that can be completed in less than 10 seconds.
