### ISSUE TITLE
Add Overgrown Entry Worldportals

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#89]
you need to move the corrador instances in overgrown, i think the photo's explain the bug. you can see into the test chamber through the skybox.

![preview0043](https://cloud.githubusercontent.com/assets/11165643/9052211/e3781202-3a32-11e5-9d85-3288d5611d8c.jpg)

![preview0045](https://cloud.githubusercontent.com/assets/11165643/9052203/d14624c0-3a32-11e5-8a94-256129683359.jpg)

![preview0046](https://cloud.githubusercontent.com/assets/11165643/9052204/d31c0b3e-3a32-11e5-9c60-46bc1a8c2f51.jpg)

**Comment by TeamSpen210** [comment]
This is not actually a skybox issue, it's more that I haven't re-added the worldportal instances used in entry rooms.

**Comment by ellingtonisland** [comment]
fixed

**Comment by TheReviewers** [comment]
@TeamSpen210 To Be Honest, I Think Some Overgrown Entries Should Have That... It Looks Pretty Dope..
