### ISSUE TITLE
[Bug (?)] Mysterious floating cube

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#893]
This might be a Valve bug, but I'm reporting it just in case. If you place two (or more) cubes on top of each other, and then quickly grab the bottom one, and remove it without lifting it, the cubes that were on top of it doesn't fall down, but just mysteriously hangs in the air, even casting shadows below them.

![Floating cube](http://i.imgur.com/RAiB5Gy.jpg)

**Comment by Luke18033** [comment]
This looks like a Valve bug

**Comment by TeamSpen210** [comment]
It's a Valve bug, specifically when it's powered.
