### ISSUE TITLE
[Bug] Doors not filling their blocks 

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#900]
The doors do not quite touch their surrounding blocks, as can be seen on these pictures, where signage behind the door can be seen at the edges:
![1](http://i.imgur.com/7PI7Epw.jpg)
![2](http://i.imgur.com/LdjI19Y.jpg)

Could this be part of the reason why Tractor Beams carry through closed doors?

**Comment by ZombiePwner1** [comment]
well isn't that interesting.

**Comment by TeamSpen210** [comment]
It actually looks like the antlines are depth-sorting above the frame, which also isn't right. Place antline routers on the sides to stop the antline from going on the sides.

**Comment by LautaroL20** [comment]
Best you can do is just using some "Antline Router Strips" to prevent the antline going trhough the beemod door´s block.
