### ISSUE TITLE
[Bug] Monitor Screens not quite filling the frame

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#901]
The screens in Monitors doesn't touch the right side of the Monitor frame.
![Monitor](http://i.imgur.com/PUwq7q6.jpg)

Doors next to Monitors look a bit funny when opened too, as the picture above also shows, but I'm not sure what the best way -if any - to fix that would be.

**Comment by ZombiePwner1** [comment]
This is why you don't put monitors next to doors as strange results will happen.

**Comment by TeamSpen210** [comment]
The monitor part is a bug though.

**Comment by Luke18033** [comment]
Maybe add `EmbeddedVoxels`.

**Comment by LautaroL20** [comment]
@Luke18033 - Thats a good idea!

**Comment by Luke18033** [comment]
Wait...but monitors already have `EmbeddedVoxels`...

OH! He means the Door item, not the actual exit door like I thought.
