### ISSUE TITLE
[PRL 22 Bug] Overgrown there is a mysterious floating model in the coop disassemble room entry.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#904]
![20161007142441_1](https://cloud.githubusercontent.com/assets/18079316/19180662/32bd1168-8c9a-11e6-8666-2595a0ebfacf.jpg)

**Comment by LautaroL20** [comment]
Whut the hell is "Disassemble room"? It would be more acurate to give the Corridor Number instead.

**Comment by LautaroL20** [comment]
Ah, it is the exit elevators.

**Comment by ZombiePwner1** [comment]
I used a console command to toggle a secret flash light.

**Comment by TeamSpen210** [comment]
It's not floating, it's jammed up between the wall and that truss.

**Comment by ZombiePwner1** [comment]
Alright issue closed then.
