### ISSUE TITLE
Clean Style: Something "Mysterious" is happening with the 30° degress Angled Panel on its back

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#909]
![20161007055841_1](https://cloud.githubusercontent.com/assets/12244376/19184494/ce3bda44-8c53-11e6-9415-4735b0cffeef.jpg)

**Comment by LautaroL20** [comment]
I forgot to mention that it only happens when it has no connections.

**Comment by ZombiePwner1** [comment]
Must be a nodraw texture as they sometimes do this.

**Comment by LautaroL20** [comment]
Probably, yes.

**Comment by TeamSpen210** [comment]
It's to do with the brush clip present here, and what I was doing to try and save entities. I'll just have a `func_brush` in every panel item.

**Comment by LautaroL20** [comment]
Well, it is always a good idea to saving entities. Considering that the rest of panel degress works well, id suggest only to do that with the buggy one from 30°.

**Comment by TeamSpen210** [comment]
The issue is also why the clips block light, so the insides all become pitch-black. Even with that, it's still got an entity cost of about 3, so it's not really a big deal.
