### ISSUE TITLE
Wont Change pettles!

### ISSUE THREAD

**Issue by ClarkxlYT** [TeamSpen210/BEE2-items#911]
Please help me my pettles wont update in portal 2!

**Comment by ClarkxlYT** [comment]
Please help me.

**Comment by xDadiKx** [comment]
Are you exporting it?

**Comment by ClarkxlYT** [comment]
no

**Comment by ClarkxlYT** [comment]
im making it but when i open portal 2 it stays how it is if you dont have beemod and you have a non-modded portal 2

**Comment by ClarkxlYT** [comment]
hello?

**Comment by xDadiKx** [comment]
Are you exporting the palette, if not then that's why you are not getting your wanted items

**Comment by xDadiKx** [comment]
If not, go to file then export.

**Comment by ClarkxlYT** [comment]
like what do i do?

**Comment by xDadiKx** [comment]
Top left corner of the program, you should see File, click on that then find Export and click it, wait then play the game

**Comment by ClarkxlYT** [comment]
Thanks, it worked.

**Comment by ClarkxlYT** [comment]
also how do i make a new  pattlet?

**Comment by ClarkxlYT** [comment]
nvm this case is closed now because i have fugured it out and got help, Bye and Thanks!
