### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ClarkxlYT** [TeamSpen210/BEE2-items#914]
you guys should make a cores package! please make a cores package with the cores in it!

**Comment by ZombiePwner1** [comment]
How does this have anything to do with puzzles? Please give a reason.

**Comment by TeamSpen210** [comment]
Additionally, it causes a lot of conceptual issues - GLaDOS should be trying to figure out why the cores are randomly entering test chambers, you could have two Wheatleys, and they probably wouldn't be able to do much otherwise.

**Comment by ZombiePwner1** [comment]
Also @ClarkxlYT when your making a report please say something like [New Item] report here. or [Suggestion] And make your suggestion. Don't just put [Suggestion] Since that does not explain anything.

**Comment by Luke18033** [comment]
@ClarkxlYT The correct and wrong way to name your issues IMO:

Correct:

# Issue Title

Incorrect:

# [Issue Label] Issue Title

# [Issue Label]

Not that this really matters, I just hate it when people put [New Item] etc. at the start of their issue titles.

**Comment by LautaroL20** [comment]
Uhmm, im agree with that but ill keep with [PRL22] one, since there´s no a PRL label and it may be kinda helpful for Spen.

**Comment by Luke18033** [comment]
@LautaroL20 Yes, providing the version would be helpful, and it would be a waste of time to create a label for every version.

**Comment by TeamSpen210** [comment]
The version isn't really important, all that really matters is if it's currently an issue to resolve.

**Comment by CompyCube** [comment]
This could work if:

1. The cores come along with a core receptacle.

2. There can only be one core per test chamber.

3. There would be special lines for characters when a core is in a chamber.

4. There would be a core receiver (like the turret dropper) that would dispense a core if a core is lost or put in goo.

5. There would be rails you could put a core on.

Without these, cores in Beemod would be fun but useless.

**Comment by TeamSpen210** [comment]
That doesn't really solve anything, why is a core in a test chamber? Cores are unique, so how can you dispense another?

**Comment by FrozenDragon0** [comment]
> This could work if:
> 
> 1. The cores come along with a core receptacle.
> 2. There can only be one core per test chamber.
> 3. There would be special lines for characters when a core is in a chamber.
> 4. There would be a core receiver (like the turret dropper) that would dispense a core if a core is lost or put in goo.
> 5. There would be rails you could put a core on.
> 
> Without these, cores in Beemod would be fun but useless.

This is something you should be using hammer for and not Beemod, cores have no place in a testchamber outside of story which is something Beemod/puzzlemaker isn't designed to make.

**Comment by CompyCube** [comment]
> > This could work if:
> > 
> > 1. The cores come along with a core receptacle.
> > 2. There can only be one core per test chamber.
> > 3. There would be special lines for characters when a core is in a chamber.
> > 4. There would be a core receiver (like the turret dropper) that would dispense a core if a core is lost or put in goo.
> > 5. There would be rails you could put a core on.
> > 
> > Without these, cores in Beemod would be fun but useless.
> 
> This is something you should be using hammer for and not Beemod, cores have no place in a testchamber outside of story which is something Beemod/puzzlemaker isn't designed to make.

Fair point.
