### ISSUE TITLE
Does a package´s palette icon always have to be 64x64 pixels, or it can be a slightly different size?

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#915]
The original size from bee2.4 pallete icon:
![light_strip_warm](https://cloud.githubusercontent.com/assets/12244376/19310593/445a2026-9061-11e6-8e8d-d7ad3c627ef9.png)

Edited: I know that a bigger resolution will not be displayed, but it can save time if we aren´t forced to convert to the exact same resolution.

**Comment by TeamSpen210** [comment]
They will be resized actually, but it's probably better for you to do it beforehand - it saves file size, and you can fiddle with settings to get the best reduction.

**Comment by Luke18033** [comment]
Question has been answered - issue closed.
