### ISSUE TITLE
Bee2.4 doesn´t provide the real cause from a crash in "BEE2.log" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#916]
This is a very important thing, since its the only way to know wich file from all the packages is causing problems. But if beemod does not generate the real details into "BEE2.log", the only way would be re-install everything, losing many custom things...

---

Example of the last part from the log generated by beemod, where is not providing the real cause:

`[DEBUG] packageLoader.load_packages(): Loading Item "ITEM_SECONDARY_OBSERVATION_ROOM"!
[INFO] BEE2_config.save(): Saving changes in config "../config\config.cfg"!`

**Comment by LautaroL20** [comment]
Well, i figured out what was causing beemod to not provide the real details from the crash.... It was the aplication trying to read a folder that had an "Info.txt", inside packages folder. MORE INFO: 

https://github.com/TeamSpen210/BEE2-items/issues/918

**Comment by TheDarkBomber** [comment]
Did you enable the option that tells you what happens when it crashes?

**Comment by LautaroL20** [comment]
@TheDarkBomber - It looks like you are´t following this page, so you will be completely out of date from what happens here. Case is already closed.

**Comment by LautaroL20** [comment]
Okay guys, i had a crash caused by a wrong character into the description from properties.txt, and Bee2.4 wasn´t even able to detect wich file was causing the problem. Case Re-open.

**Comment by TeamSpen210** [comment]
Ok, I found a bug in my error code, so it wasn't actually detecting errors. That's fixed now, so any errors at all should be detected.

**Comment by LautaroL20** [comment]
It would be even better if it actually could detect not only the name of the defective file, but also providing the folder´s location too, that would be even more helpful.
