### ISSUE TITLE
Broken Death Fizzler

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#919]
I was playing with the death fizzler today and I noticed how when connecting a floor button to it, it turns into a laser field but then stepping off the button it turns the whole thing off, then I step back on and it turns into a normal fizzler, and back off again and it turns back into the death fizzler. I'm very confused to say the least and I don't expect this is a feature.

**Comment by Luke18033** [comment]
That seems broken. The [Death Fizzler](
https://github.com/TeamSpen210/BEE2-items/wiki/Death-Fizzler) page on the wiki explains the proper behavior, so if it isn't doing this then it's bugged.

**Comment by TeamSpen210** [comment]
You need the Input A/B items, it doesn't respond to normal inputs correctly.

**Comment by Konclan** [comment]
So it needs the other separate item? Shouldn't that be specified in the item description? Highlighted even..

**Comment by ZombiePwner1** [comment]
Strange everytime i make a custom death fizzler in hammer it turns off and turns back into the death field and it doesn't do what it does in beemod.

**Comment by TeamSpen210** [comment]
The item has special logic to allow transmitting the two inputs through one PeTI input. That's why it breaks. InHammer you have as many as you like, so you can just send the appropriate ones.

**Comment by ZombiePwner1** [comment]
Ah alright well sucks how it's broken in PeTI

**Comment by Luke18033** [comment]
@TeamSpen210 I thought a standard imput would just activate Input A...

**Comment by TeamSpen210** [comment]
I need to implement it in the compiler to allow that. Actually for Death Fizzlers I'd want standard inputs to activate both at once.
