### ISSUE TITLE
[PRL 22 Bug] Antlines don't return to blue when a button is pressed with 1 second

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#921]
![20161015112903_1](https://cloud.githubusercontent.com/assets/18079316/19407114/b826d7fe-92ca-11e6-8f36-d5a8624e8506.jpg)

As you can see there i pressed the button and the antlines still remain yellow even after the cube is dropped.

**Comment by Luke18033** [comment]
PeTI buttons weren't meant to be 1 second, so this would make sense.

**Comment by ZombiePwner1** [comment]
It's still a bug anyway which should be fixed

**Comment by Luke18033** [comment]
@ZombiePwner1 I know it's a bug.

**Comment by TeamSpen210** [comment]
I can't replicate this. The antline just returns to blue.

**Comment by LautaroL20** [comment]
This is invalid, Antlines does return on both 1 or 2 seconds.

**Comment by ZombiePwner1** [comment]
That's odd did you do the exact same thing I did?
