### ISSUE TITLE
[PRL 22 Bug] Piston platforms can interfere with doors 

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#930]
![20161016113133_1](https://cloud.githubusercontent.com/assets/18079316/19415132/a6a6038c-9398-11e6-8085-9cfa65818321.jpg)

Piston platforms shouldn't be allowed to be placed near doors

**Comment by ZombiePwner1** [comment]
Piston platforms shouldn't be allowed to be placed next to doors.

**Comment by TeamSpen210** [comment]
This is a general issue, the door needs space on either sides. I can't block it though, since you might want to put the door in between a Thin Wall or the like.

**Comment by ZombiePwner1** [comment]
Is there a temporary fix for this?

**Comment by TeamSpen210** [comment]
No, there isn't and i don't plan to fix it. How do you suggest it should work?

**Comment by ZombiePwner1** [comment]
Alright then issue closed

**Comment by ZombiePwner1** [comment]
ill think of a way

**Comment by LautaroL20** [comment]
TeamSpen will not fix it, since Portal Door must be free space.
