### ISSUE TITLE
Stripes from the P1 Entrance elevator room are being packed as a "Withe bar"

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#933]
![20161016114522_1](https://cloud.githubusercontent.com/assets/12244376/19418326/077eb452-9398-11e6-9dac-69d8594ed338.jpg)

**Comment by TeamSpen210** [comment]
Those are lights, they're supposed to be like that.

**Comment by LautaroL20** [comment]
Well, i thought they actually had to be blue stripes as the inside elevator is.

**Comment by ZombiePwner1** [comment]
@LautaroL20 I think you need to play the original portal.
