### ISSUE TITLE
Something "Mysterious" is happening with the P1 CO-OP Elevator Doors from the start

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#935]
![20161016120426_1](https://cloud.githubusercontent.com/assets/12244376/19418486/0788fc5c-939b-11e6-9198-3dc99d9f9096.jpg)

**Comment by ZombiePwner1** [comment]
@LautaroL20 was that stuck on the doors when the elevator was moving up or did it move with the elevator?

**Comment by LautaroL20** [comment]
Thats static.

**Comment by ZombiePwner1** [comment]
So it that strange model didn't move?

**Comment by TeamSpen210** [comment]
AH, figured out what those are - they're the lights in the elevator, being too close.
