### ISSUE TITLE
has the following been implemented yet in bee2

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#938]
has the following been implemented yet in bee2

i wish to create a custom fizzler that has a 128 wide trigger field in it that changes the fizzler texture and solidity of the field when a physics object (cube) comes near it. 

it needs to do the following programming wise

- have 128 wide trigger texture in it that toggles solidity. 
- trigger must send output to the field to change the fizzler textures and solidity. 
- must be solid to everything when physics object touches trigger.

**Comment by TeamSpen210** [comment]
I've implemented the needed compiler parts for another item, so it'll be released with the next update.

**Comment by LautaroL20** [comment]
Question answered - case closed.
