### ISSUE TITLE
[Question] There is another way other than duplicate some of the block folders to giving "Styled Icons" in the Bee2.4 Palette?

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#941]
I am trying to figuring out how to display styled versions from the Angled Block icons but, if im aware, to make Bee2.4 using styled icons, there should be a duplicate folder with a slightly variation on its name. 

Example: "Tile_clean" ----> "Tile_over", so that you can display the styled icons into the beemod pallete when switching to another style.

So, my question is: There is anothery way other than having to duplicate the same folder to using styling icons?

**Comment by TeamSpen210** [comment]
Yes, that's the only way right now to change icons.
