### ISSUE TITLE
Minimal Entrance and exit

### ISSUE THREAD

**Issue by Konclan** [TeamSpen210/BEE2-items#943]
A new design for the entrance and exit doors that just have the elevators right there without the stairs and large rooms. The reason I request this is because sometimes players going through loads of test chambers get annoyed of the short walk in the start and end sections, It's a subtle change but it may slightly improve the quality of a chamber. This could be a stylevar. Also I want to hear other people's opinion on this topic.

**Comment by LautaroL20** [comment]
I do agree with the fact that most of veterans P2 players we start to get kinda annoyed of that short walk, so i like the idea of having an aditional stylevar option for this.

**Comment by Luke18033** [comment]
See #605 for why this isn't a good idea.

**Comment by Konclan** [comment]
That's not the same...

**Comment by ZombiePwner1** [comment]
@Konclan That issue does have something to do with with the entry and exit corridors
