### ISSUE TITLE
[Voluntary Contribution] Styled Surface Maker Icons (taken from peti models - with some enhancements)

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#944]
Sending these to @TeamSpen210, so he can implement them in the near future. All icons were taken from the TeamSpen PeTi models, but ive enhanced them a bit adding some Contrast-Brightness.

### special_over
![1](https://cloud.githubusercontent.com/assets/12244376/19446548/b40379a6-946f-11e6-977f-940e7476c09c.png)
### special_50s_60s
![special_50s_60s](https://cloud.githubusercontent.com/assets/12244376/19446579/d4ea61d4-946f-11e6-9750-15e80100976a.png)
### special_70s
![special_70s](https://cloud.githubusercontent.com/assets/12244376/19446897/620e8bb6-9471-11e6-82b7-a24143a26f17.png)
### special_80s
![special_80s](https://cloud.githubusercontent.com/assets/12244376/19446901/705381e0-9471-11e6-9f3f-6efbf6f1b274.png)
### special_bts
![special_bts](https://cloud.githubusercontent.com/assets/12244376/19446923/8d0e137c-9471-11e6-8224-496ca63d1562.png)
### special_p1
![special_p1](https://cloud.githubusercontent.com/assets/12244376/19446934/9aac1254-9471-11e6-8973-b798e11c6a19.png)

**Comment by TeamSpen210** [comment]
Only thing is that this isn't the appearance of the 'special marker' in those styles. It's just using a specific texture for each anyway, which I could get from the VPK. Actually it's 2-6 textures, depending on style (white/black wall, floor, ceiling or the same for all sides).

**Comment by TheDarkBomber** [comment]
Make a pull request.
