### ISSUE TITLE
new item: texture override to create rat dens

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#946]
this one should be easy, 

a 3D voxel item like the cut out tile that effects a area of voxels that overrides the textures on the walls, ceilings, and floors in the space it is placed. would be used to create custom BTS and rat den area's in test chambers. in BTS area the texture should be clean or overgrown test chambers so these areas would be a test chamber you can see into.

**Comment by TeamSpen210** [comment]
BTS is more than just textures. You'll really want Hammer to make this sort of thing.
