### ISSUE TITLE
New Item : Living Panels / Broken Overgrown Panels

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#949]
The Ones Seen Through The Overgrown Chamber After GLaDOS Is Awake Again.

**Comment by TeamSpen210** [comment]
Overgrown chambers are before that, so panels will be shut down. I do want this though.

**Comment by ZombiePwner1** [comment]
I already suggested a issue for reconstructing panels so this issue is abit of a duplicate but the broken panels on the other hand are a nice idea

**Comment by TeamSpen210** [comment]
See BenVlodgi/BEE2.4#414.

**Comment by Jadeygaming** [comment]
I'd Like To Have The Ability To Place Them

**Comment by ZombiePwner1** [comment]
Lol I just viewed that suggestion.

**Comment by Jadeygaming** [comment]
That World Be OK I'd Just Want Panels That Ether Fix Themselves Or Or Ones That Just Sit There Not Working.
