### ISSUE TITLE
Grating requires more intelligent logic writting on compiler, so only contiguous rectangular areas get merged together

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#953]
The complete grating issues: https://youtu.be/mD43RgWR3hU

This bug may be related to another issue, where players can´t leaving cubes: https://github.com/TeamSpen210/BEE2-items/issues/464

**Comment by TeamSpen210** [comment]
That's very strange sounding.

**Comment by LautaroL20** [comment]
Actually its to do with the grating.

**Comment by LautaroL20** [comment]
Grating also causes problems in CO-OP when trying to leaving a cube in the floor, see this:

https://github.com/TeamSpen210/BEE2-items/issues/464

**Comment by LautaroL20** [comment]
Will this be fixed with the pre-release 23, please? This bug makes impossible to leaving cubes on gratings in Co-op maps, and other problems too in SP.

**Comment by LautaroL20** [comment]
Will this be fixed with the pre-release 23, please? This bug makes impossible to leaving cubes on gratings in Co-op maps, and other problems too in SP.

**Comment by ZombiePwner1** [comment]
What problems is it causing in single player.

**Comment by LautaroL20** [comment]
In SP, it causes an huge ammount of downgrade FPS when funnel reaches a portalable surface where is a grating on wall and floor. Im aware that this may not happen on all PC, but it happens for me.

**Comment by LautaroL20** [comment]
66945234c68af8df4520b7ffac4ff0e3a7bad73b

**Comment by LautaroL20** [comment]
Whoops commit did not work.....

**Comment by TeamSpen210** [comment]
You'll need the repro name + @ before it, since it's in the other repro probably.
BenVlodgi/BEE2.4@66945234c68af8df4520b7ffac4ff0e3a7bad73b
