### ISSUE TITLE
[Request] Allow Conveyor Belts to start inactive

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#955]
Currently the Conveyor Belt is set to Start Active, with the check box grayed out, meaning it's not possible to start a map with the Conveyor Belt disabled, and have a pedestal button or similar activate it. The ability to do that would be great to create tests where you suddenly start the belt, and have to look for an escape before being dragged into a crusher or laser field or something. I see no reason for not have the option available, at least.

**Comment by TeamSpen210** [comment]
The non-oscillating option disables `start active`, so just turn on oscillating mode. The conveyor will start moving from the side closest to the belt item.
