### ISSUE TITLE
Entry and Exit corridor removal stylevar

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#956]
we need a style var that acts as a Entry and Exit corridor removal override removing the exit and entry corridors and making the elevator transition you right into the test chamber. my idea for this is to accompany several items that will assist in creating custom entry and exit corridor's and BTS area's and rat dens in PETI with a few items which are:

- [ ] a test chamber signage item
- [ ] a item that over rides textures in voxels it occupies (to create rat dens, bts area's etc)
- [ ] the bts florescent light
- [ ] panels
- [ ] square beams (would use the same PETI placement logic as glass / grating)
- [ ] item for overriding style of decorations (for putting pipes etc in a BTS / rat den area in a overgrown or clean test)

**Comment by Konclan** [comment]
I keep pushing ideas like these but everyone shoots them down T_T

**Comment by LautaroL20** [comment]
@Konclan - I think that TeamSpen210 already said this would not work well, specially for styles such as Old Aperture, see: [TeamSpen210 Argument](https://github.com/TeamSpen210/BEE2-items/issues/605#issuecomment-230186306).
