### ISSUE TITLE
Crusher is missing its model in the PeTi Editor

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#957]
![20161025205044_1](https://cloud.githubusercontent.com/assets/12244376/19708415/bec3a5a6-9af4-11e6-9a8b-2e526c92b5d5.jpg)

**Comment by ZombiePwner1** [comment]
Well this is interesting.

**Comment by ZombiePwner1** [comment]
Half of these items are missing their editor models. Btw @LautaroL20 you should make some maps involving crushers.

**Comment by LautaroL20** [comment]
No, im not a fan of these things like turrets / crushers. I preffer making logic maps focused in other test elements instead.
