### ISSUE TITLE
Bee2.4 Crash when trying to changing style "KeyError: KeyError('1',)

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#958]
[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\selectorWin.py", line 894, in save
 |   File "F:\Git\BEE2.4\src\selectorWin.py", line 957, in do_callback
 |   File "F:\Git\BEE2.4\src\UI.py", line 1867, in style_select_callback
 |   File "F:\Git\BEE2.4\src\UI.py", line 338, in load_data
 |   File "F:\Git\BEE2.4\src\UI.py", line 184, in get_icon
 | KeyError: '1'
 |_

![crash](https://cloud.githubusercontent.com/assets/12244376/19710220/3391076c-9b03-11e6-861a-be6c08883b26.png)

**Comment by TeamSpen210** [comment]
What style were you switching to? I really need to add error handling to that code...

**Comment by LautaroL20** [comment]
Overgrown Style.

**Comment by TeamSpen210** [comment]
The issue is specifically with a properties.txt file for an item - it's looking for a PNG icon, but there is none set.

**Comment by TeamSpen210** [comment]
No, it's in the `properties.txt` file, with an incorrect definition.

**Comment by TeamSpen210** [comment]
Now 'fixed', so this won't crash anymore and the BEE2 will tell you where to fix the issue.
