### ISSUE TITLE
Bee2.4 Will not open anymore after getting crash message: "KeyError: KeyError('1',) - A forced Re-installation will be required

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#959]
After getting the not much very descriptive, crash message "KeyError: KeyError('1',)" If you try to open BEE.exe, it will display the loading panel and then when it finishes loading, bee2.4 will close.

**Comment by TeamSpen210** [comment]
That's because it's trying to reload the Overgrown style constantly. Delete or edit bee2/config/config.cfg to stop it.

**Comment by LautaroL20** [comment]
Deleting the config.cfg fixed the unexpected closing. However, that is a good tip to having into the readme.txt, what do you think? https://github.com/TeamSpen210/BEE2-items/issues/860

**Comment by ZombiePwner1** [comment]
Strange things tend to happen with BEEmod when you mess around in the files.

**Comment by LautaroL20** [comment]
Well, installing custom content is not easy on Bee2.4, thats why i wanted a "Packages Page" inside the Wiki.....

**Comment by TheDarkBomber** [comment]
@LautaroL20 There will be a guide on the BEE2.4 wiki eventually, but the files will be documented on for telling you how to edit the files of the packages.
