### ISSUE TITLE
give stuff needed to debug custom music loop bug

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#96]
where can i send you my uvb76 bee2 custom music package @TeamSpen210 and @BenVlodgi?

i will let you guys see if you can figure out what's causing the looping problem with custom music once you get this package.

i need a email address or something to send it to you.

**Comment by TeamSpen210** [comment]
My email is (spencerb21@live.com).

**Comment by TeamSpen210** [comment]
My email is (spencerb21@live.com).

**Comment by ellingtonisland** [comment]
lets get this fixed

**Comment by TeamSpen210** [comment]
My email is (spencerb21@live.com).

**Comment by ellingtonisland** [comment]
done!
