### ISSUE TITLE
Portal pedestal rotates inaccurate

### ISSUE THREAD

**Issue by LogicDeLuxe** [TeamSpen210/BEE2-items#961]
It seems to turn slightly less then 90 degree after each portal fired. After one complete revolution, portals start to fail to be created, and after a some more turns, they start to be fired at completely unintentional places.

**Comment by ZombiePwner1** [comment]
Send in a gif or a picture so we can see the odd placements.

**Comment by TeamSpen210** [comment]
The item uses a different method to Valve's, which causes the inprecision. I'll switch it to the same as the original pedestals.

**Comment by TeamSpen210** [comment]
The item uses a different method to Valve's, which causes the inprecision. I'll switch it to the same as the original pedestals.
