### ISSUE TITLE
[PRL22 Bug] Reflection gel has a strange red line on it's icon in the pallet selector.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#962]

**Comment by TeamSpen210** [comment]
That would be a Thermal Discouragement Beam reflecting off the Reflection Gel, so you know what it does.

**Comment by ZombiePwner1** [comment]
Ahhh okay well I would suggest changing it abit since it's abit confusing.

**Comment by TheDarkBomber** [comment]
I can tell what it is from the image.
