### ISSUE TITLE
BTS flip panel portalable on both sides

### ISSUE THREAD

**Issue by LogicDeLuxe** [TeamSpen210/BEE2-items#965]
This happens when an areal faith plate target is placed on the flip panel. The supposedly unportalable side is plain white instead of a dark texture with the target symbol on it.

**Comment by ZombiePwner1** [comment]
The otherside where it's all white is a missing texture the BTS faithplate target texture is missing so whatever surface the target is placed on will be a white texture your gonna have to use the large faith plates.
