### ISSUE TITLE
Bee2.4 Crash "TclError: TclError('image "pyimage535" doesn\'t exist',) 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#966]
It happens when right-clicking an item.

-------------------------------------------------------------------------------------

[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\contextWin.py", line 151, in open_event
 |   File "F:\Git\BEE2.4\src\contextWin.py", line 180, in show_prop
 |   File "F:\Git\BEE2.4\src\contextWin.py", line 215, in load_item_data
 |   File "C:\Python34\lib\tkinter\__init__.py", line 1331, in __setitem__
 |   File "C:\Python34\lib\tkinter\__init__.py", line 1324, in configure
 |   File "C:\Python34\lib\tkinter\__init__.py", line 1315, in _configure
 | _tkinter.TclError: ('image "pyimage535" doesn\'t exist',)
 |_

**Comment by ZombiePwner1** [comment]
Right clicking in-game or the pallet selector.

**Comment by LautaroL20** [comment]
I figured out what happened, fixed it myself.

**Comment by TeamSpen210** [comment]
What happened?

**Comment by LautaroL20** [comment]
It was something to do with properties.txt, a leftover braket was causing this.
