### ISSUE TITLE
[Bug] Crushers are too slow when rising back up allowing the player to pass.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#967]
Make the crushers rise up faster and once they finish they should instantly go down again since players can get pass 1 crusher due to how slow it is. And it should require only propulsion gel.

**Comment by TeamSpen210** [comment]
You'll want to use more than one in a row, that stops you being able to dodge.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 That's the problem there is a small gap between crushers and when ur in that gap the crushers can't kill u

**Comment by ZombiePwner1** [comment]
It's either enlarging the size of the triggers or the model itself.

**Comment by TeamSpen210** [comment]
I made the crusher triggers bigger by ⅛ of a block. That's just enough to leave no safe space for the player between the crushers.

**Comment by ZombiePwner1** [comment]
Alright.

**Comment by ZombiePwner1** [comment]
Alright now I can hopefully use crushers without this gap issue.
