### ISSUE TITLE
[PRL 22 Bug] P1 antlines are not using their original version from the original game.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#974]
![20161103203913_1](https://cloud.githubusercontent.com/assets/18079316/19966209/cadc5f78-a205-11e6-8617-36ea8f8d26af.jpg)

Portal 2 version.

![20161103204023_1](https://cloud.githubusercontent.com/assets/18079316/19966227/dc86f648-a205-11e6-9453-839037fef388.jpg)

Original antlines from original game.

**Comment by TeamSpen210** [comment]
There's a good reason for that - Portal 2's antlines are twice as wide, so in order to make them like Portal 1 I'd need to do a lot of complicated logic to move them around so they still join up.

**Comment by LautaroL20** [comment]
This is intentional. Altough i really like how P1 Beemod antlines loooks, i think it even looks better than original ones.

**Comment by ZombiePwner1** [comment]
I don't really like how these antlines look i prefer the original version.

**Comment by Luke18033** [comment]
This is already going to be worked on, see #626.

**Comment by TeamSpen210** [comment]
That's for BTS, not P1 style.
