### ISSUE TITLE
A "Mysterious" Coffe cup has just a pure brown texture and it doesn't break into little pieces once dropped.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#976]
![20161103212027_1](https://cloud.githubusercontent.com/assets/18079316/19967479/70543dcc-a20b-11e6-8f13-7d91c2b04b66.jpg)

**Comment by LautaroL20** [comment]
Thats really mysterious... Since it should look white or purple when its missing textures.

**Comment by ZombiePwner1** [comment]
That coffecup actually does have a texture but it's not properly loaded.

**Comment by TeamSpen210** [comment]
Carl Kenner did this to replicate the original mug, since Portal 2 doesn't include the model.
