### ISSUE TITLE
Bee2.4 is not replacing old codes inside the "Editoritems.txt" from Portal 2 after the very first export

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#978]
I had to close beemod in order to actually force it to replace old codes inside editoritems, since after the very first export, beemod only manages to change the items positions inside the palette  as well as styles, but it doesn´t overriding item codes.

**Comment by LautaroL20** [comment]
I noticed this after having beemod open then changing the code in one of the addons inside packages, then re-exported it, so im not sure. I think beemod would never detect new changes if i edit when the app is open anyways.

**Comment by TeamSpen210** [comment]
This is sort of intentional. When you load it up, that's what it's doing - reading all of the config files into memory. After that it doesn't touch the files - you could probably delete the packages folder and it'll still export.
