### ISSUE TITLE
SR Latch

### ISSUE THREAD

**Issue by QuantiX999** [TeamSpen210/BEE2-items#982]
So, I found out how to control laser fizzler with inputs A/B, but these things's indicators are incorrect. I mean antlines. Also, what is the latch for? For an output?

**Comment by LautaroL20** [comment]
It is a standard Set/Reset Latch and relies on Input A and B items to work. When Input A is activated, the SR Latch will set the output on. When Input B is activated, the output will be reset to the off state.

**Comment by QuantiX999** [comment]
But the indicator lines doesn't show correct! There is a button that is connected to input A that is connected to the laser fizzler. When I press the button, the antlines turn orange, but then they stay orange and don't turn back blue. Same with input B, but the antlines are always blue. Is this a bug?
