### ISSUE TITLE
P1 Concrete floors infront of flip panels make glass sounds?

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#985]
![20161105103933_1](https://cloud.githubusercontent.com/assets/18079316/20027046/3497439e-a344-11e6-80e0-8137d51c981d.jpg)

That concrete floor i'm on is making glass sounds and it was only that square all the other squares were using their concrete sound. NOTE: This only happens when u have a portal placed on the flip panel.

**Comment by LautaroL20** [comment]
This is a Valve bug. You can do the opposite too. For example, placing grating on a white surface, then portaling it and when jumping on the grate youll heard concrete sound instead of the actual grating sound.

Thats why i never reported this bug before.

**Comment by ZombiePwner1** [comment]
Wait for @TeamSpen210 to say something. also i left you a comment on steam.

**Comment by LautaroL20** [comment]
No one can get acess to the source engine code to fix these things unless the mod gets Steam Greenlight as Black Mesa Source did. So, accessing the source engine code is the only way to fix these things atm.

**Comment by ZombiePwner1** [comment]
Seems u didn't read my comment. TeamSpen told me there is a way to fix this. And come online.

**Comment by LautaroL20** [comment]
Well, i did not see the TS commen anywere else...

**Comment by TeamSpen210** [comment]
I didn't say that it's fixable necessarily. Type `surfaceprop` while looking at the tile, and check what's logged in the console.
