### ISSUE TITLE
Input A/B Indicator Bug

### ISSUE THREAD

**Issue by QuantiX999** [TeamSpen210/BEE2-items#986]
There is a button that is connected to input A that is connected to the laser fizzler. When I press the button, the antlines turn orange, but then they stay orange and don't turn back blue. Same with input B, but the antlines are always blue. Is this a bug?

**Comment by LautaroL20** [comment]
I think this is rather intentional. Imput A/B Were developed alongside the SR Latch in order to using them togheter. Imput A acts as a "Permanent Gate", while B would reset A. I do not know what type of connection are you trying to handle, but youll want to use these imputs alongside the SR Latch.

**Comment by TeamSpen210** [comment]
Actually, what you want to do is turn off antllines on the target item, then overlap the Input A and B on the same block. Then it'll look correct.
