### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by Jadeygaming** [TeamSpen210/BEE2-items#989]
Transitions can make series of levels using different styles make sense such as BTS to Overgrown such as the  level ending in a wrecked elevator. Or with the Overgrown To BTS being starting in a wrecked elevator room and going through one of the BTS Doors.

**Comment by Jadeygaming** [comment]
I want these transitions to apply to all styles.

**Comment by ZombiePwner1** [comment]
we will see what @TeamSpen210 thinks

**Comment by TeamSpen210** [comment]
There would be far too many combinations of this to do reasonably.

**Comment by ZombiePwner1** [comment]
So I'm assuming issue closed then?
