### ISSUE TITLE
what is THIS?? Your Implementing Adhesion Gel?!?! GOOD!!!!

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#99]
@TeamSpen210 & @BenVlodgi  

why didn't you tell me you where implementing sticky gel.

looks like you have all the textures needed for it in game, all it needs is some more coding to make it work

also bug: this showed up when i tried to put reflection gel in a clean map with the latest bee2.4 and as soon as i walked on it or tried to fire a portal at it the game crashed.

![preview0261](https://cloud.githubusercontent.com/assets/11165643/9158143/8e4d182a-3edf-11e5-9dae-db1e1f2e2f52.jpg)

**Comment by TeamSpen210** [comment]
I'm not implementing adhesion gel. That particular texture has been in the Stylemod for ages, it's a bug that it's actually using that invalid paint type here - which is why it's crashing since the game doesn't know what effect to give when you touch the gel.

**Comment by ZombiePwner1** [comment]
Actually adhesion gel might be possible to add since I've got felix's adhesion gel and walking on walls does work but the whole map will need to be tied to a entity to rotate. Felix is planning to make his own PeTI editor version of the gel.

**Comment by TheDarkBomber** [comment]
I've got his Adhesion Gel as well.

**Comment by ZombiePwner1** [comment]
Getting adhesion gel in the editor will be very hard actually since everything in the map needs to rotate and doing that in the PeTI editor will be very tricky.

**Comment by ZombiePwner1** [comment]
BTW that purple splat texture isn't the right color compared to the blob color.

**Comment by TheDarkBomber** [comment]
Yes, it will.

**Comment by train66453574657453456345** [comment]
come on @TeamSpen210 @genestrashcan was so exited and i was to :(

**Comment by TeamSpen210** [comment]
For many many reasons it's not possible to implement.

**Comment by train66453574657453456345** [comment]
the game crashed.
> 
> ![preview0261](https://cloud.githubusercontent.com/assets/11165643/9158143/8e4d182a-3edf-11e5-9dae-db1e1f2e2f52.jpg)














adhesion gel more like destruction gel... plz add that plus fizzler gel 

<img width="469" height="668" alt="Image" src="https://github.com/user-attachments/assets/d4d34688-898e-4072-9551-473784341bb9" />

<img width="250" height="321" alt="Image" src="https://github.com/user-attachments/assets/703125fc-ba64-4020-8a4d-12892794a192" />
