### ISSUE TITLE
[PRL23] Beemod is not making the "Cache Folder", it acts as we had ennabled "Preserve Game Dir" when its really not, leaving the "Packages Resources" without being exported to the game

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#995]
The Pseudo Pre-release 23 i have acts as i had enabled "Preserve Game Dir" when its really not, leaving "Tons of resources" without being exported. And this is how i noticed it:

HOW TO NOTICE THIS BUG (Not to worry, no need to hit the export button for this): 

1. Launch Beemod.
2. Disable "Preserve Game Directories".
3. Close Beemod.
4. Delete the "Cache" folder inside the beemod folder (So you can notice how it will not be generated anymore).
5. Launch Beemod, once the loading panel closes, notice how on the Export Options Window is not appear anymore the Progress Bar that shows "Extracting Resources (XXX/4575").

_________________________________________________________________________________________

### CLICK THE IMAGE TO GET A BETTER IDEA FROM WHAT IM TALKING ABOUT:

![beemod do not export](https://cloud.githubusercontent.com/assets/12244376/20240901/a038c1ee-a903-11e6-8ab7-5712c2d58968.png)

**Comment by ZombiePwner1** [comment]
Beemod randomly does that after a few seconds.

**Comment by TeamSpen210** [comment]
I broke the extracting sub-process with the translation additions, so it just crashes and quits.

**Comment by Jadeygaming** [comment]
PRL23?

**Comment by LautaroL20** [comment]
Well, im one of the collaborators from this section. Both TeamSpen210 and me we shared the exact same dev build from beemod.
