### ISSUE TITLE
Enhancement allow panels to be placed under exit doors.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#996]
![20161113124340_1](https://cloud.githubusercontent.com/assets/18079316/20243721/cecf2bb0-a99e-11e6-99a1-b9d29bcc2044.jpg)

It's annoying not being able to place panels right under the exit door.

**Comment by TeamSpen210** [comment]
I can't do this, the floor brush intersects the top of that panel. It might work in Clean, but other styles like Overgrown and P1 style lower down into that area.

**Comment by Luke18033** [comment]
Use a draw bridge.
