### ISSUE TITLE
Antline check marks don't display on chamberlocks when connected

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#997]
![20161113130532_1](https://cloud.githubusercontent.com/assets/18079316/20243795/ecfc7b30-a9a1-11e6-8d41-edec4b6872ed.jpg)

Where is the check box at the end of the antlines??

**Comment by TeamSpen210** [comment]
Unfortunately the PeTI doesn't let you replicate the exit door behavior where it forces the checkbox to appear. It would be 'possible' in the compiler, but I'd need to recreate a lot of the antline logic to do so.
