### ISSUE TITLE
Music stops playing afther walk trhough the SP Exit "Floor BTS" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#999]
I hope that this has any possible fix, its one of my favorite Overgrown Exits, but has a bug that makes stops the backgrown music once warking trhough it. 

Here is the video: https://youtu.be/YbnlphxOnnI

**Comment by ZombiePwner1** [comment]
Isn't that the point to make the music stop I reckon it feels weird having music that still plays at the end of the chamber.

**Comment by LautaroL20** [comment]
I think i figured out a way to fix this. Ill have to merge the "over floor bts" alongside the "exit elevator" in one instance file.

**Comment by TeamSpen210** [comment]
The output on the exit door item stops the music. Just remove that, and add it to the exit elevator.
